In [159]:
#Setup: Imports and Configuration

import pandas as pd
import csv
import time
import re
from typing import List, Dict, Callable, Optional, Tuple 
import google.generativeai as genai
import os 
from IPython.display import display #

GOOGLE_API_KEY=""

### Models
#gemma-3-27b-it
#gemini-2.5-flash-preview-05-20
#gemini-2.0-flash
#gemini-2.0-flash-exp

genai.configure(api_key=GOOGLE_API_KEY)
# --- Model Initialization ---
## Specify which model you wanna use
def get_genai_model(model_name: str = "gemini-2.5-flash-preview-05-20"):
    print(f"Initializing model: {model_name}")
    try:
        return genai.GenerativeModel(model_name)
    except Exception as e:
        print(f"Error initializing model {model_name}: {e}. Ensure API key is set.")
        return None
model = get_genai_model() # Using the default

# --- Global Configuration ---
RUN_OVERALL_TRIAL_MODE = False 
MAX_BATCHES_FOR_TRIAL = 3
DEFAULT_BATCH_SIZE = 15
DEFAULT_WAIT_TIME = 0# Seconds

# ===> SPECIFY YOUR INPUT FILE PATH HERE <===
file_path = "/Users/jonaslorler/Documents/cordis-HORIZONprojects-csv/project.csv"
# Example if it's in the same directory as the notebook:
# initial_data_file_path = "project.csv" 
#CHECKPOINT FILENAME 
MAIN_DATAFRAME_CHECKPOINT_FILE = "df_processing_checkpoint.csv"


pd.reset_option('display.max_colwidth')
print(f"Initial data file path set to: {file_path}")

Initializing model: gemini-2.5-flash-preview-05-20
Initial data file path set to: /Users/jonaslorler/Documents/cordis-HORIZONprojects-csv/project.csv

In [2]:
# Initial Data Loading and Preparation 
print(f"Performing initial data load from: {file_path}")
fixed_rows = []
current_row_ml_handler = [] # Using a distinct name for multiline state
expected_fields_ml = 0
in_multiline_ml = False

try:
    with open(file_path, 'r', encoding='utf-8') as f:
        header_line = f.readline().strip()
        header = list(csv.reader([header_line], delimiter=';', quotechar='"'))[0]
        expected_fields_ml = len(header)
        
        id_idx = header.index('id')
        title_idx = header.index('title')
        objective_idx = header.index('objective')
        
        for line_num, line_content in enumerate(f, start=2):
            try:
                parsed_line_fields = list(csv.reader([line_content.strip()], delimiter=';', quotechar='"'))
                current_fields_item = parsed_line_fields[0] if parsed_line_fields else []
                
                if len(current_fields_item) == expected_fields_ml and not in_multiline_ml:
                    fixed_rows.append([current_fields_item[id_idx], current_fields_item[title_idx], current_fields_item[objective_idx]])
                elif len(current_fields_item) < expected_fields_ml or in_multiline_ml:
                    if not in_multiline_ml:
                        current_row_ml_handler = current_fields_item
                        in_multiline_ml = True
                    else:
                        if current_row_ml_handler:
                            if len(current_row_ml_handler) > objective_idx:
                                 current_row_ml_handler[objective_idx] += ' ' + line_content.strip()
                            else:
                                 current_row_ml_handler[-1] += ' ' + line_content.strip()
                        if line_content.strip().endswith('"'):
                            combined_text_check = ';'.join(str(field) for field in current_row_ml_handler)
                            parsed_combined_check = list(csv.reader([combined_text_check], delimiter=';', quotechar='"'))
                            if parsed_combined_check and len(parsed_combined_check[0]) >= expected_fields_ml:
                                complete_row_cand = parsed_combined_check[0][:expected_fields_ml]
                                fixed_rows.append([complete_row_cand[id_idx], complete_row_cand[title_idx], complete_row_cand[objective_idx]])
                                in_multiline_ml = False
                                current_row_ml_handler = []
                elif len(current_fields_item) > expected_fields_ml:
                    fixed_rows.append([current_fields_item[id_idx], current_fields_item[title_idx], current_fields_item[objective_idx]])
            except Exception as e_row:
                # Simplified error handling for row processing
                if in_multiline_ml and current_row_ml_handler: # Try to append if in multiline
                     if len(current_row_ml_handler) > objective_idx: current_row_ml_handler[objective_idx] += ' ' + line_content.strip()
                     else: current_row_ml_handler[-1] += ' ' + line_content.strip()
                # else: print(f"Skipping line {line_num} due to error: {e_row}")


    df_complete = pd.DataFrame(fixed_rows, columns=['id', 'title', 'objective'])
    print(f"Total rows recovered: {len(df_complete)}")

    df_complete.columns = df_complete.columns.str.strip('"')
    df_complete['id'] = pd.to_numeric(df_complete['id'], errors='coerce')
    df_complete = df_complete.dropna(subset=['id'])
    if not df_complete.empty:
        df_complete['id'] = df_complete['id'].astype(int)
    print(f"Rows after cleanup: {len(df_complete)}")

    # Create 'full_text' and drop original title/objective columns (Your In[3])
    if not df_complete.empty:
        df_complete["full_text"] = df_complete["title"].astype(str) + ": " + df_complete["objective"].astype(str)
        if 'title' in df_complete.columns and 'objective' in df_complete.columns: # Check before dropping
            df_complete = df_complete.drop(columns=["title", "objective"], errors='ignore')
        print("'full_text' column created, 'title' and 'objective' dropped.")
        
        # --- SAVE INITIAL STATE TO CHECKPOINT ---
        try:
            df_complete.to_csv(MAIN_DATAFRAME_CHECKPOINT_FILE, index=False)
            print(f"Initial df_complete saved to checkpoint: {MAIN_DATAFRAME_CHECKPOINT_FILE}")
        except Exception as e_save:
            print(f"Error saving initial checkpoint: {e_save}")

    print("\nFirst 5 rows of prepared df_complete:")
    if not df_complete.empty:
        display(df_complete[['id', 'full_text']].head())
        print(df_complete.info()) # Good to see info after load
    else:
        print("df_complete is empty after initial loading.")

except FileNotFoundError:
    print(f"CRITICAL ERROR: The initial data file '{file_path}' was not found.")
    df_complete = pd.DataFrame() 
except Exception as e_load:
    print(f"An unexpected error occurred during initial data loading: {e_load}")
    df_complete = pd.DataFrame()

Performing initial data load from: /Users/jonaslorler/Documents/cordis-HORIZONprojects-csv/project.csv
Total rows recovered: 15341
Rows after cleanup: 15341
'full_text' column created, 'title' and 'objective' dropped.
Initial df_complete saved to checkpoint: df_processing_checkpoint.csv

First 5 rows of prepared df_complete:

          id                                          full_text
0  101116741  Digitizing Other Economies: A Comparative Appr...
1  101163161  MOLECULAR QUANTUM DYNAMICS IN LOW TEMPERATURE ...
2  101160499  Multiscale modelling of aberrant phase transit...
3  101166905  The first comprehensive Atlas of the Milky Way...
4  101162875  Untapping multiparametric 2D luminescence sens...

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15341 entries, 0 to 15340
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         15341 non-null  int64
 1   full_text  15341 non-null  object
dtypes: int64(1), object(1)
memory usage: 239.8+ KB
None

In [101]:
#Define functions to reuse from Level 1 to 4
def generic_classify_batch(
    batch_prompt_items: List[Dict[str, str]], 
    prompt_template: str,
    item_prompt_format: str, 
    model_instance, # Pass the actual model object
    current_batch_global_offset: int, 
    batch_num_display: int, # This is 0-indexed for internal use, display as batch_num_display + 1
    max_text_length: int = 1000, 
    max_retries: int = 3,
    domain_categories_list: Optional[List[str]] = None,
    method_categories_list: Optional[List[str]] = None
) -> str:
    if not model_instance:
        print("Model not initialized for generic_classify_batch. Skipping API call.")
        return ""

    current_prompt_template = prompt_template
    if domain_categories_list is not None and method_categories_list is not None and \
       '{domain_categories}' in prompt_template and '{method_categories}' in prompt_template:
        try:
            current_prompt_template = prompt_template.format(
                domain_categories="\n".join(domain_categories_list),
                method_categories="\n".join(method_categories_list)
            )
        except KeyError as e:
            print(f"KeyError formatting prompt template with category lists: {e}")
            # Fallback or error handling
            pass # current_prompt_template remains the original if formatting fails
    
    full_prompt = current_prompt_template 
    
    for i, item_data in enumerate(batch_prompt_items):
        processed_item_data = {}
        for key, value in item_data.items():
            # Truncate specified long text fields
            if isinstance(value, str) and key in ['full_text', 'summary', 'objective', 'Project Summary', 
                                                  'Initial Goal', 'Initial Method', 
                                                  'Level 2 Generalized Goal', 'Level 2 Generalized Method',
                                                  'Existing L3 Application/Technology Domain', 
                                                  'Existing L3 Strategic Method Category']:
                processed_item_data[key] = value.strip()[:max_text_length]
            else:
                processed_item_data[key] = value
        processed_item_data['project_num_in_prompt'] = current_batch_global_offset + i + 1 # 1-based for LLM
        
        try:
            full_prompt += item_prompt_format.format(**processed_item_data)
        except KeyError as e:
            print(f"KeyError formatting item prompt: {e}. Item data: {processed_item_data}, Format: '{item_prompt_format}'")
            continue 

    if batch_num_display == 0: # Only log the first batch's prompt structure in detail (0-indexed display here)
        print(f"\n=== FIRST PROMPT FOR BATCH 1 (Structure Preview) ===")
        prompt_start_preview = current_prompt_template.split("Projects to Classify:",1)[0] if "Projects to Classify:" in current_prompt_template else current_prompt_template.split("Now, analyze the following projects",1)[0]
        prompt_start_preview = prompt_start_preview[:1000] + "..." if len(prompt_start_preview) > 1000 else prompt_start_preview
        print(prompt_start_preview)
        if batch_prompt_items:
             sample_item_data_for_format = {'project_num_in_prompt': current_batch_global_offset + 1}
             # Extract keys from item_prompt_format to build a complete sample_item_data
             # This regex finds all placeholders like {key_name}
             placeholders_in_format = re.findall(r'{(\w+)}', item_prompt_format)
             for key_in_item_format in placeholders_in_format:
                 if key_in_item_format != 'project_num_in_prompt': # Already added
                     # Check if this key is expected from input_fields_for_prompt (via batch_prompt_items)
                     # or provide a generic placeholder if not directly from input_fields_for_prompt
                     if batch_prompt_items and key_in_item_format in batch_prompt_items[0]:
                         sample_item_data_for_format[key_in_item_format] = f"[SAMPLE_{key_in_item_format.upper()}_FROM_DATA]"
                     else:
                         sample_item_data_for_format[key_in_item_format] = f"[SAMPLE_PLACEHOLDER_FOR_{key_in_item_format.upper()}]"
             try:
                print(f"Item Format Example: {item_prompt_format.format(**sample_item_data_for_format)}")
             except KeyError as e:
                print(f"Could not generate item format example due to missing keys for format '{item_prompt_format}': {e}")
                print(f"  Sample data used: {sample_item_data_for_format}")


        print("=== END PROMPT PREVIEW ===\n")

    for attempt in range(max_retries):
        try:
            response = model_instance.generate_content(full_prompt)
            return response.text
        except Exception as e:
            print(f"Error on API call attempt {attempt + 1} for batch {batch_num_display + 1}, offset {current_batch_global_offset}: {type(e).__name__} - {e}")
            sleep_time = (2 ** attempt)
            if "quota" in str(e).lower() or "rate limit" in str(e).lower() or "429" in str(e).lower() or "503" in str(e).lower():
                sleep_time = (2 ** attempt) * 5 
                print(f"Quota/Rate limit likely hit. Sleeping for {sleep_time}s...")
            else:
                print(f"Sleeping for {sleep_time}s before retry...")
            
            if attempt < max_retries - 1:
                time.sleep(sleep_time) 
            else:
                print(f"Failed all API retry attempts for batch {batch_num_display + 1}.")
                return "" 
    return ""

def generic_extract_labels(
    llm_output_text: str,
    expected_labels_map: Dict[str, str], 
    batch_num_display: int, # 0-indexed for internal use, display as batch_num_display + 1
    num_items_in_batch: int,
    valid_domains: Optional[List[str]] = None,
    valid_methods: Optional[List[str]] = None,
    separator: str = "---" 
) -> Dict[int, Dict[str, str]]: 
    if batch_num_display < 3: 
        print(f"\n--- RAW LLM OUTPUT (Batch {batch_num_display+1}, {num_items_in_batch} items) ---")
        print(llm_output_text[:1000] + ("..." if len(llm_output_text) > 1000 else ""))
        print("--- END RAW LLM OUTPUT ---\n")

    parsed_results_for_batch = {} 
    
    project_blocks_raw = []
    if separator and separator in llm_output_text and len(llm_output_text.split(separator)) >= num_items_in_batch * 0.5:
        project_blocks_raw = llm_output_text.split(separator)
    else:
        project_starts = list(re.finditer(r'Project\s*#\d+:', llm_output_text, re.IGNORECASE))
        if not project_starts:
            if llm_output_text.strip(): project_blocks_raw = [llm_output_text] 
        else:
            for i, start_match in enumerate(project_starts):
                start_pos = start_match.start()
                end_pos = project_starts[i+1].start() if i + 1 < len(project_starts) else len(llm_output_text)
                project_blocks_raw.append(llm_output_text[start_pos:end_pos])

    current_batch_item_idx = 0 
    for block_text_raw in project_blocks_raw:
        block_text = block_text_raw.strip()
        if not block_text:
            continue
        
        if current_batch_item_idx >= num_items_in_batch:
            if batch_num_display < 3: print(f"Warning (Batch {batch_num_display+1}): Parser got more blocks ({len(project_blocks_raw)}) than items sent ({num_items_in_batch}). Stopping parse for this batch.")
            break 

        labels_for_this_item = {}
        for _llm_key, out_key in expected_labels_map.items():
            labels_for_this_item[out_key] = "Not Found in LLM Output" 

        for line in block_text.splitlines():
            line_stripped = line.strip()
            for llm_key_prefix, output_dict_key in expected_labels_map.items():
                if line_stripped.lower().startswith(llm_key_prefix.lower()):
                    value = line_stripped[len(llm_key_prefix):].strip()
                    
                    parser_key_for_validation = output_dict_key 
                    if parser_key_for_validation.endswith(("_parsed", "_val")): # Generalize common suffixes
                        parser_key_for_validation = re.sub(r'(_parsed|_val)$', '', parser_key_for_validation)


                    if parser_key_for_validation == "domain" and valid_domains: 
                        if value not in valid_domains:
                            original_llm_value = value
                            value = find_closest_match_in_list(value, valid_domains)
                            if batch_num_display < 3 and original_llm_value != value : 
                                print(f"  LLM Domain Mismatch (B{batch_num_display+1}, Item {current_batch_item_idx}): '{original_llm_value}' -> '{value}'")
                    elif parser_key_for_validation == "method" and valid_methods: 
                        if value not in valid_methods:
                            original_llm_value = value
                            value = find_closest_match_in_list(value, valid_methods)
                            if batch_num_display < 3 and original_llm_value != value:
                                print(f"  LLM Method Mismatch (B{batch_num_display+1}, Item {current_batch_item_idx}): '{original_llm_value}' -> '{value}'")
                        
                    labels_for_this_item[output_dict_key] = value
                    break 
        
        parsed_results_for_batch[current_batch_item_idx] = labels_for_this_item
        current_batch_item_idx += 1

    if batch_num_display < 3:
        print(f"--- PARSED LABELS (Batch {batch_num_display+1}) ---")
        for batch_idx, labels in sorted(parsed_results_for_batch.items()):
            print(f"  Item in batch at offset {batch_idx}: {labels}")
        print(f"  (Parsed {len(parsed_results_for_batch)} items from this batch output, expected {num_items_in_batch})")
        print("--- END PARSED LABELS ---\n")
    return parsed_results_for_batch

def find_closest_match_in_list(value_from_llm: str, predefined_category_list: List[str]) -> str:
    if not value_from_llm or not predefined_category_list: return "Classification Failed"
    for category_in_list in predefined_category_list:
        if value_from_llm.lower() == category_in_list.lower():
            return category_in_list 
    return "Classification Failed"

def process_stage(
    df_main: pd.DataFrame, 
    stage_name: str,
    prompt_template_str: str,
    item_prompt_format_str: str, 
    input_fields_for_prompt: List[str], 
    llm_expected_labels_map: Dict[str, str], 
    output_col_names_map: Dict[str, str], 
    model_instance, 
    eligibility_filter_fn: Optional[Callable[[pd.DataFrame], pd.Series]] = None, 
    batch_size: int = DEFAULT_BATCH_SIZE, 
    wait_time: int = DEFAULT_WAIT_TIME,   
    run_trial_mode: bool = RUN_OVERALL_TRIAL_MODE, 
    max_batches_trial: int = MAX_BATCHES_FOR_TRIAL, 
    domain_categories_for_classification: Optional[List[str]] = None, 
    method_categories_for_classification: Optional[List[str]] = None, 
    llm_output_separator: str = "---" 
) -> pd.DataFrame: 

    print(f"\n{'='*20} Running Stage: {stage_name} on DataFrame with {len(df_main)} rows {'='*20}")
    if df_main.empty:
        print(f"Stage {stage_name}: Input DataFrame is empty. No changes made.")
        return df_main.copy() 

    df_working_copy = df_main.copy() 

    df_to_process_eligible = pd.DataFrame() # Initialize
    if eligibility_filter_fn:
        eligible_mask_for_this_call = eligibility_filter_fn(df_working_copy)
        df_to_process_eligible = df_working_copy[eligible_mask_for_this_call].copy()
        print(f"Stage {stage_name}: {len(df_to_process_eligible)} rows eligible for THIS processing call out of {len(df_working_copy)}.")
        if df_to_process_eligible.empty:
            print(f"Stage {stage_name}: No rows eligible for THIS call. No API calls will be made.")
            # Initialize output columns on df_working_copy for non-eligible rows if columns don't exist
            for df_col_name in output_col_names_map.values():
                if df_col_name not in df_working_copy.columns:
                    df_working_copy[df_col_name] = pd.NA 
                # Mark non-eligible rows if the column already exists and is NA (or a specific placeholder)
                df_working_copy.loc[~eligible_mask_for_this_call & (df_working_copy[df_col_name].isnull() | df_working_copy[df_col_name].isin(["Not Processed by Stage", pd.NA])), df_col_name] = "Not Eligible for Stage"
            return df_working_copy 
    else:
        df_to_process_eligible = df_working_copy.copy() 
        print(f"Stage {stage_name}: All {len(df_to_process_eligible)} rows from input are targeted for processing (no filter).")
            
    df_final_slice_for_api = df_to_process_eligible 
    if run_trial_mode: 
        num_records_for_trial = min(len(df_to_process_eligible), batch_size * max_batches_trial) 
        df_final_slice_for_api = df_to_process_eligible.iloc[:num_records_for_trial].copy()
        print(f"Stage {stage_name}: TRIAL MODE - Will send {len(df_final_slice_for_api)} (eligible) records to API.")
    else:
        # df_final_slice_for_api is already df_to_process_eligible (or its copy)
        print(f"Stage {stage_name}: FULL MODE - Will send {len(df_final_slice_for_api)} (eligible) records to API.")

    if df_final_slice_for_api.empty:
        print(f"Stage {stage_name}: No records to send to API after eligibility/trial slicing.")
        for df_col_name in output_col_names_map.values():
            if df_col_name not in df_working_copy.columns:
                df_working_copy[df_col_name] = "No Data Sent to API"
        return df_working_copy

    results_by_original_idx = {} 
    successful_batches_count = 0
    total_records_in_final_slice = len(df_final_slice_for_api)
    total_batches = (total_records_in_final_slice + batch_size - 1) // batch_size
    
    if total_batches > 0: print(f"  Will take {total_batches} batches. Est. API wait: {total_batches * wait_time / 60:.1f} min.\n")

    for batch_num_0_indexed, i_offset_in_slice in enumerate(range(0, total_records_in_final_slice, batch_size)):
        i_end_offset_in_slice = min(i_offset_in_slice + batch_size, total_records_in_final_slice)
        current_batch_df_for_api = df_final_slice_for_api.iloc[i_offset_in_slice:i_end_offset_in_slice]
        if current_batch_df_for_api.empty: continue

        batch_prompt_items_data = []
        for _original_idx, row_series in current_batch_df_for_api.iterrows():
            item_data = {field: row_series.get(field, "") for field in input_fields_for_prompt}
            batch_prompt_items_data.append(item_data)
        
        num_items_in_this_batch = len(batch_prompt_items_data)
        current_batch_global_prompt_offset = i_offset_in_slice 

        if batch_num_0_indexed < 3 or (batch_num_0_indexed % 5 == 0 and total_batches > 10):
            print(f"\n  {stage_name} - Batch {batch_num_0_indexed + 1}/{total_batches} (Slice Offsets {i_offset_in_slice}-{i_end_offset_in_slice-1})")

        llm_response_text = generic_classify_batch(
            batch_prompt_items_data, prompt_template_str, item_prompt_format_str,
            model_instance, current_batch_global_offset=current_batch_global_prompt_offset,
            batch_num_display=batch_num_0_indexed, 
            domain_categories_list=domain_categories_for_classification,
            method_categories_list=method_categories_for_classification
        )

        if llm_response_text:
            parsed_labels_for_batch = generic_extract_labels(
                llm_response_text, llm_expected_labels_map,
                batch_num_display=batch_num_0_indexed, 
                num_items_in_batch=num_items_in_this_batch,
                valid_domains=domain_categories_for_classification,
                valid_methods=method_categories_for_classification,
                separator=llm_output_separator
            )
            
            for batch_local_idx, labels_dict_from_parser in parsed_labels_for_batch.items():
                if batch_local_idx < len(current_batch_df_for_api): 
                    original_df_index = current_batch_df_for_api.index[batch_local_idx] 
                    results_by_original_idx[original_df_index] = labels_dict_from_parser
            
            if parsed_labels_for_batch: successful_batches_count += 1
            if batch_num_0_indexed < 3: print(f"  Batch {batch_num_0_indexed + 1} outcome: {'Labels extracted.' if parsed_labels_for_batch else 'No labels extracted.'}")
        else: # No LLM response text
            if batch_num_0_indexed < 3: print(f"  Batch {batch_num_0_indexed + 1} outcome: Failed to get LLM output.")
            for idx_in_failed_batch in current_batch_df_for_api.index:
                # Ensure results_by_original_idx has an entry for all items in the failed batch
                # Mark all expected output keys with "API Error in Batch"
                results_by_original_idx[idx_in_failed_batch] = {
                    parser_key: "API Error in Batch" for parser_key in llm_expected_labels_map.values() # Use parser keys
                }
        
        if batch_num_0_indexed < total_batches - 1: 
            if batch_num_0_indexed < 3 or (batch_num_0_indexed % 10 == 0 and total_batches > 20): print(f"  Waiting {wait_time}s...")
            time.sleep(wait_time)
            
    print(f"\nStage {stage_name}: API calls complete. {successful_batches_count}/{total_batches} batches yielded some parsable results.")
    
    # --- Update df_working_copy IN PLACE (which started as df_main.copy()) ---
    # Initialize output columns if they don't exist yet on df_working_copy for all rows first.
    # This ensures columns exist before trying to loc-assign.
    for df_col_name in output_col_names_map.values():
        if df_col_name not in df_working_copy.columns:
            df_working_copy[df_col_name] = pd.NA 
            print(f"Stage {stage_name}: Initialized new column '{df_col_name}' in working copy with pd.NA.")

    # Apply successfully parsed results (or error indicators like "API Error in Batch")
    # to the corresponding rows in df_working_copy.
    # Only updates rows that were part of df_final_slice_for_api (i.e., processed).
    for original_idx, parsed_labels_dict in results_by_original_idx.items():
        if original_idx in df_working_copy.index: 
            for parser_key, df_col_name in output_col_names_map.items():
                value_to_assign = parsed_labels_dict.get(parser_key, "Parse Error (Key Missing)")
                df_working_copy.loc[original_idx, df_col_name] = value_to_assign
        else:
            print(f"Critical Warning: Original index {original_idx} from results not found in working_copy for stage {stage_name}.")

    # --- Summary Stats (Corrected) ---
    processed_and_got_valid_labels_count = 0
    # Iterate through the indices that were actually processed (sent to API)
    for original_idx_processed in df_final_slice_for_api.index:
        if original_idx_processed in results_by_original_idx:
            labels_dict_from_parser = results_by_original_idx[original_idx_processed]
            at_least_one_valid_label_for_this_item = False
            for parser_key in output_col_names_map.keys(): 
                value_from_llm = labels_dict_from_parser.get(parser_key)
                invalid_values_for_summary = [
                    "Parse Error (Key Missing)", "Not Found in LLM Output", 
                    "Classification Failed", "API Error in Batch", ""                       
                ] 
                if pd.isna(value_from_llm) or (isinstance(value_from_llm, str) and value_from_llm in invalid_values_for_summary):
                    pass 
                else:
                    at_least_one_valid_label_for_this_item = True 
                    break 
            if at_least_one_valid_label_for_this_item:
                processed_and_got_valid_labels_count += 1
    
    print(f"\n{'='*15} Stage {stage_name} - FINAL SUMMARY {'='*15}")
    print(f"  Input records to stage (df_main): {len(df_main)}")
    if eligibility_filter_fn: print(f"  Eligible records (before trial slice): {len(df_to_process_eligible)}")
    print(f"  Records sent to API (after trial slice if any): {total_records_in_final_slice}")
    print(f"  Successfully received and parsed at least one valid label for: {processed_and_got_valid_labels_count} records.")
    if total_records_in_final_slice > 0 : 
        success_rate = (processed_and_got_valid_labels_count / total_records_in_final_slice) * 100
        print(f"  Success rate on records sent to API: {success_rate:.0f}%")
    
    print(f"\n  Top values for output columns in Stage {stage_name} (from {len(df_working_copy)} total rows):")
    for df_col_name in output_col_names_map.values():
        if df_col_name in df_working_copy.columns:
            print(f"    Column '{df_col_name}':")
            counts = df_working_copy[df_col_name].value_counts(dropna=False) 
            for val, count in counts.head(7).items():
                 display_val = str(val)[:70] if not pd.isna(val) else "pd.NA"
                 print(f"      - \"{display_val}\": {count}") 
            if len(counts) > 7: print("        ...")
        
    return df_working_copy 

print("Generic processing functions defined.")

Generic processing functions defined.

In [4]:
# ## Stage 1: Initial L1 Goal and Method Classification

# --- Stage 1 Configuration ---
STAGE_NAME_S1 = "L1_Initial_Classification"

PROMPT_TEMPLATE_S1 = """You are analyzing EU-funded research projects.
For each project, provide two short labels:
The first label should describe the project’s main purpose or intended societal impact — what the project is ultimately trying to achieve. 
Keep it short (max 8 words) and focus on the real-world outcome or benefit. For example:  
Goal: Inclusive English Language Access

The second label should describe the core method, approach, or technology being used. 
What is the main approach, method, or technology used to achieve the goal? This should reflect *how* the project is doing its work.
If the method involves multiple elements, you may combine them into a single phrase (maximum 7 words). 
However, avoid using “&” alone. Instead, use wording that clarifies how the elements are related,
for example, whether one enables the other, they are used together, or one is a format for the other.
To identify the true method, ask yourself:** Is this item something the project primarily does as an action (e.g., 'Organizing Conference', 'Developing Software', 'Conducting Workshops'),
creates as a main deliverable (e.g., 'Building a Database', 'Creating Online Platform'), or uses as a core technique (e.g., 'AI Algorithms', 'Survey Methodology', 'Case Study Analysis')?
Example of this distinction: Consider a project aiming to "Strengthen research infrastructure strategy" by organizing a conference. 
If this conference plans to discuss "RI strategic autonomy," "societal impact of RIs," and "ecosystems of RIs (including ecosystem analysis),
the ideal method is 'Policy Dialogue via Research Infrastructure Conference'
A method like 'Conference & Ecosystem Analysis' would be incorrect in this context. 'Ecosystem Analysis' is a topic
or theme to be discussed at the conference; it is not a separate, 
co-equal methodological activity being performed by the project alongside organizing the conference. 
The conference is the vehicle or *platform* for these discussions. The project's primary action is organizing the event.
Avoid listing topics of discussion or sub-components as if they are the method itself.
Avoid phrases where the role of the method is unclear.

Unclear: “Digital Platform & Stakeholder Mapping”  
Clear: “Creation of Digital Stakeholder Platform”

Keep it concise (max 7 words) and use standard scientific or technical terms. For example:  
Method: AI Language Assistants

Format your response like this for each project in the batch:
Project #{project_num_in_prompt}:  
Goal: [impact-driven purpose]  
Method: [technical or methodological approach]

Do not include anything else in your response.

Projects to Classify:
""" 
ITEM_PROMPT_FORMAT_S1 = "Project #{project_num_in_prompt}: {full_text}\n" 
INPUT_FIELDS_S1 = ['full_text'] 
LLM_EXPECTED_LABELS_S1 = {"Goal:": "s1_goal_parsed", "Method:": "s1_method_parsed"}
OUTPUT_COL_NAMES_S1 = {"s1_goal_parsed": "l1_goal", "s1_method_parsed": "l1_method"}
ELIGIBILITY_FILTER_S1 = None 

# --- Execute Stage 1 ---
# df_complete is loaded/initialized in Cell 2.
# model, RUN_OVERALL_TRIAL_MODE, etc., are from Cell 1.

if 'df_complete' in locals() and isinstance(df_complete, pd.DataFrame) and not df_complete.empty and model:
    print(f"Input for Stage 1 ({STAGE_NAME_S1}): df_complete with {len(df_complete)} rows.")
    # Ensure 'full_text' column exists from Cell 2
    if 'full_text' not in df_complete.columns:
        print(f"ERROR: 'full_text' column not found in df_complete for Stage {STAGE_NAME_S1}. Please check Cell 2 (Data Loading).")
        # df_complete might be an empty shell if initial loading totally failed; process_stage handles empty df_main.
    else:
        df_complete = process_stage( # Update df_complete with results
            df_main=df_complete, 
            stage_name=STAGE_NAME_S1,
            prompt_template_str=PROMPT_TEMPLATE_S1,
            item_prompt_format_str=ITEM_PROMPT_FORMAT_S1,
            input_fields_for_prompt=INPUT_FIELDS_S1,
            llm_expected_labels_map=LLM_EXPECTED_LABELS_S1,
            output_col_names_map=OUTPUT_COL_NAMES_S1,
            model_instance=model, 
            eligibility_filter_fn=ELIGIBILITY_FILTER_S1,
            run_trial_mode=RUN_OVERALL_TRIAL_MODE, 
            max_batches_trial=MAX_BATCHES_FOR_TRIAL, 
            batch_size=DEFAULT_BATCH_SIZE, 
            wait_time=DEFAULT_WAIT_TIME,
            llm_output_separator=None # S1 prompt doesn't specify "---" between items for LLM output
        )
        
        if not df_complete.empty: # Check the result of process_stage
            print(f"\n{STAGE_NAME_S1} completed. Sample of updated df_complete:")
            # from IPython.display import display # Should be imported in Cell 3
            display(df_complete[['id', 'full_text', 'l1_goal', 'l1_method']].head())
            
            # ---> SAVE THE UPDATED df_complete TO THE MAIN CHECKPOINT FILE <---
            # MAIN_DATAFRAME_CHECKPOINT_FILE should be defined in Cell 1
            try:
                df_complete.to_csv(MAIN_DATAFRAME_CHECKPOINT_FILE, index=False) # OVERWRITE
                print(f"Saved updated df_complete after {STAGE_NAME_S1} to checkpoint: {MAIN_DATAFRAME_CHECKPOINT_FILE}")
            except Exception as e:
                print(f"Error saving checkpoint after {STAGE_NAME_S1}: {e}")
        else:
            print(f"Stage {STAGE_NAME_S1} resulted in an empty DataFrame. This indicates a problem if input was not empty.")
else:
    if 'df_complete' not in locals() or not isinstance(df_complete, pd.DataFrame) or df_complete.empty:
        print("Skipping Stage 1: Input DataFrame 'df_complete' (from Cell 2) is not available or is empty.")
    if not model:
        print("Skipping Stage 1: LLM Model is not initialized (check Cell 1).")

Input for Stage 1 (L1_Initial_Classification): df_complete with 15341 rows.

==================== Running Stage: L1_Initial_Classification on DataFrame with 15341 rows ====================
Stage L1_Initial_Classification: All 15341 rows from input are targeted for processing (no filter).
Stage L1_Initial_Classification: FULL MODE - Will send 15341 (eligible) records to API.
  Will take 1705 batches. Est. API wait: 142.1 min.


  L1_Initial_Classification - Batch 1/1705 (Slice Offsets 0-8)

=== FIRST PROMPT FOR BATCH 1 (Structure Preview) ===
You are analyzing EU-funded research projects.
For each project, provide two short labels:
The first label should describe the project’s main purpose or intended societal impact — what the project is ultimately trying to achieve.
Keep it short (max 8 words) and focus on the real-world outcome or benefit. For example:
Goal: Inclusive English Language Access

The second label should describe the core method, approach, or technology being used.
What is the main approach, method, or technology used to achieve the goal? This should reflect *how* the project is doing its work.
If the method involves multiple elements, you may combine them into a single phrase (maximum 7 words).
However, avoid using “&” alone. Instead, use wording that clarifies how the elements are related,
for example, whether one enables the other, they are used together, or one is a format for the other.
To identify the true method, ask yourself:** Is this item something the project primarily does as an action (e.g.,...
Item Format Example: Project #1: [SAMPLE_FULL_TEXT_FROM_DATA]

=== END PROMPT PREVIEW ===


--- RAW LLM OUTPUT (Batch 1, 9 items) ---
Project #1:
Goal: Understanding Digital Adoption in Non-Industrial Societies
Method: Comparative Ethnographic Analysis of Digitization

Project #2:
Goal: Unveiling Astrochemistry of Molecular Ices
Method: Molecular Quantum Dynamics & Spectroscopy

Project #3:
Goal: Resolving Aberrant Condensate Dynamics in Cells
Method: Multiscale Computational Modeling of Biomolecules

Project #4:
Goal: Creating a 3D Map of the Milky Way
Method: Comprehensive Galactic Data Integration & Mapping

Project #5:
Goal: Improving Cellular Luminescence Nanosensing Reliability
Method: Machine Learning & Spectral Sorting of Signals

Project #6:
Goal: Detecting Anomalies in Gravitational Wave Signals
Method: Precision Gravitational Wave Data Analysis

Project #7:
Goal: Reconstructing Early Knowledge Management Systems
Method: Historical Analysis of Coln’s Library Catalogues

Project #8:
Goal: Integrating Ukrainian Nuclear Research into Europe
Method: National Contact Point Support & Networking

P...
--- END RAW LLM OUTPUT ---

--- PARSED LABELS (Batch 1) ---
  Item in batch at offset 0: {'s1_goal_parsed': 'Understanding Digital Adoption in Non-Industrial Societies', 's1_method_parsed': 'Comparative Ethnographic Analysis of Digitization'}
  Item in batch at offset 1: {'s1_goal_parsed': 'Unveiling Astrochemistry of Molecular Ices', 's1_method_parsed': 'Molecular Quantum Dynamics & Spectroscopy'}
  Item in batch at offset 2: {'s1_goal_parsed': 'Resolving Aberrant Condensate Dynamics in Cells', 's1_method_parsed': 'Multiscale Computational Modeling of Biomolecules'}
  Item in batch at offset 3: {'s1_goal_parsed': 'Creating a 3D Map of the Milky Way', 's1_method_parsed': 'Comprehensive Galactic Data Integration & Mapping'}
  Item in batch at offset 4: {'s1_goal_parsed': 'Improving Cellular Luminescence Nanosensing Reliability', 's1_method_parsed': 'Machine Learning & Spectral Sorting of Signals'}
  Item in batch at offset 5: {'s1_goal_parsed': 'Detecting Anomalies in Gravitational Wave Signals', 's1_method_parsed': 'Precision Gravitational Wave Data Analysis'}
  Item in batch at offset 6: {'s1_goal_parsed': 'Reconstructing Early Knowledge Management Systems', 's1_method_parsed': 'Historical Analysis of Coln’s Library Catalogues'}
  Item in batch at offset 7: {'s1_goal_parsed': 'Integrating Ukrainian Nuclear Research into Europe', 's1_method_parsed': 'National Contact Point Support & Networking'}
  Item in batch at offset 8: {'s1_goal_parsed': 'Disseminating Euratom Nuclear Research Outcomes', 's1_method_parsed': 'Organizing International Research Policy Conference'}
  (Parsed 9 items from this batch output, expected 9)
--- END PARSED LABELS ---

  Batch 1 outcome: Labels extracted.
  Waiting 5s...

  L1_Initial_Classification - Batch 2/1705 (Slice Offsets 9-17)

--- RAW LLM OUTPUT (Batch 2, 9 items) ---
Project #10:
Goal: Optimize pollutant removal material applications
Method: Market & Technical Feasibility Analysis

Project #11:
Goal: Improve chronic disease management with AI
Method: AI-driven Digital Health Solution Development

Project #12:
Goal: Increase IVF pregnancy success rates
Method: Uterine Receptivity Biomarker Identification

Project #13:
Goal: Democratize English language learning access
Method: AI-Powered Personal Language Assistant

Project #14:
Goal: Foster young scientific talent development
Method: Organization of Science Competition & Pilot

Project #15:
Goal: Promote European student science achievement
Method: International Student Science Competition

Project #16:
Goal: Advance Open Access scholarly publishing
Method: Evaluation of Open Access Policy Impact

Project #17:
Goal: Integrate science into city governance
Method: Science-Driven Urban Development Initiative

Project #18:
Goal: Facilitate researcher mobility in Europe ...
--- END RAW LLM OUTPUT ---

--- PARSED LABELS (Batch 2) ---
  Item in batch at offset 0: {'s1_goal_parsed': 'Optimize pollutant removal material applications', 's1_method_parsed': 'Market & Technical Feasibility Analysis'}
  Item in batch at offset 1: {'s1_goal_parsed': 'Improve chronic disease management with AI', 's1_method_parsed': 'AI-driven Digital Health Solution Development'}
  Item in batch at offset 2: {'s1_goal_parsed': 'Increase IVF pregnancy success rates', 's1_method_parsed': 'Uterine Receptivity Biomarker Identification'}
  Item in batch at offset 3: {'s1_goal_parsed': 'Democratize English language learning access', 's1_method_parsed': 'AI-Powered Personal Language Assistant'}
  Item in batch at offset 4: {'s1_goal_parsed': 'Foster young scientific talent development', 's1_method_parsed': 'Organization of Science Competition & Pilot'}
  Item in batch at offset 5: {'s1_goal_parsed': 'Promote European student science achievement', 's1_method_parsed': 'International Student Science Competition'}
  Item in batch at offset 6: {'s1_goal_parsed': 'Advance Open Access scholarly publishing', 's1_method_parsed': 'Evaluation of Open Access Policy Impact'}
  Item in batch at offset 7: {'s1_goal_parsed': 'Integrate science into city governance', 's1_method_parsed': 'Science-Driven Urban Development Initiative'}
  Item in batch at offset 8: {'s1_goal_parsed': 'Facilitate researcher mobility in Europe', 's1_method_parsed': 'Pension Fund Operational Improvement'}
  (Parsed 9 items from this batch output, expected 9)
--- END PARSED LABELS ---

  Batch 2 outcome: Labels extracted.
  Waiting 5s...

  L1_Initial_Classification - Batch 3/1705 (Slice Offsets 18-26)

--- RAW LLM OUTPUT (Batch 3, 9 items) ---
Project #19:
Goal: Foster solutions to global challenges via research
Method: Research Contest with Workshops & Mentorship

Project #20:
Goal: Shape the future European Research Area
Method: Policy Dialogue via ERA Conference

Project #21:
Goal: Increase impact of research through co-valorisation
Method: Co-valorisation Experimentation in Regional Territories

Project #22:
Goal: Promote science and public engagement with research
Method: Organisation of European City of Science Festival

Project #23:
Goal: Enable researcher mobility across Europe
Method: Cross-border Pension Fund Establishment

Project #24:
Goal: Inspire young scientists and promote STEM careers
Method: Organisation of EU Young Scientists Contest

Project #25:
Goal: Accelerate climate innovation for city & industry
Method: Place-based Systems Innovation Model

Project #26:
Goal: Expand European innovation globally
Method: Establishing International EIT Innovation Hubs

Project #27:
Goa...
--- END RAW LLM OUTPUT ---

--- PARSED LABELS (Batch 3) ---
  Item in batch at offset 0: {'s1_goal_parsed': 'Foster solutions to global challenges via research', 's1_method_parsed': 'Research Contest with Workshops & Mentorship'}
  Item in batch at offset 1: {'s1_goal_parsed': 'Shape the future European Research Area', 's1_method_parsed': 'Policy Dialogue via ERA Conference'}
  Item in batch at offset 2: {'s1_goal_parsed': 'Increase impact of research through co-valorisation', 's1_method_parsed': 'Co-valorisation Experimentation in Regional Territories'}
  Item in batch at offset 3: {'s1_goal_parsed': 'Promote science and public engagement with research', 's1_method_parsed': 'Organisation of European City of Science Festival'}
  Item in batch at offset 4: {'s1_goal_parsed': 'Enable researcher mobility across Europe', 's1_method_parsed': 'Cross-border Pension Fund Establishment'}
  Item in batch at offset 5: {'s1_goal_parsed': 'Inspire young scientists and promote STEM careers', 's1_method_parsed': 'Organisation of EU Young Scientists Contest'}
  Item in batch at offset 6: {'s1_goal_parsed': 'Accelerate climate innovation for city & industry', 's1_method_parsed': 'Place-based Systems Innovation Model'}
  Item in batch at offset 7: {'s1_goal_parsed': 'Expand European innovation globally', 's1_method_parsed': 'Establishing International EIT Innovation Hubs'}
  Item in batch at offset 8: {'s1_goal_parsed': 'Strengthen European digital sovereignty', 's1_method_parsed': 'Deep Tech Venture Building & Upskilling'}
  (Parsed 9 items from this batch output, expected 9)
--- END PARSED LABELS ---

  Batch 3 outcome: Labels extracted.
  Waiting 5s...

  L1_Initial_Classification - Batch 6/1705 (Slice Offsets 45-53)

  L1_Initial_Classification - Batch 11/1705 (Slice Offsets 90-98)
  Waiting 5s...

  L1_Initial_Classification - Batch 16/1705 (Slice Offsets 135-143)

  L1_Initial_Classification - Batch 21/1705 (Slice Offsets 180-188)
  Waiting 5s...

  L1_Initial_Classification - Batch 26/1705 (Slice Offsets 225-233)

  L1_Initial_Classification - Batch 31/1705 (Slice Offsets 270-278)
  Waiting 5s...

  L1_Initial_Classification - Batch 36/1705 (Slice Offsets 315-323)

  L1_Initial_Classification - Batch 41/1705 (Slice Offsets 360-368)
  Waiting 5s...

  L1_Initial_Classification - Batch 46/1705 (Slice Offsets 405-413)

  L1_Initial_Classification - Batch 51/1705 (Slice Offsets 450-458)
  Waiting 5s...

  L1_Initial_Classification - Batch 56/1705 (Slice Offsets 495-503)

  L1_Initial_Classification - Batch 61/1705 (Slice Offsets 540-548)
  Waiting 5s...

  L1_Initial_Classification - Batch 66/1705 (Slice Offsets 585-593)

  L1_Initial_Classification - Batch 71/1705 (Slice Offsets 630-638)
  Waiting 5s...

  L1_Initial_Classification - Batch 76/1705 (Slice Offsets 675-683)

  L1_Initial_Classification - Batch 81/1705 (Slice Offsets 720-728)
  Waiting 5s...

  L1_Initial_Classification - Batch 86/1705 (Slice Offsets 765-773)

  L1_Initial_Classification - Batch 91/1705 (Slice Offsets 810-818)
  Waiting 5s...
Error on API call attempt 1 for batch 94, offset 837: DeadlineExceeded - 504 Deadline Exceeded
Sleeping for 1s before retry...

  L1_Initial_Classification - Batch 96/1705 (Slice Offsets 855-863)

  L1_Initial_Classification - Batch 101/1705 (Slice Offsets 900-908)
  Waiting 5s...

  L1_Initial_Classification - Batch 106/1705 (Slice Offsets 945-953)

  L1_Initial_Classification - Batch 111/1705 (Slice Offsets 990-998)
  Waiting 5s...

  L1_Initial_Classification - Batch 116/1705 (Slice Offsets 1035-1043)

  L1_Initial_Classification - Batch 121/1705 (Slice Offsets 1080-1088)
  Waiting 5s...

  L1_Initial_Classification - Batch 126/1705 (Slice Offsets 1125-1133)

  L1_Initial_Classification - Batch 131/1705 (Slice Offsets 1170-1178)
  Waiting 5s...

  L1_Initial_Classification - Batch 136/1705 (Slice Offsets 1215-1223)

  L1_Initial_Classification - Batch 141/1705 (Slice Offsets 1260-1268)
  Waiting 5s...

  L1_Initial_Classification - Batch 146/1705 (Slice Offsets 1305-1313)

  L1_Initial_Classification - Batch 151/1705 (Slice Offsets 1350-1358)
  Waiting 5s...

  L1_Initial_Classification - Batch 156/1705 (Slice Offsets 1395-1403)

  L1_Initial_Classification - Batch 161/1705 (Slice Offsets 1440-1448)
  Waiting 5s...

  L1_Initial_Classification - Batch 166/1705 (Slice Offsets 1485-1493)

  L1_Initial_Classification - Batch 171/1705 (Slice Offsets 1530-1538)
  Waiting 5s...

  L1_Initial_Classification - Batch 176/1705 (Slice Offsets 1575-1583)

  L1_Initial_Classification - Batch 181/1705 (Slice Offsets 1620-1628)
  Waiting 5s...

  L1_Initial_Classification - Batch 186/1705 (Slice Offsets 1665-1673)

  L1_Initial_Classification - Batch 191/1705 (Slice Offsets 1710-1718)
  Waiting 5s...

  L1_Initial_Classification - Batch 196/1705 (Slice Offsets 1755-1763)

  L1_Initial_Classification - Batch 201/1705 (Slice Offsets 1800-1808)
  Waiting 5s...

  L1_Initial_Classification - Batch 206/1705 (Slice Offsets 1845-1853)

  L1_Initial_Classification - Batch 211/1705 (Slice Offsets 1890-1898)
  Waiting 5s...

  L1_Initial_Classification - Batch 216/1705 (Slice Offsets 1935-1943)

  L1_Initial_Classification - Batch 221/1705 (Slice Offsets 1980-1988)
  Waiting 5s...

  L1_Initial_Classification - Batch 226/1705 (Slice Offsets 2025-2033)

  L1_Initial_Classification - Batch 231/1705 (Slice Offsets 2070-2078)
  Waiting 5s...

  L1_Initial_Classification - Batch 236/1705 (Slice Offsets 2115-2123)

  L1_Initial_Classification - Batch 241/1705 (Slice Offsets 2160-2168)
  Waiting 5s...

  L1_Initial_Classification - Batch 246/1705 (Slice Offsets 2205-2213)

  L1_Initial_Classification - Batch 251/1705 (Slice Offsets 2250-2258)
  Waiting 5s...

  L1_Initial_Classification - Batch 256/1705 (Slice Offsets 2295-2303)

  L1_Initial_Classification - Batch 261/1705 (Slice Offsets 2340-2348)
  Waiting 5s...

  L1_Initial_Classification - Batch 266/1705 (Slice Offsets 2385-2393)

  L1_Initial_Classification - Batch 271/1705 (Slice Offsets 2430-2438)
  Waiting 5s...

  L1_Initial_Classification - Batch 276/1705 (Slice Offsets 2475-2483)

  L1_Initial_Classification - Batch 281/1705 (Slice Offsets 2520-2528)
  Waiting 5s...

  L1_Initial_Classification - Batch 286/1705 (Slice Offsets 2565-2573)

  L1_Initial_Classification - Batch 291/1705 (Slice Offsets 2610-2618)
  Waiting 5s...

  L1_Initial_Classification - Batch 296/1705 (Slice Offsets 2655-2663)

  L1_Initial_Classification - Batch 301/1705 (Slice Offsets 2700-2708)
  Waiting 5s...

  L1_Initial_Classification - Batch 306/1705 (Slice Offsets 2745-2753)

  L1_Initial_Classification - Batch 311/1705 (Slice Offsets 2790-2798)
  Waiting 5s...

  L1_Initial_Classification - Batch 316/1705 (Slice Offsets 2835-2843)

  L1_Initial_Classification - Batch 321/1705 (Slice Offsets 2880-2888)
  Waiting 5s...

  L1_Initial_Classification - Batch 326/1705 (Slice Offsets 2925-2933)

  L1_Initial_Classification - Batch 331/1705 (Slice Offsets 2970-2978)
  Waiting 5s...

  L1_Initial_Classification - Batch 336/1705 (Slice Offsets 3015-3023)

  L1_Initial_Classification - Batch 341/1705 (Slice Offsets 3060-3068)
  Waiting 5s...

  L1_Initial_Classification - Batch 346/1705 (Slice Offsets 3105-3113)

  L1_Initial_Classification - Batch 351/1705 (Slice Offsets 3150-3158)
  Waiting 5s...

  L1_Initial_Classification - Batch 356/1705 (Slice Offsets 3195-3203)

  L1_Initial_Classification - Batch 361/1705 (Slice Offsets 3240-3248)
  Waiting 5s...

  L1_Initial_Classification - Batch 366/1705 (Slice Offsets 3285-3293)

  L1_Initial_Classification - Batch 371/1705 (Slice Offsets 3330-3338)
  Waiting 5s...

  L1_Initial_Classification - Batch 376/1705 (Slice Offsets 3375-3383)

  L1_Initial_Classification - Batch 381/1705 (Slice Offsets 3420-3428)
  Waiting 5s...

  L1_Initial_Classification - Batch 386/1705 (Slice Offsets 3465-3473)

  L1_Initial_Classification - Batch 391/1705 (Slice Offsets 3510-3518)
  Waiting 5s...

  L1_Initial_Classification - Batch 396/1705 (Slice Offsets 3555-3563)

  L1_Initial_Classification - Batch 401/1705 (Slice Offsets 3600-3608)
  Waiting 5s...

  L1_Initial_Classification - Batch 406/1705 (Slice Offsets 3645-3653)

  L1_Initial_Classification - Batch 411/1705 (Slice Offsets 3690-3698)
  Waiting 5s...

  L1_Initial_Classification - Batch 416/1705 (Slice Offsets 3735-3743)

  L1_Initial_Classification - Batch 421/1705 (Slice Offsets 3780-3788)
  Waiting 5s...

  L1_Initial_Classification - Batch 426/1705 (Slice Offsets 3825-3833)

  L1_Initial_Classification - Batch 431/1705 (Slice Offsets 3870-3878)
  Waiting 5s...

  L1_Initial_Classification - Batch 436/1705 (Slice Offsets 3915-3923)

  L1_Initial_Classification - Batch 441/1705 (Slice Offsets 3960-3968)
  Waiting 5s...

  L1_Initial_Classification - Batch 446/1705 (Slice Offsets 4005-4013)

  L1_Initial_Classification - Batch 451/1705 (Slice Offsets 4050-4058)
  Waiting 5s...

  L1_Initial_Classification - Batch 456/1705 (Slice Offsets 4095-4103)

  L1_Initial_Classification - Batch 461/1705 (Slice Offsets 4140-4148)
  Waiting 5s...

  L1_Initial_Classification - Batch 466/1705 (Slice Offsets 4185-4193)

  L1_Initial_Classification - Batch 471/1705 (Slice Offsets 4230-4238)
  Waiting 5s...

  L1_Initial_Classification - Batch 476/1705 (Slice Offsets 4275-4283)

  L1_Initial_Classification - Batch 481/1705 (Slice Offsets 4320-4328)
  Waiting 5s...

  L1_Initial_Classification - Batch 486/1705 (Slice Offsets 4365-4373)

  L1_Initial_Classification - Batch 491/1705 (Slice Offsets 4410-4418)
  Waiting 5s...

  L1_Initial_Classification - Batch 496/1705 (Slice Offsets 4455-4463)

  L1_Initial_Classification - Batch 501/1705 (Slice Offsets 4500-4508)
  Waiting 5s...

  L1_Initial_Classification - Batch 506/1705 (Slice Offsets 4545-4553)

  L1_Initial_Classification - Batch 511/1705 (Slice Offsets 4590-4598)
  Waiting 5s...

  L1_Initial_Classification - Batch 516/1705 (Slice Offsets 4635-4643)

  L1_Initial_Classification - Batch 521/1705 (Slice Offsets 4680-4688)
  Waiting 5s...

  L1_Initial_Classification - Batch 526/1705 (Slice Offsets 4725-4733)

  L1_Initial_Classification - Batch 531/1705 (Slice Offsets 4770-4778)
  Waiting 5s...

  L1_Initial_Classification - Batch 536/1705 (Slice Offsets 4815-4823)

  L1_Initial_Classification - Batch 541/1705 (Slice Offsets 4860-4868)
  Waiting 5s...

  L1_Initial_Classification - Batch 546/1705 (Slice Offsets 4905-4913)

  L1_Initial_Classification - Batch 551/1705 (Slice Offsets 4950-4958)
  Waiting 5s...

  L1_Initial_Classification - Batch 556/1705 (Slice Offsets 4995-5003)

  L1_Initial_Classification - Batch 561/1705 (Slice Offsets 5040-5048)
  Waiting 5s...

  L1_Initial_Classification - Batch 566/1705 (Slice Offsets 5085-5093)

  L1_Initial_Classification - Batch 571/1705 (Slice Offsets 5130-5138)
  Waiting 5s...

  L1_Initial_Classification - Batch 576/1705 (Slice Offsets 5175-5183)

  L1_Initial_Classification - Batch 581/1705 (Slice Offsets 5220-5228)
  Waiting 5s...

  L1_Initial_Classification - Batch 586/1705 (Slice Offsets 5265-5273)

  L1_Initial_Classification - Batch 591/1705 (Slice Offsets 5310-5318)
  Waiting 5s...

  L1_Initial_Classification - Batch 596/1705 (Slice Offsets 5355-5363)

  L1_Initial_Classification - Batch 601/1705 (Slice Offsets 5400-5408)
  Waiting 5s...

  L1_Initial_Classification - Batch 606/1705 (Slice Offsets 5445-5453)

  L1_Initial_Classification - Batch 611/1705 (Slice Offsets 5490-5498)
  Waiting 5s...

  L1_Initial_Classification - Batch 616/1705 (Slice Offsets 5535-5543)

  L1_Initial_Classification - Batch 621/1705 (Slice Offsets 5580-5588)
  Waiting 5s...

  L1_Initial_Classification - Batch 626/1705 (Slice Offsets 5625-5633)

  L1_Initial_Classification - Batch 631/1705 (Slice Offsets 5670-5678)
  Waiting 5s...


,id,full_text,l1_goal,l1_method
0,101116741,Digitizing Other Economies: A Comparative Appr...,Understanding Digital Adoption in Non-Industri...,Comparative Ethnographic Analysis of Digitization
1,101163161,MOLECULAR QUANTUM DYNAMICS IN LOW TEMPERATURE ...,Unveiling Astrochemistry of Molecular Ices,Molecular Quantum Dynamics & Spectroscopy
2,101160499,Multiscale modelling of aberrant phase transit...,Resolving Aberrant Condensate Dynamics in Cells,Multiscale Computational Modeling of Biomolecules
3,101166905,The first comprehensive Atlas of the Milky Way...,Creating a 3D Map of the Milky Way,Comprehensive Galactic Data Integration & Mapping
4,101162875,Untapping multiparametric 2D luminescence sens...,Improving Cellular Luminescence Nanosensing Re...,Machine Learning & Spectral Sorting of Signals

Saved updated df_complete after L1_Initial_Classification to checkpoint: df_processing_checkpoint.csv

In [5]:
# ## Stage 1.1: Fixing Failed L1 Classifications
# --- Stage 1.1 Configuration ---
STAGE_NAME_S1_FIX = "L1_Fix_Failed_Classification"

# We re-use the prompt, item format, input fields, LLM labels, and output columns 
# from Stage 1 (defined in Cell 4 / your In[5]).


# Define an eligibility filter specifically for rows that failed in Stage 1
def eligibility_filter_s1_fix(df: pd.DataFrame) -> pd.Series:
    # Ensure the output columns from S1 exist in the DataFrame
    # OUTPUT_COL_NAMES_S1 is {"s1_goal_parsed": "l1_goal", "s1_method_parsed": "l1_method"}
    l1_goal_col = OUTPUT_COL_NAMES_S1.get("s1_goal_parsed", "l1_goal") # Get actual column name
    l1_method_col = OUTPUT_COL_NAMES_S1.get("s1_method_parsed", "l1_method")

    if l1_goal_col not in df.columns or l1_method_col not in df.columns:
        print(f"Warning for {STAGE_NAME_S1_FIX} eligibility: '{l1_goal_col}' or '{l1_method_col}' columns are missing.")
        return pd.Series([False] * len(df), index=df.index) 

    # Define what constitutes a "failure" from Stage 1 that needs fixing.
    failed_values_to_retry = [
        "Parse Error (Key Missing)", 
        "Not Found in LLM Output", 
        "API Error in Batch", 
        "Classification Failed", # If S1 used validation that could result in this
        ""                       # Empty string from LLM might indicate failure to extract
        # pd.NA # Handled by .isnull() below
    ]

    # A row needs fixing if either its l1_goal or l1_method contains one of the failure indicators, or is null.
    failed_l1_goal = df[l1_goal_col].astype(str).isin(failed_values_to_retry) | df[l1_goal_col].isnull()
    failed_l1_method = df[l1_method_col].astype(str).isin(failed_values_to_retry) | df[l1_method_col].isnull()
    
    return failed_l1_goal | failed_l1_method

# --- Execute Stage 1.1 ---
# df_complete is the main DataFrame, assumed to be updated by Cell 4 (Stage 1)
# model, RUN_OVERALL_TRIAL_MODE, etc., are from Cell 1 (your In[19])
# MAIN_DATAFRAME_CHECKPOINT_FILE from Cell 1

if 'df_complete' in locals() and isinstance(df_complete, pd.DataFrame) and not df_complete.empty and model:
    
    rows_needing_s1_fix_mask = eligibility_filter_s1_fix(df_complete)
    if not rows_needing_s1_fix_mask.any():
        print(f"Stage {STAGE_NAME_S1_FIX}: No rows found needing L1 fix based on current failure criteria. df_complete remains unchanged.")
        # Optionally, save the checkpoint even if no fixes were made, to mark this step as considered
        # try:
        #     df_complete.to_csv(MAIN_DATAFRAME_CHECKPOINT_FILE, index=False)
        #     print(f"No L1 fixes needed. Saved current df_complete to checkpoint: {MAIN_DATAFRAME_CHECKPOINT_FILE}")
        # except Exception as e:
        #     print(f"Error saving checkpoint when no L1 fixes needed: {e}")
    else:
        print(f"Input for Stage 1.1 ({STAGE_NAME_S1_FIX}): df_complete with {len(df_complete)} total rows.")
        print(f"Number of rows targeted for L1 fixing: {rows_needing_s1_fix_mask.sum()}")
        
        # Ensure 'full_text' (from INPUT_FIELDS_S1) column exists for the fix stage
        if INPUT_FIELDS_S1[0] not in df_complete.columns: # Assuming INPUT_FIELDS_S1 = ['full_text']
            print(f"CRITICAL ERROR for {STAGE_NAME_S1_FIX}: Required input column '{INPUT_FIELDS_S1[0]}' is missing. Cannot proceed.")
        else:
            df_complete = process_stage( # Reassign to update df_complete
                df_main=df_complete,       
                stage_name=STAGE_NAME_S1_FIX,
                prompt_template_str=PROMPT_TEMPLATE_S1, # Reuse S1 prompt
                item_prompt_format_str=ITEM_PROMPT_FORMAT_S1, # Reuse S1 item format
                input_fields_for_prompt=INPUT_FIELDS_S1,     # Reuse S1 input fields
                llm_expected_labels_map=LLM_EXPECTED_LABELS_S1, # Reuse S1 LLM label map
                output_col_names_map=OUTPUT_COL_NAMES_S1,    # Output to the same l1_goal, l1_method cols
                model_instance=model,
                eligibility_filter_fn=eligibility_filter_s1_fix, # This is the key difference
                run_trial_mode=RUN_OVERALL_TRIAL_MODE, 
                max_batches_trial=MAX_BATCHES_FOR_TRIAL, 
                batch_size=5,  # Smaller batch size for fixing
                wait_time=10,  # Override default for fixing (or use DEFAULT_WAIT_TIME)
                llm_output_separator=None # S1 prompt implies no "---"
            )
            
            if not df_complete.empty:
                print(f"\n{STAGE_NAME_S1_FIX} completed.")
                # Display a sample of rows that were targeted by the fix process.
                # It's useful to see their state *after* the fix attempt.
                print("Sample of rows that were targeted for L1 Fix (first 5, showing L1 cols):")
                # from IPython.display import display # Should be imported in Cell 3
                # We use the mask `rows_needing_s1_fix_mask` which was calculated *before* this process_stage call.
                # This shows the rows that *were* targeted. Their values in df_complete are now updated.
                cols_to_display_s1_fix = ['id', 'full_text'] + list(OUTPUT_COL_NAMES_S1.values())
                cols_to_display_s1_fix = [col for col in cols_to_display_s1_fix if col in df_complete.columns]
                if rows_needing_s1_fix_mask.any() and cols_to_display_s1_fix: # Only display if some were targeted and cols exist
                     display(df_complete[rows_needing_s1_fix_mask][cols_to_display_s1_fix].head())
                else:
                     print("No rows were targeted for fix, or relevant columns are missing for display.")


                # Save the updated df_complete to the main checkpoint file
                try:
                    df_complete.to_csv(MAIN_DATAFRAME_CHECKPOINT_FILE, index=False) # OVERWRITE
                    print(f"Saved updated df_complete after {STAGE_NAME_S1_FIX} to checkpoint: {MAIN_DATAFRAME_CHECKPOINT_FILE}")
                except Exception as e:
                    print(f"Error saving checkpoint after {STAGE_NAME_S1_FIX}: {e}")
            else:
                print(f"Stage {STAGE_NAME_S1_FIX} resulted in an empty DataFrame. This should be investigated.")
else:
    if 'df_complete' not in locals() or not isinstance(df_complete, pd.DataFrame) or df_complete.empty:
        print(f"Skipping Stage {STAGE_NAME_S1_FIX}: DataFrame 'df_complete' (from Stage 1 processing) is not available or is empty.")
    if not model:
        print(f"Skipping Stage {STAGE_NAME_S1_FIX}: LLM Model is not initialized.")

Stage L1_Fix_Failed_Classification: No rows found needing L1 fix based on current failure criteria. df_complete remains unchanged.

In [6]:
# ## Stage 2: L2 Generalization of Goal and Method
STAGE_NAME_S2 = "L2_Generalization"

# Full prompt for L2 Generalization (PROMPT_PREFIX_L2_GENERALIZE from your original script)
PROMPT_TEMPLATE_S2_FULL = """You are an expert taxonomist creating highly searchable, general category labels for EU research projects to improve grouping and navigation.

You will receive a Project Summary, an Initial Goal, and an Initial Method.
Your task is to elevate the Initial labels into **Generalized Goal** and **Generalized Method** labels.

**Core Generalization Principle: Think Like a User Searching for Categories & Strive for Broader Groupings.**
*   Generalized labels should be intuitive category headings a user would search for.
*   Use the **Project Summary** for essential context to find the most accurate encompassing category.
*   **Your primary task is to abstract to a significantly broader level of generality.** Only if an initial label is *already* a very broad, established, and highly searchable category, AND further generalization would make it too vague or inaccurate, may it be minimally adjusted or (rarely) reused.

Instructions & Examples (Crucial):
1.  **4 Words Max** per label.
2.  **Generalized Goal:** (Keep as is from previous good version - focuses on "goal-ness")
    *   The overarching domain of impact or strategic objective.
    *   **Must clearly articulate an aim, improvement, or achievement.** Think: "What is being *advanced, improved, developed, understood, achieved, or made possible*?"
    *   *Good (Improvement/Action):* 'Cellular Nanosensing Improvement,' 'Transport Decarbonization,' 'Regional Innovation Support.'
    *   *Good (Advancement/Understanding for research):* 'Advancing Astrochemistry Knowledge,' 'Uncovering Disease Mechanisms.'
    *   *Avoid (Static Topic/Problem):* 'Biocondensate Dysfunction,' 'Molecular Origins.'
3.  **Generalized Method: Identify a significantly broader conceptual category for the approach.**
    *   For the **Generalized Method**, aim for a high-level categorization suitable for broad user searches.
    *   Think: "What is the *most encompassing and widely understood category* for this type of work, moving up the conceptual hierarchy?"
    *   **For specific scientific/technical methods:**
        *   Your goal is to find a label that groups many specific techniques. Consider moving from the *specific technique* -> to its *broader technical field* -> and if that field is still too niche for top-level search, consider an even *more general scientific/engineering domain or type of analytical approach.*
        *   *Example - Path to Abstraction:*
            *   Initial: "Machine Learning Algorithm for Image Recognition"
            *   (Intermediate thought: Broader field is "Artificial Intelligence" or "Computer Science Applications")
            *   **Generalized Method: Applied Computational Methods** (if "AI" or "CS Apps" is still too granular for your top-level taxonomy) or **AI & Data Analytics**
        *   *More Examples:*
            *   Initial: "Quantum Dynamics of Condensed Phase Systems" -> **Generalized Method: Advanced Scientific Modeling** (or **Theoretical Physics Methods**)
            *   Initial: "Comparative Ethnographic Digital Analysis" -> **Generalized Method: Social Science Research** (or **Qualitative Data Analysis**)
    *   **For activities/processes (e.g., conferences, policy work):** Generalize to the fundamental *type* of strategic action, collaboration, or engagement.
        *   Initial: "Policy dialogue via research conference" -> **Generalized Method: Stakeholder Engagement Strategies**
        *   Initial: "Transnational Joint Action Planning" -> **Generalized Method: Collaborative Program Development**
    *   **Avoid minimal rephrasing. Seek a clear jump in abstraction.**
4.  **Wording:** Use established, common, searchable terms.
5.  **Relevance & Context:** Generalized labels must be direct conceptual parents of the initial labels, deeply informed by the **Project Summary**.
6.  **Unassigned:** For "Unassigned" initial inputs, output "Unassigned."

Output Format (one section per project, separated by "---"):
Goal Summary: [short generalized label]
Method Summary: [short generalized label]
---

Example of processing an individual project input:
Project Summary: The project aims to organize a series of workshops and a final conference bringing together policymakers, industry leaders, and researchers to discuss and formulate new strategies for reducing CO2 emissions in the European logistics sector, particularly focusing on heavy-duty vehicles.
Initial Goal: New strategies for CO2 reduction in logistics
Initial Method: Workshops & Conference for Policy Formulation

Your output for this project:
Goal Summary: Transport Decarbonization
Method Summary: Stakeholder Engagement
---

Now, analyze the following projects. For each, provide 'Goal Summary' and 'Method Summary' per format, separated by "---".
"""

ITEM_PROMPT_FORMAT_S2 = (
    "\nProject #{project_num_in_prompt}:\n" 
    "Project Summary: {full_text}\n"      # Placeholder for full_text from DataFrame
    "Initial Goal: {l1_goal}\n"           # Placeholder for l1_goal from DataFrame (output of S1/S1.1)
    "Initial Method: {l1_method}\n"       # Placeholder for l1_method from DataFrame (output of S1/S1.1)
) 

INPUT_FIELDS_S2 = ['full_text', 'l1_goal', 'l1_method'] 

LLM_EXPECTED_LABELS_S2 = {"Goal Summary:": "s2_g_goal_parsed", "Method Summary:": "s2_g_method_parsed"}

OUTPUT_COL_NAMES_S2 = {"s2_g_goal_parsed": "l2_generalized_goal", "s2_g_method_parsed": "l2_generalized_method"}

# Eligibility for L2: L1 goal and method must be valid and not error placeholders.
def eligibility_filter_s2(df: pd.DataFrame) -> pd.Series:
    # Ensure L1 output columns exist
    l1_goal_col = OUTPUT_COL_NAMES_S1.get("s1_goal_parsed", "l1_goal") # From S1 config
    l1_method_col = OUTPUT_COL_NAMES_S1.get("s1_method_parsed", "l1_method") # From S1 config

    if l1_goal_col not in df.columns or l1_method_col not in df.columns:
        print(f"Warning for {STAGE_NAME_S2} eligibility: '{l1_goal_col}' or '{l1_method_col}' columns missing.")
        return pd.Series([False] * len(df), index=df.index)
    
    # Values from L1 that make a row ineligible for L2
    invalid_l1_values_for_s2_input = [
        "Parse Error (Key Missing)", 
        "Not Found in LLM Output", 
        "API Error in Batch",
        "Classification Failed", 
        "",                      
        "Unassigned", # If "Unassigned" from L1 means LLM couldn't determine L1 goal/method
        "Not Processed by Stage",
        "Not Eligible for Stage",
        "Input Error (full_text missing)", # If S1 couldn't run due to this
        pd.NA                   
    ]

    is_l1_goal_valid = df[l1_goal_col].notna() & (~df[l1_goal_col].astype(str).isin(invalid_l1_values_for_s2_input))
    is_l1_method_valid = df[l1_method_col].notna() & (~df[l1_method_col].astype(str).isin(invalid_l1_values_for_s2_input))
    
    return is_l1_goal_valid & is_l1_method_valid

# --- Execute Stage 2 ---
# df_complete is the main DataFrame, assumed to be updated by Cell 5 (Stage 1.1 Fix)
# model, RUN_OVERALL_TRIAL_MODE, etc., are from Cell 1 (your In[19])
# MAIN_DATAFRAME_CHECKPOINT_FILE from Cell 1

if 'df_complete' in locals() and isinstance(df_complete, pd.DataFrame) and not df_complete.empty and model:
    print(f"Input for Stage 2 ({STAGE_NAME_S2}): df_complete with {len(df_complete)} rows.")
    print(f"df_complete columns before S2: {df_complete.columns.tolist()}")
    
    s2_input_cols_ok = all(col in df_complete.columns for col in INPUT_FIELDS_S2)
    
    if s2_input_cols_ok:
        df_complete = process_stage( 
            df_main=df_complete, 
            stage_name=STAGE_NAME_S2,
            prompt_template_str=PROMPT_TEMPLATE_S2_FULL,
            item_prompt_format_str=ITEM_PROMPT_FORMAT_S2,
            input_fields_for_prompt=INPUT_FIELDS_S2,
            llm_expected_labels_map=LLM_EXPECTED_LABELS_S2,
            output_col_names_map=OUTPUT_COL_NAMES_S2,
            model_instance=model,
            eligibility_filter_fn=eligibility_filter_s2, 
            run_trial_mode=RUN_OVERALL_TRIAL_MODE,
            max_batches_trial=MAX_BATCHES_FOR_TRIAL,
            batch_size=DEFAULT_BATCH_SIZE, 
            wait_time=DEFAULT_WAIT_TIME,   
            llm_output_separator="---" # L2 prompt specifies "---" as output separator
        )
        
        if not df_complete.empty:
            print(f"\n{STAGE_NAME_S2} completed. df_complete columns after S2: {df_complete.columns.tolist()}")
            print(f"Sample of updated df_complete (first 5 rows showing L1 and L2 cols):")
            # from IPython.display import display # Should be imported in Cell 3
            cols_to_display_s2 = ['id', 'full_text'] + \
                                 [OUTPUT_COL_NAMES_S1.get("s1_goal_parsed", "l1_goal"), OUTPUT_COL_NAMES_S1.get("s1_method_parsed", "l1_method")] + \
                                 list(OUTPUT_COL_NAMES_S2.values())
            cols_to_display_s2 = [col for col in cols_to_display_s2 if col in df_complete.columns]
            if cols_to_display_s2: display(df_complete[cols_to_display_s2].head())


            # Save the updated df_complete to the main checkpoint file
            try:
                df_complete.to_csv(MAIN_DATAFRAME_CHECKPOINT_FILE, index=False) # OVERWRITE
                print(f"Saved updated df_complete after {STAGE_NAME_S2} to checkpoint: {MAIN_DATAFRAME_CHECKPOINT_FILE}")
            except Exception as e:
                print(f"Error saving checkpoint after {STAGE_NAME_S2}: {e}")
        else:
            print(f"Stage {STAGE_NAME_S2} resulted in an empty DataFrame.")
    else:
        print(f"Skipping {STAGE_NAME_S2} due to missing required input columns ({INPUT_FIELDS_S2}) in df_complete.")
else:
    if 'df_complete' not in locals() or not isinstance(df_complete, pd.DataFrame) or df_complete.empty:
        print(f"Skipping Stage 2: DataFrame 'df_complete' (from Stage 1.1 Fix) is not available or is empty.")
    if not model:
        print("Skipping Stage 2: LLM Model is not initialized.")

Input for Stage 2 (L2_Generalization): df_complete with 15341 rows.
df_complete columns before S2: ['id', 'full_text', 'l1_goal', 'l1_method']

==================== Running Stage: L2_Generalization on DataFrame with 15341 rows ====================
Stage L2_Generalization: 15341 rows eligible for THIS processing call out of 15341.
Stage L2_Generalization: FULL MODE - Will send 15341 (eligible) records to API.
  Will take 415 batches. Est. API wait: 34.6 min.


  L2_Generalization - Batch 1/415 (Slice Offsets 0-36)

=== FIRST PROMPT FOR BATCH 1 (Structure Preview) ===
You are an expert taxonomist creating highly searchable, general category labels for EU research projects to improve grouping and navigation.

You will receive a Project Summary, an Initial Goal, and an Initial Method.
Your task is to elevate the Initial labels into **Generalized Goal** and **Generalized Method** labels.

**Core Generalization Principle: Think Like a User Searching for Categories & Strive for Broader Groupings.**
*   Generalized labels should be intuitive category headings a user would search for.
*   Use the **Project Summary** for essential context to find the most accurate encompassing category.
*   **Your primary task is to abstract to a significantly broader level of generality.** Only if an initial label is *already* a very broad, established, and highly searchable category, AND further generalization would make it too vague or inaccurate, may it be minimally adjusted or (rarely) reused.

Instructions & Examples (Crucial):
1.  **4 Words Max** per label.
2.  **Gen...
Item Format Example:
Project #1:
Project Summary: [SAMPLE_FULL_TEXT_FROM_DATA]
Initial Goal: [SAMPLE_L1_GOAL_FROM_DATA]
Initial Method: [SAMPLE_L1_METHOD_FROM_DATA]

=== END PROMPT PREVIEW ===


--- RAW LLM OUTPUT (Batch 1, 37 items) ---
Project #1:
Goal Summary: Socio-Digital Transformation
Method Summary: Social Science Research
---
Project #2:
Goal Summary: Astrochemical Process Understanding
Method Summary: Scientific Modeling & Experimentation
---
Project #3:
Goal Summary: Understanding Cellular Mechanisms
Method Summary: Computational Biology Methods
---
Project #4:
Goal Summary: Mapping Cosmic Structures
Method Summary: Large-scale Data Mapping
---
Project #5:
Goal Summary: Improving Bio-Sensing Technology
Method Summary: AI & Data Analytics
---
Project #6:
Goal Summary: Advancing Fundamental Physics
Method Summary: Advanced Data Analytics
---
Project #7:
Goal Summary: Understanding Information Systems History
Method Summary: Historical Archival Research
---
Project #8:
Goal Summary: Strengthening Research Integration
Method Summary: Capacity Building & Networking
---
Project #9:
Goal Summary: Promoting Research Dissemination
Method Summary: Stakeholder Engagement Strategies
---
Project #10:
Goal Summary: Accele...
--- END RAW LLM OUTPUT ---

--- PARSED LABELS (Batch 1) ---
  Item in batch at offset 0: {'s2_g_goal_parsed': 'Socio-Digital Transformation', 's2_g_method_parsed': 'Social Science Research'}
  Item in batch at offset 1: {'s2_g_goal_parsed': 'Astrochemical Process Understanding', 's2_g_method_parsed': 'Scientific Modeling & Experimentation'}
  Item in batch at offset 2: {'s2_g_goal_parsed': 'Understanding Cellular Mechanisms', 's2_g_method_parsed': 'Computational Biology Methods'}
  Item in batch at offset 3: {'s2_g_goal_parsed': 'Mapping Cosmic Structures', 's2_g_method_parsed': 'Large-scale Data Mapping'}
  Item in batch at offset 4: {'s2_g_goal_parsed': 'Improving Bio-Sensing Technology', 's2_g_method_parsed': 'AI & Data Analytics'}
  Item in batch at offset 5: {'s2_g_goal_parsed': 'Advancing Fundamental Physics', 's2_g_method_parsed': 'Advanced Data Analytics'}
  Item in batch at offset 6: {'s2_g_goal_parsed': 'Understanding Information Systems History', 's2_g_method_parsed': 'Historical Archival Research'}
  Item in batch at offset 7: {'s2_g_goal_parsed': 'Strengthening Research Integration', 's2_g_method_parsed': 'Capacity Building & Networking'}
  Item in batch at offset 8: {'s2_g_goal_parsed': 'Promoting Research Dissemination', 's2_g_method_parsed': 'Stakeholder Engagement Strategies'}
  Item in batch at offset 9: {'s2_g_goal_parsed': 'Accelerating Technology Commercialization', 's2_g_method_parsed': 'Innovation Feasibility Assessment'}
  Item in batch at offset 10: {'s2_g_goal_parsed': 'Advancing Digital Healthcare', 's2_g_method_parsed': 'Digital Health Solution Development'}
  Item in batch at offset 11: {'s2_g_goal_parsed': 'Advancing Reproductive Medicine', 's2_g_method_parsed': 'Biomarker Discovery & Validation'}
  Item in batch at offset 12: {'s2_g_goal_parsed': 'Promoting Inclusive Education', 's2_g_method_parsed': 'Educational Technology Development'}
  Item in batch at offset 13: {'s2_g_goal_parsed': 'Cultivating Research Careers', 's2_g_method_parsed': 'Youth Engagement Programs'}
  Item in batch at offset 14: {'s2_g_goal_parsed': 'Fostering Youth Innovation', 's2_g_method_parsed': 'Youth Engagement Programs'}
  Item in batch at offset 15: {'s2_g_goal_parsed': 'Promoting Open Science Practices', 's2_g_method_parsed': 'Policy Impact Assessment'}
  Item in batch at offset 16: {'s2_g_goal_parsed': 'Science for Urban Development', 's2_g_method_parsed': 'Strategic Urban Development'}
  Item in batch at offset 17: {'s2_g_goal_parsed': 'Supporting Researcher Mobility', 's2_g_method_parsed': 'Financial Service Enhancement'}
  Item in batch at offset 18: {'s2_g_goal_parsed': 'Addressing Global Challenges', 's2_g_method_parsed': 'Talent Development Programs'}
  Item in batch at offset 19: {'s2_g_goal_parsed': 'Developing Research Policy', 's2_g_method_parsed': 'Stakeholder Engagement Strategies'}
  Item in batch at offset 20: {'s2_g_goal_parsed': 'Promoting Knowledge Valorisation', 's2_g_method_parsed': 'Collaborative Innovation Pilots'}
  Item in batch at offset 21: {'s2_g_goal_parsed': 'Enhancing Public Science Engagement', 's2_g_method_parsed': 'Science Outreach Events'}
  Item in batch at offset 22: {'s2_g_goal_parsed': 'Supporting Researcher Mobility', 's2_g_method_parsed': 'Financial Infrastructure Development'}
  Item in batch at offset 23: {'s2_g_goal_parsed': 'Cultivating Scientific Talent', 's2_g_method_parsed': 'Youth Engagement Programs'}
  Item in batch at offset 24: {'s2_g_goal_parsed': 'Driving Climate Innovation', 's2_g_method_parsed': 'Collaborative Innovation Strategies'}
  Item in batch at offset 25: {'s2_g_goal_parsed': 'Promoting Global Innovation', 's2_g_method_parsed': 'International Network Development'}
  Item in batch at offset 26: {'s2_g_goal_parsed': 'Ensuring Digital Autonomy', 's2_g_method_parsed': 'Entrepreneurship & Talent Development'}
  Item in batch at offset 27: {'s2_g_goal_parsed': 'Developing Cancer Therapies', 's2_g_method_parsed': 'Preclinical Drug Development'}
  Item in batch at offset 28: {'s2_g_goal_parsed': 'Sustainable Infrastructure Management', 's2_g_method_parsed': 'AI-powered Remote Sensing'}
  Item in batch at offset 29: {'s2_g_goal_parsed': 'Improving Patient Care Quality', 's2_g_method_parsed': 'Medical Device Development'}
  Item in batch at offset 30: {'s2_g_goal_parsed': 'Optimizing Research Infrastructures', 's2_g_method_parsed': 'Stakeholder Engagement Strategies'}
  Item in batch at offset 31: {'s2_g_goal_parsed': 'Accelerating Medical Innovation', 's2_g_method_parsed': 'Strategic Fundraising Initiatives'}
  Item in batch at offset 32: {'s2_g_goal_parsed': 'Promoting Open Science Governance', 's2_g_method_parsed': 'Policy Monitoring System Development'}
  Item in batch at offset 33: {'s2_g_goal_parsed': 'Improving Medical Imaging Safety', 's2_g_method_parsed': 'AI-driven Medical Diagnostics'}
  Item in batch at offset 34: {'s2_g_goal_parsed': 'Promoting Circular Economy', 's2_g_method_parsed': 'Sustainable Industrial Biotechnology'}
  Item in batch at offset 35: {'s2_g_goal_parsed': 'Developing Entrepreneurial Talent', 's2_g_method_parsed': 'Entrepreneurship Education Programs'}
  Item in batch at offset 36: {'s2_g_goal_parsed': 'Fostering Regional Innovation', 's2_g_method_parsed': 'Innovation Network Development'}
  (Parsed 37 items from this batch output, expected 37)
--- END PARSED LABELS ---

  Batch 1 outcome: Labels extracted.
  Waiting 5s...

  L2_Generalization - Batch 2/415 (Slice Offsets 37-73)
Error on API call attempt 1 for batch 2, offset 37: DeadlineExceeded - 504 Deadline Exceeded
Sleeping for 1s before retry...

--- RAW LLM OUTPUT (Batch 2, 37 items) ---
Goal Summary: Agri-food Ecosystem Development
Method Summary: Digital Network Building
---
Goal Summary: Healthcare Innovation Adoption
Method Summary: Innovation Procurement Policy
---
Goal Summary: Innovation Ecosystem Development
Method Summary: Collaborative Capacity Building
---
Goal Summary: Industrial Sustainability Transition
Method Summary: Collaborative Policy Development
---
Goal Summary: Social Entrepreneurship Development
Method Summary: Knowledge & Learning Platforms
---
Goal Summary: Regional Innovation Equity
Method Summary: Collaborative Framework Development
---
Goal Summary: Urban Decarbonization Acceleration
Method Summary: Innovation Networking & Matchmaking
---
Goal Summary: Regional Innovation Ecosystem Capacity
Method Summary: Collaborative Program Development
---
Goal Summary: Urban Innovation Procurement Improvement
Method Summary: Public Procurement Training
---
Goal Summary: Life Sciences Innovation Advancement
Method Summary: Inter-Ecosystem Collaboration
-...
--- END RAW LLM OUTPUT ---

--- PARSED LABELS (Batch 2) ---
  Item in batch at offset 0: {'s2_g_goal_parsed': 'Agri-food Ecosystem Development', 's2_g_method_parsed': 'Digital Network Building'}
  Item in batch at offset 1: {'s2_g_goal_parsed': 'Healthcare Innovation Adoption', 's2_g_method_parsed': 'Innovation Procurement Policy'}
  Item in batch at offset 2: {'s2_g_goal_parsed': 'Innovation Ecosystem Development', 's2_g_method_parsed': 'Collaborative Capacity Building'}
  Item in batch at offset 3: {'s2_g_goal_parsed': 'Industrial Sustainability Transition', 's2_g_method_parsed': 'Collaborative Policy Development'}
  Item in batch at offset 4: {'s2_g_goal_parsed': 'Social Entrepreneurship Development', 's2_g_method_parsed': 'Knowledge & Learning Platforms'}
  Item in batch at offset 5: {'s2_g_goal_parsed': 'Regional Innovation Equity', 's2_g_method_parsed': 'Collaborative Framework Development'}
  Item in batch at offset 6: {'s2_g_goal_parsed': 'Urban Decarbonization Acceleration', 's2_g_method_parsed': 'Innovation Networking & Matchmaking'}
  Item in batch at offset 7: {'s2_g_goal_parsed': 'Regional Innovation Ecosystem Capacity', 's2_g_method_parsed': 'Collaborative Program Development'}
  Item in batch at offset 8: {'s2_g_goal_parsed': 'Urban Innovation Procurement Improvement', 's2_g_method_parsed': 'Public Procurement Training'}
  Item in batch at offset 9: {'s2_g_goal_parsed': 'Life Sciences Innovation Advancement', 's2_g_method_parsed': 'Inter-Ecosystem Collaboration'}
  Item in batch at offset 10: {'s2_g_goal_parsed': 'Gender-Inclusive Investment Mobilization', 's2_g_method_parsed': 'Innovation Networking & Knowledge Exchange'}
  Item in batch at offset 11: {'s2_g_goal_parsed': 'Social Entrepreneurship Development', 's2_g_method_parsed': 'Cross-Sector Capacity Building'}
  Item in batch at offset 12: {'s2_g_goal_parsed': 'Sustainable Mobility Advancement', 's2_g_method_parsed': 'Ecosystem Networking & Support'}
  Item in batch at offset 13: {'s2_g_goal_parsed': 'Regional Innovation Ecosystem Development', 's2_g_method_parsed': 'Collaborative Ecosystem Programs'}
  Item in batch at offset 14: {'s2_g_goal_parsed': 'Aging in Place Support', 's2_g_method_parsed': 'AI-Powered Monitoring Systems'}
  Item in batch at offset 15: {'s2_g_goal_parsed': 'Clean Tech Ecosystem Development', 's2_g_method_parsed': 'Ecosystem Diagnostics & Learning'}
  Item in batch at offset 16: {'s2_g_goal_parsed': 'Global Digital Connectivity', 's2_g_method_parsed': 'Digital Infrastructure Investment'}
  Item in batch at offset 17: {'s2_g_goal_parsed': 'Business Operations Optimization', 's2_g_method_parsed': 'Business Intelligence Solutions'}
  Item in batch at offset 18: {'s2_g_goal_parsed': 'Surgical Treatment Advancement', 's2_g_method_parsed': 'Medical Device Development'}
  Item in batch at offset 19: {'s2_g_goal_parsed': 'Minimally Invasive Surgery Advancement', 's2_g_method_parsed': 'Surgical Imaging Development'}
  Item in batch at offset 20: {'s2_g_goal_parsed': 'Regional Innovation Procurement', 's2_g_method_parsed': 'Policy Development & Planning'}
  Item in batch at offset 21: {'s2_g_goal_parsed': 'Research Infrastructure Impact', 's2_g_method_parsed': 'Strategic Knowledge Dissemination'}
  Item in batch at offset 22: {'s2_g_goal_parsed': 'Startup Ecosystem Development', 's2_g_method_parsed': 'Collaborative Framework Development'}
  Item in batch at offset 23: {'s2_g_goal_parsed': 'Decentralized Finance Risk Assessment', 's2_g_method_parsed': 'Blockchain Data Analytics'}
  Item in batch at offset 24: {'s2_g_goal_parsed': 'Healthcare Data Security', 's2_g_method_parsed': 'Privacy-Enhancing Technologies'}
  Item in batch at offset 25: {'s2_g_goal_parsed': 'Industrial Materials Analysis', 's2_g_method_parsed': 'Advanced Spectroscopic Techniques'}
  Item in batch at offset 26: {'s2_g_goal_parsed': 'Additive Manufacturing Improvement', 's2_g_method_parsed': 'AI Process Optimization'}
  Item in batch at offset 27: {'s2_g_goal_parsed': 'Drug Development Acceleration', 's2_g_method_parsed': 'Organ-on-Chip Technology'}
  Item in batch at offset 28: {'s2_g_goal_parsed': 'Industrial Decarbonization', 's2_g_method_parsed': 'Renewable Heat Technology'}
  Item in batch at offset 29: {'s2_g_goal_parsed': 'Renewable Hydrogen Production', 's2_g_method_parsed': 'Wave Energy Conversion'}
  Item in batch at offset 30: {'s2_g_goal_parsed': 'Carbon Capture & Utilization', 's2_g_method_parsed': 'Direct Air Capture Technology'}
  Item in batch at offset 31: {'s2_g_goal_parsed': 'Respiratory Disease Diagnostics', 's2_g_method_parsed': 'Diagnostic Platform Development'}
  Item in batch at offset 32: {'s2_g_goal_parsed': 'Sustainable Aquaculture Development', 's2_g_method_parsed': 'Biocontrol System Development'}
  Item in batch at offset 33: {'s2_g_goal_parsed': 'Drug Discovery Acceleration', 's2_g_method_parsed': 'AI-Powered Data Analytics'}
  Item in batch at offset 34: {'s2_g_goal_parsed': 'Digital Forensics Improvement', 's2_g_method_parsed': 'Collaborative Framework Development'}
  Item in batch at offset 35: {'s2_g_goal_parsed': 'Financial Decision Support', 's2_g_method_parsed': 'AI Financial Analytics'}
  Item in batch at offset 36: {'s2_g_goal_parsed': 'Sustainable Electronics Cooling', 's2_g_method_parsed': 'Advanced Cooling Technology'}
  (Parsed 37 items from this batch output, expected 37)
--- END PARSED LABELS ---

  Batch 2 outcome: Labels extracted.
  Waiting 5s...

  L2_Generalization - Batch 3/415 (Slice Offsets 74-110)

--- RAW LLM OUTPUT (Batch 3, 37 items) ---
Project #75:
Goal Summary: Patient Outcome Improvement
Method Summary: Medical Device Development
---
Project #76:
Goal Summary: Regional Innovation Ecosystems
Method Summary: Strategic Collaboration Platform
---
Project #77:
Goal Summary: Higher Education Development
Method Summary: Ecosystem Development Strategy
---
Project #78:
Goal Summary: Innovation Funding Support
Method Summary: Collaborative Investment Strategy
---
Project #79:
Goal Summary: Talent Development Strategy
Method Summary: Cross-KIC Program Development
---
Project #80:
Goal Summary: Sustainable Textiles Development
Method Summary: Technology Business Evaluation
---
Project #81:
Goal Summary: Food Waste Reduction
Method Summary: Smart Packaging Technology
---
Project #82:
Goal Summary: Research Standardization Advancement
Method Summary: Standardization Support Services
---
Project #83:
Goal Summary: Stroke Outcome Improvement
Method Summary: Diagnostic Medical Device
---
Project #84:
Goal Summary: Accelerated Strok...
--- END RAW LLM OUTPUT ---

--- PARSED LABELS (Batch 3) ---
  Item in batch at offset 0: {'s2_g_goal_parsed': 'Patient Outcome Improvement', 's2_g_method_parsed': 'Medical Device Development'}
  Item in batch at offset 1: {'s2_g_goal_parsed': 'Regional Innovation Ecosystems', 's2_g_method_parsed': 'Strategic Collaboration Platform'}
  Item in batch at offset 2: {'s2_g_goal_parsed': 'Higher Education Development', 's2_g_method_parsed': 'Ecosystem Development Strategy'}
  Item in batch at offset 3: {'s2_g_goal_parsed': 'Innovation Funding Support', 's2_g_method_parsed': 'Collaborative Investment Strategy'}
  Item in batch at offset 4: {'s2_g_goal_parsed': 'Talent Development Strategy', 's2_g_method_parsed': 'Cross-KIC Program Development'}
  Item in batch at offset 5: {'s2_g_goal_parsed': 'Sustainable Textiles Development', 's2_g_method_parsed': 'Technology Business Evaluation'}
  Item in batch at offset 6: {'s2_g_goal_parsed': 'Food Waste Reduction', 's2_g_method_parsed': 'Smart Packaging Technology'}
  Item in batch at offset 7: {'s2_g_goal_parsed': 'Research Standardization Advancement', 's2_g_method_parsed': 'Standardization Support Services'}
  Item in batch at offset 8: {'s2_g_goal_parsed': 'Stroke Outcome Improvement', 's2_g_method_parsed': 'Diagnostic Medical Device'}
  Item in batch at offset 9: {'s2_g_goal_parsed': 'Accelerated Stroke Treatment', 's2_g_method_parsed': 'Advanced Diagnostic Development'}
  Item in batch at offset 10: {'s2_g_goal_parsed': 'Electronics Material Innovation', 's2_g_method_parsed': 'Nanomaterial Production Technology'}
  Item in batch at offset 11: {'s2_g_goal_parsed': 'Solar Energy Optimization', 's2_g_method_parsed': 'AI for Energy Management'}
  Item in batch at offset 12: {'s2_g_goal_parsed': 'Industrial Decarbonization Solutions', 's2_g_method_parsed': 'Carbon Conversion Technology'}
  Item in batch at offset 13: {'s2_g_goal_parsed': 'Food Waste Reduction', 's2_g_method_parsed': 'Food Technology Development'}
  Item in batch at offset 14: {'s2_g_goal_parsed': 'Medical Training Innovation', 's2_g_method_parsed': 'Strategic Business Analysis'}
  Item in batch at offset 15: {'s2_g_goal_parsed': 'Strengthen Science Trust', 's2_g_method_parsed': 'Societal Engagement Research'}
  Item in batch at offset 16: {'s2_g_goal_parsed': 'Circular Materials Development', 's2_g_method_parsed': 'Bio-based Material Production'}
  Item in batch at offset 17: {'s2_g_goal_parsed': 'Climate Action Solutions', 's2_g_method_parsed': 'Bio-based Carbon Capture'}
  Item in batch at offset 18: {'s2_g_goal_parsed': 'Hydrogen Energy Deployment', 's2_g_method_parsed': 'Urban Innovation Partnership'}
  Item in batch at offset 19: {'s2_g_goal_parsed': 'Disease Prevention & Diagnostics', 's2_g_method_parsed': 'AI-Powered Diagnostics'}
  Item in batch at offset 20: {'s2_g_goal_parsed': 'Infertility Treatment Improvement', 's2_g_method_parsed': 'AI for Healthcare Applications'}
  Item in batch at offset 21: {'s2_g_goal_parsed': 'Inclusive Innovation Development', 's2_g_method_parsed': 'Ecosystem Collaboration Programs'}
  Item in batch at offset 22: {'s2_g_goal_parsed': 'Health Innovation Ecosystem', 's2_g_method_parsed': 'Ecosystem Collaboration Strategy'}
  Item in batch at offset 23: {'s2_g_goal_parsed': 'Biologics Production Optimization', 's2_g_method_parsed': 'Synthetic Biology Engineering'}
  Item in batch at offset 24: {'s2_g_goal_parsed': 'Sustainable Food Ingredients', 's2_g_method_parsed': 'Green Chemistry Processes'}
  Item in batch at offset 25: {'s2_g_goal_parsed': 'Social Innovation Ecosystems', 's2_g_method_parsed': 'Capacity Building Initiatives'}
  Item in batch at offset 26: {'s2_g_goal_parsed': 'Data Economy Transformation', 's2_g_method_parsed': 'Distributed Ledger Technology'}
  Item in batch at offset 27: {'s2_g_goal_parsed': 'Drug Discovery Optimization', 's2_g_method_parsed': 'Biomedical Research Technologies'}

,id,full_text,l1_goal,l1_method,l2_generalized_goal,l2_generalized_method
0,101116741,Digitizing Other Economies: A Comparative Appr...,Understanding Digital Adoption in Non-Industri...,Comparative Ethnographic Analysis of Digitization,Socio-Digital Transformation,Social Science Research
1,101163161,MOLECULAR QUANTUM DYNAMICS IN LOW TEMPERATURE ...,Unveiling Astrochemistry of Molecular Ices,Molecular Quantum Dynamics & Spectroscopy,Astrochemical Process Understanding,Scientific Modeling & Experimentation
2,101160499,Multiscale modelling of aberrant phase transit...,Resolving Aberrant Condensate Dynamics in Cells,Multiscale Computational Modeling of Biomolecules,Understanding Cellular Mechanisms,Computational Biology Methods
3,101166905,The first comprehensive Atlas of the Milky Way...,Creating a 3D Map of the Milky Way,Comprehensive Galactic Data Integration & Mapping,Mapping Cosmic Structures,Large-scale Data Mapping
4,101162875,Untapping multiparametric 2D luminescence sens...,Improving Cellular Luminescence Nanosensing Re...,Machine Learning & Spectral Sorting of Signals,Improving Bio-Sensing Technology,AI & Data Analytics

Saved updated df_complete after L2_Generalization to checkpoint: df_processing_checkpoint.csv

In [7]:
# ## Stage 2.1: Fixing Failed L2 Generalizations

# --- Stage 2.1 Configuration ---
STAGE_NAME_S2_FIX = "L2_Fix_Failed_Generalization"
# Reuses S2 configs: PROMPT_TEMPLATE_S2_FULL, ITEM_PROMPT_FORMAT_S2, INPUT_FIELDS_S2, 
#                    LLM_EXPECTED_LABELS_S2, OUTPUT_COL_NAMES_S2 (defined in Cell 6)

# Define an eligibility filter specifically for rows that were eligible for L2 but failed.
def eligibility_filter_s2_fix(df: pd.DataFrame) -> pd.Series:
    # L2 output columns
    l2_goal_col = OUTPUT_COL_NAMES_S2.get("s2_g_goal_parsed", "l2_generalized_goal")
    l2_method_col = OUTPUT_COL_NAMES_S2.get("s2_g_method_parsed", "l2_generalized_method")

    if l2_goal_col not in df.columns or l2_method_col not in df.columns:
        print(f"Warning for {STAGE_NAME_S2_FIX} eligibility: '{l2_goal_col}' or '{l2_method_col}' columns missing.")
        return pd.Series([False] * len(df), index=df.index)

    # Was it eligible for the main S2 run? (Uses eligibility_filter_s2 from Cell 6)
    was_eligible_for_s2_main = eligibility_filter_s2(df) 

    # Define what indicates an L2 failure needing a retry
    failed_l2_output_values = [
        "Parse Error (Key Missing)", 
        "Not Found in LLM Output", 
        "API Error in Batch",
        "Classification Failed", 
        "Not Processed by Stage",
        # "Not Generalized", # If this was a specific LLM output meaning failure for L2
        "",                      
        pd.NA                   
    ]


    failed_l2_goal = df[l2_goal_col].astype(str).isin(failed_l2_output_values) | df[l2_goal_col].isnull()
    failed_l2_method = df[l2_method_col].astype(str).isin(failed_l2_output_values) | df[l2_method_col].isnull()
    
    return was_eligible_for_s2_main & (failed_l2_goal | failed_l2_method)

# --- Execute Stage 2.1 ---
# df_complete is the main DataFrame, assumed to be updated by Cell 6 (Stage 2)

if 'df_complete' in locals() and isinstance(df_complete, pd.DataFrame) and not df_complete.empty and model:
    
    rows_needing_s2_fix_mask = eligibility_filter_s2_fix(df_complete)
    if not rows_needing_s2_fix_mask.any():
        print(f"Stage {STAGE_NAME_S2_FIX}: No rows found needing L2 fix. df_complete remains unchanged.")
    else:
        print(f"Input for {STAGE_NAME_S2_FIX}: df_complete ({len(df_complete)} rows). Target to fix: {rows_needing_s2_fix_mask.sum()}")
        s2_fix_input_cols_ok = all(col in df_complete.columns for col in INPUT_FIELDS_S2) # INPUT_FIELDS_S2 from Cell 6
        
        if s2_fix_input_cols_ok:
            df_complete = process_stage(
                df_main=df_complete,       
                stage_name=STAGE_NAME_S2_FIX,
                prompt_template_str=PROMPT_TEMPLATE_S2_FULL, 
                item_prompt_format_str=ITEM_PROMPT_FORMAT_S2, 
                input_fields_for_prompt=INPUT_FIELDS_S2,     
                llm_expected_labels_map=LLM_EXPECTED_LABELS_S2, 
                output_col_names_map=OUTPUT_COL_NAMES_S2,    
                model_instance=model,
                eligibility_filter_fn=eligibility_filter_s2_fix, 
                run_trial_mode=RUN_OVERALL_TRIAL_MODE, 
                max_batches_trial=MAX_BATCHES_FOR_TRIAL, 
                batch_size=5,  # Smaller batch for fixing
                wait_time=15,  # Override default: Longer wait for fixing
                llm_output_separator="---" 
            )
            
            if not df_complete.empty:
                print(f"\n{STAGE_NAME_S2_FIX} completed.")
                print("Sample of rows that were targeted for L2 Fix (first 5, showing L1 and L2 cols):")
                # from IPython.display import display # Should be imported in Cell 3
                cols_to_display_s2_fix = ['id', 'full_text'] + \
                                     [OUTPUT_COL_NAMES_S1.get("s1_goal_parsed", "l1_goal"), OUTPUT_COL_NAMES_S1.get("s1_method_parsed", "l1_method")] + \
                                     list(OUTPUT_COL_NAMES_S2.values())
                cols_to_display_s2_fix = [col for col in cols_to_display_s2_fix if col in df_complete.columns]
                
                # Show data for rows that were *attempted* by this fix stage
                if rows_needing_s2_fix_mask.any() and cols_to_display_s2_fix:
                     display(df_complete[rows_needing_s2_fix_mask][cols_to_display_s2_fix].head())
                else:
                     print("No rows were targeted for S2 fix for display, or relevant columns missing.")

                # Save the updated df_complete to the main checkpoint file
                try:
                    df_complete.to_csv(MAIN_DATAFRAME_CHECKPOINT_FILE, index=False) # OVERWRITE
                    print(f"Saved updated df_complete after {STAGE_NAME_S2_FIX} to checkpoint: {MAIN_DATAFRAME_CHECKPOINT_FILE}")
                except Exception as e:
                    print(f"Error saving checkpoint after {STAGE_NAME_S2_FIX}: {e}")
        else:
            print(f"Skipping {STAGE_NAME_S2_FIX} due to missing required input columns.")
else:
    if 'df_complete' not in locals() or not isinstance(df_complete, pd.DataFrame) or df_complete.empty:
        print(f"Skipping Stage {STAGE_NAME_S2_FIX}: df_complete not ready or model not initialized.")
    if not model:
        print(f"Skipping Stage {STAGE_NAME_S2_FIX}: LLM Model is not initialized.")

Input for L2_Fix_Failed_Generalization: df_complete (15341 rows). Target to fix: 27

==================== Running Stage: L2_Fix_Failed_Generalization on DataFrame with 15341 rows ====================
Stage L2_Fix_Failed_Generalization: 27 rows eligible for THIS processing call out of 15341.
Stage L2_Fix_Failed_Generalization: FULL MODE - Will send 27 (eligible) records to API.
  Will take 6 batches. Est. API wait: 1.5 min.


  L2_Fix_Failed_Generalization - Batch 1/6 (Slice Offsets 0-4)

=== FIRST PROMPT FOR BATCH 1 (Structure Preview) ===
You are an expert taxonomist creating highly searchable, general category labels for EU research projects to improve grouping and navigation.

You will receive a Project Summary, an Initial Goal, and an Initial Method.
Your task is to elevate the Initial labels into **Generalized Goal** and **Generalized Method** labels.

**Core Generalization Principle: Think Like a User Searching for Categories & Strive for Broader Groupings.**
*   Generalized labels should be intuitive category headings a user would search for.
*   Use the **Project Summary** for essential context to find the most accurate encompassing category.
*   **Your primary task is to abstract to a significantly broader level of generality.** Only if an initial label is *already* a very broad, established, and highly searchable category, AND further generalization would make it too vague or inaccurate, may it be minimally adjusted or (rarely) reused.

Instructions & Examples (Crucial):
1.  **4 Words Max** per label.
2.  **Gen...
Item Format Example:
Project #1:
Project Summary: [SAMPLE_FULL_TEXT_FROM_DATA]
Initial Goal: [SAMPLE_L1_GOAL_FROM_DATA]
Initial Method: [SAMPLE_L1_METHOD_FROM_DATA]

=== END PROMPT PREVIEW ===


--- RAW LLM OUTPUT (Batch 1, 5 items) ---
Goal Summary: Therapeutic Drug Advancement
Method Summary: Advanced Chemical Synthesis
---
Goal Summary: Animal Sensory Research
Method Summary: Neuroscience Research Methods
---
Goal Summary: Biomarker Discovery Diagnostics
Method Summary: High-throughput Molecular Assays
---
Goal Summary: Personalized Learning Systems
Method Summary: Biosignal Data Analysis
---
Goal Summary: Neuroimmune System Research
Method Summary: In Vivo Mapping Technologies
--- END RAW LLM OUTPUT ---

--- PARSED LABELS (Batch 1) ---
  Item in batch at offset 0: {'s2_g_goal_parsed': 'Therapeutic Drug Advancement', 's2_g_method_parsed': 'Advanced Chemical Synthesis'}
  Item in batch at offset 1: {'s2_g_goal_parsed': 'Animal Sensory Research', 's2_g_method_parsed': 'Neuroscience Research Methods'}
  Item in batch at offset 2: {'s2_g_goal_parsed': 'Biomarker Discovery Diagnostics', 's2_g_method_parsed': 'High-throughput Molecular Assays'}
  Item in batch at offset 3: {'s2_g_goal_parsed': 'Personalized Learning Systems', 's2_g_method_parsed': 'Biosignal Data Analysis'}
  Item in batch at offset 4: {'s2_g_goal_parsed': 'Neuroimmune System Research', 's2_g_method_parsed': 'In Vivo Mapping Technologies'}
  (Parsed 5 items from this batch output, expected 5)
--- END PARSED LABELS ---

  Batch 1 outcome: Labels extracted.
  Waiting 15s...

  L2_Fix_Failed_Generalization - Batch 2/6 (Slice Offsets 5-9)

--- RAW LLM OUTPUT (Batch 2, 5 items) ---
Project #6:
Goal Summary: Socio-Environmental Sustainability
Method Summary: Social Science Research
---
Project #7:
Goal Summary: Human Evolutionary History
Method Summary: Integrated Data Analysis
---
Project #8:
Goal Summary: Skeletal Tissue Regeneration
Method Summary: Biomaterials Engineering
---
Project #9:
Goal Summary: Advanced Tissue Engineering
Method Summary: Biofabrication Technologies
---
Project #10:
Goal Summary: Assessing Societal Impact
Method Summary: Multidisciplinary Modeling
--- END RAW LLM OUTPUT ---

--- PARSED LABELS (Batch 2) ---
  Item in batch at offset 0: {'s2_g_goal_parsed': 'Socio-Environmental Sustainability', 's2_g_method_parsed': 'Social Science Research'}
  Item in batch at offset 1: {'s2_g_goal_parsed': 'Human Evolutionary History', 's2_g_method_parsed': 'Integrated Data Analysis'}
  Item in batch at offset 2: {'s2_g_goal_parsed': 'Skeletal Tissue Regeneration', 's2_g_method_parsed': 'Biomaterials Engineering'}
  Item in batch at offset 3: {'s2_g_goal_parsed': 'Advanced Tissue Engineering', 's2_g_method_parsed': 'Biofabrication Technologies'}
  Item in batch at offset 4: {'s2_g_goal_parsed': 'Assessing Societal Impact', 's2_g_method_parsed': 'Multidisciplinary Modeling'}
  (Parsed 5 items from this batch output, expected 5)
--- END PARSED LABELS ---

  Batch 2 outcome: Labels extracted.
  Waiting 15s...

  L2_Fix_Failed_Generalization - Batch 3/6 (Slice Offsets 10-14)

--- RAW LLM OUTPUT (Batch 3, 5 items) ---
Goal Summary: Ecosystem Climate Adaptation
Method Summary: Applied Ecological Research
---
Goal Summary: Antimicrobial Drug Discovery
Method Summary: Biomolecular Discovery & Characterization
---
Goal Summary: Advancing Human Computer Interaction
Method Summary: Haptic Interface Technologies
---
Goal Summary: Cancer Diagnosis & Therapy
Method Summary: Advanced Molecular Diagnostics
---
Goal Summary: Advancing Brain Function Research
Method Summary: Behavioral Neuroscience Research
--- END RAW LLM OUTPUT ---

--- PARSED LABELS (Batch 3) ---
  Item in batch at offset 0: {'s2_g_goal_parsed': 'Ecosystem Climate Adaptation', 's2_g_method_parsed': 'Applied Ecological Research'}
  Item in batch at offset 1: {'s2_g_goal_parsed': 'Antimicrobial Drug Discovery', 's2_g_method_parsed': 'Biomolecular Discovery & Characterization'}
  Item in batch at offset 2: {'s2_g_goal_parsed': 'Advancing Human Computer Interaction', 's2_g_method_parsed': 'Haptic Interface Technologies'}
  Item in batch at offset 3: {'s2_g_goal_parsed': 'Cancer Diagnosis & Therapy', 's2_g_method_parsed': 'Advanced Molecular Diagnostics'}
  Item in batch at offset 4: {'s2_g_goal_parsed': 'Advancing Brain Function Research', 's2_g_method_parsed': 'Behavioral Neuroscience Research'}
  (Parsed 5 items from this batch output, expected 5)
--- END PARSED LABELS ---

  Batch 3 outcome: Labels extracted.
  Waiting 15s...

Stage L2_Fix_Failed_Generalization: API calls complete. 6/6 batches yielded some parsable results.

=============== Stage L2_Fix_Failed_Generalization - FINAL SUMMARY ===============
  Input records to stage (df_main): 15341
  Eligible records (before trial slice): 27
  Records sent to API (after trial slice if any): 27
  Successfully received and parsed at least one valid label for: 27 records.
  Success rate on records sent to API: 100%

  Top values for output columns in Stage L2_Fix_Failed_Generalization (from 15341 total rows):
    Column 'l2_generalized_goal':
      - "Sustainable Food Systems": 47
      - "Cancer Therapy Development": 44
      - "Sustainable Chemical Production": 39
      - "Industrial Decarbonization": 39
      - "Sustainable Materials Development": 36
      - "Public Science Engagement": 32
      - "Quantum Computing Advancement": 31
        ...
    Column 'l2_generalized_method':
      - "Qualitative Social Research": 104
      - "Advanced Materials Engineering": 85
      - "Historical Research Methods": 60
      - "Research Capacity Building": 59
      - "Theoretical Physics Modeling": 42
      - "Social Science Research": 40
      - "Digital Platform Development": 37
        ...

L2_Fix_Failed_Generalization completed.
Sample of rows that were targeted for L2 Fix (first 5, showing L1 and L2 cols):

,id,full_text,l1_goal,l1_method,l2_generalized_goal,l2_generalized_method
3810,101148413,Backbone-Optimized OligonucleotideS for Therap...,Accelerate therapeutic oligonucleotide drug de...,Efficient Oligonucleotide Backbone Modification,Therapeutic Drug Advancement,Advanced Chemical Synthesis
4698,101151077,Understanding the unseen: Function Of CUttlefi...,Understand cuttlefish polarization communicati...,Polarization Imaging & Neural Signal Analysis,Animal Sensory Research,Neuroscience Research Methods
8176,101069334,Development and commercialization of a kit for...,High-throughput ubiquitination profiling in bi...,Enzymatic Activity-Based PTM Profiling,Biomarker Discovery Diagnostics,High-throughput Molecular Assays
8908,101138291,Skill Performance Estimation from cARdiac Sign...,Personalize training via cardiac signal analysis,Cardiac signal analysis for skill estimation,Personalized Learning Systems,Biosignal Data Analysis
8909,101097830,Architecture of Peripheral Neuroimmune Circuit...,Map neuroimmune interactions for health insights,In vivo neuroimmune circuit mapping tools,Neuroimmune System Research,In Vivo Mapping Technologies

Saved updated df_complete after L2_Fix_Failed_Generalization to checkpoint: df_processing_checkpoint.csv

In [11]:
# ## Stage 3: L3 Categorization (Application/Technology Domain & Strategic Method)

# --- Stage 3 Configuration ---
STAGE_NAME_S3 = "L3_Categorization"

# Full prompt for L3 Categorization (PROMPT_PREFIX_L3 from your original script)
PROMPT_TEMPLATE_S3_FULL = """You are a senior taxonomist tasked with creating truly high-level, strategic categories for EU research projects. These Level 3 categories MUST represent a significant conceptual leap from the Level 2 inputs and will be used for broad thematic grouping and simplified navigation. MINOR REPHRASING OR SLIGHT GENERALIZATIONS OF LEVEL 2 LABELS ARE NOT ACCEPTABLE FOR LEVEL 3.

You will be given:
1.  The original **Project Summary** (for essential context and grounding).
2.  A **Level 2 Generalized Goal** (an already generalized aim/objective).
3.  A **Level 2 Generalized Method** (an already generalized approach/activity type).

Your task is to:
1.  Abstract the 'Level 2 Generalized Goal' into a **'Level 3 Application/Technology Domain'**. This domain should be a recognized, distinct field.
2.  Abstract the 'Level 2 Generalized Method' into a **'Level 3 Strategic Method Category'**. This category should represent a fundamental type of strategic action or core operational domain.

**Core Principle for Level 3 Abstraction: DEMAND A SIGNIFICANT CONCEPTUAL LEAP TO MAJOR CATEGORIES.**
*   **For BOTH Goal & Method Paths:** The Level 3 category MUST be a substantially broader, more encompassing category than the Level 2 input. Think of L3 as major pillars or strategic divisions.
*   **Goal Path (Application/Technology Domain):** Identify the primary specific field of technology, application area, or distinct research domain. This should be broader than the L2 Goal. For example, an L2 goal about "Advanced Microchip Cooling" should map to a broader L3 domain like "Microelectronics" or "Semiconductor Technology," not just "Advanced Cooling Systems."
*   **Method Path (Strategic Method Category):** Identify the fundamental type of strategic action, core operational domain, or overarching domain of expertise. This often means moving from a specific L2 method (e.g., "Social Science Research," "Advanced Scientific Modeling") to a higher-level strategic function or capability (e.g., "Evidence-Based Analysis," "Research & Development Methods," "Strategic Collaboration").
*   These L3 categories should be concise (ideally 2-4 words).
*   Use the **Project Summary** to ensure the chosen major category is accurate.

Instructions & Examples (Crucial - Demonstrating SIGNIFICANT Abstraction):
1.  **Max 3 Words** per Level 3 label.
2.  **Level 3 Application/Technology Domain (from L2 Goal): Focus on Established Fields/Sectors.**
    *   Think: "What is the recognized **technological sector, key industry, or established research field** this L2 Goal belongs to?"
    *   Ensure a clear step up in generality from L2.
    *   *Examples of L2 Goal -> Level 3 Application/Technology Domain (Significant Leap):*
        *   L2 Goal: "Advanced Microchip Cooling" -> **L3: Semiconductor Technology**
        *   L2 Goal: "Developing Efficient Solar Cells" -> **L3: Renewable Energy Systems**
        *   L2 Goal: "AI for Medical Diagnosis" -> **L3: Digital Health Applications**
        *   L2 Goal: "Improving Battery Energy Density" -> **L3: Energy Storage Solutions**
        *   L2 Goal: "Understanding Digital Inclusion & Society" -> **L3: Digital Society Studies**
        *   L2 Goal: "Advancing Astrochemistry Knowledge" -> **L3: Space & Planetary Science**
3.  **Level 3 Strategic Method Category (from L2 Method): Focus on Fundamental Strategic Functions or Core Capabilities.**
    *   Think: "What is the **highest-level strategic function, core operational capability, or fundamental type of intervention** that this L2 Method represents?"
    *   **THIS REQUIRES A MAJOR JUMP.** An L2 method like "Social Science Research" is still too specific for L3. What is its strategic function? Perhaps "Societal Understanding & Analysis." An L2 method like "Advanced Scientific Modeling" might become "Predictive & Analytical Methods."
    *   *Examples of L2 Method -> Level 3 Strategic Method Category (Significant Leap):*
        *   L2 Method: "Integrated Liquid Cooling" -> **L3: Advanced Hardware Engineering** (or **Specialized System Design**)
        *   L2 Method: "Social Science Research" -> **L3: Societal Impact Analysis** (or **Human & Social Dynamics Research**)
        *   L2 Method: "Advanced Scientific Modeling" -> **L3: Complex Systems Simulation** (or **Theoretical & Predictive Modeling**)
        *   L2 Method: "AI & Data Analytics" -> **L3: Data-Driven Innovation** (or **Advanced Analytics Capability**)
        *   L2 Method: "European Student Science Competition" -> **L3: Talent Development Programs**
        *   L2 Method: "Implementing Open Science Policies" -> **L3: Research Policy & Governance**
        *   L2 Method: "City-Based Innovation Ecosystems" -> **L3: Regional Development Strategies**
4.  **MANDATE SIGNIFICANT ABSTRACTION:** The jump from Level 2 to Level 3 is NOT optional. Rephrasing or making only minor adjustments to Level 2 labels to create Level 3 labels is incorrect. If a Level 2 label seems very broad, you must still find its encompassing Level 3 strategic category.
5.  **Wording:** Use established, high-level strategic terms.
6.  **Context is King:** The **Project Summary** is vital.
7.  **Unassigned:** If Level 2 inputs are "Unassigned," "Not Generalized," or "Not Applicable" the L3 output should also reflect an inability to categorize, e.g., "Not Categorized L3".

Output Format (one section per project, separated by "---"):
Level 3 Application/Technology Domain: [specific domain label - significant abstraction from L2 Goal]
Level 3 Strategic Method Category: [strategic method type label - significant abstraction from L2 Method]
---

Example (Your UNISCOOL Case - Aiming for Stronger Abstraction):
Project Summary: UNISCOOL: SMART IN-CHIP LIQUID COOLING FOR ADVANCED MICROELECTRONIC SYSTEMS...
Level 2 Generalized Goal: Advanced Microchip Cooling
Level 2 Generalized Method: Integrated Liquid Cooling

Your output for this project:
Level 3 Application/Technology Domain: Semiconductor Technology
Level 3 Strategic Method Category: Advanced Hardware Engineering
---

Example 2 (Project #1 from your output - Demonstrating Stronger Method Abstraction):
Project Summary: Digitizing Other Economies: A Comparative Approach: How do longstanding, primarily non-industrial, n...
Level 2 Goal: Digital Inclusion & Society
Level 2 Method: Social Science Research

Your output for this project:
Level 3 Application/Technology Domain: Digital Society Studies
Level 3 Strategic Method Category: Societal Impact Analysis
---

Example 3 (Project #2 from your output - Demonstrating Stronger Method Abstraction):
Project Summary: MOLECULAR QUANTUM DYNAMICS IN LOW TEMPERATURE CONDENSED PHASE ASTROCHEMISTRY...
Level 2 Goal: Advancing Astrochemistry Knowledge
Level 2 Method: Advanced Scientific Modeling

Your output for this project:
Level 3 Application/Technology Domain: Space & Planetary Science
Level 3 Strategic Method Category: Theoretical & Predictive Modeling
---

Now, analyze the following projects. For each, provide 'Level 3 Application/Technology Domain' and 'Level 3 Strategic Method Category' per format, separated by "---". YOU MUST ENSURE A SIGNIFICANT LEVEL OF ABSTRACTION FOR BOTH OUTPUTS.
"""

ITEM_PROMPT_FORMAT_S3 = (
    "\nProject #{project_num_in_prompt}:\n"
    "Project Summary: {full_text}\n"
    "Level 2 Generalized Goal: {l2_generalized_goal}\n"
    "Level 2 Generalized Method: {l2_generalized_method}\n"
)

INPUT_FIELDS_S3 = ['full_text', 'l2_generalized_goal', 'l2_generalized_method']

LLM_EXPECTED_LABELS_S3 = {
    "Level 3 Application/Technology Domain:": "s3_tech_domain_parsed",
    "Level 3 Strategic Method Category:": "s3_strat_method_parsed"
}

OUTPUT_COL_NAMES_S3 = {
    "s3_tech_domain_parsed": "l3_tech_domain",
    "s3_strat_method_parsed": "l3_strategic_method"
}

def eligibility_filter_s3(df: pd.DataFrame) -> pd.Series:
    # L2 output columns (ensure these match what OUTPUT_COL_NAMES_S2 produced)
    l2_goal_col = OUTPUT_COL_NAMES_S2.get("s2_g_goal_parsed", "l2_generalized_goal")
    l2_method_col = OUTPUT_COL_NAMES_S2.get("s2_g_method_parsed", "l2_generalized_method")

    if l2_goal_col not in df.columns or l2_method_col not in df.columns:
        print(f"Warning for {STAGE_NAME_S3} eligibility: '{l2_goal_col}' or '{l2_method_col}' columns missing.")
        return pd.Series([False] * len(df), index=df.index)

    invalid_l2_output_values = [
        "Parse Error (Key Missing)", "Not Found in LLM Output", "API Error in Batch",
        "Classification Failed", "Not Processed by Stage", "Not Eligible for Stage",
        "Not Applicable", "Not Generalized", "Unassigned", "", pd.NA
    ]
    is_l2_goal_valid = df[l2_goal_col].notna() & (~df[l2_goal_col].astype(str).isin(invalid_l2_output_values))
    is_l2_method_valid = df[l2_method_col].notna() & (~df[l2_method_col].astype(str).isin(invalid_l2_output_values))
    return is_l2_goal_valid & is_l2_method_valid

# --- Execute Stage 3 ---
# df_complete is the main DataFrame, assumed to be updated by Cell 7 (Stage 2.1 Fix)

if 'df_complete' in locals() and isinstance(df_complete, pd.DataFrame) and not df_complete.empty and model:
    print(f"Input for Stage 3 ({STAGE_NAME_S3}): df_complete with {len(df_complete)} rows.")
    print(f"df_complete columns before S3: {df_complete.columns.tolist()}")
    
    s3_input_cols_ok = all(col in df_complete.columns for col in INPUT_FIELDS_S3)
            
    if s3_input_cols_ok:
        df_complete = process_stage(
            df_main=df_complete, 
            stage_name=STAGE_NAME_S3,
            prompt_template_str=PROMPT_TEMPLATE_S3_FULL,
            item_prompt_format_str=ITEM_PROMPT_FORMAT_S3,
            input_fields_for_prompt=INPUT_FIELDS_S3,
            llm_expected_labels_map=LLM_EXPECTED_LABELS_S3,
            output_col_names_map=OUTPUT_COL_NAMES_S3,
            model_instance=model,
            eligibility_filter_fn=eligibility_filter_s3,
            run_trial_mode=RUN_OVERALL_TRIAL_MODE,
            max_batches_trial=MAX_BATCHES_FOR_TRIAL,
            batch_size=DEFAULT_BATCH_SIZE, 
            wait_time=DEFAULT_WAIT_TIME, # Using global default (was 15 in your specific L3 code)
            llm_output_separator="---" 
        )
        
        if not df_complete.empty:
            print(f"\n{STAGE_NAME_S3} completed. df_complete columns after S3: {df_complete.columns.tolist()}")
            print(f"Sample of updated df_complete (first 5 rows showing L2 and L3 cols):")
            cols_to_display_s3 = ['id', 'full_text'] + \
                                 [OUTPUT_COL_NAMES_S2.get("s2_g_goal_parsed", "l2_generalized_goal"), 
                                  OUTPUT_COL_NAMES_S2.get("s2_g_method_parsed", "l2_generalized_method")] + \
                                 list(OUTPUT_COL_NAMES_S3.values())
            cols_to_display_s3 = [col for col in cols_to_display_s3 if col in df_complete.columns]
            if cols_to_display_s3: display(df_complete[cols_to_display_s3].head())

            try:
                df_complete.to_csv(MAIN_DATAFRAME_CHECKPOINT_FILE, index=False)
                print(f"Saved updated df_complete after {STAGE_NAME_S3} to checkpoint: {MAIN_DATAFRAME_CHECKPOINT_FILE}")
            except Exception as e:
                print(f"Error saving checkpoint after {STAGE_NAME_S3}: {e}")
        else:
            print(f"Stage {STAGE_NAME_S3} resulted in an empty DataFrame.")
    else:
        print(f"Skipping {STAGE_NAME_S3} due to missing required input columns in df_complete.")
else:
    if 'df_complete' not in locals() or not isinstance(df_complete, pd.DataFrame) or df_complete.empty:
        print(f"Skipping Stage 3: df_complete not ready or is empty.")
    if not model: 
        print("Skipping Stage 3: LLM Model not initialized.")

Input for Stage 3 (L3_Categorization): df_complete with 15341 rows.
df_complete columns before S3: ['id', 'full_text', 'l1_goal', 'l1_method', 'l2_generalized_goal', 'l2_generalized_method']

==================== Running Stage: L3_Categorization on DataFrame with 15341 rows ====================
Stage L3_Categorization: 15340 rows eligible for THIS processing call out of 15341.
Stage L3_Categorization: FULL MODE - Will send 15340 (eligible) records to API.
  Will take 767 batches. Est. API wait: 63.9 min.


  L3_Categorization - Batch 1/767 (Slice Offsets 0-19)

=== FIRST PROMPT FOR BATCH 1 (Structure Preview) ===
You are a senior taxonomist tasked with creating truly high-level, strategic categories for EU research projects. These Level 3 categories MUST represent a significant conceptual leap from the Level 2 inputs and will be used for broad thematic grouping and simplified navigation. MINOR REPHRASING OR SLIGHT GENERALIZATIONS OF LEVEL 2 LABELS ARE NOT ACCEPTABLE FOR LEVEL 3.

You will be given:
1.  The original **Project Summary** (for essential context and grounding).
2.  A **Level 2 Generalized Goal** (an already generalized aim/objective).
3.  A **Level 2 Generalized Method** (an already generalized approach/activity type).

Your task is to:
1.  Abstract the 'Level 2 Generalized Goal' into a **'Level 3 Application/Technology Domain'**. This domain should be a recognized, distinct field.
2.  Abstract the 'Level 2 Generalized Method' into a **'Level 3 Strategic Method Category'**. This category should represent a fundamental type of strategic action or core operational domain.

**Core Prin...
Item Format Example:
Project #1:
Project Summary: [SAMPLE_FULL_TEXT_FROM_DATA]
Level 2 Generalized Goal: [SAMPLE_L2_GENERALIZED_GOAL_FROM_DATA]
Level 2 Generalized Method: [SAMPLE_L2_GENERALIZED_METHOD_FROM_DATA]

=== END PROMPT PREVIEW ===


--- RAW LLM OUTPUT (Batch 1, 20 items) ---
Project #1:
Level 3 Application/Technology Domain: Digital Society Studies
Level 3 Strategic Method Category: Societal Impact Analysis
---
Project #2:
Level 3 Application/Technology Domain: Space & Planetary Science
Level 3 Strategic Method Category: Theoretical & Predictive Modeling
---
Project #3:
Level 3 Application/Technology Domain: Systems Biology
Level 3 Strategic Method Category: Complex Systems Simulation
---
Project #4:
Level 3 Application/Technology Domain: Astronomy & Astrophysics
Level 3 Strategic Method Category: Advanced Data Visualization
---
Project #5:
Level 3 Application/Technology Domain: Biomedical Engineering
Level 3 Strategic Method Category: Data-Driven Innovation
---
Project #6:
Level 3 Application/Technology Domain: Theoretical Physics
Level 3 Strategic Method Category: Advanced Analytics Capability
---
Project #7:
Level 3 Application/Technology Domain: Cultural Heritage Preservation
Level 3 Strategic Method Category: Knowledge Organization Systems
---
Project...
--- END RAW LLM OUTPUT ---

--- PARSED LABELS (Batch 1) ---
  Item in batch at offset 0: {'s3_tech_domain_parsed': 'Digital Society Studies', 's3_strat_method_parsed': 'Societal Impact Analysis'}
  Item in batch at offset 1: {'s3_tech_domain_parsed': 'Space & Planetary Science', 's3_strat_method_parsed': 'Theoretical & Predictive Modeling'}
  Item in batch at offset 2: {'s3_tech_domain_parsed': 'Systems Biology', 's3_strat_method_parsed': 'Complex Systems Simulation'}
  Item in batch at offset 3: {'s3_tech_domain_parsed': 'Astronomy & Astrophysics', 's3_strat_method_parsed': 'Advanced Data Visualization'}
  Item in batch at offset 4: {'s3_tech_domain_parsed': 'Biomedical Engineering', 's3_strat_method_parsed': 'Data-Driven Innovation'}
  Item in batch at offset 5: {'s3_tech_domain_parsed': 'Theoretical Physics', 's3_strat_method_parsed': 'Advanced Analytics Capability'}
  Item in batch at offset 6: {'s3_tech_domain_parsed': 'Cultural Heritage Preservation', 's3_strat_method_parsed': 'Knowledge Organization Systems'}
  Item in batch at offset 7: {'s3_tech_domain_parsed': 'Nuclear Energy Research', 's3_strat_method_parsed': 'Research & Development Coordination'}
  Item in batch at offset 8: {'s3_tech_domain_parsed': 'Nuclear Energy Research', 's3_strat_method_parsed': 'Knowledge Transfer Activities'}
  Item in batch at offset 9: {'s3_tech_domain_parsed': 'Materials Science', 's3_strat_method_parsed': 'Technology Market Assessment'}
  Item in batch at offset 10: {'s3_tech_domain_parsed': 'Digital Health Applications', 's3_strat_method_parsed': 'Software Product Engineering'}
  Item in batch at offset 11: {'s3_tech_domain_parsed': 'Clinical Medicine Research', 's3_strat_method_parsed': 'Translational Research Methods'}
  Item in batch at offset 12: {'s3_tech_domain_parsed': 'Digital Education Platforms', 's3_strat_method_parsed': 'Personalized Learning Systems'}
  Item in batch at offset 13: {'s3_tech_domain_parsed': 'Science Education Outreach', 's3_strat_method_parsed': 'Talent Development Programs'}
  Item in batch at offset 14: {'s3_tech_domain_parsed': 'Science Education Outreach', 's3_strat_method_parsed': 'Talent Development Programs'}
  Item in batch at offset 15: {'s3_tech_domain_parsed': 'Research Policy & Governance', 's3_strat_method_parsed': 'Research Policy Evaluation'}
  Item in batch at offset 16: {'s3_tech_domain_parsed': 'Urban Planning & Policy', 's3_strat_method_parsed': 'Regional Development Strategies'}
  Item in batch at offset 17: {'s3_tech_domain_parsed': 'Research Workforce Management', 's3_strat_method_parsed': 'Institutional Finance Optimization'}
  Item in batch at offset 18: {'s3_tech_domain_parsed': 'Sustainable Development Research', 's3_strat_method_parsed': 'Solution-Oriented Innovation'}
  Item in batch at offset 19: {'s3_tech_domain_parsed': 'Research Policy & Governance', 's3_strat_method_parsed': 'Strategic Policy Dialogue'}
  (Parsed 20 items from this batch output, expected 20)
--- END PARSED LABELS ---

  Batch 1 outcome: Labels extracted.
  Waiting 5s...

  L3_Categorization - Batch 2/767 (Slice Offsets 20-39)

--- RAW LLM OUTPUT (Batch 2, 20 items) ---
Project #21:
Level 3 Application/Technology Domain: Knowledge Transfer Strategies
Level 3 Strategic Method Category: Stakeholder Engagement

---
Project #22:
Level 3 Application/Technology Domain: Science Communication
Level 3 Strategic Method Category: Public Awareness Campaigns

---
Project #23:
Level 3 Application/Technology Domain: Research Workforce Development
Level 3 Strategic Method Category: Cross-Border Infrastructure

---
Project #24:
Level 3 Application/Technology Domain: STEM Education
Level 3 Strategic Method Category: Talent Development Programs

---
Project #25:
Level 3 Application/Technology Domain: Climate Solutions
Level 3 Strategic Method Category: Systemic Change Initiatives

---
Project #26:
Level 3 Application/Technology Domain: Global Research Collaboration
Level 3 Strategic Method Category: Transnational Partnerships

---
Project #27:
Level 3 Application/Technology Domain: Digital Technologies
Level 3 Strategic Method Category: Innovation Value Chains

---
Proj...
--- END RAW LLM OUTPUT ---

--- PARSED LABELS (Batch 2) ---
  Item in batch at offset 0: {'s3_tech_domain_parsed': 'Knowledge Transfer Strategies', 's3_strat_method_parsed': 'Stakeholder Engagement'}
  Item in batch at offset 1: {'s3_tech_domain_parsed': 'Science Communication', 's3_strat_method_parsed': 'Public Awareness Campaigns'}
  Item in batch at offset 2: {'s3_tech_domain_parsed': 'Research Workforce Development', 's3_strat_method_parsed': 'Cross-Border Infrastructure'}
  Item in batch at offset 3: {'s3_tech_domain_parsed': 'STEM Education', 's3_strat_method_parsed': 'Talent Development Programs'}
  Item in batch at offset 4: {'s3_tech_domain_parsed': 'Climate Solutions', 's3_strat_method_parsed': 'Systemic Change Initiatives'}
  Item in batch at offset 5: {'s3_tech_domain_parsed': 'Global Research Collaboration', 's3_strat_method_parsed': 'Transnational Partnerships'}
  Item in batch at offset 6: {'s3_tech_domain_parsed': 'Digital Technologies', 's3_strat_method_parsed': 'Innovation Value Chains'}
  Item in batch at offset 7: {'s3_tech_domain_parsed': 'Oncology Research', 's3_strat_method_parsed': 'Pharmaceutical Development'}
  Item in batch at offset 8: {'s3_tech_domain_parsed': 'Infrastructure Technologies', 's3_strat_method_parsed': 'Automated Inspection Systems'}
  Item in batch at offset 9: {'s3_tech_domain_parsed': 'Digital Health Applications', 's3_strat_method_parsed': 'Diagnostic Technology'}
  Item in batch at offset 10: {'s3_tech_domain_parsed': 'Research & Innovation Policy', 's3_strat_method_parsed': 'Policy Dialogue Platforms'}
  Item in batch at offset 11: {'s3_tech_domain_parsed': 'Biomedical Innovation', 's3_strat_method_parsed': 'Investment & Resource Mobilization'}
  Item in batch at offset 12: {'s3_tech_domain_parsed': 'Open Science Infrastructure', 's3_strat_method_parsed': 'Research Policy & Governance'}
  Item in batch at offset 13: {'s3_tech_domain_parsed': 'Medical Imaging', 's3_strat_method_parsed': 'Personalized Medicine'}
  Item in batch at offset 14: {'s3_tech_domain_parsed': 'Sustainable Agriculture', 's3_strat_method_parsed': 'Resource Recovery Technologies'}
  Item in batch at offset 15: {'s3_tech_domain_parsed': 'Entrepreneurship', 's3_strat_method_parsed': 'Ecosystem Building'}
  Item in batch at offset 16: {'s3_tech_domain_parsed': 'ICT Sector', 's3_strat_method_parsed': 'Cluster Development Initiatives'}
  Item in batch at offset 17: {'s3_tech_domain_parsed': 'Agri-Food Technologies', 's3_strat_method_parsed': 'Regional Development Strategies'}
  Item in batch at offset 18: {'s3_tech_domain_parsed': 'Pediatric Healthcare', 's3_strat_method_parsed': 'Demand-Side Innovation Policies'}
  Item in batch at offset 19: {'s3_tech_domain_parsed': 'Sustainable Development Goals', 's3_strat_method_parsed': 'Multi-Stakeholder Partnerships'}
  (Parsed 20 items from this batch output, expected 20)
--- END PARSED LABELS ---

  Batch 2 outcome: Labels extracted.
  Waiting 5s...

  L3_Categorization - Batch 3/767 (Slice Offsets 40-59)

--- RAW LLM OUTPUT (Batch 3, 20 items) ---
Project #41:
Level 3 Application/Technology Domain: Sustainable Industrial Policy
Level 3 Strategic Method Category: Ecosystem Orchestration

---
Project #42:
Level 3 Application/Technology Domain: Social Innovation Ecosystem
Level 3 Strategic Method Category: Capacity Building Programs

---
Project #43:
Level 3 Application/Technology Domain: Regional Development Strategies
Level 3 Strategic Method Category: Interregional Collaboration

---
Project #44:
Level 3 Application/Technology Domain: Sustainable Urban Development
Level 3 Strategic Method Category: Multi-Stakeholder Partnerships

---
Project #45:
Level 3 Application/Technology Domain: Regional Innovation Systems
Level 3 Strategic Method Category: Program Design & Implementation

---
Project #46:
Level 3 Application/Technology Domain: Public Sector Modernization
Level 3 Strategic Method Category: Workforce Development

---
Project #47:
Level 3 Application/Technology Domain: Health Innovation Ecosystems
Level 3 Strategic Method Ca...
--- END RAW LLM OUTPUT ---

--- PARSED LABELS (Batch 3) ---
  Item in batch at offset 0: {'s3_tech_domain_parsed': 'Sustainable Industrial Policy', 's3_strat_method_parsed': 'Ecosystem Orchestration'}
  Item in batch at offset 1: {'s3_tech_domain_parsed': 'Social Innovation Ecosystem', 's3_strat_method_parsed': 'Capacity Building Programs'}
  Item in batch at offset 2: {'s3_tech_domain_parsed': 'Regional Development Strategies', 's3_strat_method_parsed': 'Interregional Collaboration'}
  Item in batch at offset 3: {'s3_tech_domain_parsed': 'Sustainable Urban Development', 's3_strat_method_parsed': 'Multi-Stakeholder Partnerships'}
  Item in batch at offset 4: {'s3_tech_domain_parsed': 'Regional Innovation Systems', 's3_strat_method_parsed': 'Program Design & Implementation'}
  Item in batch at offset 5: {'s3_tech_domain_parsed': 'Public Sector Modernization', 's3_strat_method_parsed': 'Workforce Development'}
  Item in batch at offset 6: {'s3_tech_domain_parsed': 'Health Innovation Ecosystems', 's3_strat_method_parsed': 'Cross-Border Collaboration'}
  Item in batch at offset 7: {'s3_tech_domain_parsed': 'Venture Capital Markets', 's3_strat_method_parsed': 'Investment Ecosystem Development'}
  Item in batch at offset 8: {'s3_tech_domain_parsed': 'Social Enterprise Development', 's3_strat_method_parsed': 'Interdisciplinary Training'}
  Item in batch at offset 9: {'s3_tech_domain_parsed': 'Sustainable Transportation Systems', 's3_strat_method_parsed': 'Innovation Ecosystem Support'}
  Item in batch at offset 10: {'s3_tech_domain_parsed': 'Regional Development Strategies', 's3_strat_method_parsed': 'Ecosystem Partnership Programs'}
  Item in batch at offset 11: {'s3_tech_domain_parsed': 'Gerontechnology', 's3_strat_method_parsed': 'Remote Monitoring Solutions'}
  Item in batch at offset 12: {'s3_tech_domain_parsed': 'Clean Technology Sector', 's3_strat_method_parsed': 'Regional Ecosystem Assessment'}
  Item in batch at offset 13: {'s3_tech_domain_parsed': 'Global Research Networks', 's3_strat_method_parsed': 'Infrastructure Modernization'}
  Item in batch at offset 14: {'s3_tech_domain_parsed': 'Supply Chain Management', 's3_strat_method_parsed': 'Data-Driven Insights'}
  Item in batch at offset 15: {'s3_tech_domain_parsed': 'Cancer Treatment Technologies', 's3_strat_method_parsed': 'Surgical Technology Innovation'}
  Item in batch at offset 16: {'s3_tech_domain_parsed': 'Advanced Surgical Technologies', 's3_strat_method_parsed': 'Medical Imaging Solutions'}
  Item in batch at offset 17: {'s3_tech_domain_parsed': 'Innovation Procurement Policy', 's3_strat_method_parsed': 'Regional Policy Implementation'}
  Item in batch at offset 18: {'s3_tech_domain_parsed': 'Research Infrastructure', 's3_strat_method_parsed': 'Knowledge Translation'}
  Item in batch at offset 19: {'s3_tech_domain_parsed': 'Startup Ecosystems', 's3_strat_method_parsed': 'Ecosystem Integration'}
  (Parsed 20 items from this batch output, expected 20)
--- END PARSED LABELS ---

  Batch 3 outcome: Labels extracted.
  Waiting 5s...

  L3_Categorization - Batch 6/767 (Slice Offsets 100-119)

  L3_Categorization - Batch 11/767 (Slice Offsets 200-219)
  Waiting 5s...

  L3_Categorization - Batch 16/767 (Slice Offsets 300-319)

  L3_Categorization - Batch 21/767 (Slice Offsets 400-419)
  Waiting 5s...

  L3_Categorization - Batch 26/767 (Slice Offsets 500-519)

  L3_Categorization - Batch 31/767 (Slice Offsets 600-619)
  Waiting 5s...

  L3_Categorization - Batch 36/767 (Slice Offsets 700-719)

  L3_Categorization - Batch 41/767 (Slice Offsets 800-819)
  Waiting 5s...

  L3_Categorization - Batch 46/767 (Slice Offsets 900-919)

  L3_Categorization - Batch 51/767 (Slice Offsets 1000-1019)
  Waiting 5s...

  L3_Categorization - Batch 56/767 (Slice Offsets 1100-1119)

  L3_Categorization - Batch 61/767 (Slice Offsets 1200-1219)
  Waiting 5s...

  L3_Categorization - Batch 66/767 (Slice Offsets 1300-1319)

  L3_Categorization - Batch 71/767 (Slice Offsets 1400-1419)
  Waiting 5s...

  L3_Categorization - Batch 76/767 (Slice Offsets 1500-1519)

  L3_Categorization - Batch 81/767 (Slice Offsets 1600-1619)
  Waiting 5s...

  L3_Categorization - Batch 86/767 (Slice Offsets 1700-1719)

  L3_Categorization - Batch 91/767 (Slice Offsets 1800-1819)
  Waiting 5s...

  L3_Categorization - Batch 96/767 (Slice Offsets 1900-1919)

  L3_Categorization - Batch 101/767 (Slice Offsets 2000-2019)
  Waiting 5s...

  L3_Categorization - Batch 106/767 (Slice Offsets 2100-2119)

  L3_Categorization - Batch 111/767 (Slice Offsets 2200-2219)
  Waiting 5s...

  L3_Categorization - Batch 116/767 (Slice Offsets 2300-2319)

  L3_Categorization - Batch 121/767 (Slice Offsets 2400-2419)
  Waiting 5s...

  L3_Categorization - Batch 126/767 (Slice Offsets 2500-2519)

  L3_Categorization - Batch 131/767 (Slice Offsets 2600-2619)
  Waiting 5s...

  L3_Categorization - Batch 136/767 (Slice Offsets 2700-2719)

  L3_Categorization - Batch 141/767 (Slice Offsets 2800-2819)
  Waiting 5s...

  L3_Categorization - Batch 146/767 (Slice Offsets 2900-2919)

  L3_Categorization - Batch 151/767 (Slice Offsets 3000-3019)
  Waiting 5s...

  L3_Categorization - Batch 156/767 (Slice Offsets 3100-3119)

  L3_Categorization - Batch 161/767 (Slice Offsets 3200-3219)
  Waiting 5s...

  L3_Categorization - Batch 166/767 (Slice Offsets 3300-3319)

  L3_Categorization - Batch 171/767 (Slice Offsets 3400-3419)
  Waiting 5s...

  L3_Categorization - Batch 176/767 (Slice Offsets 3500-3519)

  L3_Categorization - Batch 181/767 (Slice Offsets 3600-3619)
  Waiting 5s...

  L3_Categorization - Batch 186/767 (Slice Offsets 3700-3719)

  L3_Categorization - Batch 191/767 (Slice Offsets 3800-3819)
  Waiting 5s...

  L3_Categorization - Batch 196/767 (Slice Offsets 3900-3919)

  L3_Categorization - Batch 201/767 (Slice Offsets 4000-4019)
  Waiting 5s...

  L3_Categorization - Batch 206/767 (Slice Offsets 4100-4119)

  L3_Categorization - Batch 211/767 (Slice Offsets 4200-4219)
  Waiting 5s...

  L3_Categorization - Batch 216/767 (Slice Offsets 4300-4319)

  L3_Categorization - Batch 221/767 (Slice Offsets 4400-4419)
  Waiting 5s...

  L3_Categorization - Batch 226/767 (Slice Offsets 4500-4519)

  L3_Categorization - Batch 231/767 (Slice Offsets 4600-4619)
  Waiting 5s...

  L3_Categorization - Batch 236/767 (Slice Offsets 4700-4719)

  L3_Categorization - Batch 241/767 (Slice Offsets 4800-4819)
  Waiting 5s...

  L3_Categorization - Batch 246/767 (Slice Offsets 4900-4919)

  L3_Categorization - Batch 251/767 (Slice Offsets 5000-5019)
  Waiting 5s...

  L3_Categorization - Batch 256/767 (Slice Offsets 5100-5119)

  L3_Categorization - Batch 261/767 (Slice Offsets 5200-5219)
  Waiting 5s...

  L3_Categorization - Batch 266/767 (Slice Offsets 5300-5319)

  L3_Categorization - Batch 271/767 (Slice Offsets 5400-5419)
  Waiting 5s...

  L3_Categorization - Batch 276/767 (Slice Offsets 5500-5519)

  L3_Categorization - Batch 281/767 (Slice Offsets 5600-5619)
  Waiting 5s...

  L3_Categorization - Batch 286/767 (Slice Offsets 5700-5719)

  L3_Categorization - Batch 291/767 (Slice Offsets 5800-5819)
  Waiting 5s...

  L3_Categorization - Batch 296/767 (Slice Offsets 5900-5919)

  L3_Categorization - Batch 301/767 (Slice Offsets 6000-6019)
  Waiting 5s...

  L3_Categorization - Batch 306/767 (Slice Offsets 6100-6119)

  L3_Categorization - Batch 311/767 (Slice Offsets 6200-6219)
  Waiting 5s...

  L3_Categorization - Batch 316/767 (Slice Offsets 6300-6319)

  L3_Categorization - Batch 321/767 (Slice Offsets 6400-6419)
  Waiting 5s...

  L3_Categorization - Batch 326/767 (Slice Offsets 6500-6519)

  L3_Categorization - Batch 331/767 (Slice Offsets 6600-6619)
  Waiting 5s...

  L3_Categorization - Batch 336/767 (Slice Offsets 6700-6719)

  L3_Categorization - Batch 341/767 (Slice Offsets 6800-6819)
  Waiting 5s...

  L3_Categorization - Batch 346/767 (Slice Offsets 6900-6919)

  L3_Categorization - Batch 351/767 (Slice Offsets 7000-7019)
  Waiting 5s...

  L3_Categorization - Batch 356/767 (Slice Offsets 7100-7119)

  L3_Categorization - Batch 361/767 (Slice Offsets 7200-7219)
  Waiting 5s...

  L3_Categorization - Batch 366/767 (Slice Offsets 7300-7319)

  L3_Categorization - Batch 371/767 (Slice Offsets 7400-7419)
  Waiting 5s...

  L3_Categorization - Batch 376/767 (Slice Offsets 7500-7519)

  L3_Categorization - Batch 381/767 (Slice Offsets 7600-7619)
  Waiting 5s...

  L3_Categorization - Batch 386/767 (Slice Offsets 7700-7719)

  L3_Categorization - Batch 391/767 (Slice Offsets 7800-7819)
  Waiting 5s...

  L3_Categorization - Batch 396/767 (Slice Offsets 7900-7919)

  L3_Categorization - Batch 401/767 (Slice Offsets 8000-8019)
  Waiting 5s...

  L3_Categorization - Batch 406/767 (Slice Offsets 8100-8119)

  L3_Categorization - Batch 411/767 (Slice Offsets 8200-8219)
  Waiting 5s...


,id,full_text,l2_generalized_goal,l2_generalized_method,l3_tech_domain,l3_strategic_method
0,101116741,Digitizing Other Economies: A Comparative Appr...,Socio-Digital Transformation,Social Science Research,Digital Society Studies,Societal Impact Analysis
1,101163161,MOLECULAR QUANTUM DYNAMICS IN LOW TEMPERATURE ...,Astrochemical Process Understanding,Scientific Modeling & Experimentation,Space & Planetary Science,Theoretical & Predictive Modeling
2,101160499,Multiscale modelling of aberrant phase transit...,Understanding Cellular Mechanisms,Computational Biology Methods,Systems Biology,Complex Systems Simulation
3,101166905,The first comprehensive Atlas of the Milky Way...,Mapping Cosmic Structures,Large-scale Data Mapping,Astronomy & Astrophysics,Advanced Data Visualization
4,101162875,Untapping multiparametric 2D luminescence sens...,Improving Bio-Sensing Technology,AI & Data Analytics,Biomedical Engineering,Data-Driven Innovation

Saved updated df_complete after L3_Categorization to checkpoint: df_processing_checkpoint.csv

In [12]:
# ## Stage 3.1: Fixing Failed L3 Categorizations

STAGE_NAME_S3_FIX = "L3_Fix_Failed_Categorization"
# Reuses S3 configs: PROMPT_TEMPLATE_S3_FULL, ITEM_PROMPT_FORMAT_S3, INPUT_FIELDS_S3, 
#                    LLM_EXPECTED_LABELS_S3, OUTPUT_COL_NAMES_S3 (defined in Cell 8)

def eligibility_filter_s3_fix(df: pd.DataFrame) -> pd.Series:
    # L3 output columns (ensure these match what OUTPUT_COL_NAMES_S3 produced)
    l3_domain_col = OUTPUT_COL_NAMES_S3.get("s3_tech_domain_parsed", "l3_tech_domain")
    l3_method_col = OUTPUT_COL_NAMES_S3.get("s3_strat_method_parsed", "l3_strategic_method")

    if l3_domain_col not in df.columns or l3_method_col not in df.columns:
        print(f"Warning for {STAGE_NAME_S3_FIX} eligibility: '{l3_domain_col}' or '{l3_method_col}' columns missing.")
        return pd.Series([False] * len(df), index=df.index)
        
    # Was it eligible for the main S3 run? (Uses eligibility_filter_s3 from Cell 8)
    was_eligible_for_s3_main = eligibility_filter_s3(df) 
    
    # Define what indicates an L3 failure needing a retry
    failed_l3_output_values = [ 
        "Parse Error (Key Missing)", "Not Found in LLM Output", 
        "API Error in Batch", "Classification Failed", "", 
        "Not Categorized L3", # Placeholder from original L3 script if LLM couldn't categorize
        "Not Processed by Stage", "Not Eligible for Stage", pd.NA 
    ] 
    
    failed_l3_domain = df[l3_domain_col].astype(str).isin(failed_l3_output_values) | df[l3_domain_col].isnull()
    failed_l3_method = df[l3_method_col].astype(str).isin(failed_l3_output_values) | df[l3_method_col].isnull()
    
    return was_eligible_for_s3_main & (failed_l3_domain | failed_l3_method)

# --- Execute Stage 3.1 ---
if 'df_complete' in locals() and isinstance(df_complete, pd.DataFrame) and not df_complete.empty and model:
    rows_needing_s3_fix_mask = eligibility_filter_s3_fix(df_complete)
    if not rows_needing_s3_fix_mask.any():
        print(f"Stage {STAGE_NAME_S3_FIX}: No rows found needing L3 fix. df_complete remains unchanged.")
    else:
        print(f"Input for {STAGE_NAME_S3_FIX}: df_complete ({len(df_complete)} rows). Target to fix: {rows_needing_s3_fix_mask.sum()}")
        s3_fix_input_cols_ok = all(col in df_complete.columns for col in INPUT_FIELDS_S3) # INPUT_FIELDS_S3 from Cell 8
        
        if s3_fix_input_cols_ok:
            df_complete = process_stage(
                df_main=df_complete,       
                stage_name=STAGE_NAME_S3_FIX,
                prompt_template_str=PROMPT_TEMPLATE_S3_FULL, 
                item_prompt_format_str=ITEM_PROMPT_FORMAT_S3, 
                input_fields_for_prompt=INPUT_FIELDS_S3,     
                llm_expected_labels_map=LLM_EXPECTED_LABELS_S3, 
                output_col_names_map=OUTPUT_COL_NAMES_S3,    
                model_instance=model,
                eligibility_filter_fn=eligibility_filter_s3_fix, 
                run_trial_mode=RUN_OVERALL_TRIAL_MODE, 
                max_batches_trial=MAX_BATCHES_FOR_TRIAL, 
                batch_size=5,  # Smaller batch for fixing
                wait_time=15,  # Override default: Longer wait for fixing complex L3
                llm_output_separator="---" 
            )
            
            if not df_complete.empty:
                print(f"\n{STAGE_NAME_S3_FIX} completed.")
                print("Sample of rows that were targeted for L3 Fix (first 5, showing L3 cols):")
                cols_to_display_s3_fix = ['id', 'full_text'] + list(OUTPUT_COL_NAMES_S3.values())
                cols_to_display_s3_fix = [col for col in cols_to_display_s3_fix if col in df_complete.columns]
                if rows_needing_s3_fix_mask.any() and cols_to_display_s3_fix:
                     display(df_complete[rows_needing_s3_fix_mask][cols_to_display_s3_fix].head())
                else:
                     print("No rows were targeted for S3 fix for display, or relevant columns missing.")

                try:
                    df_complete.to_csv(MAIN_DATAFRAME_CHECKPOINT_FILE, index=False)
                    print(f"Saved updated df_complete after {STAGE_NAME_S3_FIX} to checkpoint: {MAIN_DATAFRAME_CHECKPOINT_FILE}")
                except Exception as e:
                    print(f"Error saving checkpoint after {STAGE_NAME_S3_FIX}: {e}")
        else:
            print(f"Skipping {STAGE_NAME_S3_FIX} due to missing input columns.")
else:
    if 'df_complete' not in locals() or not isinstance(df_complete, pd.DataFrame) or df_complete.empty:
        print(f"Skipping Stage {STAGE_NAME_S3_FIX}: df_complete not ready or model not initialized.")
    if not model:
        print(f"Skipping Stage {STAGE_NAME_S3_FIX}: LLM Model is not initialized.")

Stage L3_Fix_Failed_Categorization: No rows found needing L3 fix. df_complete remains unchanged.

In [17]:
# ## Stage 4: L3 Area Consolidation->L4
# --- Stage 4 Configuration ---
STAGE_NAME_S4 = "L3_Area_Consolidation"

# Full prompt for L3 Area Consolidation (PROMPT_PREFIX_L3_AREA_CONSOLIDATION from your original In[188])
PROMPT_TEMPLATE_S4_FULL = """You are an expert taxonomist. Your primary task is to consolidate and standardize existing Level 3 project labels. The strict goal is to refine the current lists into:
A highly consolidated set of 70-80 distinct 'Standardized L3 Domain Areas'.
A highly consolidated set of 70-80 distinct 'Standardized L3 Method Areas'.
Adherence to this target number range (70-80) for each list is paramount. Each standardized category should be a clear, searchable, and appropriately broad Level 3 representation of either a thematic domain or a functional approach.
For each project, you will be given:
The original Project Summary (for essential context and disambiguation).
Two existing Level 3 labels:
An Existing L3 Application/Technology Domain (the current, potentially too granular or inconsistently phrased, domain label).
An Existing L3 Strategic Method Category (the current, potentially too granular or inconsistently phrased, method label).
Your task is to map BOTH of these existing L3 labels to new, standardized Level 3 categories:
A Standardized L3 Domain Area.
A Standardized L3 Method Area.
Core Principles for This Level 3 Standardization & Consolidation:
Each standardized L3 area must represent a well-recognized and significant domain, field, societal challenge, strategic approach, or core function, suitable for a list strictly limited to 70-80 distinct items per type. Prioritize broader categories to meet this numerical constraint.
Abstract away all non-essential specificity or minor variations from the 'Existing L3' labels. Aggressively broaden categories. For 'Domain Areas', remove action qualifiers (e.g., "improvement") if the core theme is clear, consolidating under the core thematic concept.
The domain area should more reflect the purpose of the projects, while the method should reflect how this is being achieved.
Use the Project Summary to determine the most fitting standardized L3 areas.
Employ significant, systematic consolidation: Group closely related 'Existing L3' labels under a unified 'Standardized L3 Area'. To achieve the 70-80 target for each list, you MUST favor broader categorizations. For example, while 'Solar Energy' and 'Wind Energy' could be distinct, if many such specific sub-types exist, you should strongly consider consolidating them under a broader category like 'Renewable Energy Technologies' if it helps meet the 70-80 target and aligns with the exemplar breadth. The primary driver is the reduction of category count to the target range.
Exemplar Standardized L3 Domain Areas (illustrative of target breadth):
Biomedical Research & Discovery
Public Health & Prevention
Healthcare Services & Innovation
Pharmaceutical Development
Neurological Disorders & Therapies
Climate Change Mitigation
Environmental Protection & Restoration
Renewable Energy Technologies
Sustainable Energy Systems
Energy Efficiency & Conservation
Circular Economy & Resource Efficiency
Materials Science & Engineering
Nanomaterials & Nanotechnology
Advanced Manufacturing & Industrial Processes
Artificial Intelligence & Machine Learning
Data Science & Big Data Analytics
Cybersecurity & Digital Privacy
Sustainable Mobility & Transport
Urban Planning & Smart Cities
Biodiversity & Conservation
Public Policy & Administration
Entrepreneurship & Innovation
Agricultural Systems & Food Security
Water Resource Management
Space Exploration & Technology
Exemplar Standardized L3 Method Areas (illustrative of target breadth):
Basic & Applied Research
Experimental Design & Execution
Field Research & Observation
Computational Modeling & Simulation
Statistical Analysis & Quantitative Methods
Qualitative Research Methods
Data Collection & Curation
AI & Machine Learning Application
Software & Algorithm Development
Engineering Design & Systems Integration
Pre-clinical Drug Development
Clinical Research
Policy Analysis & Formulation
Stakeholder Engagement & Co-Design
Capacity Building & Training Delivery
Educational Program Development
Communication Strategies
Monitoring, Reporting & Evaluation
Innovation Ecosystem Facilitation
Technology Transfer & Commercialization
Supply Chain Optimization
Risk Assessment & Management
Prototyping & Pilot Projects
Instructions:
Output TWO standardized L3 areas (max 3 words each) - one for domain, one for method.
Map to Categories of Exemplar Breadth: Your primary goal is to map 'Existing L3' labels to 'Standardized L3 Areas' that match the level of specificity shown in the provided exemplar lists. Crucially, this requires aggressive consolidation to ensure the total distinct categories for Domains and Methods each strictly fall within the 70-80 range. If an 'Existing L3' label is more granular than the exemplars or would lead to exceeding the target count, it must be broadened and mapped to a more general standardized category.
Consolidate Synonyms, Minor Variations, and Conceptually Related Items: Actively seek to merge very similar 'Existing L3' labels. Extend this principle to group conceptually related items even if not direct synonyms, if doing so is necessary to achieve the target of 70-80 distinct categories per list and aligns with the exemplar breadth. For example, "AI-Driven Analysis," "AI-Powered Analytics," and "Machine Learning for Data Insight" must consolidate, e.g., to "AI & Machine Learning Application" (Method Area).
Use Project Summary for Disambiguation & Best Fit: Crucial for selecting the most appropriate standardized L3 area that aligns with the consolidation goals.
Standardize Terminology: Use consistent terms for the output standardized L3 areas, drawing inspiration from the style and breadth of the exemplars. Do not invent highly niche categories.
Overarching Directive: The success of this task is measured by your ability to reduce category proliferation and strictly adhere to the 70-80 distinct category limit for both Domain Areas and Method Areas. Be decisive in merging and broadening existing labels to meet this target. If an existing label is highly specific, find the appropriate broader exemplar-style category it belongs to.
Output Format (one section per project, separated by "---"):
Standardized Domain Area: [short, thematic area label of target L3 breadth]
Standardized Method Area: [short, functional area label of target L3 breadth]
---
Example 2:
Project Summary: Project focusing on developing new drugs for Alzheimer's disease through identification of novel biological targets and extensive pre-clinical testing.
Existing L3 Application/Technology Domain: Neurological Disease Treatment
Existing L3 Strategic Method Category: Biomedical R&D Methodology
Your output for this project:
Standardized Domain Area: Neurological Disorders & Therapies
Standardized Method Area: Pre-clinical Drug Development
---
Example 3:
Project Summary: Initiative to create pan-European educational programs for young entrepreneurs, fostering innovation and cross-border collaboration, with specific modules on digital marketing and venture finance.
Existing L3 Application/Technology Domain: Entrepreneurship Education
Existing L3 Strategic Method Category: Ecosystem Development
Your output for this project:
Standardized Domain Area: Entrepreneurship & Innovation
Standardized Method Area: Educational Program Development
---
Now, analyze the following projects. For each, provide BOTH 'Standardized Domain Area' and 'Standardized Method Area' labels per the format above, separated by "---". Ensure consolidation into categories matching the breadth and style of the exemplar lists, strictly aiming for 70-80 distinct categories for domains and 70-80 for methods.
"""

ITEM_PROMPT_FORMAT_S4 = (
    "\nProject #{project_num_in_prompt}:\n"
    "Project Summary: {full_text}\n"
    "Existing L3 Application/Technology Domain: {l3_tech_domain}\n"    # Uses output from S3/S3.1
    "Existing L3 Strategic Method Category: {l3_strategic_method}\n" # Uses output from S3/S3.1
)

INPUT_FIELDS_S4 = ['full_text', 'l3_tech_domain', 'l3_strategic_method']

# Note: The parser needs to handle optional "L3" in the LLM's output keys
LLM_EXPECTED_LABELS_S4 = {
    "Standardized Domain Area:": "s4_std_domain_parsed", # Will also match "Standardized L3 Domain Area:" due to how generic_extract_labels works
    "Standardized Method Area:": "s4_std_method_parsed"  # Will also match "Standardized L3 Method Area:"
}
# If the LLM is inconsistent, you might add more specific keys here, or improve the regex in generic_extract_labels.
# For now, relying on the case-insensitive prefix match in generic_extract_labels.

OUTPUT_COL_NAMES_S4 = {
    "s4_std_domain_parsed": "l3_std_domain_area",
    "s4_std_method_parsed": "l3_std_method_area"
}

def eligibility_filter_s4(df: pd.DataFrame) -> pd.Series:
    l3_domain_col = OUTPUT_COL_NAMES_S3.get("s3_tech_domain_parsed", "l3_tech_domain")
    l3_method_col = OUTPUT_COL_NAMES_S3.get("s3_strat_method_parsed", "l3_strategic_method")

    if l3_domain_col not in df.columns or l3_method_col not in df.columns:
        print(f"Warning for {STAGE_NAME_S4} eligibility: L3 columns '{l3_domain_col}' or '{l3_method_col}' missing.")
        return pd.Series([False] * len(df), index=df.index)

    invalid_l3_output_values = [
        "Parse Error (Key Missing)", "Not Found in LLM Output", "API Error in Batch",
        "Classification Failed", "Not Processed by Stage", "Not Eligible for Stage",
        "Not Applicable L3", "Not Categorized L3", "", pd.NA # "Not Categorized L3" was from original L3 script
    ]
    is_l3_domain_valid = df[l3_domain_col].notna() & (~df[l3_domain_col].astype(str).isin(invalid_l3_output_values))
    is_l3_method_valid = df[l3_method_col].notna() & (~df[l3_method_col].astype(str).isin(invalid_l3_output_values))
    return is_l3_domain_valid & is_l3_method_valid

# --- Execute Stage 4 ---
# df_complete is the main DataFrame, assumed to be updated by Cell 9 (Stage 3.1 Fix)

if 'df_complete' in locals() and isinstance(df_complete, pd.DataFrame) and not df_complete.empty and model:
    print(f"Input for Stage 4 ({STAGE_NAME_S4}): df_complete with {len(df_complete)} rows.")
    print(f"df_complete columns before S4: {df_complete.columns.tolist()}")
    
    s4_input_cols_ok = all(col in df_complete.columns for col in INPUT_FIELDS_S4)
            
    if s4_input_cols_ok:
        df_complete = process_stage( 
            df_main=df_complete, 
            stage_name=STAGE_NAME_S4,
            prompt_template_str=PROMPT_TEMPLATE_S4_FULL,
            item_prompt_format_str=ITEM_PROMPT_FORMAT_S4,
            input_fields_for_prompt=INPUT_FIELDS_S4,
            llm_expected_labels_map=LLM_EXPECTED_LABELS_S4,
            output_col_names_map=OUTPUT_COL_NAMES_S4,
            model_instance=model, # Or model_for_l3_consolidation if you defined it separately
            eligibility_filter_fn=eligibility_filter_s4,
            run_trial_mode=RUN_OVERALL_TRIAL_MODE,
            max_batches_trial=MAX_BATCHES_FOR_TRIAL,
            batch_size=DEFAULT_BATCH_SIZE, 
            wait_time=DEFAULT_WAIT_TIME, 
            llm_output_separator="---" 
        )
        
        if not df_complete.empty:
            print(f"\n{STAGE_NAME_S4} completed. df_complete columns after S4: {df_complete.columns.tolist()}")
            print(f"Sample of updated df_complete (first 5 rows showing L3 and consolidated L3 cols):")
            cols_to_display_s4 = ['id', 'full_text'] + \
                                 [OUTPUT_COL_NAMES_S3.get("s3_tech_domain_parsed", "l3_tech_domain"), 
                                  OUTPUT_COL_NAMES_S3.get("s3_strat_method_parsed", "l3_strategic_method")] + \
                                 list(OUTPUT_COL_NAMES_S4.values())
            cols_to_display_s4 = [col for col in cols_to_display_s4 if col in df_complete.columns]
            if cols_to_display_s4: display(df_complete[cols_to_display_s4].head())

            try:
                df_complete.to_csv(MAIN_DATAFRAME_CHECKPOINT_FILE, index=False)
                print(f"Saved updated df_complete after {STAGE_NAME_S4} to checkpoint: {MAIN_DATAFRAME_CHECKPOINT_FILE}")
            except Exception as e:
                print(f"Error saving checkpoint after {STAGE_NAME_S4}: {e}")
        else:
            print(f"Stage {STAGE_NAME_S4} resulted in an empty DataFrame.")
    else:
        print(f"Skipping {STAGE_NAME_S4} due to missing required input columns in df_complete.")
else:
    if 'df_complete' not in locals() or not isinstance(df_complete, pd.DataFrame) or df_complete.empty:
        print(f"Skipping Stage 4: df_complete not ready or is empty.")
    if not model: 
        print("Skipping Stage 4: LLM Model not initialized.")

Input for Stage 4 (L3_Area_Consolidation): df_complete with 15341 rows.
df_complete columns before S4: ['id', 'full_text', 'l1_goal', 'l1_method', 'l2_generalized_goal', 'l2_generalized_method', 'l3_tech_domain', 'l3_strategic_method']

==================== Running Stage: L3_Area_Consolidation on DataFrame with 15341 rows ====================
Stage L3_Area_Consolidation: 15340 rows eligible for THIS processing call out of 15341.
Stage L3_Area_Consolidation: FULL MODE - Will send 15340 (eligible) records to API.
  Will take 427 batches. Est. API wait: 35.6 min.


  L3_Area_Consolidation - Batch 1/427 (Slice Offsets 0-35)

=== FIRST PROMPT FOR BATCH 1 (Structure Preview) ===
You are an expert taxonomist. Your primary task is to consolidate and standardize existing Level 3 project labels. The strict goal is to refine the current lists into:
A highly consolidated set of 70-80 distinct 'Standardized L3 Domain Areas'.
A highly consolidated set of 70-80 distinct 'Standardized L3 Method Areas'.
Adherence to this target number range (70-80) for each list is paramount. Each standardized category should be a clear, searchable, and appropriately broad Level 3 representation of either a thematic domain or a functional approach.
For each project, you will be given:
The original Project Summary (for essential context and disambiguation).
Two existing Level 3 labels:
An Existing L3 Application/Technology Domain (the current, potentially too granular or inconsistently phrased, domain label).
An Existing L3 Strategic Method Category (the current, potentially too granular or inconsistently phrased, method label).
Your task is to map BOTH of these existing L3 labels to new,...
Item Format Example:
Project #1:
Project Summary: [SAMPLE_FULL_TEXT_FROM_DATA]
Existing L3 Application/Technology Domain: [SAMPLE_L3_TECH_DOMAIN_FROM_DATA]
Existing L3 Strategic Method Category: [SAMPLE_L3_STRATEGIC_METHOD_FROM_DATA]

=== END PROMPT PREVIEW ===


--- RAW LLM OUTPUT (Batch 1, 36 items) ---
Here are the standardized Level 3 domain and method areas for each project, strictly adhering to the specified consolidation and breadth targets:

Project #1:
Standardized Domain Area: Digital Society
Standardized Method Area: Monitoring, Reporting & Evaluation
---
Project #2:
Standardized Domain Area: Space Exploration & Technology
Standardized Method Area: Computational Modeling & Simulation
---
Project #3:
Standardized Domain Area: Biomedical Research & Discovery
Standardized Method Area: Computational Modeling & Simulation
---
Project #4:
Standardized Domain Area: Space Exploration & Technology
Standardized Method Area: Data Science & Big Data Analytics
---
Project #5:
Standardized Domain Area: Biomedical Research & Discovery
Standardized Method Area: AI & Machine Learning Application
---
Project #6:
Standardized Domain Area: Space Exploration & Technology
Standardized Method Area: Data Science & Big Data Analytics
---
Project #7:
Standardized Domain Area: Cultural Heritage Preserv...
--- END RAW LLM OUTPUT ---

--- PARSED LABELS (Batch 1) ---
  Item in batch at offset 0: {'s4_std_domain_parsed': 'Digital Society', 's4_std_method_parsed': 'Monitoring, Reporting & Evaluation'}
  Item in batch at offset 1: {'s4_std_domain_parsed': 'Space Exploration & Technology', 's4_std_method_parsed': 'Computational Modeling & Simulation'}
  Item in batch at offset 2: {'s4_std_domain_parsed': 'Biomedical Research & Discovery', 's4_std_method_parsed': 'Computational Modeling & Simulation'}
  Item in batch at offset 3: {'s4_std_domain_parsed': 'Space Exploration & Technology', 's4_std_method_parsed': 'Data Science & Big Data Analytics'}
  Item in batch at offset 4: {'s4_std_domain_parsed': 'Biomedical Research & Discovery', 's4_std_method_parsed': 'AI & Machine Learning Application'}
  Item in batch at offset 5: {'s4_std_domain_parsed': 'Space Exploration & Technology', 's4_std_method_parsed': 'Data Science & Big Data Analytics'}
  Item in batch at offset 6: {'s4_std_domain_parsed': 'Cultural Heritage Preservation', 's4_std_method_parsed': 'Data Collection & Curation'}
  Item in batch at offset 7: {'s4_std_domain_parsed': 'Nuclear Energy', 's4_std_method_parsed': 'Innovation Ecosystem Facilitation'}
  Item in batch at offset 8: {'s4_std_domain_parsed': 'Nuclear Energy', 's4_std_method_parsed': 'Communication Strategies'}
  Item in batch at offset 9: {'s4_std_domain_parsed': 'Materials Science & Engineering', 's4_std_method_parsed': 'Technology Transfer & Commercialization'}
  Item in batch at offset 10: {'s4_std_domain_parsed': 'Healthcare Services & Innovation', 's4_std_method_parsed': 'Software & Algorithm Development'}
  Item in batch at offset 11: {'s4_std_domain_parsed': 'Healthcare Services & Innovation', 's4_std_method_parsed': 'Clinical Research'}
  Item in batch at offset 12: {'s4_std_domain_parsed': 'Education & Learning', 's4_std_method_parsed': 'Educational Program Development'}
  Item in batch at offset 13: {'s4_std_domain_parsed': 'Education & Learning', 's4_std_method_parsed': 'Capacity Building & Training Delivery'}
  Item in batch at offset 14: {'s4_std_domain_parsed': 'Education & Learning', 's4_std_method_parsed': 'Capacity Building & Training Delivery'}
  Item in batch at offset 15: {'s4_std_domain_parsed': 'Public Policy & Administration', 's4_std_method_parsed': 'Monitoring, Reporting & Evaluation'}
  Item in batch at offset 16: {'s4_std_domain_parsed': 'Urban Planning & Smart Cities', 's4_std_method_parsed': 'Innovation Ecosystem Facilitation'}
  Item in batch at offset 17: {'s4_std_domain_parsed': 'Research Workforce Development', 's4_std_method_parsed': 'Organizational Development'}
  Item in batch at offset 18: {'s4_std_domain_parsed': 'Sustainable Development', 's4_std_method_parsed': 'Innovation Ecosystem Facilitation'}
  Item in batch at offset 19: {'s4_std_domain_parsed': 'Public Policy & Administration', 's4_std_method_parsed': 'Stakeholder Engagement & Co-Design'}
  Item in batch at offset 20: {'s4_std_domain_parsed': 'Knowledge & Innovation', 's4_std_method_parsed': 'Stakeholder Engagement & Co-Design'}
  Item in batch at offset 21: {'s4_std_domain_parsed': 'Science Outreach & Engagement', 's4_std_method_parsed': 'Communication Strategies'}
  Item in batch at offset 22: {'s4_std_domain_parsed': 'Research Workforce Development', 's4_std_method_parsed': 'Organizational Development'}
  Item in batch at offset 23: {'s4_std_domain_parsed': 'Education & Learning', 's4_std_method_parsed': 'Capacity Building & Training Delivery'}
  Item in batch at offset 24: {'s4_std_domain_parsed': 'Climate Change Mitigation', 's4_std_method_parsed': 'Innovation Ecosystem Facilitation'}
  Item in batch at offset 25: {'s4_std_domain_parsed': 'International Research Cooperation', 's4_std_method_parsed': 'Innovation Ecosystem Facilitation'}
  Item in batch at offset 26: {'s4_std_domain_parsed': 'Digital Technologies', 's4_std_method_parsed': 'Innovation Ecosystem Facilitation'}
  Item in batch at offset 27: {'s4_std_domain_parsed': 'Pharmaceutical Development', 's4_std_method_parsed': 'Pre-clinical Drug Development'}
  Item in batch at offset 28: {'s4_std_domain_parsed': 'Infrastructure Systems', 's4_std_method_parsed': 'Automated Systems'}
  Item in batch at offset 29: {'s4_std_domain_parsed': 'Healthcare Services & Innovation', 's4_std_method_parsed': 'Medical Device Development'}
  Item in batch at offset 30: {'s4_std_domain_parsed': 'Public Policy & Administration', 's4_std_method_parsed': 'Stakeholder Engagement & Co-Design'}
  Item in batch at offset 31: {'s4_std_domain_parsed': 'Neurological Disorders & & Therapies', 's4_std_method_parsed': 'Technology Transfer & Commercialization'}
  Item in batch at offset 32: {'s4_std_domain_parsed': 'Open Science', 's4_std_method_parsed': 'Monitoring, Reporting & Evaluation'}
  Item in batch at offset 33: {'s4_std_domain_parsed': 'Healthcare Services & Innovation', 's4_std_method_parsed': 'AI & Machine Learning Application'}
  Item in batch at offset 34: {'s4_std_domain_parsed': 'Agricultural Systems & Food Security', 's4_std_method_parsed': 'Engineering Design & Systems Integration'}
  Item in batch at offset 35: {'s4_std_domain_parsed': 'Entrepreneurship & Innovation', 's4_std_method_parsed': 'Innovation Ecosystem Facilitation'}
  (Parsed 36 items from this batch output, expected 36)
--- END PARSED LABELS ---

  Batch 1 outcome: Labels extracted.
  Waiting 5s...

  L3_Area_Consolidation - Batch 2/427 (Slice Offsets 36-71)

--- RAW LLM OUTPUT (Batch 2, 36 items) ---
Project #37:
Standardized Domain Area: Entrepreneurship & Innovation
Standardized Method Area: Innovation Ecosystem Facilitation
---
Project #38:
Standardized Domain Area: Agricultural Systems & Food Security
Standardized Method Area: Innovation Ecosystem Facilitation
---
Project #39:
Standardized Domain Area: Healthcare Services & Innovation
Standardized Method Area: Policy Analysis & Formulation
---
Project #40:
Standardized Domain Area: Sustainable Development
Standardized Method Area: Stakeholder Engagement & Co-Design
---
Project #41:
Standardized Domain Area: Sustainable Industrial Systems
Standardized Method Area: Innovation Ecosystem Facilitation
---
Project #42:
Standardized Domain Area: Entrepreneurship & Innovation
Standardized Method Area: Capacity Building & Training Delivery
---
Project #43:
Standardized Domain Area: Entrepreneurship & Innovation
Standardized Method Area: Stakeholder Engagement & Co-Design
---
Project #44:
Standardized Domain Area: Urban Planning & Smart ...
--- END RAW LLM OUTPUT ---

--- PARSED LABELS (Batch 2) ---
  Item in batch at offset 0: {'s4_std_domain_parsed': 'Entrepreneurship & Innovation', 's4_std_method_parsed': 'Innovation Ecosystem Facilitation'}
  Item in batch at offset 1: {'s4_std_domain_parsed': 'Agricultural Systems & Food Security', 's4_std_method_parsed': 'Innovation Ecosystem Facilitation'}
  Item in batch at offset 2: {'s4_std_domain_parsed': 'Healthcare Services & Innovation', 's4_std_method_parsed': 'Policy Analysis & Formulation'}
  Item in batch at offset 3: {'s4_std_domain_parsed': 'Sustainable Development', 's4_std_method_parsed': 'Stakeholder Engagement & Co-Design'}
  Item in batch at offset 4: {'s4_std_domain_parsed': 'Sustainable Industrial Systems', 's4_std_method_parsed': 'Innovation Ecosystem Facilitation'}
  Item in batch at offset 5: {'s4_std_domain_parsed': 'Entrepreneurship & Innovation', 's4_std_method_parsed': 'Capacity Building & Training Delivery'}
  Item in batch at offset 6: {'s4_std_domain_parsed': 'Entrepreneurship & Innovation', 's4_std_method_parsed': 'Stakeholder Engagement & Co-Design'}
  Item in batch at offset 7: {'s4_std_domain_parsed': 'Urban Planning & Smart Cities', 's4_std_method_parsed': 'Stakeholder Engagement & Co-Design'}
  Item in batch at offset 8: {'s4_std_domain_parsed': 'Entrepreneurship & Innovation', 's4_std_method_parsed': 'Innovation Ecosystem Facilitation'}
  Item in batch at offset 9: {'s4_std_domain_parsed': 'Public Policy & Administration', 's4_std_method_parsed': 'Capacity Building & Training Delivery'}
  Item in batch at offset 10: {'s4_std_domain_parsed': 'Healthcare Services & Innovation', 's4_std_method_parsed': 'Stakeholder Engagement & Co-Design'}
  Item in batch at offset 11: {'s4_std_domain_parsed': 'Entrepreneurship & Innovation', 's4_std_method_parsed': 'Innovation Ecosystem Facilitation'}
  Item in batch at offset 12: {'s4_std_domain_parsed': 'Entrepreneurship & Innovation', 's4_std_method_parsed': 'Capacity Building & Training Delivery'}
  Item in batch at offset 13: {'s4_std_domain_parsed': 'Sustainable Mobility & Transport', 's4_std_method_parsed': 'Innovation Ecosystem Facilitation'}
  Item in batch at offset 14: {'s4_std_domain_parsed': 'Entrepreneurship & Innovation', 's4_std_method_parsed': 'Innovation Ecosystem Facilitation'}
  Item in batch at offset 15: {'s4_std_domain_parsed': 'Healthcare Services & Innovation', 's4_std_method_parsed': 'AI & Machine Learning Application'}
  Item in batch at offset 16: {'s4_std_domain_parsed': 'Sustainable Energy Systems', 's4_std_method_parsed': 'Stakeholder Engagement & Co-Design'}
  Item in batch at offset 17: {'s4_std_domain_parsed': 'Digital Infrastructure', 's4_std_method_parsed': 'Engineering Design & Systems Integration'}
  Item in batch at offset 18: {'s4_std_domain_parsed': 'Supply Chain Optimization', 's4_std_method_parsed': 'Data Science & Big Data Analytics'}
  Item in batch at offset 19: {'s4_std_domain_parsed': 'Healthcare Services & Innovation', 's4_std_method_parsed': 'Engineering Design & Systems Integration'}
  Item in batch at offset 20: {'s4_std_domain_parsed': 'Healthcare Services & Innovation', 's4_std_method_parsed': 'Engineering Design & Systems Integration'}
  Item in batch at offset 21: {'s4_std_domain_parsed': 'Public Policy & Administration', 's4_std_method_parsed': 'Policy Analysis & Formulation'}
  Item in batch at offset 22: {'s4_std_domain_parsed': 'Research & Development', 's4_std_method_parsed': 'Knowledge Translation'}
  Item in batch at offset 23: {'s4_std_domain_parsed': 'Entrepreneurship & Innovation', 's4_std_method_parsed': 'Innovation Ecosystem Facilitation'}
  Item in batch at offset 24: {'s4_std_domain_parsed': 'Financial Services Innovation', 's4_std_method_parsed': 'Data Science & Big Data Analytics'}
  Item in batch at offset 25: {'s4_std_domain_parsed': 'Healthcare Services & Innovation', 's4_std_method_parsed': 'Cybersecurity & Digital Privacy'}
  Item in batch at offset 26: {'s4_std_domain_parsed': 'Materials Science & Engineering', 's4_std_method_parsed': 'Engineering Design & Systems Integration'}
  Item in batch at offset 27: {'s4_std_domain_parsed': 'Advanced Manufacturing & Industrial Processes', 's4_std_method_parsed': 'AI & Machine Learning Application'}
  Item in batch at offset 28: {'s4_std_domain_parsed': 'Pharmaceutical Development', 's4_std_method_parsed': 'Pre-clinical Drug Development'}
  Item in batch at offset 29: {'s4_std_domain_parsed': 'Sustainable Energy Systems', 's4_std_method_parsed': 'Renewable Energy Integration'}
  Item in batch at offset 30: {'s4_std_domain_parsed': 'Renewable Energy Technologies', 's4_std_method_parsed': 'Sustainable Energy Production'}
  Item in batch at offset 31: {'s4_std_domain_parsed': 'Climate Change Mitigation', 's4_std_method_parsed': 'Technology Development'}
  Item in batch at offset 32: {'s4_std_domain_parsed': 'Healthcare Services & Innovation', 's4_std_method_parsed': 'Engineering Design & Systems Integration'}
  Item in batch at offset 33: {'s4_std_domain_parsed': 'Agricultural Systems & Food Security', 's4_std_method_parsed': 'Technology Transfer & Commercialization'}
  Item in batch at offset 34: {'s4_std_domain_parsed': 'Pharmaceutical Development', 's4_std_method_parsed': 'AI & Machine Learning Application'}
  Item in batch at offset 35: {'s4_std_domain_parsed': 'Cybersecurity & Digital Privacy', 's4_std_method_parsed': 'Stakeholder Engagement & Co-Design'}
  (Parsed 36 items from this batch output, expected 36)
--- END PARSED LABELS ---

  Batch 2 outcome: Labels extracted.
  Waiting 5s...

  L3_Area_Consolidation - Batch 3/427 (Slice Offsets 72-107)

--- RAW LLM OUTPUT (Batch 3, 36 items) ---
Standardized Domain Area: Financial Services
Standardized Method Area: AI & Machine Learning Application
---
Standardized Domain Area: Semiconductor Technology
Standardized Method Area: Engineering Design & Systems Integration
---
Standardized Domain Area: Medical Device Technology
Standardized Method Area: Engineering Design & Systems Integration
---
Standardized Domain Area: Regional Development
Standardized Method Area: Innovation Ecosystem Facilitation
---
Standardized Domain Area: Higher Education
Standardized Method Area: Capacity Building & Training Delivery
---
Standardized Domain Area: Entrepreneurship & Innovation
Standardized Method Area: Technology Transfer & Commercialization
---
Standardized Domain Area: Workforce Development
Standardized Method Area: Educational Program Development
---
Standardized Domain Area: Circular Economy & Resource Efficiency
Standardized Method Area: Technology Transfer & Commercialization
---
Standardized Domain Area: Agricultural Systems & Food...
--- END RAW LLM OUTPUT ---

--- PARSED LABELS (Batch 3) ---
  Item in batch at offset 0: {'s4_std_domain_parsed': 'Financial Services', 's4_std_method_parsed': 'AI & Machine Learning Application'}
  Item in batch at offset 1: {'s4_std_domain_parsed': 'Semiconductor Technology', 's4_std_method_parsed': 'Engineering Design & Systems Integration'}
  Item in batch at offset 2: {'s4_std_domain_parsed': 'Medical Device Technology', 's4_std_method_parsed': 'Engineering Design & Systems Integration'}
  Item in batch at offset 3: {'s4_std_domain_parsed': 'Regional Development', 's4_std_method_parsed': 'Innovation Ecosystem Facilitation'}
  Item in batch at offset 4: {'s4_std_domain_parsed': 'Higher Education', 's4_std_method_parsed': 'Capacity Building & Training Delivery'}
  Item in batch at offset 5: {'s4_std_domain_parsed': 'Entrepreneurship & Innovation', 's4_std_method_parsed': 'Technology Transfer & Commercialization'}
  Item in batch at offset 6: {'s4_std_domain_parsed': 'Workforce Development', 's4_std_method_parsed': 'Educational Program Development'}
  Item in batch at offset 7: {'s4_std_domain_parsed': 'Circular Economy & Resource Efficiency', 's4_std_method_parsed': 'Technology Transfer & Commercialization'}
  Item in batch at offset 8: {'s4_std_domain_parsed': 'Agricultural Systems & Food Security', 's4_std_method_parsed': 'Engineering Design & Systems Integration'}
  Item in batch at offset 9: {'s4_std_domain_parsed': 'Entrepreneurship & Innovation', 's4_std_method_parsed': 'Innovation Ecosystem Facilitation'}
  Item in batch at offset 10: {'s4_std_domain_parsed': 'Medical Device Technology', 's4_std_method_parsed': 'Engineering Design & Systems Integration'}
  Item in batch at offset 11: {'s4_std_domain_parsed': 'Medical Device Technology', 's4_std_method_parsed': 'Engineering Design & Systems Integration'}
  Item in batch at offset 12: {'s4_std_domain_parsed': 'Materials Science & Engineering', 's4_std_method_parsed': 'Advanced Manufacturing & Industrial Processes'}
  Item in batch at offset 13: {'s4_std_domain_parsed': 'Renewable Energy Technologies', 's4_std_method_parsed': 'AI & Machine Learning Application'}
  Item in batch at offset 14: {'s4_std_domain_parsed': 'Circular Economy & Resource Efficiency', 's4_std_method_parsed': 'Engineering Design & Systems Integration'}
  Item in batch at offset 15: {'s4_std_domain_parsed': 'Agricultural Systems & Food Security', 's4_std_method_parsed': 'Engineering Design & Systems Integration'}
  Item in batch at offset 16: {'s4_std_domain_parsed': 'Healthcare Services & Innovation', 's4_std_method_parsed': 'Technology Transfer & Commercialization'}
  Item in batch at offset 17: {'s4_std_domain_parsed': 'Public Policy & Administration', 's4_std_method_parsed': 'Policy Analysis & Formulation'}
  Item in batch at offset 18: {'s4_std_domain_parsed': 'Materials Science & Engineering', 's4_std_method_parsed': 'Engineering Design & Systems Integration'}
  Item in batch at offset 19: {'s4_std_domain_parsed': 'Environmental Protection & Restoration', 's4_std_method_parsed': 'Engineering Design & Systems Integration'}
  Item in batch at offset 20: {'s4_std_domain_parsed': 'Sustainable Mobility & Transport', 's4_std_method_parsed': 'Stakeholder Engagement & Co-Design'}
  Item in batch at offset 21: {'s4_std_domain_parsed': 'Medical Device Technology', 's4_std_method_parsed': 'Data Science & Big Data Analytics'}
  Item in batch at offset 22: {'s4_std_domain_parsed': 'Healthcare Services & Innovation', 's4_std_method_parsed': 'AI & Machine Learning Application'}
  Item in batch at offset 23: {'s4_std_domain_parsed': 'Entrepreneurship & Innovation', 's4_std_method_parsed': 'Innovation Ecosystem Facilitation'}

,id,full_text,l3_tech_domain,l3_strategic_method,l3_std_domain_area,l3_std_method_area
0,101116741,Digitizing Other Economies: A Comparative Appr...,Digital Society Studies,Societal Impact Analysis,Digital Society,"Monitoring, Reporting & Evaluation"
1,101163161,MOLECULAR QUANTUM DYNAMICS IN LOW TEMPERATURE ...,Space & Planetary Science,Theoretical & Predictive Modeling,Space Exploration & Technology,Computational Modeling & Simulation
2,101160499,Multiscale modelling of aberrant phase transit...,Systems Biology,Complex Systems Simulation,Biomedical Research & Discovery,Computational Modeling & Simulation
3,101166905,The first comprehensive Atlas of the Milky Way...,Astronomy & Astrophysics,Advanced Data Visualization,Space Exploration & Technology,Data Science & Big Data Analytics
4,101162875,Untapping multiparametric 2D luminescence sens...,Biomedical Engineering,Data-Driven Innovation,Biomedical Research & Discovery,AI & Machine Learning Application

Saved updated df_complete after L3_Area_Consolidation to checkpoint: df_processing_checkpoint.csv

In [18]:
# ## Stage 4.1: Fixing Failed L3 Area Consolidations

STAGE_NAME_S4_FIX = "L3_Fix_Failed_Area_Consolidation"
# Reuses S4 configs: PROMPT_TEMPLATE_S4_FULL, ITEM_PROMPT_FORMAT_S4, INPUT_FIELDS_S4, 
#                    LLM_EXPECTED_LABELS_S4, OUTPUT_COL_NAMES_S4 (defined in Cell 10)

def eligibility_filter_s4_fix(df: pd.DataFrame) -> pd.Series:
    l3_std_domain_col = OUTPUT_COL_NAMES_S4.get("s4_std_domain_parsed", "l3_std_domain_area")
    l3_std_method_col = OUTPUT_COL_NAMES_S4.get("s4_std_method_parsed", "l3_std_method_area")

    if l3_std_domain_col not in df.columns or l3_std_method_col not in df.columns:
        print(f"Warning for {STAGE_NAME_S4_FIX} eligibility: L3 Standardized output columns missing.")
        return pd.Series([False] * len(df), index=df.index)
        
    was_eligible_for_s4_main = eligibility_filter_s4(df) # Uses S4 eligibility from Cell 10
    
    failed_s4_values = [ 
        "Parse Error (Key Missing)", "Not Found in LLM Output", 
        "API Error in Batch", "Classification Failed", "", 
        "Not Standardized", # Placeholder from original L3 consolidation script
        "Not Processed by Stage", "Not Eligible for Stage", pd.NA 
    ] 
    
    failed_s4_domain = df[l3_std_domain_col].astype(str).isin(failed_s4_values) | df[l3_std_domain_col].isnull()
    failed_s4_method = df[l3_std_method_col].astype(str).isin(failed_s4_values) | df[l3_std_method_col].isnull()
    
    return was_eligible_for_s4_main & (failed_s4_domain | failed_s4_method)

# --- Execute Stage 4.1 ---
if 'df_complete' in locals() and isinstance(df_complete, pd.DataFrame) and not df_complete.empty and model:
    rows_needing_s4_fix_mask = eligibility_filter_s4_fix(df_complete)
    if not rows_needing_s4_fix_mask.any():
        print(f"Stage {STAGE_NAME_S4_FIX}: No rows found needing L3 Area Consolidation fix.")
    else:
        print(f"Input for {STAGE_NAME_S4_FIX}: df_complete ({len(df_complete)} rows). Target to fix: {rows_needing_s4_fix_mask.sum()}")
        s4_fix_input_cols_ok = all(col in df_complete.columns for col in INPUT_FIELDS_S4) # INPUT_FIELDS_S4 from Cell 10
        
        if s4_fix_input_cols_ok:
            df_complete = process_stage(
                df_main=df_complete,       
                stage_name=STAGE_NAME_S4_FIX,
                prompt_template_str=PROMPT_TEMPLATE_S4_FULL, 
                item_prompt_format_str=ITEM_PROMPT_FORMAT_S4, 
                input_fields_for_prompt=INPUT_FIELDS_S4,     
                llm_expected_labels_map=LLM_EXPECTED_LABELS_S4, 
                output_col_names_map=OUTPUT_COL_NAMES_S4,    
                model_instance=model, # Or model_for_l3_consolidation
                eligibility_filter_fn=eligibility_filter_s4_fix, 
                run_trial_mode=RUN_OVERALL_TRIAL_MODE, 
                max_batches_trial=MAX_BATCHES_FOR_TRIAL, 
                batch_size=10, # Smaller batch for fixing
                wait_time=20,  # Override default: Longer wait for this complex fix
                llm_output_separator="---" 
            )
            
            if not df_complete.empty:
                print(f"\n{STAGE_NAME_S4_FIX} completed.")
                print("Sample of rows that were targeted for L3 Consolidation Fix (first 5):")
                cols_to_display_s4_fix = ['id', 'full_text'] + list(OUTPUT_COL_NAMES_S4.values())
                cols_to_display_s4_fix = [col for col in cols_to_display_s4_fix if col in df_complete.columns]
                if rows_needing_s4_fix_mask.any() and cols_to_display_s4_fix:
                     display(df_complete[rows_needing_s4_fix_mask][cols_to_display_s4_fix].head())

                try:
                    df_complete.to_csv(MAIN_DATAFRAME_CHECKPOINT_FILE, index=False)
                    print(f"Saved updated df_complete after {STAGE_NAME_S4_FIX} to checkpoint: {MAIN_DATAFRAME_CHECKPOINT_FILE}")
                except Exception as e:
                    print(f"Error saving checkpoint after {STAGE_NAME_S4_FIX}: {e}")
        else:
            print(f"Skipping {STAGE_NAME_S4_FIX} due to missing input columns.")
else:
    print(f"Skipping Stage {STAGE_NAME_S4_FIX}: df_complete not ready or model not initialized.")

Input for L3_Fix_Failed_Area_Consolidation: df_complete (15341 rows). Target to fix: 451

==================== Running Stage: L3_Fix_Failed_Area_Consolidation on DataFrame with 15341 rows ====================
Stage L3_Fix_Failed_Area_Consolidation: 451 rows eligible for THIS processing call out of 15341.
Stage L3_Fix_Failed_Area_Consolidation: FULL MODE - Will send 451 (eligible) records to API.
  Will take 46 batches. Est. API wait: 15.3 min.


  L3_Fix_Failed_Area_Consolidation - Batch 1/46 (Slice Offsets 0-9)

=== FIRST PROMPT FOR BATCH 1 (Structure Preview) ===
You are an expert taxonomist. Your primary task is to consolidate and standardize existing Level 3 project labels. The strict goal is to refine the current lists into:
A highly consolidated set of 70-80 distinct 'Standardized L3 Domain Areas'.
A highly consolidated set of 70-80 distinct 'Standardized L3 Method Areas'.
Adherence to this target number range (70-80) for each list is paramount. Each standardized category should be a clear, searchable, and appropriately broad Level 3 representation of either a thematic domain or a functional approach.
For each project, you will be given:
The original Project Summary (for essential context and disambiguation).
Two existing Level 3 labels:
An Existing L3 Application/Technology Domain (the current, potentially too granular or inconsistently phrased, domain label).
An Existing L3 Strategic Method Category (the current, potentially too granular or inconsistently phrased, method label).
Your task is to map BOTH of these existing L3 labels to new,...
Item Format Example:
Project #1:
Project Summary: [SAMPLE_FULL_TEXT_FROM_DATA]
Existing L3 Application/Technology Domain: [SAMPLE_L3_TECH_DOMAIN_FROM_DATA]
Existing L3 Strategic Method Category: [SAMPLE_L3_STRATEGIC_METHOD_FROM_DATA]

=== END PROMPT PREVIEW ===


--- RAW LLM OUTPUT (Batch 1, 10 items) ---
Standardized Domain Area: Industrial Safety & Health
Standardized Method Area: Engineering Design & Systems Integration
---
Standardized Domain Area: Agricultural Systems & Food Security
Standardized Method Area: Systems Analysis
---
Standardized Domain Area: Food Safety
Standardized Method Area: Innovation Ecosystem Facilitation
---
Standardized Domain Area: Marine Biotechnology
Standardized Method Area: Engineering Design & Systems Integration
---
Standardized Domain Area: Sustainable Agriculture
Standardized Method Area: Robotics & Automation
---
Standardized Domain Area: Agricultural Systems & Food Security
Standardized Method Area: Capacity Building & Training Delivery
---
Standardized Domain Area: Sustainable Agriculture
Standardized Method Area: Computational Modeling & Simulation
---
Standardized Domain Area: Circular Economy & Resource Efficiency
Standardized Method Area: Stakeholder Engagement & Co-Design
---
Standardized Domain Area: Materials Science & Engineering
Standardi...
--- END RAW LLM OUTPUT ---

--- PARSED LABELS (Batch 1) ---
  Item in batch at offset 0: {'s4_std_domain_parsed': 'Industrial Safety & Health', 's4_std_method_parsed': 'Engineering Design & Systems Integration'}
  Item in batch at offset 1: {'s4_std_domain_parsed': 'Agricultural Systems & Food Security', 's4_std_method_parsed': 'Systems Analysis'}
  Item in batch at offset 2: {'s4_std_domain_parsed': 'Food Safety', 's4_std_method_parsed': 'Innovation Ecosystem Facilitation'}
  Item in batch at offset 3: {'s4_std_domain_parsed': 'Marine Biotechnology', 's4_std_method_parsed': 'Engineering Design & Systems Integration'}
  Item in batch at offset 4: {'s4_std_domain_parsed': 'Sustainable Agriculture', 's4_std_method_parsed': 'Robotics & Automation'}
  Item in batch at offset 5: {'s4_std_domain_parsed': 'Agricultural Systems & Food Security', 's4_std_method_parsed': 'Capacity Building & Training Delivery'}
  Item in batch at offset 6: {'s4_std_domain_parsed': 'Sustainable Agriculture', 's4_std_method_parsed': 'Computational Modeling & Simulation'}
  Item in batch at offset 7: {'s4_std_domain_parsed': 'Circular Economy & Resource Efficiency', 's4_std_method_parsed': 'Stakeholder Engagement & Co-Design'}
  Item in batch at offset 8: {'s4_std_domain_parsed': 'Materials Science & Engineering', 's4_std_method_parsed': 'Materials Development'}
  Item in batch at offset 9: {'s4_std_domain_parsed': 'Energy Storage Solutions', 's4_std_method_parsed': 'Materials Development'}
  (Parsed 10 items from this batch output, expected 10)
--- END PARSED LABELS ---

  Batch 1 outcome: Labels extracted.
  Waiting 20s...

  L3_Fix_Failed_Area_Consolidation - Batch 2/46 (Slice Offsets 10-19)

--- RAW LLM OUTPUT (Batch 2, 10 items) ---
Standardized Domain Area: Circular Economy & Resource Efficiency
Standardized Method Area: Supply Chain Optimization
---
Standardized Domain Area: Advanced Manufacturing & Industrial Processes
Standardized Method Area: Engineering Design & Systems Integration
---
Standardized Domain Area: Cybersecurity & Digital Privacy
Standardized Method Area: Risk Assessment & Management
---
Standardized Domain Area: Public Policy & Administration
Standardized Method Area: Policy Analysis & Formulation
---
Standardized Domain Area: Artificial Intelligence & Machine Learning
Standardized Method Area: Software & Algorithm Development
---
Standardized Domain Area: Healthcare Services & Innovation
Standardized Method Area: AI & Machine Learning Application
---
Standardized Domain Area: Agricultural Systems & Food Security
Standardized Method Area: Educational Program Development
---
Standardized Domain Area: Biodiversity & Conservation
Standardized Method Area: Ecosystem Management Strategies
---
Standa...
--- END RAW LLM OUTPUT ---

--- PARSED LABELS (Batch 2) ---
  Item in batch at offset 0: {'s4_std_domain_parsed': 'Circular Economy & Resource Efficiency', 's4_std_method_parsed': 'Supply Chain Optimization'}
  Item in batch at offset 1: {'s4_std_domain_parsed': 'Advanced Manufacturing & Industrial Processes', 's4_std_method_parsed': 'Engineering Design & Systems Integration'}
  Item in batch at offset 2: {'s4_std_domain_parsed': 'Cybersecurity & Digital Privacy', 's4_std_method_parsed': 'Risk Assessment & Management'}
  Item in batch at offset 3: {'s4_std_domain_parsed': 'Public Policy & Administration', 's4_std_method_parsed': 'Policy Analysis & Formulation'}
  Item in batch at offset 4: {'s4_std_domain_parsed': 'Artificial Intelligence & Machine Learning', 's4_std_method_parsed': 'Software & Algorithm Development'}
  Item in batch at offset 5: {'s4_std_domain_parsed': 'Healthcare Services & Innovation', 's4_std_method_parsed': 'AI & Machine Learning Application'}
  Item in batch at offset 6: {'s4_std_domain_parsed': 'Agricultural Systems & Food Security', 's4_std_method_parsed': 'Educational Program Development'}
  Item in batch at offset 7: {'s4_std_domain_parsed': 'Biodiversity & Conservation', 's4_std_method_parsed': 'Ecosystem Management Strategies'}
  Item in batch at offset 8: {'s4_std_domain_parsed': 'Data Science & Big Data Analytics', 's4_std_method_parsed': 'Open Science Implementation'}
  Item in batch at offset 9: {'s4_std_domain_parsed': 'Agricultural Systems & Food Security', 's4_std_method_parsed': 'Innovation Ecosystem Facilitation'}
  (Parsed 10 items from this batch output, expected 10)
--- END PARSED LABELS ---

  Batch 2 outcome: Labels extracted.
  Waiting 20s...

  L3_Fix_Failed_Area_Consolidation - Batch 3/46 (Slice Offsets 20-29)

--- RAW LLM OUTPUT (Batch 3, 10 items) ---
Standardized Domain Area: Advanced Manufacturing & Industrial Processes
Standardized Method Area: Prototyping & Pilot Projects
---
Standardized Domain Area: Public Policy & Administration
Standardized Method Area: Policy Analysis & Formulation
---
Standardized Domain Area: Entrepreneurship & Innovation
Standardized Method Area: Software & Algorithm Development
---
Standardized Domain Area: Circular Economy & Resource Efficiency
Standardized Method Area: Supply Chain Optimization
---
Standardized Domain Area: Workforce Development & Training
Standardized Method Area: Capacity Building & Training Delivery
---
Standardized Domain Area: Critical Infrastructure Protection
Standardized Method Area: Innovation Ecosystem Facilitation
---
Standardized Domain Area: Water Resource Management
Standardized Method Area: Stakeholder Engagement & Co-Design
---
Standardized Domain Area: Social Equity & Welfare
Standardized Method Area: Policy Analysis & Formulation
---
Standardized Domain Area: Educati...
--- END RAW LLM OUTPUT ---

--- PARSED LABELS (Batch 3) ---
  Item in batch at offset 0: {'s4_std_domain_parsed': 'Advanced Manufacturing & Industrial Processes', 's4_std_method_parsed': 'Prototyping & Pilot Projects'}
  Item in batch at offset 1: {'s4_std_domain_parsed': 'Public Policy & Administration', 's4_std_method_parsed': 'Policy Analysis & Formulation'}
  Item in batch at offset 2: {'s4_std_domain_parsed': 'Entrepreneurship & Innovation', 's4_std_method_parsed': 'Software & Algorithm Development'}
  Item in batch at offset 3: {'s4_std_domain_parsed': 'Circular Economy & Resource Efficiency', 's4_std_method_parsed': 'Supply Chain Optimization'}
  Item in batch at offset 4: {'s4_std_domain_parsed': 'Workforce Development & Training', 's4_std_method_parsed': 'Capacity Building & Training Delivery'}
  Item in batch at offset 5: {'s4_std_domain_parsed': 'Critical Infrastructure Protection', 's4_std_method_parsed': 'Innovation Ecosystem Facilitation'}
  Item in batch at offset 6: {'s4_std_domain_parsed': 'Water Resource Management', 's4_std_method_parsed': 'Stakeholder Engagement & Co-Design'}
  Item in batch at offset 7: {'s4_std_domain_parsed': 'Social Equity & Welfare', 's4_std_method_parsed': 'Policy Analysis & Formulation'}
  Item in batch at offset 8: {'s4_std_domain_parsed': 'Education Systems & Policy', 's4_std_method_parsed': 'Educational Program Development'}
  Item in batch at offset 9: {'s4_std_domain_parsed': 'Agricultural Systems & Food Security', 's4_std_method_parsed': 'Stakeholder Engagement & Co-Design'}
  (Parsed 10 items from this batch output, expected 10)
--- END PARSED LABELS ---

  Batch 3 outcome: Labels extracted.
  Waiting 20s...

  L3_Fix_Failed_Area_Consolidation - Batch 6/46 (Slice Offsets 50-59)

  L3_Fix_Failed_Area_Consolidation - Batch 11/46 (Slice Offsets 100-109)
  Waiting 20s...

  L3_Fix_Failed_Area_Consolidation - Batch 16/46 (Slice Offsets 150-159)

  L3_Fix_Failed_Area_Consolidation - Batch 21/46 (Slice Offsets 200-209)
  Waiting 20s...

  L3_Fix_Failed_Area_Consolidation - Batch 26/46 (Slice Offsets 250-259)

  L3_Fix_Failed_Area_Consolidation - Batch 31/46 (Slice Offsets 300-309)
  Waiting 20s...

  L3_Fix_Failed_Area_Consolidation - Batch 36/46 (Slice Offsets 350-359)

  L3_Fix_Failed_Area_Consolidation - Batch 41/46 (Slice Offsets 400-409)
  Waiting 20s...

  L3_Fix_Failed_Area_Consolidation - Batch 46/46 (Slice Offsets 450-450)

Stage L3_Fix_Failed_Area_Consolidation: API calls complete. 46/46 batches yielded some parsable results.

=============== Stage L3_Fix_Failed_Area_Consolidation - FINAL SUMMARY ===============
  Input records to stage (df_main): 15341
  Eligible records (before trial slice): 451
  Records sent to API (after trial slice if any): 451
  Successfully received and parsed at least one valid label for: 451 records.
  Success rate on records sent to API: 100%

  Top values for output columns in Stage L3_Fix_Failed_Area_Consolidation (from 15341 total rows):
    Column 'l3_std_domain_area':
      - "Biomedical Research & Discovery": 918
      - "Materials Science & Engineering": 602
      - "Healthcare Services & Innovation": 544
      - "Sustainable Energy Systems": 533
      - "Agricultural Systems & Food Security": 515
      - "Public Policy & Administration": 469
      - "Pharmaceutical Development": 463
        ...
    Column 'l3_std_method_area':
      - "Engineering Design & Systems Integration": 2274
      - "Computational Modeling & Simulation": 1094
      - "Basic & Applied Research": 1039
      - "Policy Analysis & Formulation": 622
      - "AI & Machine Learning Application": 608
      - "Experimental Design & Execution": 554
      - "Qualitative Research Methods": 525
        ...

L3_Fix_Failed_Area_Consolidation completed.
Sample of rows that were targeted for L3 Consolidation Fix (first 5):

,id,full_text,l3_std_domain_area,l3_std_method_area
180,101071600,"Louis, the smart earplug for industry made in ...",Industrial Safety & Health,Engineering Design & Systems Integration
792,101060887,Food Systems Transformation in Southern Africa...,Agricultural Systems & Food Security,Systems Analysis
793,101136754,Catalysing scientific innovation into food saf...,Food Safety,Innovation Ecosystem Facilitation
794,101134820,Bioprocesses for metabolite production from ma...,Marine Biotechnology,Engineering Design & Systems Integration
795,101070496,Accelerating the achievement of EU Green Deal ...,Sustainable Agriculture,Robotics & Automation

Saved updated df_complete after L3_Fix_Failed_Area_Consolidation to checkpoint: df_processing_checkpoint.csv

In [33]:
# CELL 12 - Stage 5.1: Batch Consolidate Unique L3 Std. Areas to ~100/100 Lists
# (Assuming LLM now outputs clean categories directly, no prefix cleaning needed)

# ## Stage 5.1: Consolidate Unique L3 Standardized Areas to ~100 Categories Each

STAGE_NAME_S5_1 = "S5.1_Consolidate_L3Std_To_100"
print(f"\n{'='*20} Starting Stage: {STAGE_NAME_S5_1} {'='*20}")

model_cat_list_gen = model # Using the globally defined model

# --- Helper Functions for Stage 5.1 ---

# IMPORTANT: Your PROMPT_S5_1_CONSOLIDATE_TO_100 should now include an instruction
# like "Do not add any numbering or bullet points to the category names."
PROMPT_S5_1_CONSOLIDATE_TO_100 = """You are an expert taxonomist. Your task is to consolidate the provided list of categories into a smaller, more manageable set of standardized categories.

You will be given:
1. A list of Domain Area categories to consolidate (e.g., up to 505 entries in this batch)
2. A list of Method Area categories to consolidate (e.g., up to 505 entries in this batch)

Your task is to:
1. Reduce the provided list of Domain Area categories to approximately 100 standardized categories.
2. Reduce the provided list of Method Area categories to approximately 100 standardized categories.

Core Principles for Consolidation:
* Identify common themes and patterns across related categories.
* Group conceptually similar items together under broader labels.
* Ensure each consolidated category is clear, descriptive, and represents a distinct domain or method.
* Use established terminology from research and industry.
* The consolidated categories should cover the full range of the original categories provided in this batch.
* Each standardized category should have a clear scope and purpose. Example target breadth: "Microelectronics".

Consolidate by:
* Merging synonyms and near-synonyms (e.g., "AI Applications" and "Artificial Intelligence Utilization").
* Grouping sub-areas under broader domains (e.g., "Solar Energy", "Wind Energy" → "Renewable Energy Technologies").
* Standardizing terminology and removing qualifiers when the core concept is clear.

Output Format:
----Domain Areas----
[Consolidated Category Name 1]
[Consolidated Category Name 2]
... 
[Approximately 100 Consolidated Categories]

----Method Areas----
[Consolidated Category Name 1]
[Consolidated Category Name 2]
...
[Approximately 100 Consolidated Categories]

**IMPORTANT INSTRUCTION: Ensure that the category names themselves do NOT include any leading numbers, bullet points, or other list markers (e.g., no "1. Category Name", just "Category Name").**

Here are the categories for THIS BATCH to consolidate:

----Domain Areas to Consolidate----
{domain_categories_list_str}

----Method Areas to Consolidate----
{method_categories_list_str}
Remember: For the lists provided in THIS BATCH, produce approximately 100 Domain Areas and approximately 100 Method Areas in your response.
"""

def batch_category_strings_by_count(
    categories: List[str], 
    batch_size_count: int = 505 
) -> List[List[str]]:
    if not categories: return [[]] 
    return [categories[i:i + batch_size_count] for i in range(0, len(categories), batch_size_count)]

def call_llm_for_category_batch_consolidation( 
    domain_category_batch_list: List[str], 
    method_category_batch_list: List[str], 
    model_to_use, 
    prompt_template: str,
    batch_num_for_api: int, 
    max_retries: int = 3
) -> Dict[str, List[str]]:
    if not model_to_use:
        print(f"Model not available for S5.1 batch {batch_num_for_api}. Skipping API call.")
        return {"domains_raw": [], "methods_raw": []} 

    domain_categories_str_for_prompt = "\n".join(domain_category_batch_list)
    method_categories_str_for_prompt = "\n".join(method_category_batch_list)
    prompt = prompt_template.format(
        domain_categories_list_str=domain_categories_str_for_prompt,
        method_categories_list_str=method_categories_str_for_prompt
    )

    if batch_num_for_api == 1 : 
        print(f"\n=== S5.1 CONSOLIDATION PROMPT (Batch 1 - Structure Preview) ===")
        sample_prompt = prompt_template.format(
            domain_categories_list_str=f"[List of {len(domain_category_batch_list)} Domain Categories...]",
            method_categories_list_str=f"[List of {len(method_category_batch_list)} Method Categories...]"
        )
        print(sample_prompt.split("Here are the categories",1)[0] + "...") 
        print("=== END S5.1 PROMPT SAMPLE ===\n")
        
    output_text = ""
    for attempt in range(max_retries):
        try:
            response = model_to_use.generate_content(prompt)
            output_text = response.text
            break
        except Exception as e:
            print(f"Error on S5.1 API call (Batch {batch_num_for_api}, Attempt {attempt + 1}): {type(e).__name__} - {e}")
            if attempt < max_retries - 1: 
                sleep_duration = (2 ** attempt) * 3 
                print(f"  Retrying S5.1 Batch {batch_num_for_api} in {sleep_duration}s...")
                time.sleep(sleep_duration)
            else: print(f"Failed all S5.1 retry attempts for Batch {batch_num_for_api}.")

    # Directly extract lists, assuming they are clean from LLM
    extracted_domains, extracted_methods = [], []
    if output_text:
        if batch_num_for_api == 1: 
             print(f"\n--- RAW LLM OUTPUT (S5.1 Batch 1) ---")
             print(output_text[:1000] + ("..." if len(output_text) > 1000 else ""))
             print("--- END RAW LLM OUTPUT ---\n")

        domains_section = re.search(r'----Domain Areas----\s*([\s\S]*?)(?=----Method Areas----|\Z)', output_text, re.IGNORECASE)
        methods_section = re.search(r'----Method Areas----\s*([\s\S]*?)(?=\Z)', output_text, re.IGNORECASE)
        
        if domains_section:
            extracted_domains = [line.strip() for line in domains_section.group(1).strip().split('\n') if line.strip()]
        if methods_section:
            extracted_methods = [line.strip() for line in methods_section.group(1).strip().split('\n') if line.strip()]
    
    print(f"  S5.1 Batch {batch_num_for_api} -> LLM returned {len(extracted_domains)} domain strings, {len(extracted_methods)} method strings.")
    # Return "domains_raw" and "methods_raw" for consistency, even though we expect them to be clean
    return {"domains_raw": extracted_domains, "methods_raw": extracted_methods}

# --- Execute Stage 5.1 ---
s5_1_final_consolidated_domains = [] # Changed from s5_1_final_cleaned_domains
s5_1_final_consolidated_methods = [] # Changed from s5_1_final_cleaned_methods

if 'df_complete' in locals() and isinstance(df_complete, pd.DataFrame) and not df_complete.empty and model_cat_list_gen:
    print(f"Input for {STAGE_NAME_S5_1}: df_complete with {len(df_complete)} rows.")
    
    std_domain_col_s4 = OUTPUT_COL_NAMES_S4.get("s4_std_domain_parsed", "l3_std_domain_area")
    std_method_col_s4 = OUTPUT_COL_NAMES_S4.get("s4_std_method_parsed", "l3_std_method_area")

    if std_domain_col_s4 not in df_complete.columns or std_method_col_s4 not in df_complete.columns:
        print(f"ERROR for {STAGE_NAME_S5_1}: L3 Standardized columns ('{std_domain_col_s4}', '{std_method_col_s4}') not found.")
    else:
        s4_error_placeholders = [ "Not Standardized", "Not Applicable Std", "Parse Error (Key Missing)", 
                                  "Not Found in LLM Output", "API Error in Batch", 
                                  "Classification Failed", "", pd.NA ]
        unique_s4_domains_input_list = sorted(list(df_complete[
            df_complete[std_domain_col_s4].notna() & \
            (~df_complete[std_domain_col_s4].astype(str).isin(s4_error_placeholders))
        ][std_domain_col_s4].unique()))
        unique_s4_methods_input_list = sorted(list(df_complete[
            df_complete[std_method_col_s4].notna() & \
            (~df_complete[std_method_col_s4].astype(str).isin(s4_error_placeholders))
        ][std_method_col_s4].unique()))

        print(f"Found {len(unique_s4_domains_input_list)} unique valid L3 Std Domain Areas to consolidate.")
        print(f"Found {len(unique_s4_methods_input_list)} unique valid L3 Std Method Areas to consolidate.")

        if not unique_s4_domains_input_list and not unique_s4_methods_input_list:
            print(f"{STAGE_NAME_S5_1}: No unique valid categories. Skipping LLM consolidation.")
        else:
            domain_category_batches = batch_category_strings_by_count(unique_s4_domains_input_list, batch_size_count=600)
            method_category_batches = batch_category_strings_by_count(unique_s4_methods_input_list, batch_size_count=600)
            num_api_calls = max(len(domain_category_batches), len(method_category_batches))
            if num_api_calls == 0 and (unique_s4_domains_input_list or unique_s4_methods_input_list): num_api_calls = 1
            while len(domain_category_batches) < num_api_calls: domain_category_batches.append([])
            while len(method_category_batches) < num_api_calls: method_category_batches.append([])

            print(f"{STAGE_NAME_S5_1}: Will make {num_api_calls} API call(s).")

            # These lists will now store the directly extracted (hopefully clean) categories
            collected_domains_from_llm = []
            collected_methods_from_llm = []

            for i_batch_for_api in range(num_api_calls):
                current_domain_batch_for_api = domain_category_batches[i_batch_for_api]
                current_method_batch_for_api = method_category_batches[i_batch_for_api]
                print(f"\n--- Processing S5.1 API Batch {i_batch_for_api+1}/{num_api_calls} ---")
                if not current_domain_batch_for_api and not current_method_batch_for_api:
                    print(f"  Skipping API call for S5.1 batch {i_batch_for_api+1} as both input lists are empty.")
                    continue
                batch_result_dict = call_llm_for_category_batch_consolidation(
                    current_domain_batch_for_api, current_method_batch_for_api,
                    model_cat_list_gen, PROMPT_S5_1_CONSOLIDATE_TO_100,
                    batch_num_for_api=i_batch_for_api + 1 )
                collected_domains_from_llm.extend(batch_result_dict["domains_raw"]) 
                collected_methods_from_llm.extend(batch_result_dict["methods_raw"])
                if i_batch_for_api < num_api_calls - 1: 
                    wait_s5_1 = DEFAULT_WAIT_TIME * 2 
                    print(f"  Waiting {wait_s5_1}s before next S5.1 API call...") 
                    time.sleep(wait_s5_1)
            
            # NO CLEANING FUNCTION CALL HERE - Assuming LLM provides clean output due to prompt
            
            # Get unique categories from the (assumed clean) lists
            s5_1_final_consolidated_domains = sorted(list(set(cat for cat in collected_domains_from_llm if cat))) # Filter empty strings just in case
            s5_1_final_consolidated_methods = sorted(list(set(cat for cat in collected_methods_from_llm if cat)))

            print(f"\n{STAGE_NAME_S5_1} LLM processing completed.")
            print(f"  Total unique consolidated domains after S5.1: {len(s5_1_final_consolidated_domains)}")
            print(f"  Total unique consolidated methods after S5.1: {len(s5_1_final_consolidated_methods)}")

            mode_str_for_filename = "trial" if RUN_OVERALL_TRIAL_MODE and MAX_BATCHES_FOR_TRIAL > 0 else "full"
            s5_1_domain_output_filename = f"s5_1_consolidated_approx100_domains_{mode_str_for_filename}.csv"
            s5_1_method_output_filename = f"s5_1_consolidated_approx100_methods_{mode_str_for_filename}.csv"
            
            if s5_1_final_consolidated_domains:
                pd.DataFrame({'consolidated_domain_area_S5_1': s5_1_final_consolidated_domains}).to_csv(s5_1_domain_output_filename, index=False)
            else: pd.DataFrame(columns=['consolidated_domain_area_S5_1']).to_csv(s5_1_domain_output_filename, index=False)
            if s5_1_final_consolidated_methods:
                pd.DataFrame({'consolidated_method_area_S5_1': s5_1_final_consolidated_methods}).to_csv(s5_1_method_output_filename, index=False)
            else: pd.DataFrame(columns=['consolidated_method_area_S5_1']).to_csv(s5_1_method_output_filename, index=False)
            
            if s5_1_final_consolidated_domains or s5_1_final_consolidated_methods :
                 print(f"S5.1 consolidated lists saved to '{s5_1_domain_output_filename}' and '{s5_1_method_output_filename}'")
            else:
                 print("S5.1: No categories to save (lists might be empty).")
else:
    print(f"Skipping {STAGE_NAME_S5_1}: df_complete not ready, model not initialized, or S4 columns missing.")

==================== Starting Stage: S5.1_Consolidate_L3Std_To_100 ====================
Input for S5.1_Consolidate_L3Std_To_100: df_complete with 15341 rows.
Found 2014 unique valid L3 Std Domain Areas to consolidate.
Found 1823 unique valid L3 Std Method Areas to consolidate.
S5.1_Consolidate_L3Std_To_100: Will make 4 API call(s).

--- Processing S5.1 API Batch 1/4 ---

=== S5.1 CONSOLIDATION PROMPT (Batch 1 - Structure Preview) ===
You are an expert taxonomist. Your task is to consolidate the provided list of categories into a smaller, more manageable set of standardized categories.

You will be given:
1. A list of Domain Area categories to consolidate (e.g., up to 505 entries in this batch)
2. A list of Method Area categories to consolidate (e.g., up to 505 entries in this batch)

Your task is to:
1. Reduce the provided list of Domain Area categories to approximately 100 standardized categories.
2. Reduce the provided list of Method Area categories to approximately 100 standardized categories.

Core Principles for Consolidation:
* Identify common themes and patterns across related categories.
* Group conceptually similar items together under broader labels.
* Ensure each consolidated category is clear, descriptive, and represents a distinct domain or method.
* Use established terminology from research and industry.
* The consolidated categories should cover the full range of the original categories provided in this batch.
* Each standardized category should have a clear scope and purpose. Example target breadth: "Microelectronics".

Consolidate by:
* Merging synonyms and near-synonyms (e.g., "AI Applications" and "Artificial Intelligence Utilization").
* Grouping sub-areas under broader domains (e.g., "Solar Energy", "Wind Energy" → "Renewable Energy Technologies").
* Standardizing terminology and removing qualifiers when the core concept is clear.

Output Format:
----Domain Areas----
[Consolidated Category Name 1]
[Consolidated Category Name 2]
...
[Approximately 100 Consolidated Categories]

----Method Areas----
[Consolidated Category Name 1]
[Consolidated Category Name 2]
...
[Approximately 100 Consolidated Categories]

**IMPORTANT INSTRUCTION: Ensure that the category names themselves do NOT include any leading numbers, bullet points, or other list markers (e.g., no "1. Category Name", just "Category Name").**

...
=== END S5.1 PROMPT SAMPLE ===


--- RAW LLM OUTPUT (S5.1 Batch 1) ---
As an expert taxonomist, I have consolidated the provided lists of Domain Area and Method Area categories, adhering to the core principles of identifying common themes, grouping conceptually similar items, ensuring clarity and distinctiveness, and using established terminology. Each list has been reduced to approximately 100 standardized categories, covering the full range of the original entries.

----Domain Areas----
Artificial Intelligence Core
AI Applications
AI Ethics & Governance
Advanced Computing & Electronics
Quantum Technologies
Cloud & Distributed Computing
Computer Science
Data Science & Analytics
Cybersecurity & Digital Privacy
Digital Infrastructure
Digital Economy & Innovation
Digital Governance & Policy
Digital Society & Culture
Digital Communication Systems
Digital Humanities & Cultural Heritage
Digital Health & Medical Technologies
Robotics & Automation
Autonomous Systems
Human-Computer Interaction & Assistive Technologies
Computer Vision & Graphics
Applied Physics
Ba...
--- END RAW LLM OUTPUT ---

  S5.1 Batch 1 -> LLM returned 102 domain strings, 100 method strings.
  Waiting 10s before next S5.1 API call...

--- Processing S5.1 API Batch 2/4 ---
  S5.1 Batch 2 -> LLM returned 0 domain strings, 100 method strings.
  Waiting 10s before next S5.1 API call...

--- Processing S5.1 API Batch 3/4 ---
  S5.1 Batch 3 -> LLM returned 92 domain strings, 88 method strings.
  Waiting 10s before next S5.1 API call...

--- Processing S5.1 API Batch 4/4 ---
  S5.1 Batch 4 -> LLM returned 81 domain strings, 12 method strings.

S5.1_Consolidate_L3Std_To_100 LLM processing completed.
  Total unique consolidated domains after S5.1: 275
  Total unique consolidated methods after S5.1: 300
S5.1 consolidated lists saved to 's5_1_consolidated_approx100_domains_full.csv' and 's5_1_consolidated_approx100_methods_full.csv'

### Using a combination of AI and human feedback, we refined the extracted categories into a set of distinct, well-defined categories that effectively encompass the underlying concepts.

In [123]:
STAGE_NAME_S5 = "S5_Classification_Working_Approach"
print(f"\n{'='*20} Starting Stage: {STAGE_NAME_S5} {'='*20}")

# Your detailed categories (same as before)
DOMAIN_CATEGORIES_CURATED = [
    "AI & Machine Learning", "Advanced Computing & Electronics", "Advanced Manufacturing & Industry", 
    "Advanced Therapies & Regenerative Medicine", "Aerospace Engineering & Aviation", "Agricultural Systems & Plant Science", 
    "Alternative & Biofuels", "Analytical & Theoretical Chemistry", "Animal & Veterinary Sciences", 
    "Anthropology & Archaeology", "Applied & Plasma Physics", "Aquaculture & Fisheries", 
    "Arts, Humanities & Culture", "Astronomy, Cosmology & Particle Physics", "Atmospheric, Climate & Environmental Science", 
    "Autoimmune & Chronic Disease", "Autonomous Systems & Robotics", "Basic & Cross-Domain Science", 
    "Behavioral Science & Psychology", "Biodiversity & Ecology", "Bioeconomy & Circular Economy", 
    "Bioengineering & Synthetic Biology", "Bioinformatics & Systems Biology", "Biological Sciences", 
    "Biomedical Devices & Imaging", "Biomedical Engineering", "Biomedical Research (General)", 
    "Biotechnology", "Brain Science & Neuroscience", "Business & Organizational Behavior", 
    "Cancer Research & Oncology", "Carbon Management & Climate Technology", "Cardiovascular Health", 
    "Chemical & Process Engineering", "Chemical Safety & Toxicology", "Civic Engagement & Governance", 
    "Civil Engineering & Infrastructure", "Clean & Renewable Energy", "Climate Adaptation & Impact", 
    "Cloud & Digital Infrastructure", "Cognitive Science", "Communication & Media Studies", 
    "Complex Systems Science", "Computer Science (General)", "Computer Vision & Graphics", 
    "Conflict, Security & Justice", "Crisis & Disaster Management", "Critical Infrastructure & Safety", 
    "Critical Materials & Waste Management", "Cybersecurity & Digital Governance", "Data Science & Analytics", 
    "Dental & Oral Health", "Design Research & Human-Computer Interaction", "Digital Economy & Innovation", 
    "Digital Health & Medical Technology", "Digital Humanities & Cultural Heritage", "Drug Discovery & Pharmaceutical Development", 
    "Economics & Development Studies", "Energy Generation & Systems", "Food Science, Nutrition & Security", 
    "Genomics & Precision Medicine", "Gerontology & Aging Studies", "Historical Studies", 
    "Imaging & Instrumentation Technologies", "Immunology & Vaccine Development", "Life Sciences (General)", 
    "Linguistics & Language Studies", "Logistics & Supply Chain Management", "Marine, Ocean & Water Science", 
    "Materials Science & Engineering", "Mathematics & Applied Statistics", "Mechanical Engineering", 
    "Medical Education & Training", "Mental Health & Psychiatry", "Metabolic & Endocrine Health", 
    "Metrology & Measurement Science", "Microbiology & Microbiome Science", "Migration & Urban Studies", 
    "Musculoskeletal Health & Rehabilitation", "National Security & Defense Studies", "Natural Language Processing", 
    "Natural Resources & Environmental Management", "Neglected & Rare Diseases", "Network Science & Telecommunications", 
    "Nuclear Science & Engineering", "Occupational Health & Safety", "Optics & Photonics", 
    "Organic & Inorganic Chemistry", "Patient Care & Health Systems", "Pediatric & Women's Health", 
    "Philosophy, Logic & Ethics", "Physical & Chemical Sciences", "Planetary & Space Science", 
    "Political Science & Policy", "Public Health & Global Health", "Quantum Science & Technology", 
    "Regional & Urban Planning", "Religious Studies & Theology", "Remote Sensing & Geospatial Technology", 
    "Research & Innovation Policy", "Science & Technology Studies", "Simulation & Training Technology", 
    "Smart Systems & Internet of Things", "Social Justice & Equity", "Social Research & Sociology", 
    "Software Systems Engineering", "Stem Cell & Regenerative Engineering", "Sustainability Science & Education", 
    "Sustainable Consumption & Lifestyles", "Systems Engineering (General)", "Theoretical Physics", 
    "Toxicology & Risk Assessment", "Translational Medicine", "Transport Safety & Emissions reduction", 
    "Venture Capital & Innovation Finance", "Wildlife Health & Ecology"
]

METHOD_CATEGORIES_CURATED = [
    "AI & Machine Learning Development", "Advanced Analytical Techniques", "Advanced Engineering Methods", 
    "Advanced Manufacturing & Nanotechnology", "Measurement & Precision Engineering", "Agricultural & Crop Research Methods", 
    "Applied Biotechnology & Bioresource Utilization", "Cultural Heritage Research & Preservation Methods", "Aerospace & Space Engineering Methods", 
    "Autonomous Systems & Robotics Development", "Behavioral Science Research & Design Interventions", "Bio-Inspired Computing & Algorithm Design", 
    "Bioengineering & Biomanufacturing Processes", "Waste Processing & Resource Valorization", 
    "Biomarker Discovery & Diagnostic Development", "Biomedical Data Analysis & Computational Biology", "Biotechnology Research Methodologies", 
    "Business Model & Market Innovation Strategies", "Capacity Building, Training & Workforce Development", "Chemical & Green Process Engineering", 
    "Circular Economy Analysis & Lifecycle Assessment", "Community Engagement & Stakeholder Collaboration", "Clean Propulsion & Emission Control Technologies", 
    "Climate & Ecological System Modeling", "Clinical Research & Human Trials Methodology", "Communication, Dissemination & Outreach Strategies", 
    "Complex Systems Modeling & Analysis", "Computational Modeling & Simulation Techniques", "Computational Social Science Methods", 
    "Computer Graphics & Virtual Prototyping", "Computer Vision & Image Processing Systems", "Conservation Management & Ecological Monitoring", 
    "Cybersecurity Protocols & Data Privacy Techniques", "Data Analysis & Statistical Methods", "Data Collection, Curation & Governance", 
    "Decision Support Systems & Science", "Device Design & Instrument Engineering", "Digital Content Creation & Digital Scholarship Methods", 
    "Digital User Experience & Human-Computer Interaction Design", "Digital Health Solutions & Remote Care Delivery", "Digital Infrastructure Development & Transformation Strategies", 
    "Disease Modeling & Epidemiological Surveillance", "Drug Discovery, Delivery & Preclinical Development", "Earth Observation & Geospatial Analytics", 
    "Energy Infrastructure & Efficiency Optimization", "Engineering Design & Development Methodology", "Environmental Impact Assessment & Monitoring", 
    "Ethical Framework Development & Policy Analysis", "Experimental Design & Laboratory Analysis", "Food Processing, Quality & Safety Methods", 
    "Gene Therapy & Genetic Engineering Techniques", "Healthcare System Design & Optimization", "Health Impact Assessment & Health Promotion Strategies", 
    "Advanced Imaging & Microscopy Techniques", "Immunological Assays & Therapeutic Development", "Impact Assessment & Policy Implementation", 
    "Industrial Process Design & Optimization", "Information Retrieval & Knowledge Management Systems", "Infrastructure Planning & Smart Systems Integration", 
    "Innovation Management & Technology Transfer", "Instrumentation Development & Sensor Technology", "Integrated Assessment Frameworks & Modeling", 
    "Internet of Things & Digital Automation Solutions", "Laboratory Automation & High-Throughput Screening", "Language Processing & Text Analysis Methods", 
    "Material Design, Synthesis & Characterization", "Mathematical Modeling & Numerical Analysis", "Medical Technology Design & Innovation", 
    "Microbiome Engineering & Host-Microbe Interaction Research", "Mixed Methods Research Approaches", "Neuroscience & Cognitive Research Methods", 
    "Open Science Practices & Research Governance", "Operational Efficiency & Systems Engineering", "Organizational Development & Strategic Management", 
    "Participatory Action Research & Co-Design Methods", "Philosophical Inquiry & Ethical Analysis", "Physical Sciences Experimental Research", 
    "Physiological Measurement & Analysis Studies", "Plant Biotechnology & Applied Agricultural Research", "Product Development & Lifecycle Management", 
    "Proteomics, Metabolomics & Mass Spectrometry", "Qualitative Research Methodologies", "Quantitative Research Methodologies", 
    "Urban & Regional Development Modeling & Planning", "Reliability Engineering & Risk Assessment", "Resource Management & Optimization Strategies", 
    "Scenario Analysis & Foresight Planning", "Scientific Infrastructure Development & Management", "Social & Economic Impact Research", 
    "Software Development & Systems Engineering", "Supply Chain Design & Optimization", "Synthetic Biology & Metabolic Engineering", 
    "Theoretical Modeling & Computational Physics/Chemistry", "Indigenous Knowledge Systems & Co-creation", "Translational Research & Clinical Application", 
    "System Verification, Validation & Testing", "Water Resource Management & Purification Technologies"
]

print(f"Using {len(DOMAIN_CATEGORIES_CURATED)} detailed domains and {len(METHOD_CATEGORIES_CURATED)} detailed methods")

# Proven prompt template (same structure as the working approach)
BATCH_CLASSIFY_PROMPT_TEMPLATE = """You are an expert taxonomist specializing in research project classification. Your task is to classify multiple research project summaries, assigning each project exactly one domain area and one method area from the provided lists.

Domain Areas:
{domain_categories}

Method Areas:
{method_categories}

Classification Guidelines:
1. For Domain Area, focus on the TECHNICAL AREA OF OPERATION or SCIENTIFIC FIELD rather than business function.
   - Example: If a project involves a business developing biotechnology products, classify it as "Biotechnology" rather than "Business & Organizational Behavior"
   - Always prioritize the specialized technical or scientific domain over generic business categories
   - Look for the core scientific, technical, or application area that best represents what the project is about

2. For Method Area, select the primary methodology, approach, or technique used in the project.
   - Focus on HOW the work is being accomplished

For each project, select:
- The single most appropriate domain area that best captures the primary technical field or area of operation
- The single most appropriate method area that best captures the main methodology

Projects to Classify:
{project_summaries}

Output Format:
Project 1:
Domain Area: [Selected Domain Area - must be exactly as shown in the list]
Method Area: [Selected Method Area - must be exactly as shown in the list]

Project 2:
Domain Area: [Selected Domain Area - must be exactly as shown in the list]
Method Area: [Selected Method Area - must be exactly as shown in the list]

... continue for all projects ...

Important: For each project, select only ONE domain area and ONE method area. Both must be exact matches from the provided lists. Number your responses to match the project numbers exactly."""

# Improved find_closest_match function (fixed fallback)
def find_closest_match(value: str, category_list: List[str]) -> str:
    """Find the closest match for a value in a category list"""
    if not value:
        return "Classification Failed"
    
    # First try exact match
    for category in category_list:
        if value.lower() == category.lower():
            return category
    
    # Then try partial matches
    for category in category_list:
        if value.lower() in category.lower() or category.lower() in value.lower():
            return category
    
    # If no match found, return Classification Failed (honest fallback)
    return "Classification Failed"

# Proven classify_batch function (no validation - let LLM assign anything)
def classify_batch(project_summaries: List[str], domain_categories: List[str], 
                   method_categories: List[str], max_retries: int = 3) -> List[Dict[str, str]]:
    """Classify a batch of project text summaries - accepts any LLM output"""
    
    # Format the project summaries for the prompt (use FULL summaries)
    formatted_summaries = ""
    for i, summary in enumerate(project_summaries, 1):
        # Use full summaries without truncation (key difference!)
        formatted_summaries += f"Project {i}:\n{summary}\n\n"
    
    # Create the prompt
    prompt = BATCH_CLASSIFY_PROMPT_TEMPLATE.format(
        domain_categories="\n".join(domain_categories),
        method_categories="\n".join(method_categories),
        project_summaries=formatted_summaries
    )
    
    # Process with model (with retries)
    output_text = ""
    for attempt in range(max_retries):
        try:
            response = model.generate_content(prompt)
            output_text = response.text
            break
        except Exception as e:
            print(f"Error on attempt {attempt + 1}: {e}")
            if attempt < max_retries - 1:
                sleep_time = 2 ** (attempt + 1)  # Exponential backoff
                print(f"Retrying in {sleep_time} seconds...")
                time.sleep(sleep_time)
            else:
                print("Failed all retry attempts")
                return [{"domain": "API Failed", "method": "API Failed"} for _ in project_summaries]
    
    # Parse results - accept whatever the LLM assigns
    results = []
    project_blocks = re.split(r'Project \d+:', output_text)
    
    # Skip the first item if it's empty
    if project_blocks and not project_blocks[0].strip():
        project_blocks = project_blocks[1:]
    
    # If we didn't get enough results, pad with failures
    if len(project_blocks) < len(project_summaries):
        print(f"Warning: Expected {len(project_summaries)} results but got {len(project_blocks)}")
        project_blocks.extend(["" for _ in range(len(project_summaries) - len(project_blocks))])
    
    # Process each project block - NO VALIDATION
    for i, block in enumerate(project_blocks[:len(project_summaries)]):
        domain = "Parse Failed"
        method = "Parse Failed"
        
        for line in block.strip().split('\n'):
            if line.startswith("Domain Area:"):
                domain = line.replace("Domain Area:", "").strip()
            elif line.startswith("Method Area:"):
                method = line.replace("Method Area:", "").strip()
        
        # Just accept whatever the LLM assigned - no validation!
        results.append({"domain": domain, "method": method})
    
    return results

# Display detailed results for first batch (from working approach)
def display_first_batch_results(batch_summaries: List[str], batch_results: List[Dict[str, str]]):
    """Display detailed results for the first batch for verification"""
    print("\n===== FIRST BATCH RESULTS =====")
    print(f"Showing results for the first batch of {len(batch_summaries)} projects")
    
    for i, result in enumerate(batch_results):
        summary = batch_summaries[i]
        domain = result["domain"]
        method = result["method"]
        
        # Truncate summary for display
        truncated_summary = summary[:150] + "..." if len(summary) > 150 else summary
        truncated_summary = truncated_summary.replace('\n', ' ')
        
        print(f"\nProject {i+1}:")
        print(f"Summary: {truncated_summary}")
        print(f"Assigned Domain: {domain}")
        print(f"Assigned Method: {method}")
    
    print("\n================================")

# Main processing function (uses your global variables)
def classify_dataset_working_approach():
    """Process the dataset using the proven working approach with your global settings"""
    
    print(f"Using proven approach with YOUR settings:")
    print(f"  Batch size: {DEFAULT_BATCH_SIZE}")
    print(f"  Model: {model.model_name if hasattr(model, 'model_name') else 'Global model'}")
    print(f"  Trial mode: {RUN_OVERALL_TRIAL_MODE}")
    if RUN_OVERALL_TRIAL_MODE:
        print(f"  Max trial batches: {MAX_BATCHES_FOR_TRIAL}")
    
    # Initialize result columns
    df_complete['s5_curated_domain'] = ""
    df_complete['s5_curated_method'] = ""
    
    # Determine scope using YOUR global variables
    if RUN_OVERALL_TRIAL_MODE:
        max_rows = DEFAULT_BATCH_SIZE * MAX_BATCHES_FOR_TRIAL
        process_df = df_complete.iloc[:max_rows].copy()
        print(f"TRIAL MODE: Processing {len(process_df)} rows")
    else:
        process_df = df_complete.copy()
        print(f"FULL MODE: Processing {len(process_df)} rows")
    
    # Process in batches using YOUR batch size
    total_records = len(process_df)
    total_batches = (total_records + DEFAULT_BATCH_SIZE - 1) // DEFAULT_BATCH_SIZE
    
    for batch_num, start_idx in enumerate(range(0, total_records, DEFAULT_BATCH_SIZE)):
        end_idx = min(start_idx + DEFAULT_BATCH_SIZE, total_records)
        batch_size_actual = end_idx - start_idx
        
        print(f"\nProcessing batch {batch_num + 1}/{total_batches} (records {start_idx+1}-{end_idx})")
        
        # Extract summaries for this batch
        batch_summaries = []
        for idx in range(start_idx, end_idx):
            summary = process_df.iloc[idx]['full_text']
            batch_summaries.append(summary)
        
        # Classify the batch using YOUR global model
        batch_results = classify_batch(batch_summaries, DOMAIN_CATEGORIES_CURATED, METHOD_CATEGORIES_CURATED)
        
        # Save results directly to df_complete
        for i in range(batch_size_actual):
            original_idx = process_df.index[start_idx + i]
            if i < len(batch_results):
                df_complete.loc[original_idx, 's5_curated_domain'] = batch_results[i]['domain']
                df_complete.loc[original_idx, 's5_curated_method'] = batch_results[i]['method']
            else:
                df_complete.loc[original_idx, 's5_curated_domain'] = "API Failed"
                df_complete.loc[original_idx, 's5_curated_method'] = "API Failed"
        
        # Display detailed results for first batch only
        if batch_num == 0:
            display_first_batch_results(batch_summaries, batch_results)
        
        # Save every 20 batches
        if (batch_num + 1) % 20 == 0:
            df_complete.to_csv(MAIN_DATAFRAME_CHECKPOINT_FILE, index=False)
            print(f"  ✅ SAVED at batch {batch_num + 1}")
        
        # Wait between batches using YOUR global wait time
        if batch_num < total_batches - 1:
            print(f"Waiting {DEFAULT_WAIT_TIME} seconds before next batch...")
            time.sleep(DEFAULT_WAIT_TIME)
    
    return df_complete

# Run the proven approach
if 'df_complete' not in locals() or df_complete.empty:
    print("ERROR: df_complete not available")
elif 'model' not in locals() or not model:
    print("ERROR: model not available")  
elif 'full_text' not in df_complete.columns:
    print("ERROR: 'full_text' column missing")
else:
    # Use the proven working approach with YOUR global settings
    df_result = classify_dataset_working_approach()
    
    # Final save
    df_complete.to_csv(MAIN_DATAFRAME_CHECKPOINT_FILE, index=False)
    print(f"✅ FINAL SAVE COMPLETE")
    
    # Generate summary statistics (from working approach)
    domain_counts = df_complete['s5_curated_domain'].value_counts()
    method_counts = df_complete['s5_curated_method'].value_counts()
    
    print("\nTop 10 assigned domain categories:")
    for domain, count in domain_counts.head(10).items():
        print(f"- {domain}: {count}")
    
    print("\nTop 10 assigned method categories:")
    for method, count in method_counts.head(10).items():
        print(f"- {method}: {count}")
    
    print(f"\n🎉 STAGE 5 COMPLETE!")
    print(f"Total projects processed: {len(df_complete)}")
    
    # Show sample results
    display(df_complete[['id', 'full_text', 's5_curated_domain', 's5_curated_method']].head())

# SEPARATE CELL - Check for non-matching categories
def check_category_matches():
    """Check which assigned categories don't match the provided lists"""
    
    print("="*60)
    print("CHECKING FOR NON-MATCHING CATEGORIES") 
    print("="*60)
    
    # Get all assigned categories
    assigned_domains = df_complete['s5_curated_domain'].dropna().unique()
    assigned_methods = df_complete['s5_curated_method'].dropna().unique()
    
    # Find non-matching domains
    non_matching_domains = []
    for domain in assigned_domains:
        if domain not in DOMAIN_CATEGORIES_CURATED and domain not in ["API Failed", "Parse Failed"]:
            non_matching_domains.append(domain)
    
    # Find non-matching methods  
    non_matching_methods = []
    for method in assigned_methods:
        if method not in METHOD_CATEGORIES_CURATED and method not in ["API Failed", "Parse Failed"]:
            non_matching_methods.append(method)
    
    # Report results
    print(f"Total unique domains assigned: {len(assigned_domains)}")
    print(f"Domains matching your list: {len(assigned_domains) - len(non_matching_domains)}")
    print(f"Domains NOT in your list: {len(non_matching_domains)}")
    
    if non_matching_domains:
        print(f"\nNON-MATCHING DOMAINS:")
        for domain in non_matching_domains:
            count = (df_complete['s5_curated_domain'] == domain).sum()
            print(f"  '{domain}': {count} projects")
    
    print(f"\nTotal unique methods assigned: {len(assigned_methods)}")
    print(f"Methods matching your list: {len(assigned_methods) - len(non_matching_methods)}")
    print(f"Methods NOT in your list: {len(non_matching_methods)}")
    
    if non_matching_methods:
        print(f"\nNON-MATCHING METHODS:")
        for method in non_matching_methods:
            count = (df_complete['s5_curated_method'] == method).sum()
            print(f"  '{method}': {count} projects")
    
    # Calculate match rates
    total_projects = len(df_complete)
    domain_exact_matches = sum(1 for d in df_complete['s5_curated_domain'] if d in DOMAIN_CATEGORIES_CURATED)
    method_exact_matches = sum(1 for m in df_complete['s5_curated_method'] if m in METHOD_CATEGORIES_CURATED)
    
    print(f"\n" + "="*60)
    print("MATCH RATES")
    print("="*60)
    print(f"Domain exact match rate: {domain_exact_matches}/{total_projects} ({domain_exact_matches/total_projects*100:.1f}%)")
    print(f"Method exact match rate: {method_exact_matches}/{total_projects} ({method_exact_matches/total_projects*100:.1f}%)")
    
    return non_matching_domains, non_matching_methods

# Run the check after Stage 5 completes
check_category_matches()

==================== Starting Stage: S5_Classification_Working_Approach ====================
Using 116 detailed domains and 97 detailed methods
Using proven approach with YOUR settings:
  Batch size: 20
  Model: models/gemini-2.0-flash
  Trial mode: False
FULL MODE: Processing 15341 rows

Processing batch 1/768 (records 1-20)

===== FIRST BATCH RESULTS =====
Showing results for the first batch of 20 projects

Project 1:
Summary: Digitizing Other Economies: A Comparative Approach: How do longstanding, primarily non-industrial, non-capitalist societies adopt and adapt digital te...
Assigned Domain: Anthropology & Archaeology
Assigned Method: Qualitative Research Methodologies

Project 2:
Summary: MOLECULAR QUANTUM DYNAMICS IN LOW TEMPERATURE CONDENSED PHASE ASTROCHEMISTRY: The James Webb Space Telescope (JWST) has ushered in a new era in observ...
Assigned Domain: Astronomy, Cosmology & Particle Physics
Assigned Method: Advanced Imaging & Microscopy Techniques

Project 3:
Summary: Multiscale modelling of aberrant phase transitions in biocondensates: The spatiotemporal organization of the cell material represents one of the great...
Assigned Domain: Bioinformatics & Systems Biology
Assigned Method: Computational Modeling & Simulation Techniques

Project 4:
Summary: The first comprehensive Atlas of the Milky Way: The Milky Way is the cosmic environment in which the solar system, the Earth, and life as we know it c...
Assigned Domain: Astronomy, Cosmology & Particle Physics
Assigned Method: Data Analysis & Statistical Methods

Project 5:
Summary: Untapping multiparametric 2D luminescence sensing through MACHine LEarning and Spectral Sorting: Cellular organisms are complex machines whose health ...
Assigned Domain: Biomedical Devices & Imaging
Assigned Method: AI & Machine Learning Development

Project 6:
Summary: Making Sense of the Unexpected in the Gravitational-Wave Sky: General Relativity (GR) is more than a century old, but is still our best macroscopic de...
Assigned Domain: Theoretical Physics
Assigned Method: Computational Modeling & Simulation Techniques

Project 7:
Summary: Hernando Colón’s universal library. European culture and intellectual production at the dawn of the global world: While newly printed books were circu...
Assigned Domain: Historical Studies
Assigned Method: Cultural Heritage Research & Preservation Methods

Project 8:
Summary: UA EURATOM NCP SUPPORT OF UKRAINIAN RESEARCH ENTITIES INTEGRATION INTO NUCLEAR RESEARCH FUNDED BY THE EURATOM RESEARCH AND TRAINING PROGRAMME 2021-202...
Assigned Domain: Nuclear Science & Engineering
Assigned Method: Capacity Building, Training & Workforce Development

Project 9:
Summary: FISA 2025 – EURADWASTE’25  conferences on Euratom fission research and training: The FISA-EURADWASTE event is a high-level, research policy conference...
Assigned Domain: Nuclear Science & Engineering
Assigned Method: Communication, Dissemination & Outreach Strategies

Project 10:
Summary: Market & Technology Analysis: Adsorbi is a deep tech startup company from Gothenburg Sweden and was founded after several years of research within mat...
Assigned Domain: Chemical & Process Engineering
Assigned Method: Business Model & Market Innovation Strategies

Project 11:
Summary: Female leadership in Medsensio, a digital health technology startup: Medsensio was founded in 2017 as a spinout from a research project in health data...
Assigned Domain: Digital Health & Medical Technology
Assigned Method: Organizational Development & Strategic Management

Project 12:
Summary: Detecting the right moment to do embryo transfer in In Vitro Fertilisation treatments.: In-vitro Fertilization (IVF) is a well-known fertility treatme...
Assigned Domain: Biomedical Devices & Imaging
Assigned Method: Device Design & Instrument Engineering

Project 13:
Summary: Elia - Smart Assistant for English Learning: We are a startup founded exclusively by women holding the top positions CEO and CTO. Our vision is to red...
Assigned Domain: Linguistics & Language Studies
Assigned Method: Software Development & Systems Engineering

Project 14:
Summary: EUCYS Leiden2022: The main objective of this Proposal is the organisation of the Young Talents Programme which contains two separate events. The first...
Assigned Domain: Research & Innovation Policy
Assigned Method: Capacity Building, Training & Workforce Development

Project 15:
Summary: European Union Contest for Young Scientists (EUCYS) 2024: This proposal concerns the organization of the 35th European Union Contest for Young Scienti...
Assigned Domain: Research & Innovation Policy
Assigned Method: Communication, Dissemination & Outreach Strategies

Project 16:
Summary: BUILDING ON THE ACHIEVEMENTS OF PLAN S TO FURTHER ADVANCE OPEN ACCESS AND SCHOLARLY COMMUNICATION: The European Commission has made great strides in p...
Assigned Domain: Research & Innovation Policy
Assigned Method: Impact Assessment & Policy Implementation

Project 17:
Summary: EUROPEAN SCIENCE IN THE CITY AND EUROSCIENCE OPEN FORUM – KATOWICE 2024: The project aims to build a Real City of Science in which: 1) science becomes...
Assigned Domain: Science & Technology Studies
Assigned Method: Community Engagement & Stakeholder Collaboration

Project 18:
Summary: Support to Retirement Savings Vehicle for European Research Institutions and research performing individuals (RESAVER): The overall aim of the RESAVER...
Assigned Domain: Research & Innovation Policy
Assigned Method: Organizational Development & Strategic Management

Project 19:
Summary: EU TalentON Katowice 2024 - European Union Contest for early-career researchers: EU TalentON Katowice 2024 - European Union Contest for early-career r...
Assigned Domain: Research & Innovation Policy
Assigned Method: Capacity Building, Training & Workforce Development

Project 20:
Summary: New ERA - Towards a responsible knowledge driven society of the 3rd Millenium: The objective of the project »ERA conference« is to create a space for ...
Assigned Domain: Research & Innovation Policy
Assigned Method: Impact Assessment & Policy Implementation

================================
Waiting 5 seconds before next batch...

Processing batch 2/768 (records 21-40)
Waiting 5 seconds before next batch...

Processing batch 3/768 (records 41-60)
Waiting 5 seconds before next batch...

Processing batch 4/768 (records 61-80)
Waiting 5 seconds before next batch...

Processing batch 5/768 (records 81-100)
Waiting 5 seconds before next batch...

Processing batch 6/768 (records 101-120)
Waiting 5 seconds before next batch...

Processing batch 7/768 (records 121-140)
Waiting 5 seconds before next batch...

Processing batch 8/768 (records 141-160)
Waiting 5 seconds before next batch...

Processing batch 9/768 (records 161-180)
Waiting 5 seconds before next batch...

Processing batch 10/768 (records 181-200)
Waiting 5 seconds before next batch...

Processing batch 11/768 (records 201-220)
Waiting 5 seconds before next batch...

Processing batch 12/768 (records 221-240)
Waiting 5 seconds before next batch...

Processing batch 13/768 (records 241-260)
Waiting 5 seconds before next batch...

Processing batch 14/768 (records 261-280)
Waiting 5 seconds before next batch...

Processing batch 15/768 (records 281-300)
Waiting 5 seconds before next batch...

Processing batch 16/768 (records 301-320)
Waiting 5 seconds before next batch...

Processing batch 17/768 (records 321-340)
Waiting 5 seconds before next batch...

Processing batch 18/768 (records 341-360)
Waiting 5 seconds before next batch...

Processing batch 19/768 (records 361-380)
Waiting 5 seconds before next batch...

Processing batch 20/768 (records 381-400)
  ✅ SAVED at batch 20
Waiting 5 seconds before next batch...

Processing batch 21/768 (records 401-420)
Waiting 5 seconds before next batch...

Processing batch 22/768 (records 421-440)
Waiting 5 seconds before next batch...

Processing batch 23/768 (records 441-460)
Waiting 5 seconds before next batch...

Processing batch 24/768 (records 461-480)
Waiting 5 seconds before next batch...

Processing batch 25/768 (records 481-500)
Waiting 5 seconds before next batch...

Processing batch 26/768 (records 501-520)
Waiting 5 seconds before next batch...

Processing batch 27/768 (records 521-540)
Waiting 5 seconds before next batch...

Processing batch 28/768 (records 541-560)
Waiting 5 seconds before next batch...

Processing batch 29/768 (records 561-580)
Waiting 5 seconds before next batch...

Processing batch 30/768 (records 581-600)
Waiting 5 seconds before next batch...

Processing batch 31/768 (records 601-620)
Waiting 5 seconds before next batch...

Processing batch 32/768 (records 621-640)
Waiting 5 seconds before next batch...

Processing batch 33/768 (records 641-660)
Waiting 5 seconds before next batch...

Processing batch 34/768 (records 661-680)
Waiting 5 seconds before next batch...

Processing batch 35/768 (records 681-700)
Waiting 5 seconds before next batch...

Processing batch 36/768 (records 701-720)
Waiting 5 seconds before next batch...

Processing batch 37/768 (records 721-740)
Waiting 5 seconds before next batch...

Processing batch 38/768 (records 741-760)
Waiting 5 seconds before next batch...

Processing batch 39/768 (records 761-780)
Waiting 5 seconds before next batch...

Processing batch 40/768 (records 781-800)
  ✅ SAVED at batch 40
Waiting 5 seconds before next batch...

Processing batch 41/768 (records 801-820)
Waiting 5 seconds before next batch...

Processing batch 42/768 (records 821-840)
Waiting 5 seconds before next batch...

Processing batch 43/768 (records 841-860)
Waiting 5 seconds before next batch...

Processing batch 44/768 (records 861-880)
Waiting 5 seconds before next batch...

Processing batch 45/768 (records 881-900)
Waiting 5 seconds before next batch...

Processing batch 46/768 (records 901-920)
Waiting 5 seconds before next batch...

Processing batch 47/768 (records 921-940)
Waiting 5 seconds before next batch...

Processing batch 48/768 (records 941-960)
Waiting 5 seconds before next batch...

Processing batch 49/768 (records 961-980)
Waiting 5 seconds before next batch...

Processing batch 50/768 (records 981-1000)
Waiting 5 seconds before next batch...

Processing batch 51/768 (records 1001-1020)
Waiting 5 seconds before next batch...

Processing batch 52/768 (records 1021-1040)
Waiting 5 seconds before next batch...

Processing batch 53/768 (records 1041-1060)
Waiting 5 seconds before next batch...

Processing batch 54/768 (records 1061-1080)
Waiting 5 seconds before next batch...

Processing batch 55/768 (records 1081-1100)
Waiting 5 seconds before next batch...

Processing batch 56/768 (records 1101-1120)
Waiting 5 seconds before next batch...

Processing batch 57/768 (records 1121-1140)
Waiting 5 seconds before next batch...

Processing batch 58/768 (records 1141-1160)
Waiting 5 seconds before next batch...

Processing batch 59/768 (records 1161-1180)
Waiting 5 seconds before next batch...

Processing batch 60/768 (records 1181-1200)
  ✅ SAVED at batch 60
Waiting 5 seconds before next batch...

Processing batch 61/768 (records 1201-1220)
Waiting 5 seconds before next batch...

Processing batch 62/768 (records 1221-1240)
Waiting 5 seconds before next batch...

Processing batch 63/768 (records 1241-1260)
Waiting 5 seconds before next batch...

Processing batch 64/768 (records 1261-1280)
Waiting 5 seconds before next batch...

Processing batch 65/768 (records 1281-1300)
Waiting 5 seconds before next batch...

Processing batch 66/768 (records 1301-1320)
Waiting 5 seconds before next batch...

Processing batch 67/768 (records 1321-1340)
Waiting 5 seconds before next batch...

Processing batch 68/768 (records 1341-1360)
Waiting 5 seconds before next batch...

Processing batch 69/768 (records 1361-1380)
Waiting 5 seconds before next batch...

Processing batch 70/768 (records 1381-1400)
Waiting 5 seconds before next batch...

Processing batch 71/768 (records 1401-1420)
Waiting 5 seconds before next batch...

Processing batch 72/768 (records 1421-1440)
Waiting 5 seconds before next batch...

Processing batch 73/768 (records 1441-1460)
Waiting 5 seconds before next batch...

Processing batch 74/768 (records 1461-1480)
Waiting 5 seconds before next batch...

Processing batch 75/768 (records 1481-1500)
Waiting 5 seconds before next batch...

Processing batch 76/768 (records 1501-1520)
Waiting 5 seconds before next batch...

Processing batch 77/768 (records 1521-1540)
Waiting 5 seconds before next batch...

Processing batch 78/768 (records 1541-1560)
Waiting 5 seconds before next batch...

Processing batch 79/768 (records 1561-1580)
Waiting 5 seconds before next batch...

Processing batch 80/768 (records 1581-1600)
  ✅ SAVED at batch 80
Waiting 5 seconds before next batch...

Processing batch 81/768 (records 1601-1620)
Waiting 5 seconds before next batch...

Processing batch 82/768 (records 1621-1640)
Waiting 5 seconds before next batch...

Processing batch 83/768 (records 1641-1660)
Waiting 5 seconds before next batch...

Processing batch 84/768 (records 1661-1680)
Waiting 5 seconds before next batch...

Processing batch 85/768 (records 1681-1700)
Waiting 5 seconds before next batch...

Processing batch 86/768 (records 1701-1720)
Waiting 5 seconds before next batch...

Processing batch 87/768 (records 1721-1740)
Waiting 5 seconds before next batch...

Processing batch 88/768 (records 1741-1760)
Waiting 5 seconds before next batch...

Processing batch 89/768 (records 1761-1780)
Waiting 5 seconds before next batch...

Processing batch 90/768 (records 1781-1800)
Waiting 5 seconds before next batch...

Processing batch 91/768 (records 1801-1820)
Waiting 5 seconds before next batch...

Processing batch 92/768 (records 1821-1840)
Waiting 5 seconds before next batch...

Processing batch 93/768 (records 1841-1860)
Waiting 5 seconds before next batch...

Processing batch 94/768 (records 1861-1880)
Waiting 5 seconds before next batch...

Processing batch 95/768 (records 1881-1900)
Waiting 5 seconds before next batch...

Processing batch 96/768 (records 1901-1920)
Waiting 5 seconds before next batch...

Processing batch 97/768 (records 1921-1940)
Waiting 5 seconds before next batch...

Processing batch 98/768 (records 1941-1960)
Waiting 5 seconds before next batch...

Processing batch 99/768 (records 1961-1980)
Waiting 5 seconds before next batch...

Processing batch 100/768 (records 1981-2000)
  ✅ SAVED at batch 100
Waiting 5 seconds before next batch...

Processing batch 101/768 (records 2001-2020)
Waiting 5 seconds before next batch...

Processing batch 102/768 (records 2021-2040)
Waiting 5 seconds before next batch...

Processing batch 103/768 (records 2041-2060)
Waiting 5 seconds before next batch...

Processing batch 104/768 (records 2061-2080)
Waiting 5 seconds before next batch...

Processing batch 105/768 (records 2081-2100)
Waiting 5 seconds before next batch...

Processing batch 106/768 (records 2101-2120)
Waiting 5 seconds before next batch...

Processing batch 107/768 (records 2121-2140)
Waiting 5 seconds before next batch...

Processing batch 108/768 (records 2141-2160)
Waiting 5 seconds before next batch...

Processing batch 109/768 (records 2161-2180)
Waiting 5 seconds before next batch...

Processing batch 110/768 (records 2181-2200)
Waiting 5 seconds before next batch...

Processing batch 111/768 (records 2201-2220)
Waiting 5 seconds before next batch...

Processing batch 112/768 (records 2221-2240)
Waiting 5 seconds before next batch...

Processing batch 113/768 (records 2241-2260)
Waiting 5 seconds before next batch...

Processing batch 114/768 (records 2261-2280)
Waiting 5 seconds before next batch...

Processing batch 115/768 (records 2281-2300)
Waiting 5 seconds before next batch...

Processing batch 116/768 (records 2301-2320)
Waiting 5 seconds before next batch...

Processing batch 117/768 (records 2321-2340)
Waiting 5 seconds before next batch...

Processing batch 118/768 (records 2341-2360)
Waiting 5 seconds before next batch...

Processing batch 119/768 (records 2361-2380)
Waiting 5 seconds before next batch...

Processing batch 120/768 (records 2381-2400)
  ✅ SAVED at batch 120
Waiting 5 seconds before next batch...

Processing batch 121/768 (records 2401-2420)
Waiting 5 seconds before next batch...

Processing batch 122/768 (records 2421-2440)
Waiting 5 seconds before next batch...

Processing batch 123/768 (records 2441-2460)
Waiting 5 seconds before next batch...

Processing batch 124/768 (records 2461-2480)
Waiting 5 seconds before next batch...

Processing batch 125/768 (records 2481-2500)
Waiting 5 seconds before next batch...

Processing batch 126/768 (records 2501-2520)
Waiting 5 seconds before next batch...

Processing batch 127/768 (records 2521-2540)
Waiting 5 seconds before next batch...

Processing batch 128/768 (records 2541-2560)
Waiting 5 seconds before next batch...

Processing batch 129/768 (records 2561-2580)
Waiting 5 seconds before next batch...

Processing batch 130/768 (records 2581-2600)
Waiting 5 seconds before next batch...

Processing batch 131/768 (records 2601-2620)
Waiting 5 seconds before next batch...

Processing batch 132/768 (records 2621-2640)
Waiting 5 seconds before next batch...

Processing batch 133/768 (records 2641-2660)
Waiting 5 seconds before next batch...

Processing batch 134/768 (records 2661-2680)
Waiting 5 seconds before next batch...

Processing batch 135/768 (records 2681-2700)
Waiting 5 seconds before next batch...

Processing batch 136/768 (records 2701-2720)
Waiting 5 seconds before next batch...

Processing batch 137/768 (records 2721-2740)
Waiting 5 seconds before next batch...

Processing batch 138/768 (records 2741-2760)
Waiting 5 seconds before next batch...

Processing batch 139/768 (records 2761-2780)
Waiting 5 seconds before next batch...

Processing batch 140/768 (records 2781-2800)
  ✅ SAVED at batch 140
Waiting 5 seconds before next batch...

Processing batch 141/768 (records 2801-2820)
Waiting 5 seconds before next batch...

Processing batch 142/768 (records 2821-2840)
Waiting 5 seconds before next batch...

Processing batch 143/768 (records 2841-2860)
Waiting 5 seconds before next batch...

Processing batch 144/768 (records 2861-2880)
Waiting 5 seconds before next batch...

Processing batch 145/768 (records 2881-2900)
Waiting 5 seconds before next batch...

Processing batch 146/768 (records 2901-2920)
Waiting 5 seconds before next batch...

Processing batch 147/768 (records 2921-2940)
Waiting 5 seconds before next batch...

Processing batch 148/768 (records 2941-2960)
Waiting 5 seconds before next batch...

Processing batch 149/768 (records 2961-2980)
Waiting 5 seconds before next batch...

Processing batch 150/768 (records 2981-3000)
Waiting 5 seconds before next batch...

Processing batch 151/768 (records 3001-3020)
Waiting 5 seconds before next batch...

Processing batch 152/768 (records 3021-3040)
Waiting 5 seconds before next batch...

Processing batch 153/768 (records 3041-3060)
Waiting 5 seconds before next batch...

Processing batch 154/768 (records 3061-3080)
Waiting 5 seconds before next batch...

Processing batch 155/768 (records 3081-3100)
Waiting 5 seconds before next batch...

Processing batch 156/768 (records 3101-3120)
Waiting 5 seconds before next batch...

Processing batch 157/768 (records 3121-3140)
Waiting 5 seconds before next batch...

Processing batch 158/768 (records 3141-3160)
Waiting 5 seconds before next batch...

Processing batch 159/768 (records 3161-3180)
Waiting 5 seconds before next batch...

Processing batch 160/768 (records 3181-3200)
  ✅ SAVED at batch 160
Waiting 5 seconds before next batch...

Processing batch 161/768 (records 3201-3220)
Waiting 5 seconds before next batch...

Processing batch 162/768 (records 3221-3240)
Waiting 5 seconds before next batch...

Processing batch 163/768 (records 3241-3260)
Waiting 5 seconds before next batch...

Processing batch 164/768 (records 3261-3280)

,id,full_text,s5_curated_domain,s5_curated_method
0,101116741,Digitizing Other Economies: A Comparative Appr...,Anthropology & Archaeology,Qualitative Research Methodologies
1,101163161,MOLECULAR QUANTUM DYNAMICS IN LOW TEMPERATURE ...,"Astronomy, Cosmology & Particle Physics",Advanced Imaging & Microscopy Techniques
2,101160499,Multiscale modelling of aberrant phase transit...,Bioinformatics & Systems Biology,Computational Modeling & Simulation Techniques
3,101166905,The first comprehensive Atlas of the Milky Way...,"Astronomy, Cosmology & Particle Physics",Data Analysis & Statistical Methods
4,101162875,Untapping multiparametric 2D luminescence sens...,Biomedical Devices & Imaging,AI & Machine Learning Development

============================================================
CHECKING FOR NON-MATCHING CATEGORIES
============================================================
Total unique domains assigned: 145
Domains matching your list: 117
Domains NOT in your list: 28

NON-MATCHING DOMAINS:
  'Gene Therapy & Genetic Engineering Techniques': 16 projects
  'Environmental Impact Assessment & Monitoring': 6 projects
  'Automotive Engineering & Aviation': 1 projects
  'Proteomics, Metabolomics & Mass Spectrometry': 2 projects
  'Plant Biotechnology & Applied Agricultural Research': 19 projects
  'Education & Training': 1 projects
  'Alzheimer's Disease Diagnostics & Oncology': 1 projects
  'Battery Technology': 1 projects
  'Virology': 1 projects
  'Health Economics & Development Studies': 1 projects
  'Automotive Systems & Robotics': 1 projects
  'Nanomedicine': 1 projects
  'Paleontology': 2 projects
  'Environmental Science': 1 projects
  'Biochemistry': 1 projects
  'Electrical Engineering & Electronics': 1 projects
  'Alzheimer's Disease': 1 projects
  'Cell Biology': 1 projects
  'Geophysics': 2 projects
  'Atomic & Theoretical Physics': 1 projects
  'Biochemistry & Structural Biology': 1 projects
  'Autism & Related Disabilities': 1 projects
  'Genetics & Precision Medicine': 2 projects
  'Electrical Engineering': 1 projects
  'Archaeology': 1 projects
  'Mining & Urban Studies': 1 projects
  'Water Resource Management & Purification Technologies': 1 projects
  'Gene Therapy & Precision Medicine': 1 projects

Total unique methods assigned: 141
Methods matching your list: 98
Methods NOT in your list: 43

NON-MATCHING METHODS:
  'Smart Systems & Internet of Things': 2 projects
  'Network Science & Telecommunications': 8 projects
  'Simulation & Training Technology': 21 projects
  'Regional & Urban Planning': 1 projects
  'Systems Engineering (General)': 12 projects
  'Bioinformatics & Systems Biology': 67 projects
  'Research & Innovation Policy': 13 projects
  'Remote Sensing & Geospatial Technology': 7 projects
  'Energy Generation & Systems': 3 projects
  'Chemical & Process Engineering': 2 projects
  'Stem Cell & Regenerative Engineering': 2 projects
  'Genomics & Precision Medicine': 60 projects
  'Regional & Urban Development Modeling & Planning': 1 projects
  'Risk Assessment & Policy Implementation': 3 projects
  'Computer Simulation & Modeling Techniques': 1 projects
  'Immunology & Vaccine Development': 3 projects
  'Toxicology & Risk Assessment': 4 projects
  'Animal & Veterinary Sciences': 1 projects
  'Historical Studies': 45 projects
  'Metagenomics & Metaproteomics': 1 projects
  'Biodiversity & Ecology': 2 projects
  'Metagenomics & Microbial Ecology': 1 projects
  'Archaeological & Crop Research Methods': 4 projects
  'Signal Processing': 1 projects
  'Electrochemical & Green Process Engineering': 1 projects
  'Organic & Inorganic Chemistry': 2 projects
  'Natural Language Processing': 3 projects
  'High-Throughput Screening': 1 projects
  'Archaeological Research Methods': 1 projects
  'Metabolic & Endocrine Health': 1 projects
  'Archaeological Science': 1 projects
  'Microbiology & Microbiome Science': 1 projects
  'Design Research & Human-Computer Interaction': 1 projects
  'Biomedical Engineering': 5 projects
  'Medical Education & Training': 1 projects
  'Microsimulation Analysis using the EUROMOD platform and its expansions': 1 projects
  'Biomedical Devices & Imaging': 3 projects
  'Climate Adaptation & Impact': 1 projects
  'Social Research & Sociology': 1 projects
  'Digital Humanities & Cultural Heritage': 2 projects
  'Archaeological Research Methodologies': 1 projects
  'Applied & Plasma Physics': 1 projects
  'Computer Architecture & System Design': 1 projects

============================================================
MATCH RATES
============================================================
Domain exact match rate: 15258/15341 (99.5%)
Method exact match rate: 15034/15341 (98.0%)

(['Gene Therapy & Genetic Engineering Techniques',
  'Environmental Impact Assessment & Monitoring',
  'Automotive Engineering & Aviation',
  'Proteomics, Metabolomics & Mass Spectrometry',
  'Plant Biotechnology & Applied Agricultural Research',
  'Education & Training',
  "Alzheimer's Disease Diagnostics & Oncology",
  'Battery Technology',
  'Virology',
  'Health Economics & Development Studies',
  'Automotive Systems & Robotics',
  'Nanomedicine',
  'Paleontology',
  'Environmental Science',
  'Biochemistry',
  'Electrical Engineering & Electronics',
  "Alzheimer's Disease",
  'Cell Biology',
  'Geophysics',
  'Atomic & Theoretical Physics',
  'Biochemistry & Structural Biology',
  'Autism & Related Disabilities',
  'Genetics & Precision Medicine',
  'Electrical Engineering',
  'Archaeology',
  'Mining & Urban Studies',
  'Water Resource Management & Purification Technologies',
  'Gene Therapy & Precision Medicine'],
 ['Smart Systems & Internet of Things',
  'Network Science & Telecommunications',
  'Simulation & Training Technology',
  'Regional & Urban Planning',
  'Systems Engineering (General)',
  'Bioinformatics & Systems Biology',
  'Research & Innovation Policy',
  'Remote Sensing & Geospatial Technology',
  'Energy Generation & Systems',
  'Chemical & Process Engineering',
  'Stem Cell & Regenerative Engineering',
  'Genomics & Precision Medicine',
  'Regional & Urban Development Modeling & Planning',
  'Risk Assessment & Policy Implementation',
  'Computer Simulation & Modeling Techniques',
  'Immunology & Vaccine Development',
  'Toxicology & Risk Assessment',
  'Animal & Veterinary Sciences',
  'Historical Studies',
  'Metagenomics & Metaproteomics',
  'Biodiversity & Ecology',
  'Metagenomics & Microbial Ecology',
  'Archaeological & Crop Research Methods',
  'Signal Processing',
  'Electrochemical & Green Process Engineering',
  'Organic & Inorganic Chemistry',
  'Natural Language Processing',
  'High-Throughput Screening',
  'Archaeological Research Methods',
  'Metabolic & Endocrine Health',
  'Archaeological Science',
  'Microbiology & Microbiome Science',
  'Design Research & Human-Computer Interaction',
  'Biomedical Engineering',
  'Medical Education & Training',
  'Microsimulation Analysis using the EUROMOD platform and its expansions',
  'Biomedical Devices & Imaging',
  'Climate Adaptation & Impact',
  'Social Research & Sociology',
  'Digital Humanities & Cultural Heritage',
  'Archaeological Research Methodologies',
  'Applied & Plasma Physics',
  'Computer Architecture & System Design'])

### We further condensed the categories

In [135]:
# COMPLETE S5 FIX STAGE
# S5 CURATED CATEGORIES (from your original code)
S5_DOMAIN_CATEGORIES = [
    "AI & Machine Learning", "Advanced Computing & Electronics", "Advanced Manufacturing & Industry", 
    "Advanced Therapies & Regenerative Medicine", "Aerospace Engineering & Aviation", "Agricultural Systems & Plant Science", 
    "Alternative & Biofuels", "Analytical & Theoretical Chemistry", "Animal & Veterinary Sciences", 
    "Anthropology & Archaeology", "Applied & Plasma Physics", "Aquaculture & Fisheries", 
    "Arts, Humanities & Culture", "Astronomy, Cosmology & Particle Physics", "Atmospheric, Climate & Environmental Science", 
    "Autoimmune & Chronic Disease", "Autonomous Systems & Robotics", "Basic & Cross-Domain Science", 
    "Behavioral Science & Psychology", "Biodiversity & Ecology", "Bioeconomy & Circular Economy", 
    "Bioengineering & Synthetic Biology", "Bioinformatics & Systems Biology", "Biological Sciences", 
    "Biomedical Devices & Imaging", "Biomedical Engineering", "Biomedical Research (General)", 
    "Biotechnology", "Brain Science & Neuroscience", "Business & Organizational Behavior", 
    "Cancer Research & Oncology", "Carbon Management & Climate Technology", "Cardiovascular Health", 
    "Chemical & Process Engineering", "Chemical Safety & Toxicology", "Civic Engagement & Governance", 
    "Civil Engineering & Infrastructure", "Clean & Renewable Energy", "Climate Adaptation & Impact", 
    "Cloud & Digital Infrastructure", "Cognitive Science", "Communication & Media Studies", 
    "Complex Systems Science", "Computer Science (General)", "Computer Vision & Graphics", 
    "Conflict, Security & Justice", "Crisis & Disaster Management", "Critical Infrastructure & Safety", 
    "Critical Materials & Waste Management", "Cybersecurity & Digital Governance", "Data Science & Analytics", 
    "Dental & Oral Health", "Design Research & Human-Computer Interaction", "Digital Economy & Innovation", 
    "Digital Health & Medical Technology", "Digital Humanities & Cultural Heritage", "Drug Discovery & Pharmaceutical Development", 
    "Economics & Development Studies", "Energy Generation & Systems", "Food Science, Nutrition & Security", 
    "Genomics & Precision Medicine", "Gerontology & Aging Studies", "Historical Studies", 
    "Imaging & Instrumentation Technologies", "Immunology & Vaccine Development", "Life Sciences (General)", 
    "Linguistics & Language Studies", "Logistics & Supply Chain Management", "Marine, Ocean & Water Science", 
    "Materials Science & Engineering", "Mathematics & Applied Statistics", "Mechanical Engineering", 
    "Medical Education & Training", "Mental Health & Psychiatry", "Metabolic & Endocrine Health", 
    "Metrology & Measurement Science", "Microbiology & Microbiome Science", "Migration & Urban Studies", 
    "Musculoskeletal Health & Rehabilitation", "National Security & Defense Studies", "Natural Language Processing", 
    "Natural Resources & Environmental Management", "Neglected & Rare Diseases", "Network Science & Telecommunications", 
    "Nuclear Science & Engineering", "Occupational Health & Safety", "Optics & Photonics", 
    "Organic & Inorganic Chemistry", "Patient Care & Health Systems", "Pediatric & Women's Health", 
    "Philosophy, Logic & Ethics", "Physical & Chemical Sciences", "Planetary & Space Science", 
    "Political Science & Policy", "Public Health & Global Health", "Quantum Science & Technology", 
    "Regional & Urban Planning", "Religious Studies & Theology", "Remote Sensing & Geospatial Technology", 
    "Research & Innovation Policy", "Science & Technology Studies", "Simulation & Training Technology", 
    "Smart Systems & Internet of Things", "Social Justice & Equity", "Social Research & Sociology", 
    "Software Systems Engineering", "Stem Cell & Regenerative Engineering", "Sustainability Science & Education", 
    "Sustainable Consumption & Lifestyles", "Systems Engineering (General)", "Theoretical Physics", 
    "Toxicology & Risk Assessment", "Translational Medicine", "Transport Safety & Emissions reduction", 
    "Venture Capital & Innovation Finance", "Wildlife Health & Ecology"
]

S5_METHOD_CATEGORIES = [
    "AI & Machine Learning Development", "Advanced Analytical Techniques", "Advanced Engineering Methods", 
    "Advanced Manufacturing & Nanotechnology", "Measurement & Precision Engineering", "Agricultural & Crop Research Methods", 
    "Applied Biotechnology & Bioresource Utilization", "Cultural Heritage Research & Preservation Methods", "Aerospace & Space Engineering Methods", 
    "Autonomous Systems & Robotics Development", "Behavioral Science Research & Design Interventions", "Bio-Inspired Computing & Algorithm Design", 
    "Bioengineering & Biomanufacturing Processes", "Waste Processing & Resource Valorization", 
    "Biomarker Discovery & Diagnostic Development", "Biomedical Data Analysis & Computational Biology", "Biotechnology Research Methodologies", 
    "Business Model & Market Innovation Strategies", "Capacity Building, Training & Workforce Development", "Chemical & Green Process Engineering", 
    "Circular Economy Analysis & Lifecycle Assessment", "Community Engagement & Stakeholder Collaboration", "Clean Propulsion & Emission Control Technologies", 
    "Climate & Ecological System Modeling", "Clinical Research & Human Trials Methodology", "Communication, Dissemination & Outreach Strategies", 
    "Complex Systems Modeling & Analysis", "Computational Modeling & Simulation Techniques", "Computational Social Science Methods", 
    "Computer Graphics & Virtual Prototyping", "Computer Vision & Image Processing Systems", "Conservation Management & Ecological Monitoring", 
    "Cybersecurity Protocols & Data Privacy Techniques", "Data Analysis & Statistical Methods", "Data Collection, Curation & Governance", 
    "Decision Support Systems & Science", "Device Design & Instrument Engineering", "Digital Content Creation & Digital Scholarship Methods", 
    "Digital User Experience & Human-Computer Interaction Design", "Digital Health Solutions & Remote Care Delivery", "Digital Infrastructure Development & Transformation Strategies", 
    "Disease Modeling & Epidemiological Surveillance", "Drug Discovery, Delivery & Preclinical Development", "Earth Observation & Geospatial Analytics", 
    "Energy Infrastructure & Efficiency Optimization", "Engineering Design & Development Methodology", "Environmental Impact Assessment & Monitoring", 
    "Ethical Framework Development & Policy Analysis", "Experimental Design & Laboratory Analysis", "Food Processing, Quality & Safety Methods", 
    "Gene Therapy & Genetic Engineering Techniques", "Healthcare System Design & Optimization", "Health Impact Assessment & Health Promotion Strategies", 
    "Advanced Imaging & Microscopy Techniques", "Immunological Assays & Therapeutic Development", "Impact Assessment & Policy Implementation", 
    "Industrial Process Design & Optimization", "Information Retrieval & Knowledge Management Systems", "Infrastructure Planning & Smart Systems Integration", 
    "Innovation Management & Technology Transfer", "Instrumentation Development & Sensor Technology", "Integrated Assessment Frameworks & Modeling", 
    "Internet of Things & Digital Automation Solutions", "Laboratory Automation & High-Throughput Screening", "Language Processing & Text Analysis Methods", 
    "Material Design, Synthesis & Characterization", "Mathematical Modeling & Numerical Analysis", "Medical Technology Design & Innovation", 
    "Microbiome Engineering & Host-Microbe Interaction Research", "Mixed Methods Research Approaches", "Neuroscience & Cognitive Research Methods", 
    "Open Science Practices & Research Governance", "Operational Efficiency & Systems Engineering", "Organizational Development & Strategic Management", 
    "Participatory Action Research & Co-Design Methods", "Philosophical Inquiry & Ethical Analysis", "Physical Sciences Experimental Research", 
    "Physiological Measurement & Analysis Studies", "Plant Biotechnology & Applied Agricultural Research", "Product Development & Lifecycle Management", 
    "Proteomics, Metabolomics & Mass Spectrometry", "Qualitative Research Methodologies", "Quantitative Research Methodologies", 
    "Urban & Regional Development Modeling & Planning", "Reliability Engineering & Risk Assessment", "Resource Management & Optimization Strategies", 
    "Scenario Analysis & Foresight Planning", "Scientific Infrastructure Development & Management", "Social & Economic Impact Research", 
    "Software Development & Systems Engineering", "Supply Chain Design & Optimization", "Synthetic Biology & Metabolic Engineering", 
    "Theoretical Modeling & Computational Physics/Chemistry", "Indigenous Knowledge Systems & Co-creation", "Translational Research & Clinical Application", 
    "System Verification, Validation & Testing", "Water Resource Management & Purification Technologies"
]

def find_s5_failed_projects():
    """Find the exact projects that still have non-matching S5 categories - STRICT MODE"""
    
    print("🔍 FINDING S5 FAILED PROJECTS (STRICT - NO PARSE FAILED ALLOWED)")
    print("="*60)
    
    # Load current data
    try:
        df = pd.read_csv("df_processing_checkpoint.csv")
        print(f"✅ Loaded checkpoint CSV: {df.shape}")
    except:
        df = globals()['df_complete'].copy()
        print(f"✅ Using global df_complete: {df.shape}")
    
    # STRICT: Only empty strings and None are acceptable "failures"
    # Everything else (including "Parse Failed", "API Failed", etc.) must be fixed
    acceptable_errors = ["", None]
    
    failed_projects = []
    
    for idx in df.index:
        domain = df.loc[idx, 's5_curated_domain']
        method = df.loc[idx, 's5_curated_method']
        
        # Check if domain is problematic
        domain_bad = (pd.notna(domain) and 
                     str(domain).strip() != "" and  # Not empty string
                     domain not in S5_DOMAIN_CATEGORIES)  # Not valid category
        
        # Check if method is problematic  
        method_bad = (pd.notna(method) and 
                     str(method).strip() != "" and  # Not empty string
                     method not in S5_METHOD_CATEGORIES)  # Not valid category
        
        if domain_bad or method_bad:
            project_id = df.loc[idx, 'id'] if 'id' in df.columns else idx
            failed_projects.append({
                'index': idx,
                'id': project_id,
                'domain': domain,
                'method': method,
                'domain_bad': domain_bad,
                'method_bad': method_bad,
                'summary': str(df.loc[idx, 'full_text'])[:200] + "..."
            })
    
    print(f"Found {len(failed_projects)} projects with invalid S5 categories")
    
    # Group by bad categories to see patterns
    if failed_projects:
        domain_issues = {}
        method_issues = {}
        
        for proj in failed_projects:
            if proj['domain_bad']:
                domain = str(proj['domain'])
                if domain not in domain_issues:
                    domain_issues[domain] = []
                domain_issues[domain].append(proj['index'])
            
            if proj['method_bad']:
                method = str(proj['method'])
                if method not in method_issues:
                    method_issues[method] = []
                method_issues[method].append(proj['index'])
        
        print(f"\n❌ ALL PROBLEMATIC S5 DOMAINS (including Parse Failed, API Failed, etc.):")
        for domain, indices in domain_issues.items():
            print(f"  '{domain}': {len(indices)} projects")
        
        print(f"\n❌ ALL PROBLEMATIC S5 METHODS (including Parse Failed, API Failed, etc.):")
        for method, indices in method_issues.items():
            print(f"  '{method}': {len(indices)} projects")
    
    return failed_projects, df

def fix_s5_failed_projects_no_parse_failed(failed_projects, df, model):
    """Fix S5 projects - return empty strings instead of failure messages"""
    
    if not failed_projects:
        print("✅ No S5 failed projects to fix!")
        return df
    
    print(f"🔧 S5 FIXING - {len(failed_projects)} PROJECTS (NO PARSE FAILED ALLOWED)")
    print("="*60)
    
    # Enhanced prompt for problem cases
    TARGETED_S5_PROMPT = """You are an expert research taxonomist. You must classify these projects using ONLY the exact categories from the lists below.

CRITICAL RULES:
1. Select EXACTLY ONE domain from the Domain list for each project
2. Select EXACTLY ONE method from the Method list for each project  
3. Use the EXACT spelling, punctuation, and capitalization shown
4. DO NOT create new categories or modify existing ones
5. DO NOT confuse domains with methods

DOMAIN AREAS (Scientific/Technical Fields - choose ONE per project):
{domain_list}

METHOD AREAS (Research Approaches/Techniques - choose ONE per project):
{method_list}

PROJECTS TO CLASSIFY:
{project_summaries}

RESPOND IN THIS EXACT FORMAT:
Project 1:
Domain Area: [EXACT match from Domain list above]
Method Area: [EXACT match from Method list above]

Project 2:
Domain Area: [EXACT match from Domain list above]
Method Area: [EXACT match from Method list above]

... continue for all projects ...

Remember: Domain = WHAT field/area, Method = HOW it's done."""

    changes_made = []
    df_working = df.copy()
    
    # Process 6 projects at a time
    batch_size = 6
    total_batches = (len(failed_projects) + batch_size - 1) // batch_size
    
    for batch_num in range(total_batches):
        start_idx = batch_num * batch_size
        end_idx = min(start_idx + batch_size, len(failed_projects))
        batch_projects = failed_projects[start_idx:end_idx]
        
        print(f"\n--- S5 Batch {batch_num+1}/{total_batches} ({len(batch_projects)} projects) ---")
        
        # Show what we're fixing
        for i, proj in enumerate(batch_projects):
            print(f"  Project {i+1} (ID {proj['id']}, Index {proj['index']}):")
            print(f"    Current Domain: '{proj['domain']}' {'❌' if proj['domain_bad'] else '✅'}")
            print(f"    Current Method: '{proj['method']}' {'❌' if proj['method_bad'] else '✅'}")
        
        # Prepare batch summaries
        project_summaries = ""
        for i, proj in enumerate(batch_projects, 1):
            project_text = str(df_working.loc[proj['index'], 'full_text'])[:1200]  # Limit length
            project_summaries += f"Project {i}:\nTitle and Description: {project_text}\n\n"
        
        # Create focused prompt
        prompt = TARGETED_S5_PROMPT.format(
            domain_list="\n".join(S5_DOMAIN_CATEGORIES),
            method_list="\n".join(S5_METHOD_CATEGORIES),
            project_summaries=project_summaries
        )
        
        # Try to get results from LLM
        batch_success = False
        try:
            print(f"🤖 Calling LLM for batch {batch_num+1}...")
            
            response = model.generate_content(prompt)
            output = response.text.strip()
            
            print(f"✅ Got LLM response, parsing...")
            
            # Parse results for the batch
            project_blocks = re.split(r'Project \d+:', output)
            if project_blocks and not project_blocks[0].strip():
                project_blocks = project_blocks[1:]
            
            if len(project_blocks) >= len(batch_projects):
                batch_results = []
                
                for i, block in enumerate(project_blocks[:len(batch_projects)]):
                    new_domain = ""  # Default to EMPTY instead of "Parse Failed"
                    new_method = ""  # Default to EMPTY instead of "Parse Failed"
                    
                    lines = block.strip().split('\n')
                    for line in lines:
                        line = line.strip()
                        if line.startswith("Domain Area:"):
                            candidate = line.replace("Domain Area:", "").strip()
                            candidate = candidate.strip('"\'- ')
                            # Only assign if it's actually in our valid list
                            if candidate in S5_DOMAIN_CATEGORIES:
                                new_domain = candidate
                        elif line.startswith("Method Area:"):
                            candidate = line.replace("Method Area:", "").strip()
                            candidate = candidate.strip('"\'- ')
                            # Only assign if it's actually in our valid list
                            if candidate in S5_METHOD_CATEGORIES:
                                new_method = candidate
                    
                    batch_results.append({
                        'domain': new_domain,
                        'method': new_method
                    })
                
                # Apply all results in this batch
                for i, result in enumerate(batch_results):
                    proj = batch_projects[i]
                    idx = proj['index']
                    
                    old_domain = df_working.loc[idx, 's5_curated_domain']
                    old_method = df_working.loc[idx, 's5_curated_method']
                    
                    # Only update categories that were actually problematic
                    if proj['domain_bad']:
                        df_working.loc[idx, 's5_curated_domain'] = result['domain']
                        print(f"  🔄 Fixed Domain {idx}: '{old_domain}' → '{result['domain']}'")
                    
                    if proj['method_bad']:
                        df_working.loc[idx, 's5_curated_method'] = result['method']
                        print(f"  🔄 Fixed Method {idx}: '{old_method}' → '{result['method']}'")
                    
                    changes_made.append({
                        'index': idx,
                        'id': proj['id'],
                        'old_domain': old_domain,
                        'new_domain': result['domain'] if proj['domain_bad'] else old_domain,
                        'old_method': old_method,
                        'new_method': result['method'] if proj['method_bad'] else old_method
                    })
                
                batch_success = True
                print(f"  ✅ Batch {batch_num+1} processed successfully")
            else:
                print(f"  ⚠️ Got {len(project_blocks)} project blocks, expected {len(batch_projects)}")
                
        except Exception as e:
            print(f"  ❌ LLM error for batch {batch_num+1}: {e}")
        
        if not batch_success:
            print(f"  🔄 Batch {batch_num+1} failed - setting empty strings for problematic categories")
            # Set empty strings for failed attempts (so they get caught in next iteration)
            for proj in batch_projects:
                idx = proj['index']
                if proj['domain_bad']:
                    df_working.loc[idx, 's5_curated_domain'] = ""
                    print(f"    Set domain to empty for index {idx}")
                if proj['method_bad']:
                    df_working.loc[idx, 's5_curated_method'] = ""
                    print(f"    Set method to empty for index {idx}")
        
        # Small delay between batches
        if batch_num < total_batches - 1:
            time.sleep(3)
    
    print(f"\n💾 SAVING S5 FIXES")
    print("="*60)
    
    # Save back to CSV
    df_working.to_csv("df_processing_checkpoint.csv", index=False)
    print(f"✅ Saved to df_processing_checkpoint.csv")
    
    # Update global if possible
    try:
        globals()['df_complete'] = df_working.copy()
        print(f"✅ Updated global df_complete")
    except:
        pass
    
    print(f"\n📊 S5 FIX SUMMARY:")
    print(f"   Failed projects processed: {len(failed_projects)}")
    print(f"   Batches processed: {total_batches}")
    print(f"   Changes attempted: {len(changes_made)}")
    
    return df_working

def run_s5_complete_fix():
    """Main function to run complete S5 fixes until everything is clean"""
    
    print("🎯 S5 COMPLETE FIX - NO PARSE FAILED ALLOWED")
    print("="*80)
    
    # Get model
    try:
        model = globals()['model']
        print(f"✅ Using global model")
    except:
        print("❌ ERROR: Global 'model' not found")
        return None
    
    # Keep running fix iterations until no more failures
    max_iterations = 5
    
    for iteration in range(max_iterations):
        print(f"\n🔄 S5 FIX ITERATION {iteration + 1}/{max_iterations}")
        print("="*60)
        
        # Step 1: Find failed projects (strict mode)
        failed_projects, df = find_s5_failed_projects()
        
        if not failed_projects:
            print(f"🎉 S5 COMPLETE - No more failed projects after {iteration + 1} iteration(s)!")
            break
        
        print(f"📋 Found {len(failed_projects)} projects that need fixing")
        
        # Step 2: Apply fixes
        df = fix_s5_failed_projects_no_parse_failed(failed_projects, df, model)
        
        # Step 3: Show progress
        print(f"\n📊 Iteration {iteration + 1} complete")
        
        if iteration == max_iterations - 1:
            print(f"⚠️ Reached maximum iterations ({max_iterations})")
            print(f"   Some projects may still need manual review")
    
    # Final verification
    print(f"\n🔍 FINAL S5 VERIFICATION")
    print("="*60)
    
    final_failed, df_final = find_s5_failed_projects()
    
    domain_matches = sum(1 for d in df_final['s5_curated_domain'] if d in S5_DOMAIN_CATEGORIES)
    method_matches = sum(1 for m in df_final['s5_curated_method'] if m in S5_METHOD_CATEGORIES)
    empty_domains = sum(1 for d in df_final['s5_curated_domain'] if pd.isna(d) or str(d).strip() == "")
    empty_methods = sum(1 for m in df_final['s5_curated_method'] if pd.isna(m) or str(m).strip() == "")
    total_projects = len(df_final)
    
    print(f"📊 FINAL S5 STATISTICS:")
    print(f"   Total projects: {total_projects}")
    print(f"   Valid domain categories: {domain_matches} ({domain_matches/total_projects*100:.2f}%)")
    print(f"   Valid method categories: {method_matches} ({method_matches/total_projects*100:.2f}%)")
    print(f"   Empty domains (acceptable): {empty_domains} ({empty_domains/total_projects*100:.2f}%)")
    print(f"   Empty methods (acceptable): {empty_methods} ({empty_methods/total_projects*100:.2f}%)")
    print(f"   Remaining problematic projects: {len(final_failed)}")
    
    if len(final_failed) == 0:
        print(f"\n🎉🎉🎉 PERFECT! 100% S5 SUCCESS - NO MORE PARSE FAILED! 🎉🎉🎉")
    else:
        print(f"\n⚠️ Still have {len(final_failed)} projects with invalid categories:")
        # Show first few remaining problems
        for proj in final_failed[:5]:
            print(f"   - Index {proj['index']}: Domain='{proj['domain']}', Method='{proj['method']}'")
        
        if len(final_failed) > 5:
            print(f"   ... and {len(final_failed) - 5} more")
    
    print(f"\n🎯 S5 COMPLETE FIX FINISHED!")
    
    return df_final

# USAGE:
# Just run this one function and it will handle everything
# df_s5_clean = run_s5_complete_fix()

🔍 STARTING CSV CATEGORY CHECKER AND RECLASSIFIER
============================================================
Using global df_complete
Dataset shape: (15341, 14)
Columns: ['id', 'full_text', 'l1_goal', 'l1_method', 'l2_generalized_goal', 'l2_generalized_method', 'l3_tech_domain', 'l3_strategic_method', 'l3_std_domain_area', 'l3_std_method_area', 's6_domain', 's6_method', 's5_curated_domain', 's5_curated_method']
============================================================
IDENTIFYING NON-MATCHING CATEGORIES
============================================================
Found 0 projects with non-matching domains
Found 0 projects with non-matching methods
Total unique projects needing reclassification: 0
✅ All categories already match your curated lists!
============================================================
FINAL VERIFICATION
============================================================
Total projects: 15341
Domain matches: 15341 (100.00%)
Method matches: 15341 (100.00%)

🎉 All domains now match!

🎉 All methods now match!

🎉🎉🎉 PERFECT SUCCESS - 100% MATCH RATE! 🎉🎉🎉

In [145]:
# S6 REFINED CATEGORIES 
S6_DOMAIN_CATEGORIES = [
    "Fundamental Physics & Chemistry",
    "Mathematical & Computational Sciences", 
    "Biological & Life Sciences",
    "Earth, Environmental & Climate Science",
    "Agriculture, Food & Bioresources",
    "Aerospace, Space & Astronomy",
    "Computer Science & Information Technology",
    "Artificial Intelligence & Data Science",
    "Robotics & Autonomous Systems",
    "Electrical, Electronics & Photonics Engineering",
    "Materials Science & Engineering",
    "Chemical Engineering & Applied Chemistry",
    "Mechanical & Industrial Engineering",
    "Biomedical Engineering & Medical Technology",
    "Energy Systems & Technology",
    "Transportation, Urban & Regional Development",
    "Clinical Medicine & Health Sciences",
    "Neuroscience, Neurology & Cognitive Science",
    "Microbiology, Virology & Infectious Diseases",
    "Cancer & Oncology",
    "Drug Discovery & Pharmaceutical Development",
    "Public Health, Epidemiology & Healthcare Administration",
    "Social Sciences & Human Behavior",
    "Psychology & Behavioral Science",
    "Business, Management & Economics",
    "Policy, Governance & Law",
    "Humanities, Arts & Cultural Heritage",
    "Education & Training",
    "Sustainable Development & Global Challenges",
    "Security & Defense",
    "Environmental Health & Engineering",
    "Nuclear Science & Engineering",
    "Quantum Physics & Technologies"
]

S6_METHOD_CATEGORIES = [
    "Qualitative, Archival & Interpretive Research",
    "Quantitative, Statistical & Mathematical Modeling",
    "Computational Modeling, Simulation & Optimization",
    "Artificial Intelligence & Machine Learning Methods",
    "Experimental Design & Laboratory Techniques",
    "Data Collection, Curation & Management",
    "Data Analysis, Interpretation & Visualization",
    "Engineering Design, Fabrication & Prototyping",
    "Process Engineering & Optimization",
    "Materials Synthesis, Characterization & Analysis",
    "Chemical Synthesis, Catalysis & Analytical Methods",
    "Omics, Molecular & Cellular Biology Techniques",
    "Genetic Engineering & Synthetic Biology",
    "Bioprocessing, Biomanufacturing & Bioengineering",
    "Drug Discovery, Development & Delivery Methods",
    "Clinical & Healthcare Research Methods",
    "Diagnostic, Therapeutic & Medical Technology Development",
    "Advanced Imaging, Microscopy & Spectroscopy",
    "Sensor, Monitoring & Measurement Technologies",
    "Remote Sensing, Geospatial Analysis & Mapping",
    "Ecological & Environmental Modeling & Assessment",
    "Policy, Economic & Social Impact Analysis",
    "Ethical, Legal & Societal Framework Development",
    "Neuroscience, Cognitive & Behavioral Research Methods",
    "Agricultural, Plant Science & Food System Methods",
    "Immunological & Infectious Disease Research",
    "Software Engineering, HCI & Digital System Design",
    "Cybersecurity, Network Engineering & Data Protection",
    "Lifecycle, Risk Assessment & Environmental Management",
    "Innovation, Business Development & Digital Transformation",
    "Knowledge Management, Collaboration & Dissemination",
    "Capacity Building, Education & Training Methods",
    "Quantum Computing & Technology Development",
    "Archaeological, Heritage & Conservation Methods",
    "Astro/Space Observation & Geophysical Survey Methods"
]

print(f"🎯 S6 REFINED CATEGORIES LOADED")
print(f"   Domains: {len(S6_DOMAIN_CATEGORIES)} categories")
print(f"   Methods: {len(S6_METHOD_CATEGORIES)} categories")

# S6 Classification Prompt - Based on your proven S5 approach
S6_BATCH_CLASSIFY_PROMPT = """You are an expert taxonomist specializing in research project classification. Your task is to classify multiple research project summaries, assigning each project exactly one domain area and one method area from the provided lists.

Domain Areas (33 refined categories):
{domain_categories}

Method Areas (35 refined categories):
{method_categories}

Classification Guidelines:
1. For Domain Area, focus on the PRIMARY SCIENTIFIC/TECHNICAL FIELD or APPLICATION AREA.
   - Choose the domain that best represents the core scientific discipline or application area
   - If a project spans multiple domains, select the one that represents the primary focus
   - Look for the fundamental field of knowledge or application that the project contributes to

2. For Method Area, select the primary methodology, approach, or technique used in the project.
   - Focus on HOW the research work is being accomplished
   - Choose the most significant methodological approach used
   - Consider the core techniques or approaches that drive the research

3. Each project gets exactly ONE domain and ONE method from the lists above.
   - Use EXACT spelling and capitalization as shown in the lists
   - Select the single best match for each category

Projects to Classify:
{project_summaries}

Output Format:
Project 1:
Domain Area: [Selected Domain Area - must be exactly as shown in the list]
Method Area: [Selected Method Area - must be exactly as shown in the list]

Project 2:
Domain Area: [Selected Domain Area - must be exactly as shown in the list] 
Method Area: [Selected Method Area - must be exactly as shown in the list]

... continue for all projects ...

Important: For each project, select only ONE domain area and ONE method area. Both must be exact matches from the provided lists. Number your responses to match the project numbers exactly."""

def s6_classify_batch(project_summaries: List[str], max_retries: int = 3) -> List[Dict[str, str]]:
    """Classify a batch of project summaries using S6 categories"""
    
    # Format the project summaries for the prompt
    formatted_summaries = ""
    for i, summary in enumerate(project_summaries, 1):
        # Use full summaries without truncation for best results
        formatted_summaries += f"Project {i}:\n{summary}\n\n"
    
    # Create the prompt
    prompt = S6_BATCH_CLASSIFY_PROMPT.format(
        domain_categories="\n".join(S6_DOMAIN_CATEGORIES),
        method_categories="\n".join(S6_METHOD_CATEGORIES),
        project_summaries=formatted_summaries
    )
    
    # Process with model (with retries)
    output_text = ""
    for attempt in range(max_retries):
        try:
            response = model.generate_content(prompt)
            output_text = response.text
            break
        except Exception as e:
            print(f"Error on attempt {attempt + 1}: {e}")
            if attempt < max_retries - 1:
                sleep_time = 2 ** (attempt + 1)
                print(f"Retrying in {sleep_time} seconds...")
                time.sleep(sleep_time)
            else:
                print("Failed all retry attempts")
                return [{"domain": "API Failed", "method": "API Failed"} for _ in project_summaries]
    
    # Parse results
    results = []
    project_blocks = re.split(r'Project \d+:', output_text)
    
    # Skip the first item if it's empty
    if project_blocks and not project_blocks[0].strip():
        project_blocks = project_blocks[1:]
    
    # If we didn't get enough results, pad with failures
    if len(project_blocks) < len(project_summaries):
        print(f"Warning: Expected {len(project_summaries)} results but got {len(project_blocks)}")
        project_blocks.extend(["" for _ in range(len(project_summaries) - len(project_blocks))])
    
    # Process each project block
    for i, block in enumerate(project_blocks[:len(project_summaries)]):
        domain = "Parse Failed"
        method = "Parse Failed"
        
        for line in block.strip().split('\n'):
            if line.startswith("Domain Area:"):
                domain = line.replace("Domain Area:", "").strip()
            elif line.startswith("Method Area:"):
                method = line.replace("Method Area:", "").strip()
        
        results.append({"domain": domain, "method": method})
    
    return results

def display_s6_first_batch_results(batch_summaries: List[str], batch_results: List[Dict[str, str]]):
    """Display detailed results for the first batch"""
    print("\n===== S6 FIRST BATCH RESULTS =====")
    print(f"Showing results for the first batch of {len(batch_summaries)} projects")
    
    for i, result in enumerate(batch_results):
        summary = batch_summaries[i]
        domain = result["domain"]
        method = result["method"]
        
        # Truncate summary for display
        truncated_summary = summary[:150] + "..." if len(summary) > 150 else summary
        truncated_summary = truncated_summary.replace('\n', ' ')
        
        print(f"\nProject {i+1}:")
        print(f"Summary: {truncated_summary}")
        print(f"S6 Domain: {domain}")
        print(f"S6 Method: {method}")
    
    print("\n================================")

def s6_classify_dataset():
    """Process the dataset using S6 refined categories"""
    
    print(f"🚀 STARTING S6 REFINED CLASSIFICATION")
    print(f"="*80)
    print(f"Using S6 refined categories:")
    print(f"  {len(S6_DOMAIN_CATEGORIES)} Domain areas")
    print(f"  {len(S6_METHOD_CATEGORIES)} Method areas")
    print(f"  Batch size: {DEFAULT_BATCH_SIZE}")
    print(f"  Trial mode: {RUN_OVERALL_TRIAL_MODE}")
    if RUN_OVERALL_TRIAL_MODE:
        print(f"  Max trial batches: {MAX_BATCHES_FOR_TRIAL}")
    
    # Initialize new S6 result columns
    df_complete['s6_refined_domain'] = ""
    df_complete['s6_refined_method'] = ""
    
    # Determine scope using global variables
    if RUN_OVERALL_TRIAL_MODE:
        max_rows = DEFAULT_BATCH_SIZE * MAX_BATCHES_FOR_TRIAL
        process_df = df_complete.iloc[:max_rows].copy()
        print(f"TRIAL MODE: Processing {len(process_df)} rows")
    else:
        process_df = df_complete.copy()
        print(f"FULL MODE: Processing {len(process_df)} rows")
    
    # Process in batches
    total_records = len(process_df)
    total_batches = (total_records + DEFAULT_BATCH_SIZE - 1) // DEFAULT_BATCH_SIZE
    
    for batch_num, start_idx in enumerate(range(0, total_records, DEFAULT_BATCH_SIZE)):
        end_idx = min(start_idx + DEFAULT_BATCH_SIZE, total_records)
        batch_size_actual = end_idx - start_idx
        
        print(f"\nProcessing S6 batch {batch_num + 1}/{total_batches} (records {start_idx+1}-{end_idx})")
        
        # Extract summaries for this batch
        batch_summaries = []
        for idx in range(start_idx, end_idx):
            summary = process_df.iloc[idx]['full_text']
            batch_summaries.append(summary)
        
        # Classify the batch using S6 categories
        batch_results = s6_classify_batch(batch_summaries)
        
        # Save results directly to df_complete
        for i in range(batch_size_actual):
            original_idx = process_df.index[start_idx + i]
            if i < len(batch_results):
                df_complete.loc[original_idx, 's6_refined_domain'] = batch_results[i]['domain']
                df_complete.loc[original_idx, 's6_refined_method'] = batch_results[i]['method']
            else:
                df_complete.loc[original_idx, 's6_refined_domain'] = "API Failed"
                df_complete.loc[original_idx, 's6_refined_method'] = "API Failed"
        
        # Display detailed results for first batch only
        if batch_num == 0:
            display_s6_first_batch_results(batch_summaries, batch_results)
        
        # Save every 20 batches
        if (batch_num + 1) % 20 == 0:
            df_complete.to_csv(MAIN_DATAFRAME_CHECKPOINT_FILE, index=False)
            print(f"  ✅ S6 SAVED at batch {batch_num + 1}")
        
        # Wait between batches
        if batch_num < total_batches - 1:
            print(f"Waiting {DEFAULT_WAIT_TIME} seconds before next S6 batch...")
            time.sleep(DEFAULT_WAIT_TIME)
    
    return df_complete

def s6_check_category_matches():
    """Check which S6 assigned categories match the provided lists"""
    
    print("="*60)
    print("S6 CATEGORY MATCH CHECK") 
    print("="*60)
    
    # Get all assigned categories
    assigned_domains = df_complete['s6_refined_domain'].dropna().unique()
    assigned_methods = df_complete['s6_refined_method'].dropna().unique()
    
    # Find non-matching domains
    non_matching_domains = []
    for domain in assigned_domains:
        if domain not in S6_DOMAIN_CATEGORIES and domain not in ["API Failed", "Parse Failed"]:
            non_matching_domains.append(domain)
    
    # Find non-matching methods  
    non_matching_methods = []
    for method in assigned_methods:
        if method not in S6_METHOD_CATEGORIES and method not in ["API Failed", "Parse Failed"]:
            non_matching_methods.append(method)
    
    # Report results
    print(f"Total unique S6 domains assigned: {len(assigned_domains)}")
    print(f"S6 Domains matching your list: {len(assigned_domains) - len(non_matching_domains)}")
    print(f"S6 Domains NOT in your list: {len(non_matching_domains)}")
    
    if non_matching_domains:
        print(f"\nNON-MATCHING S6 DOMAINS:")
        for domain in non_matching_domains:
            count = (df_complete['s6_refined_domain'] == domain).sum()
            print(f"  '{domain}': {count} projects")
    
    print(f"\nTotal unique S6 methods assigned: {len(assigned_methods)}")
    print(f"S6 Methods matching your list: {len(assigned_methods) - len(non_matching_methods)}")
    print(f"S6 Methods NOT in your list: {len(non_matching_methods)}")
    
    if non_matching_methods:
        print(f"\nNON-MATCHING S6 METHODS:")
        for method in non_matching_methods:
            count = (df_complete['s6_refined_method'] == method).sum()
            print(f"  '{method}': {count} projects")
    
    # Calculate match rates
    total_projects = len(df_complete)
    domain_exact_matches = sum(1 for d in df_complete['s6_refined_domain'] if d in S6_DOMAIN_CATEGORIES)
    method_exact_matches = sum(1 for m in df_complete['s6_refined_method'] if m in S6_METHOD_CATEGORIES)
    
    print(f"\n" + "="*60)
    print("S6 MATCH RATES")
    print("="*60)
    print(f"S6 Domain exact match rate: {domain_exact_matches}/{total_projects} ({domain_exact_matches/total_projects*100:.1f}%)")
    print(f"S6 Method exact match rate: {method_exact_matches}/{total_projects} ({method_exact_matches/total_projects*100:.1f}%)")
    
    return non_matching_domains, non_matching_methods

def s6_reclassify_failed_categories(small_batch_size: int = 3, max_retries: int = 5):
    """Re-classify S6 projects that got non-matching categories"""
    
    print("="*60)
    print("S6 RE-CLASSIFYING NON-MATCHING CATEGORIES")
    print("="*60)
    
    # Identify failed S6 classifications
    domain_failures = ~df_complete['s6_refined_domain'].isin(S6_DOMAIN_CATEGORIES + ["API Failed", "Parse Failed"])
    method_failures = ~df_complete['s6_refined_method'].isin(S6_METHOD_CATEGORIES + ["API Failed", "Parse Failed"])
    
    # Get indices that need re-classification
    failed_indices = df_complete[domain_failures | method_failures].index.tolist()
    
    if not failed_indices:
        print("No failed S6 classifications found. Nothing to reclassify.")
        return df_complete
    
    print(f"Found {len(failed_indices)} S6 projects with non-matching categories")
    print(f"Using smaller batch size: {small_batch_size}")
    
    # Enhanced S6 prompt for reclassification
    S6_RECLASSIFY_PROMPT = """You are an expert taxonomist. You must classify projects using ONLY the exact categories from the provided lists.

CRITICAL INSTRUCTIONS:
1. DOMAIN = The primary scientific/technical FIELD or APPLICATION AREA (WHAT the project is about)
2. METHOD = The primary APPROACH or TECHNIQUE used (HOW the work is done)
3. You MUST select exactly one domain and one method from the provided lists
4. Use the EXACT spelling and capitalization as shown in the lists

Domain Areas (33 refined categories):
{domain_categories}

Method Areas (35 refined categories):
{method_categories}

Projects to Classify:
{project_summaries}

Output Format (MUST follow exactly):
Project 1:
Domain Area: [Selected Domain Area - must be EXACTLY as shown in the Domain list above]
Method Area: [Selected Method Area - must be EXACTLY as shown in the Method list above]

Project 2:
Domain Area: [Selected Domain Area - must be EXACTLY as shown in the Domain list above]
Method Area: [Selected Method Area - must be EXACTLY as shown in the Method list above]

Continue for all projects. Select ONLY from the provided lists."""

    def s6_reclassify_small_batch(project_summaries: List[str]) -> List[Dict[str, str]]:
        """Reclassify a small batch with S6 enhanced prompt"""
        
        # Format summaries
        formatted_summaries = ""
        for i, summary in enumerate(project_summaries, 1):
            formatted_summaries += f"Project {i}:\n{summary}\n\n"
        
        # Create enhanced S6 prompt
        prompt = S6_RECLASSIFY_PROMPT.format(
            domain_categories="\n".join(S6_DOMAIN_CATEGORIES),
            method_categories="\n".join(S6_METHOD_CATEGORIES),
            project_summaries=formatted_summaries
        )
        
        # Process with more retries
        output_text = ""
        for attempt in range(max_retries):
            try:
                response = model.generate_content(prompt)
                output_text = response.text
                break
            except Exception as e:
                print(f"  S6 Retry {attempt + 1}: {e}")
                if attempt < max_retries - 1:
                    sleep_time = 2 ** (attempt + 1)
                    print(f"  Waiting {sleep_time}s...")
                    time.sleep(sleep_time)
                else:
                    print("  All S6 retries failed")
                    return [{"domain": "S6 Reclassify Failed", "method": "S6 Reclassify Failed"} for _ in project_summaries]
        
        # Parse results
        results = []
        project_blocks = re.split(r'Project \d+:', output_text)
        
        if project_blocks and not project_blocks[0].strip():
            project_blocks = project_blocks[1:]
        
        if len(project_blocks) < len(project_summaries):
            project_blocks.extend(["" for _ in range(len(project_summaries) - len(project_blocks))])
        
        for i, block in enumerate(project_blocks[:len(project_summaries)]):
            domain = "S6 Reclassify Failed"
            method = "S6 Reclassify Failed"
            
            for line in block.strip().split('\n'):
                if line.startswith("Domain Area:"):
                    domain = line.replace("Domain Area:", "").strip()
                elif line.startswith("Method Area:"):
                    method = line.replace("Method Area:", "").strip()
            
            results.append({"domain": domain, "method": method})
        
        return results
    
    # Process failed items in small batches
    total_failed = len(failed_indices)
    total_batches = (total_failed + small_batch_size - 1) // small_batch_size
    
    successful_reclassifications = 0
    
    for batch_num, start_idx in enumerate(range(0, total_failed, small_batch_size)):
        end_idx = min(start_idx + small_batch_size, total_failed)
        batch_indices = failed_indices[start_idx:end_idx]
        
        print(f"\nS6 Reclassifying batch {batch_num + 1}/{total_batches} ({len(batch_indices)} projects)")
        
        # Get batch of failed items
        batch_summaries = []
        for idx in batch_indices:
            summary = df_complete.loc[idx, 'full_text']
            batch_summaries.append(summary)
            
            # Show what failed
            old_domain = df_complete.loc[idx, 's6_refined_domain']
            old_method = df_complete.loc[idx, 's6_refined_method']
            print(f"  Project {idx}: '{old_domain}' / '{old_method}'")
        
        # Reclassify this batch
        batch_results = s6_reclassify_small_batch(batch_summaries)
        
        # Update results and show changes
        for i, idx in enumerate(batch_indices):
            if i < len(batch_results):
                new_domain = batch_results[i]['domain']
                new_method = batch_results[i]['method']
                
                df_complete.loc[idx, 's6_refined_domain'] = new_domain
                df_complete.loc[idx, 's6_refined_method'] = new_method
                
                # Check if reclassification was successful
                domain_success = new_domain in S6_DOMAIN_CATEGORIES
                method_success = new_method in S6_METHOD_CATEGORIES
                
                if domain_success and method_success:
                    successful_reclassifications += 1
                    print(f"    ✅ Fixed: '{new_domain}' / '{new_method}'")
                else:
                    print(f"    ❌ Still failed: '{new_domain}' / '{new_method}'")
        
        # Wait between batches
        if batch_num < total_batches - 1:
            print(f"  Waiting {DEFAULT_WAIT_TIME}s...")
            time.sleep(DEFAULT_WAIT_TIME)
    
    # Final save
    df_complete.to_csv(MAIN_DATAFRAME_CHECKPOINT_FILE, index=False)
    
    print(f"\n" + "="*60)
    print("S6 RECLASSIFICATION COMPLETE")
    print("="*60)
    print(f"Total S6 projects reclassified: {total_failed}")
    print(f"Successfully fixed: {successful_reclassifications}")
    print(f"Still failed: {total_failed - successful_reclassifications}")
    
    return df_complete

# MAIN S6 EXECUTION FUNCTION
def run_s6_classification():
    """Run the complete S6 classification process"""
    
    print("🎯 STARTING COMPLETE S6 REFINED CLASSIFICATION")
    print("="*80)
    
    # Check prerequisites
    if 'df_complete' not in globals() or df_complete.empty:
        print("❌ ERROR: df_complete not available")
        return None
    elif 'model' not in globals() or not model:
        print("❌ ERROR: model not available")
        return None
    elif 'full_text' not in df_complete.columns:
        print("❌ ERROR: 'full_text' column missing")
        return None
    
    # Step 1: Run main S6 classification
    print("🚀 STEP 1: Main S6 Classification")
    df_result = s6_classify_dataset()
    
    # Step 2: Check for mismatches
    print("\n🔍 STEP 2: Checking S6 Category Matches")
    non_matching_domains, non_matching_methods = s6_check_category_matches()
    
    # Step 3: Fix any mismatches
    if non_matching_domains or non_matching_methods:
        print("\n🔧 STEP 3: Fixing S6 Non-Matching Categories")
        df_result = s6_reclassify_failed_categories()
        
        # Final check
        print("\n✅ STEP 4: Final S6 Verification")
        s6_check_category_matches()
    else:
        print("\n✅ No S6 reclassification needed!")
    
    # Final save and summary
    df_complete.to_csv(MAIN_DATAFRAME_CHECKPOINT_FILE, index=False)
    print(f"\n🎉 S6 REFINED CLASSIFICATION COMPLETE!")
    
    # Show sample results
    print(f"\nS6 Sample Results:")
    sample_cols = ['id', 'full_text', 's6_refined_domain', 's6_refined_method']
    available_cols = [col for col in sample_cols if col in df_complete.columns]
    if available_cols:
        display(df_complete[available_cols].head())
    
    # Generate summary statistics
    domain_counts = df_complete['s6_refined_domain'].value_counts()
    method_counts = df_complete['s6_refined_method'].value_counts()
    
    print(f"\nTop 10 S6 assigned domain categories:")
    for domain, count in domain_counts.head(10).items():
        print(f"- {domain}: {count}")
    
    print(f"\nTop 10 S6 assigned method categories:")
    for method, count in method_counts.head(10).items():
        print(f"- {method}: {count}")
    
    return df_result

# USAGE:
df_s6_result = run_s6_classification()

🎯 S6 REFINED CATEGORIES LOADED
   Domains: 33 categories
   Methods: 35 categories
🎯 STARTING COMPLETE S6 REFINED CLASSIFICATION
================================================================================
🚀 STEP 1: Main S6 Classification
🚀 STARTING S6 REFINED CLASSIFICATION
================================================================================
Using S6 refined categories:
  33 Domain areas
  35 Method areas
  Batch size: 15
  Trial mode: False
FULL MODE: Processing 15341 rows

Processing S6 batch 1/1023 (records 1-15)

===== S6 FIRST BATCH RESULTS =====
Showing results for the first batch of 15 projects

Project 1:
Summary: Digitizing Other Economies: A Comparative Approach: How do longstanding, primarily non-industrial, non-capitalist societies adopt and adapt digital te...
S6 Domain: Social Sciences & Human Behavior
S6 Method: Qualitative, Archival & Interpretive Research

Project 2:
Summary: MOLECULAR QUANTUM DYNAMICS IN LOW TEMPERATURE CONDENSED PHASE ASTROCHEMISTRY: The James Webb Space Telescope (JWST) has ushered in a new era in observ...
S6 Domain: Aerospace, Space & Astronomy
S6 Method: Advanced Imaging, Microscopy & Spectroscopy

Project 3:
Summary: Multiscale modelling of aberrant phase transitions in biocondensates: The spatiotemporal organization of the cell material represents one of the great...
S6 Domain: Biological & Life Sciences
S6 Method: Computational Modeling, Simulation & Optimization

Project 4:
Summary: The first comprehensive Atlas of the Milky Way: The Milky Way is the cosmic environment in which the solar system, the Earth, and life as we know it c...
S6 Domain: Aerospace, Space & Astronomy
S6 Method: Astro/Space Observation & Geophysical Survey Methods

Project 5:
Summary: Untapping multiparametric 2D luminescence sensing through MACHine LEarning and Spectral Sorting: Cellular organisms are complex machines whose health ...
S6 Domain: Biomedical Engineering & Medical Technology
S6 Method: Artificial Intelligence & Machine Learning Methods

Project 6:
Summary: Making Sense of the Unexpected in the Gravitational-Wave Sky: General Relativity (GR) is more than a century old, but is still our best macroscopic de...
S6 Domain: Fundamental Physics & Chemistry
S6 Method: Quantitative, Statistical & Mathematical Modeling

Project 7:
Summary: Hernando Colón’s universal library. European culture and intellectual production at the dawn of the global world: While newly printed books were circu...
S6 Domain: Humanities, Arts & Cultural Heritage
S6 Method: Qualitative, Archival & Interpretive Research

Project 8:
Summary: UA EURATOM NCP SUPPORT OF UKRAINIAN RESEARCH ENTITIES INTEGRATION INTO NUCLEAR RESEARCH FUNDED BY THE EURATOM RESEARCH AND TRAINING PROGRAMME 2021-202...
S6 Domain: Nuclear Science & Engineering
S6 Method: Knowledge Management, Collaboration & Dissemination

Project 9:
Summary: FISA 2025 – EURADWASTE’25  conferences on Euratom fission research and training: The FISA-EURADWASTE event is a high-level, research policy conference...
S6 Domain: Nuclear Science & Engineering
S6 Method: Knowledge Management, Collaboration & Dissemination

Project 10:
Summary: Market & Technology Analysis: Adsorbi is a deep tech startup company from Gothenburg Sweden and was founded after several years of research within mat...
S6 Domain: Business, Management & Economics
S6 Method: Policy, Economic & Social Impact Analysis

Project 11:
Summary: Female leadership in Medsensio, a digital health technology startup: Medsensio was founded in 2017 as a spinout from a research project in health data...
S6 Domain: Business, Management & Economics
S6 Method: Innovation, Business Development & Digital Transformation

Project 12:
Summary: Detecting the right moment to do embryo transfer in In Vitro Fertilisation treatments.: In-vitro Fertilization (IVF) is a well-known fertility treatme...
S6 Domain: Biomedical Engineering & Medical Technology
S6 Method: Diagnostic, Therapeutic & Medical Technology Development

Project 13:
Summary: Elia - Smart Assistant for English Learning: We are a startup founded exclusively by women holding the top positions CEO and CTO. Our vision is to red...
S6 Domain: Education & Training
S6 Method: Software Engineering, HCI & Digital System Design

Project 14:
Summary: EUCYS Leiden2022: The main objective of this Proposal is the organisation of the Young Talents Programme which contains two separate events. The first...
S6 Domain: Education & Training
S6 Method: Capacity Building, Education & Training Methods

Project 15:
Summary: European Union Contest for Young Scientists (EUCYS) 2024: This proposal concerns the organization of the 35th European Union Contest for Young Scienti...
S6 Domain: Education & Training
S6 Method: Capacity Building, Education & Training Methods

================================
Waiting 0 seconds before next S6 batch...

Processing S6 batch 2/1023 (records 16-30)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 3/1023 (records 31-45)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 4/1023 (records 46-60)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 5/1023 (records 61-75)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 6/1023 (records 76-90)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 7/1023 (records 91-105)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 8/1023 (records 106-120)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 9/1023 (records 121-135)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 10/1023 (records 136-150)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 11/1023 (records 151-165)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 12/1023 (records 166-180)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 13/1023 (records 181-195)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 14/1023 (records 196-210)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 15/1023 (records 211-225)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 16/1023 (records 226-240)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 17/1023 (records 241-255)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 18/1023 (records 256-270)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 19/1023 (records 271-285)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 20/1023 (records 286-300)
  ✅ S6 SAVED at batch 20
Waiting 0 seconds before next S6 batch...

Processing S6 batch 21/1023 (records 301-315)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 22/1023 (records 316-330)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 23/1023 (records 331-345)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 24/1023 (records 346-360)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 25/1023 (records 361-375)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 26/1023 (records 376-390)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 27/1023 (records 391-405)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 28/1023 (records 406-420)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 29/1023 (records 421-435)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 30/1023 (records 436-450)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 31/1023 (records 451-465)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 32/1023 (records 466-480)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 33/1023 (records 481-495)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 34/1023 (records 496-510)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 35/1023 (records 511-525)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 36/1023 (records 526-540)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 37/1023 (records 541-555)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 38/1023 (records 556-570)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 39/1023 (records 571-585)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 40/1023 (records 586-600)
  ✅ S6 SAVED at batch 40
Waiting 0 seconds before next S6 batch...

Processing S6 batch 41/1023 (records 601-615)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 42/1023 (records 616-630)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 43/1023 (records 631-645)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 44/1023 (records 646-660)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 45/1023 (records 661-675)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 46/1023 (records 676-690)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 47/1023 (records 691-705)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 48/1023 (records 706-720)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 49/1023 (records 721-735)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 50/1023 (records 736-750)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 51/1023 (records 751-765)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 52/1023 (records 766-780)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 53/1023 (records 781-795)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 54/1023 (records 796-810)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 55/1023 (records 811-825)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 56/1023 (records 826-840)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 57/1023 (records 841-855)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 58/1023 (records 856-870)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 59/1023 (records 871-885)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 60/1023 (records 886-900)
  ✅ S6 SAVED at batch 60
Waiting 0 seconds before next S6 batch...

Processing S6 batch 61/1023 (records 901-915)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 62/1023 (records 916-930)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 63/1023 (records 931-945)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 64/1023 (records 946-960)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 65/1023 (records 961-975)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 66/1023 (records 976-990)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 67/1023 (records 991-1005)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 68/1023 (records 1006-1020)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 69/1023 (records 1021-1035)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 70/1023 (records 1036-1050)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 71/1023 (records 1051-1065)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 72/1023 (records 1066-1080)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 73/1023 (records 1081-1095)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 74/1023 (records 1096-1110)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 75/1023 (records 1111-1125)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 76/1023 (records 1126-1140)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 77/1023 (records 1141-1155)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 78/1023 (records 1156-1170)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 79/1023 (records 1171-1185)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 80/1023 (records 1186-1200)
  ✅ S6 SAVED at batch 80
Waiting 0 seconds before next S6 batch...

Processing S6 batch 81/1023 (records 1201-1215)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 82/1023 (records 1216-1230)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 83/1023 (records 1231-1245)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 84/1023 (records 1246-1260)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 85/1023 (records 1261-1275)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 86/1023 (records 1276-1290)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 87/1023 (records 1291-1305)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 88/1023 (records 1306-1320)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 89/1023 (records 1321-1335)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 90/1023 (records 1336-1350)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 91/1023 (records 1351-1365)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 92/1023 (records 1366-1380)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 93/1023 (records 1381-1395)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 94/1023 (records 1396-1410)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 95/1023 (records 1411-1425)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 96/1023 (records 1426-1440)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 97/1023 (records 1441-1455)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 98/1023 (records 1456-1470)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 99/1023 (records 1471-1485)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 100/1023 (records 1486-1500)
  ✅ S6 SAVED at batch 100
Waiting 0 seconds before next S6 batch...

Processing S6 batch 101/1023 (records 1501-1515)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 102/1023 (records 1516-1530)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 103/1023 (records 1531-1545)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 104/1023 (records 1546-1560)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 105/1023 (records 1561-1575)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 106/1023 (records 1576-1590)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 107/1023 (records 1591-1605)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 108/1023 (records 1606-1620)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 109/1023 (records 1621-1635)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 110/1023 (records 1636-1650)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 111/1023 (records 1651-1665)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 112/1023 (records 1666-1680)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 113/1023 (records 1681-1695)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 114/1023 (records 1696-1710)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 115/1023 (records 1711-1725)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 116/1023 (records 1726-1740)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 117/1023 (records 1741-1755)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 118/1023 (records 1756-1770)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 119/1023 (records 1771-1785)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 120/1023 (records 1786-1800)
  ✅ S6 SAVED at batch 120
Waiting 0 seconds before next S6 batch...

Processing S6 batch 121/1023 (records 1801-1815)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 122/1023 (records 1816-1830)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 123/1023 (records 1831-1845)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 124/1023 (records 1846-1860)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 125/1023 (records 1861-1875)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 126/1023 (records 1876-1890)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 127/1023 (records 1891-1905)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 128/1023 (records 1906-1920)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 129/1023 (records 1921-1935)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 130/1023 (records 1936-1950)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 131/1023 (records 1951-1965)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 132/1023 (records 1966-1980)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 133/1023 (records 1981-1995)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 134/1023 (records 1996-2010)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 135/1023 (records 2011-2025)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 136/1023 (records 2026-2040)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 137/1023 (records 2041-2055)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 138/1023 (records 2056-2070)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 139/1023 (records 2071-2085)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 140/1023 (records 2086-2100)
  ✅ S6 SAVED at batch 140
Waiting 0 seconds before next S6 batch...

Processing S6 batch 141/1023 (records 2101-2115)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 142/1023 (records 2116-2130)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 143/1023 (records 2131-2145)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 144/1023 (records 2146-2160)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 145/1023 (records 2161-2175)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 146/1023 (records 2176-2190)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 147/1023 (records 2191-2205)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 148/1023 (records 2206-2220)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 149/1023 (records 2221-2235)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 150/1023 (records 2236-2250)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 151/1023 (records 2251-2265)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 152/1023 (records 2266-2280)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 153/1023 (records 2281-2295)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 154/1023 (records 2296-2310)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 155/1023 (records 2311-2325)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 156/1023 (records 2326-2340)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 157/1023 (records 2341-2355)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 158/1023 (records 2356-2370)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 159/1023 (records 2371-2385)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 160/1023 (records 2386-2400)
  ✅ S6 SAVED at batch 160
Waiting 0 seconds before next S6 batch...

Processing S6 batch 161/1023 (records 2401-2415)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 162/1023 (records 2416-2430)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 163/1023 (records 2431-2445)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 164/1023 (records 2446-2460)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 165/1023 (records 2461-2475)
Waiting 0 seconds before next S6 batch...

Processing S6 batch 166/1023 (records 2476-2490)

,id,full_text,s6_refined_domain,s6_refined_method
0,101116741,Digitizing Other Economies: A Comparative Appr...,Social Sciences & Human Behavior,"Qualitative, Archival & Interpretive Research"
1,101163161,MOLECULAR QUANTUM DYNAMICS IN LOW TEMPERATURE ...,"Aerospace, Space & Astronomy","Advanced Imaging, Microscopy & Spectroscopy"
2,101160499,Multiscale modelling of aberrant phase transit...,Biological & Life Sciences,"Computational Modeling, Simulation & Optimization"
3,101166905,The first comprehensive Atlas of the Milky Way...,"Aerospace, Space & Astronomy",Astro/Space Observation & Geophysical Survey M...
4,101162875,Untapping multiparametric 2D luminescence sens...,Biomedical Engineering & Medical Technology,Artificial Intelligence & Machine Learning Met...

Top 10 S6 assigned domain categories:
- Materials Science & Engineering: 1036
- Energy Systems & Technology: 963
- Agriculture, Food & Bioresources: 911
- Biomedical Engineering & Medical Technology: 909
- Earth, Environmental & Climate Science: 891
- Humanities, Arts & Cultural Heritage: 849
- Biological & Life Sciences: 670
- Social Sciences & Human Behavior: 653
- Neuroscience, Neurology & Cognitive Science: 585
- Aerospace, Space & Astronomy: 581

Top 10 S6 assigned method categories:
- Artificial Intelligence & Machine Learning Methods: 1155
- Engineering Design, Fabrication & Prototyping: 1140
- Policy, Economic & Social Impact Analysis: 1087
- Qualitative, Archival & Interpretive Research: 1039
- Omics, Molecular & Cellular Biology Techniques: 964
- Computational Modeling, Simulation & Optimization: 950
- Quantitative, Statistical & Mathematical Modeling: 803
- Materials Synthesis, Characterization & Analysis: 707
- Experimental Design & Laboratory Techniques: 547
- Ecological & Environmental Modeling & Assessment: 528

In [154]:
# COMPLETE S6 FIX STAGE
# S6 REFINED CATEGORIES
S6_DOMAIN_CATEGORIES = [
    "Fundamental Physics & Chemistry",
    "Mathematical & Computational Sciences", 
    "Biological & Life Sciences",
    "Earth, Environmental & Climate Science",
    "Agriculture, Food & Bioresources",
    "Aerospace, Space & Astronomy",
    "Computer Science & Information Technology",
    "Artificial Intelligence & Data Science",
    "Robotics & Autonomous Systems",
    "Electrical, Electronics & Photonics Engineering",
    "Materials Science & Engineering",
    "Chemical Engineering & Applied Chemistry",
    "Mechanical & Industrial Engineering",
    "Biomedical Engineering & Medical Technology",
    "Energy Systems & Technology",
    "Transportation, Urban & Regional Development",
    "Clinical Medicine & Health Sciences",
    "Neuroscience, Neurology & Cognitive Science",
    "Microbiology, Virology & Infectious Diseases",
    "Cancer & Oncology",
    "Drug Discovery & Pharmaceutical Development",
    "Public Health, Epidemiology & Healthcare Administration",
    "Social Sciences & Human Behavior",
    "Psychology & Behavioral Science",
    "Business, Management & Economics",
    "Policy, Governance & Law",
    "Humanities, Arts & Cultural Heritage",
    "Education & Training",
    "Sustainable Development & Global Challenges",
    "Security & Defense",
    "Environmental Health & Engineering",
    "Nuclear Science & Engineering",
    "Quantum Physics & Technologies"
]

S6_METHOD_CATEGORIES = [
    "Qualitative, Archival & Interpretive Research",
    "Quantitative, Statistical & Mathematical Modeling",
    "Computational Modeling, Simulation & Optimization",
    "Artificial Intelligence & Machine Learning Methods",
    "Experimental Design & Laboratory Techniques",
    "Data Collection, Curation & Management",
    "Data Analysis, Interpretation & Visualization",
    "Engineering Design, Fabrication & Prototyping",
    "Process Engineering & Optimization",
    "Materials Synthesis, Characterization & Analysis",
    "Chemical Synthesis, Catalysis & Analytical Methods",
    "Omics, Molecular & Cellular Biology Techniques",
    "Genetic Engineering & Synthetic Biology",
    "Bioprocessing, Biomanufacturing & Bioengineering",
    "Drug Discovery, Development & Delivery Methods",
    "Clinical & Healthcare Research Methods",
    "Diagnostic, Therapeutic & Medical Technology Development",
    "Advanced Imaging, Microscopy & Spectroscopy",
    "Sensor, Monitoring & Measurement Technologies",
    "Remote Sensing, Geospatial Analysis & Mapping",
    "Ecological & Environmental Modeling & Assessment",
    "Policy, Economic & Social Impact Analysis",
    "Ethical, Legal & Societal Framework Development",
    "Neuroscience, Cognitive & Behavioral Research Methods",
    "Agricultural, Plant Science & Food System Methods",
    "Immunological & Infectious Disease Research",
    "Software Engineering, HCI & Digital System Design",
    "Cybersecurity, Network Engineering & Data Protection",
    "Lifecycle, Risk Assessment & Environmental Management",
    "Innovation, Business Development & Digital Transformation",
    "Knowledge Management, Collaboration & Dissemination",
    "Capacity Building, Education & Training Methods",
    "Quantum Computing & Technology Development",
    "Archaeological, Heritage & Conservation Methods",
    "Astro/Space Observation & Geophysical Survey Methods"
]

def find_s6_failed_projects():
    """Find the exact projects that still have non-matching S6 categories - STRICT MODE"""
    
    print("🔍 FINDING S6 FAILED PROJECTS (STRICT - NO PARSE FAILED ALLOWED)")
    print("="*60)
    
    # Load current data
    try:
        df = pd.read_csv("df_processing_checkpoint.csv")
        print(f"✅ Loaded checkpoint CSV: {df.shape}")
    except:
        df = globals()['df_complete'].copy()
        print(f"✅ Using global df_complete: {df.shape}")
    
    # STRICT: Only empty strings and None are acceptable "failures"
    # Everything else (including "Parse Failed", "API Failed", etc.) must be fixed
    acceptable_errors = ["", None]
    
    failed_projects = []
    
    for idx in df.index:
        domain = df.loc[idx, 's6_refined_domain']
        method = df.loc[idx, 's6_refined_method']
        
        # Check if domain is problematic
        domain_bad = (pd.notna(domain) and 
                     str(domain).strip() != "" and  # Not empty string
                     domain not in S6_DOMAIN_CATEGORIES)  # Not valid category
        
        # Check if method is problematic  
        method_bad = (pd.notna(method) and 
                     str(method).strip() != "" and  # Not empty string
                     method not in S6_METHOD_CATEGORIES)  # Not valid category
        
        if domain_bad or method_bad:
            project_id = df.loc[idx, 'id'] if 'id' in df.columns else idx
            failed_projects.append({
                'index': idx,
                'id': project_id,
                'domain': domain,
                'method': method,
                'domain_bad': domain_bad,
                'method_bad': method_bad,
                'summary': str(df.loc[idx, 'full_text'])[:200] + "..."
            })
    
    print(f"Found {len(failed_projects)} projects with invalid S6 categories")
    
    # Group by bad categories to see patterns
    if failed_projects:
        domain_issues = {}
        method_issues = {}
        
        for proj in failed_projects:
            if proj['domain_bad']:
                domain = str(proj['domain'])
                if domain not in domain_issues:
                    domain_issues[domain] = []
                domain_issues[domain].append(proj['index'])
            
            if proj['method_bad']:
                method = str(proj['method'])
                if method not in method_issues:
                    method_issues[method] = []
                method_issues[method].append(proj['index'])
        
        print(f"\n❌ ALL PROBLEMATIC S6 DOMAINS (including Parse Failed, API Failed, etc.):")
        for domain, indices in domain_issues.items():
            print(f"  '{domain}': {len(indices)} projects")
        
        print(f"\n❌ ALL PROBLEMATIC S6 METHODS (including Parse Failed, API Failed, etc.):")
        for method, indices in method_issues.items():
            print(f"  '{method}': {len(indices)} projects")
    
    return failed_projects, df

def fix_s6_failed_projects_no_parse_failed(failed_projects, df, model):
    """Fix S6 projects - return empty strings instead of failure messages"""
    
    if not failed_projects:
        print("✅ No S6 failed projects to fix!")
        return df
    
    print(f"🔧 S6 FIXING - {len(failed_projects)} PROJECTS (NO PARSE FAILED ALLOWED)")
    print("="*60)
    
    # Enhanced prompt for problem cases
    TARGETED_S6_PROMPT = """You are an expert research taxonomist. You must classify these projects using ONLY the exact categories from the lists below.

CRITICAL RULES:
1. Select EXACTLY ONE domain from the Domain list for each project
2. Select EXACTLY ONE method from the Method list for each project  
3. Use the EXACT spelling, punctuation, and capitalization shown
4. DO NOT create new categories or modify existing ones
5. DO NOT confuse domains with methods

DOMAIN AREAS (Scientific/Technical Fields - choose ONE per project):
{domain_list}

METHOD AREAS (Research Approaches/Techniques - choose ONE per project):
{method_list}

PROJECTS TO CLASSIFY:
{project_summaries}

RESPOND IN THIS EXACT FORMAT:
Project 1:
Domain Area: [EXACT match from Domain list above]
Method Area: [EXACT match from Method list above]

Project 2:
Domain Area: [EXACT match from Domain list above]
Method Area: [EXACT match from Method list above]

... continue for all projects ...

Remember: Domain = WHAT field/area, Method = HOW it's done."""

    changes_made = []
    df_working = df.copy()
    
    # Process 6 projects at a time
    batch_size = 6
    total_batches = (len(failed_projects) + batch_size - 1) // batch_size
    
    for batch_num in range(total_batches):
        start_idx = batch_num * batch_size
        end_idx = min(start_idx + batch_size, len(failed_projects))
        batch_projects = failed_projects[start_idx:end_idx]
        
        print(f"\n--- S6 Batch {batch_num+1}/{total_batches} ({len(batch_projects)} projects) ---")
        
        # Show what we're fixing
        for i, proj in enumerate(batch_projects):
            print(f"  Project {i+1} (ID {proj['id']}, Index {proj['index']}):")
            print(f"    Current Domain: '{proj['domain']}' {'❌' if proj['domain_bad'] else '✅'}")
            print(f"    Current Method: '{proj['method']}' {'❌' if proj['method_bad'] else '✅'}")
        
        # Prepare batch summaries
        project_summaries = ""
        for i, proj in enumerate(batch_projects, 1):
            project_text = str(df_working.loc[proj['index'], 'full_text'])[:1200]  # Limit length
            project_summaries += f"Project {i}:\nTitle and Description: {project_text}\n\n"
        
        # Create focused prompt
        prompt = TARGETED_S6_PROMPT.format(
            domain_list="\n".join(S6_DOMAIN_CATEGORIES),
            method_list="\n".join(S6_METHOD_CATEGORIES),
            project_summaries=project_summaries
        )
        
        # Try to get results from LLM
        batch_success = False
        try:
            print(f"🤖 Calling LLM for batch {batch_num+1}...")
            
            response = model.generate_content(prompt)
            output = response.text.strip()
            
            print(f"✅ Got LLM response, parsing...")
            
            # Parse results for the batch
            project_blocks = re.split(r'Project \d+:', output)
            if project_blocks and not project_blocks[0].strip():
                project_blocks = project_blocks[1:]
            
            if len(project_blocks) >= len(batch_projects):
                batch_results = []
                
                for i, block in enumerate(project_blocks[:len(batch_projects)]):
                    new_domain = ""  # Default to EMPTY instead of "Parse Failed"
                    new_method = ""  # Default to EMPTY instead of "Parse Failed"
                    
                    lines = block.strip().split('\n')
                    for line in lines:
                        line = line.strip()
                        if line.startswith("Domain Area:"):
                            candidate = line.replace("Domain Area:", "").strip()
                            candidate = candidate.strip('"\'- ')
                            # Only assign if it's actually in our valid list
                            if candidate in S6_DOMAIN_CATEGORIES:
                                new_domain = candidate
                        elif line.startswith("Method Area:"):
                            candidate = line.replace("Method Area:", "").strip()
                            candidate = candidate.strip('"\'- ')
                            # Only assign if it's actually in our valid list
                            if candidate in S6_METHOD_CATEGORIES:
                                new_method = candidate
                    
                    batch_results.append({
                        'domain': new_domain,
                        'method': new_method
                    })
                
                # Apply all results in this batch
                for i, result in enumerate(batch_results):
                    proj = batch_projects[i]
                    idx = proj['index']
                    
                    old_domain = df_working.loc[idx, 's6_refined_domain']
                    old_method = df_working.loc[idx, 's6_refined_method']
                    
                    # Only update categories that were actually problematic
                    if proj['domain_bad']:
                        df_working.loc[idx, 's6_refined_domain'] = result['domain']
                        print(f"  🔄 Fixed Domain {idx}: '{old_domain}' → '{result['domain']}'")
                    
                    if proj['method_bad']:
                        df_working.loc[idx, 's6_refined_method'] = result['method']
                        print(f"  🔄 Fixed Method {idx}: '{old_method}' → '{result['method']}'")
                    
                    changes_made.append({
                        'index': idx,
                        'id': proj['id'],
                        'old_domain': old_domain,
                        'new_domain': result['domain'] if proj['domain_bad'] else old_domain,
                        'old_method': old_method,
                        'new_method': result['method'] if proj['method_bad'] else old_method
                    })
                
                batch_success = True
                print(f"  ✅ Batch {batch_num+1} processed successfully")
            else:
                print(f"  ⚠️ Got {len(project_blocks)} project blocks, expected {len(batch_projects)}")
                
        except Exception as e:
            print(f"  ❌ LLM error for batch {batch_num+1}: {e}")
        
        if not batch_success:
            print(f"  🔄 Batch {batch_num+1} failed - setting empty strings for problematic categories")
            # Set empty strings for failed attempts (so they get caught in next iteration)
            for proj in batch_projects:
                idx = proj['index']
                if proj['domain_bad']:
                    df_working.loc[idx, 's6_refined_domain'] = ""
                    print(f"    Set domain to empty for index {idx}")
                if proj['method_bad']:
                    df_working.loc[idx, 's6_refined_method'] = ""
                    print(f"    Set method to empty for index {idx}")
        
        # Small delay between batches
        if batch_num < total_batches - 1:
            time.sleep(3)
    
    print(f"\n💾 SAVING S6 FIXES")
    print("="*60)
    
    # Save back to CSV
    df_working.to_csv("df_processing_checkpoint.csv", index=False)
    print(f"✅ Saved to df_processing_checkpoint.csv")
    
    # Update global if possible
    try:
        globals()['df_complete'] = df_working.copy()
        print(f"✅ Updated global df_complete")
    except:
        pass
    
    print(f"\n📊 S6 FIX SUMMARY:")
    print(f"   Failed projects processed: {len(failed_projects)}")
    print(f"   Batches processed: {total_batches}")
    print(f"   Changes attempted: {len(changes_made)}")
    
    return df_working

def run_s6_complete_fix():
    """Main function to run complete S6 fixes until everything is clean"""
    
    print("🎯 S6 COMPLETE FIX - NO PARSE FAILED ALLOWED")
    print("="*80)
    
    # Get model
    try:
        model = globals()['model']
        print(f"✅ Using global model")
    except:
        print("❌ ERROR: Global 'model' not found")
        return None
    
    # Keep running fix iterations until no more failures
    max_iterations = 5
    
    for iteration in range(max_iterations):
        print(f"\n🔄 S6 FIX ITERATION {iteration + 1}/{max_iterations}")
        print("="*60)
        
        # Step 1: Find failed projects (strict mode)
        failed_projects, df = find_s6_failed_projects()
        
        if not failed_projects:
            print(f"🎉 S6 COMPLETE - No more failed projects after {iteration + 1} iteration(s)!")
            break
        
        print(f"📋 Found {len(failed_projects)} projects that need fixing")
        
        # Step 2: Apply fixes
        df = fix_s6_failed_projects_no_parse_failed(failed_projects, df, model)
        
        # Step 3: Show progress
        print(f"\n📊 Iteration {iteration + 1} complete")
        
        if iteration == max_iterations - 1:
            print(f"⚠️ Reached maximum iterations ({max_iterations})")
            print(f"   Some projects may still need manual review")
    
    # Final verification
    print(f"\n🔍 FINAL S6 VERIFICATION")
    print("="*60)
    
    final_failed, df_final = find_s6_failed_projects()
    
    domain_matches = sum(1 for d in df_final['s6_refined_domain'] if d in S6_DOMAIN_CATEGORIES)
    method_matches = sum(1 for m in df_final['s6_refined_method'] if m in S6_METHOD_CATEGORIES)
    empty_domains = sum(1 for d in df_final['s6_refined_domain'] if pd.isna(d) or str(d).strip() == "")
    empty_methods = sum(1 for m in df_final['s6_refined_method'] if pd.isna(m) or str(m).strip() == "")
    total_projects = len(df_final)
    
    print(f"📊 FINAL S6 STATISTICS:")
    print(f"   Total projects: {total_projects}")
    print(f"   Valid domain categories: {domain_matches} ({domain_matches/total_projects*100:.2f}%)")
    print(f"   Valid method categories: {method_matches} ({method_matches/total_projects*100:.2f}%)")
    print(f"   Empty domains (acceptable): {empty_domains} ({empty_domains/total_projects*100:.2f}%)")
    print(f"   Empty methods (acceptable): {empty_methods} ({empty_methods/total_projects*100:.2f}%)")
    print(f"   Remaining problematic projects: {len(final_failed)}")
    
    if len(final_failed) == 0:
        print(f"\n🎉🎉🎉 PERFECT! 100% S6 SUCCESS - NO MORE PARSE FAILED! 🎉🎉🎉")
    else:
        print(f"\n⚠️ Still have {len(final_failed)} projects with invalid categories:")
        # Show first few remaining problems
        for proj in final_failed[:5]:
            print(f"   - Index {proj['index']}: Domain='{proj['domain']}', Method='{proj['method']}'")
        
        if len(final_failed) > 5:
            print(f"   ... and {len(final_failed) - 5} more")
    
    print(f"\n🎯 S6 COMPLETE FIX FINISHED!")
    
    return df_final

# Usage
df_s6_clean = run_s6_complete_fix()

🎯 S6 TARGETED FAILED PROJECT FIXER
================================================================================
🔍 FINDING S6 FAILED PROJECTS
============================================================
✅ Loaded checkpoint CSV: (15341, 14)
Found 100 projects with bad S6 categories

❌ PROBLEMATIC S6 DOMAINS:
  'Bioprocessing, Biomanufacturing & Bioengineering': 11 projects
  'Cybersecurity, Network Engineering & Data Protection': 11 projects
  'Archaeological, Heritage & Conservation Methods': 9 projects
  'Archaeological, Heritage & Cultural Heritage': 4 projects
  'Immunological & Infectious Disease Research': 12 projects
  'Immunology & Infectious Disease Research': 3 projects
  'Genetic Engineering & Synthetic Biology': 7 projects
  'Cybersecurity & Defense': 1 projects
  'Environmental Science & Climate Science': 1 projects

❌ PROBLEMATIC S6 METHODS:
  'Robotics & Autonomous Systems': 30 projects
  'Social Sciences & Human Behavior': 3 projects
  'Public Health, Epidemiology & Healthcare Administration': 1 projects
  'Mathematical & Computational Sciences': 4 projects
  'Biological & Life Sciences': 1 projects
  'Electrical, Electronics & Photonics Engineering': 1 projects
  'Microbiology, Virology & Infectious Diseases': 1 projects
  'Biomedical Engineering & Medical Technology': 1 projects
✅ Using global model
🔧 TARGETED S6 FIXING - 100 PROJECTS (batches of 6)
============================================================

--- S6 Targeted Batch 1/17 (6 projects) ---
  Project 1 (ID 101168489, Index 292):
    Domain: 'Security & Defense' ✅
    Method: 'Robotics & Autonomous Systems' ❌
  Project 2 (ID 101093150, Index 483):
    Domain: 'Bioprocessing, Biomanufacturing & Bioengineering' ❌
    Method: 'Sensor, Monitoring & Measurement Technologies' ✅
  Project 3 (ID 101132575, Index 500):
    Domain: 'Humanities, Arts & Cultural Heritage' ✅
    Method: 'Robotics & Autonomous Systems' ❌
  Project 4 (ID 101070008, Index 889):
    Domain: 'Cybersecurity, Network Engineering & Data Protection' ❌
    Method: 'Software Engineering, HCI & Digital System Design' ✅
  Project 5 (ID 101168315, Index 968):
    Domain: 'Public Health, Epidemiology & Healthcare Administration' ✅
    Method: 'Social Sciences & Human Behavior' ❌
  Project 6 (ID 101070537, Index 1230):
    Domain: 'Cybersecurity, Network Engineering & Data Protection' ❌
    Method: 'Software Engineering, HCI & Digital System Design' ✅
🤖 Batch targeted attempt 1...
Raw LLM output preview: Project 1:
Domain Area: Robotics & Autonomous Systems
Method Area: Engineering Design, Fabrication & Prototyping

Project 2:
Domain Area: Biomedical Engineering & Medical Technology
Method Area: Diagnostic, Therapeutic & Medical Technology Development

Project 3:
Domain Area: Robotics & Autonomous S...
    ✅ Project 1: Both categories valid
    ✅ Project 2: Both categories valid
    ✅ Project 3: Both categories valid
    ✅ Project 4: Both categories valid
    ✅ Project 5: Both categories valid
    ✅ Project 6: Both categories valid
  ✅ FIXED Index 292: Domain 'Security & Defense' → 'Robotics & Autonomous Systems'
  ✅ FIXED Index 292: Method 'Robotics & Autonomous Systems' → 'Engineering Design, Fabrication & Prototyping'
  ✅ FIXED Index 483: Domain 'Bioprocessing, Biomanufacturing & Bioengineering' → 'Biomedical Engineering & Medical Technology'
  ✅ FIXED Index 483: Method 'Sensor, Monitoring & Measurement Technologies' → 'Diagnostic, Therapeutic & Medical Technology Development'
  ✅ FIXED Index 500: Domain 'Humanities, Arts & Cultural Heritage' → 'Robotics & Autonomous Systems'
  ✅ FIXED Index 500: Method 'Robotics & Autonomous Systems' → 'Remote Sensing, Geospatial Analysis & Mapping'
  ✅ FIXED Index 889: Domain 'Cybersecurity, Network Engineering & Data Protection' → 'Computer Science & Information Technology'
  ✅ FIXED Index 889: Method 'Software Engineering, HCI & Digital System Design' → 'Software Engineering, HCI & Digital System Design'
  ✅ FIXED Index 968: Domain 'Public Health, Epidemiology & Healthcare Administration' → 'Social Sciences & Human Behavior'
  ✅ FIXED Index 968: Method 'Social Sciences & Human Behavior' → 'Policy, Economic & Social Impact Analysis'
  ✅ FIXED Index 1230: Domain 'Cybersecurity, Network Engineering & Data Protection' → 'Computer Science & Information Technology'
  ✅ FIXED Index 1230: Method 'Software Engineering, HCI & Digital System Design' → 'Software Engineering, HCI & Digital System Design'

--- S6 Targeted Batch 2/17 (6 projects) ---
  Project 1 (ID 101104432, Index 2069):
    Domain: 'Cancer & Oncology' ✅
    Method: 'Public Health, Epidemiology & Healthcare Administration' ❌
  Project 2 (ID 101168438, Index 2281):
    Domain: 'Cybersecurity, Network Engineering & Data Protection' ❌
    Method: 'Artificial Intelligence & Machine Learning Methods' ✅
  Project 3 (ID 101070558, Index 2401):
    Domain: 'Quantum Physics & Technologies' ✅
    Method: 'Mathematical & Computational Sciences' ❌
  Project 4 (ID 101134051, Index 2659):
    Domain: 'Agriculture, Food & Bioresources' ✅
    Method: 'Social Sciences & Human Behavior' ❌
  Project 5 (ID 101167964, Index 2756):
    Domain: 'Cybersecurity, Network Engineering & Data Protection' ❌
    Method: 'Software Engineering, HCI & Digital System Design' ✅
  Project 6 (ID 101136056, Index 2763):
    Domain: 'Mechanical & Industrial Engineering' ✅
    Method: 'Robotics & Autonomous Systems' ❌
🤖 Batch targeted attempt 1...
Raw LLM output preview: Project 1:
Domain Area: Cancer & Oncology
Method Area: Clinical & Healthcare Research Methods

Project 2:
Domain Area: Computer Science & Information Technology
Method Area: Cybersecurity, Network Engineering & Data Protection

Project 3:
Domain Area: Quantum Physics & Technologies
Method Area: Quan...
    ✅ Project 1: Both categories valid
    ✅ Project 2: Both categories valid
    ✅ Project 3: Both categories valid
    ✅ Project 4: Both categories valid
    ✅ Project 5: Both categories valid
    ✅ Project 6: Both categories valid
  ✅ FIXED Index 2069: Domain 'Cancer & Oncology' → 'Cancer & Oncology'
  ✅ FIXED Index 2069: Method 'Public Health, Epidemiology & Healthcare Administration' → 'Clinical & Healthcare Research Methods'
  ✅ FIXED Index 2281: Domain 'Cybersecurity, Network Engineering & Data Protection' → 'Computer Science & Information Technology'
  ✅ FIXED Index 2281: Method 'Artificial Intelligence & Machine Learning Methods' → 'Cybersecurity, Network Engineering & Data Protection'
  ✅ FIXED Index 2401: Domain 'Quantum Physics & Technologies' → 'Quantum Physics & Technologies'
  ✅ FIXED Index 2401: Method 'Mathematical & Computational Sciences' → 'Quantum Computing & Technology Development'
  ✅ FIXED Index 2659: Domain 'Agriculture, Food & Bioresources' → 'Agriculture, Food & Bioresources'
  ✅ FIXED Index 2659: Method 'Social Sciences & Human Behavior' → 'Neuroscience, Cognitive & Behavioral Research Methods'
  ✅ FIXED Index 2756: Domain 'Cybersecurity, Network Engineering & Data Protection' → 'Computer Science & Information Technology'
  ✅ FIXED Index 2756: Method 'Software Engineering, HCI & Digital System Design' → 'Cybersecurity, Network Engineering & Data Protection'
  ✅ FIXED Index 2763: Domain 'Mechanical & Industrial Engineering' → 'Environmental Health & Engineering'
  ✅ FIXED Index 2763: Method 'Robotics & Autonomous Systems' → 'Lifecycle, Risk Assessment & Environmental Management'

--- S6 Targeted Batch 3/17 (6 projects) ---
  Project 1 (ID 101189723, Index 2769):
    Domain: 'Energy Systems & Technology' ✅
    Method: 'Robotics & Autonomous Systems' ❌
  Project 2 (ID 101121258, Index 2830):
    Domain: 'Security & Defense' ✅
    Method: 'Robotics & Autonomous Systems' ❌
  Project 3 (ID 101182923, Index 2929):
    Domain: 'Agriculture, Food & Bioresources' ✅
    Method: 'Robotics & Autonomous Systems' ❌
  Project 4 (ID 101182299, Index 3251):
    Domain: 'Agriculture, Food & Bioresources' ✅
    Method: 'Social Sciences & Human Behavior' ❌
  Project 5 (ID 101070281, Index 3315):
    Domain: 'Bioprocessing, Biomanufacturing & Bioengineering' ❌
    Method: 'Artificial Intelligence & Machine Learning Methods' ✅
  Project 6 (ID 101094287, Index 3327):
    Domain: 'Bioprocessing, Biomanufacturing & Bioengineering' ❌
    Method: 'Artificial Intelligence & Machine Learning Methods' ✅
🤖 Batch targeted attempt 1...
Raw LLM output preview: Project 1:
Domain Area: Robotics & Autonomous Systems
Method Area: Engineering Design, Fabrication & Prototyping

Project 2:
Domain Area: Security & Defense
Method Area: Sensor, Monitoring & Measurement Technologies

Project 3:
Domain Area: Agriculture, Food & Bioresources
Method Area: Agricultural,...
    ✅ Project 1: Both categories valid
    ✅ Project 2: Both categories valid
    ✅ Project 3: Both categories valid
    ✅ Project 4: Both categories valid
    ❌ Project 5: Domain ❌, Method ✅
    ❌ Project 6: Domain ❌, Method ✅
❌ Some projects in batch still invalid after attempt 1
🤖 Batch targeted attempt 2...
Raw LLM output preview: Project 1:
Domain Area: Robotics & Autonomous Systems
Method Area: Engineering Design, Fabrication & Prototyping

Project 2:
Domain Area: Security & Defense
Method Area: Sensor, Monitoring & Measurement Technologies

Project 3:
Domain Area: Agriculture, Food & Bioresources
Method Area: Agricultural,...
    ✅ Project 1: Both categories valid
    ✅ Project 2: Both categories valid
    ✅ Project 3: Both categories valid
    ✅ Project 4: Both categories valid
    ❌ Project 5: Domain ❌, Method ✅
    ❌ Project 6: Domain ❌, Method ✅
❌ Some projects in batch still invalid after attempt 2
🤖 Batch targeted attempt 3...
Raw LLM output preview: Project 1:
Domain Area: Robotics & Autonomous Systems
Method Area: Engineering Design, Fabrication & Prototyping

Project 2:
Domain Area: Security & Defense
Method Area: Engineering Design, Fabrication & Prototyping

Project 3:
Domain Area: Agriculture, Food & Bioresources
Method Area: Agricultural,...
    ✅ Project 1: Both categories valid
    ✅ Project 2: Both categories valid
    ✅ Project 3: Both categories valid
    ✅ Project 4: Both categories valid
    ❌ Project 5: Domain ❌, Method ✅
    ❌ Project 6: Domain ❌, Method ✅
❌ Some projects in batch still invalid after attempt 3
💥 FAILED to fix batch 3 after all attempts - marking all as 'S6 Fix Failed'

--- S6 Targeted Batch 4/17 (6 projects) ---
  Project 1 (ID 101131085, Index 3331):
    Domain: 'Bioprocessing, Biomanufacturing & Bioengineering' ❌
    Method: 'Policy, Economic & Social Impact Analysis' ✅
  Project 2 (ID 101062179, Index 3508):
    Domain: 'Archaeological, Heritage & Conservation Methods' ❌
    Method: 'Omics, Molecular & Cellular Biology Techniques' ✅
  Project 3 (ID 101062307, Index 3550):
    Domain: 'Archaeological, Heritage & Conservation Methods' ❌
    Method: 'Archaeological, Heritage & Conservation Methods' ✅
  Project 4 (ID 101073056, Index 4203):
    Domain: 'Bioprocessing, Biomanufacturing & Bioengineering' ❌
    Method: 'Biological & Life Sciences' ❌
  Project 5 (ID 101152277, Index 4225):
    Domain: 'Archaeological, Heritage & Conservation Methods' ❌
    Method: 'Materials Synthesis, Characterization & Analysis' ✅
  Project 6 (ID 101152630, Index 5028):
    Domain: 'Archaeological, Heritage & Conservation Methods' ❌
    Method: 'Chemical Synthesis, Catalysis & Analytical Methods' ✅
🤖 Batch targeted attempt 1...
Raw LLM output preview: Project 1:
Domain Area: Policy, Governance & Law
Method Area: Ethical, Legal & Societal Framework Development

Project 2:
Domain Area: Humanities, Arts & Cultural Heritage
Method Area: Archaeological, Heritage & Conservation Methods

Project 3:
Domain Area: Social Sciences & Human Behavior
Method Ar...
    ✅ Project 1: Both categories valid
    ✅ Project 2: Both categories valid
    ✅ Project 3: Both categories valid
    ✅ Project 4: Both categories valid
    ✅ Project 5: Both categories valid
    ✅ Project 6: Both categories valid
  ✅ FIXED Index 3331: Domain 'Bioprocessing, Biomanufacturing & Bioengineering' → 'Policy, Governance & Law'
  ✅ FIXED Index 3331: Method 'Policy, Economic & Social Impact Analysis' → 'Ethical, Legal & Societal Framework Development'
  ✅ FIXED Index 3508: Domain 'Archaeological, Heritage & Conservation Methods' → 'Humanities, Arts & Cultural Heritage'
  ✅ FIXED Index 3508: Method 'Omics, Molecular & Cellular Biology Techniques' → 'Archaeological, Heritage & Conservation Methods'
  ✅ FIXED Index 3550: Domain 'Archaeological, Heritage & Conservation Methods' → 'Social Sciences & Human Behavior'
  ✅ FIXED Index 3550: Method 'Archaeological, Heritage & Conservation Methods' → 'Archaeological, Heritage & Conservation Methods'
  ✅ FIXED Index 4203: Domain 'Bioprocessing, Biomanufacturing & Bioengineering' → 'Chemical Engineering & Applied Chemistry'
  ✅ FIXED Index 4203: Method 'Biological & Life Sciences' → 'Bioprocessing, Biomanufacturing & Bioengineering'
  ✅ FIXED Index 4225: Domain 'Archaeological, Heritage & Conservation Methods' → 'Humanities, Arts & Cultural Heritage'
  ✅ FIXED Index 4225: Method 'Materials Synthesis, Characterization & Analysis' → 'Archaeological, Heritage & Conservation Methods'
  ✅ FIXED Index 5028: Domain 'Archaeological, Heritage & Conservation Methods' → 'Chemical Engineering & Applied Chemistry'
  ✅ FIXED Index 5028: Method 'Chemical Synthesis, Catalysis & Analytical Methods' → 'Chemical Synthesis, Catalysis & Analytical Methods'

--- S6 Targeted Batch 5/17 (6 projects) ---
  Project 1 (ID 101151285, Index 5029):
    Domain: 'Archaeological, Heritage & Conservation Methods' ❌
    Method: 'Remote Sensing, Geospatial Analysis & Mapping' ✅
  Project 2 (ID 101169042, Index 5065):
    Domain: 'Aerospace, Space & Astronomy' ✅
    Method: 'Electrical, Electronics & Photonics Engineering' ❌
  Project 3 (ID 101147067, Index 5158):
    Domain: 'Archaeological, Heritage & Cultural Heritage' ❌
    Method: 'Archaeological, Heritage & Conservation Methods' ✅
  Project 4 (ID 101153375, Index 5241):
    Domain: 'Archaeological, Heritage & Cultural Heritage' ❌
    Method: 'Archaeological, Heritage & Conservation Methods' ✅
  Project 5 (ID 101063886, Index 5277):
    Domain: 'Immunological & Infectious Disease Research' ❌
    Method: 'Omics, Molecular & Cellular Biology Techniques' ✅
  Project 6 (ID 101150963, Index 5493):
    Domain: 'Immunology & Infectious Disease Research' ❌
    Method: 'Omics, Molecular & Cellular Biology Techniques' ✅
🤖 Batch targeted attempt 1...
Raw LLM output preview: Project 1:
Domain Area: Humanities, Arts & Cultural Heritage
Method Area: Archaeological, Heritage & Conservation Methods

Project 2:
Domain Area: Electrical, Electronics & Photonics Engineering
Method Area: Engineering Design, Fabrication & Prototyping

Project 3:
Domain Area: Humanities, Arts & Cu...
    ✅ Project 1: Both categories valid
    ✅ Project 2: Both categories valid
    ✅ Project 3: Both categories valid
    ✅ Project 4: Both categories valid
    ✅ Project 5: Both categories valid
    ✅ Project 6: Both categories valid
  ✅ FIXED Index 5029: Domain 'Archaeological, Heritage & Conservation Methods' → 'Humanities, Arts & Cultural Heritage'
  ✅ FIXED Index 5029: Method 'Remote Sensing, Geospatial Analysis & Mapping' → 'Archaeological, Heritage & Conservation Methods'
  ✅ FIXED Index 5065: Domain 'Aerospace, Space & Astronomy' → 'Electrical, Electronics & Photonics Engineering'
  ✅ FIXED Index 5065: Method 'Electrical, Electronics & Photonics Engineering' → 'Engineering Design, Fabrication & Prototyping'
  ✅ FIXED Index 5158: Domain 'Archaeological, Heritage & Cultural Heritage' → 'Humanities, Arts & Cultural Heritage'
  ✅ FIXED Index 5158: Method 'Archaeological, Heritage & Conservation Methods' → 'Archaeological, Heritage & Conservation Methods'
  ✅ FIXED Index 5241: Domain 'Archaeological, Heritage & Cultural Heritage' → 'Humanities, Arts & Cultural Heritage'
  ✅ FIXED Index 5241: Method 'Archaeological, Heritage & Conservation Methods' → 'Archaeological, Heritage & Conservation Methods'
  ✅ FIXED Index 5277: Domain 'Immunological & Infectious Disease Research' → 'Biological & Life Sciences'
  ✅ FIXED Index 5277: Method 'Omics, Molecular & Cellular Biology Techniques' → 'Omics, Molecular & Cellular Biology Techniques'
  ✅ FIXED Index 5493: Domain 'Immunology & Infectious Disease Research' → 'Clinical Medicine & Health Sciences'
  ✅ FIXED Index 5493: Method 'Omics, Molecular & Cellular Biology Techniques' → 'Omics, Molecular & Cellular Biology Techniques'

--- S6 Targeted Batch 6/17 (6 projects) ---
  Project 1 (ID 101126229, Index 6241):
    Domain: 'Computer Science & Information Technology' ✅
    Method: 'Mathematical & Computational Sciences' ❌
  Project 2 (ID 101075451, Index 6640):
    Domain: 'Archaeological, Heritage & Cultural Heritage' ❌
    Method: 'Remote Sensing, Geospatial Analysis & Mapping' ✅
  Project 3 (ID 101138301, Index 6663):
    Domain: 'Biomedical Engineering & Medical Technology' ✅
    Method: 'Robotics & Autonomous Systems' ❌
  Project 4 (ID 101054341, Index 6762):
    Domain: 'Genetic Engineering & Synthetic Biology' ❌
    Method: 'Genetic Engineering & Synthetic Biology' ✅
  Project 5 (ID 101055157, Index 6798):
    Domain: 'Immunology & Infectious Disease Research' ❌
    Method: 'Omics, Molecular & Cellular Biology Techniques' ✅
  Project 6 (ID 101158350, Index 7022):
    Domain: 'Cybersecurity, Network Engineering & Data Protection' ❌
    Method: 'Software Engineering, HCI & Digital System Design' ✅
🤖 Batch targeted attempt 1...
Raw LLM output preview: Project 1:
Domain Area: Computer Science & Information Technology
Method Area: Quantitative, Statistical & Mathematical Modeling

Project 2:
Domain Area: Humanities, Arts & Cultural Heritage
Method Area: Materials Synthesis, Characterization & Analysis

Project 3:
Domain Area: Biomedical Engineering...
    ✅ Project 1: Both categories valid
    ✅ Project 2: Both categories valid
    ✅ Project 3: Both categories valid
    ✅ Project 4: Both categories valid
    ✅ Project 5: Both categories valid
    ❌ Project 6: Domain ❌, Method ✅
❌ Some projects in batch still invalid after attempt 1
🤖 Batch targeted attempt 2...
Raw LLM output preview: Project 1:
Domain Area: Mathematical & Computational Sciences
Method Area: Quantitative, Statistical & Mathematical Modeling

Project 2:
Domain Area: Humanities, Arts & Cultural Heritage
Method Area: Archaeological, Heritage & Conservation Methods

Project 3:
Domain Area: Cancer & Oncology
Method Ar...
    ✅ Project 1: Both categories valid
    ✅ Project 2: Both categories valid
    ✅ Project 3: Both categories valid
    ✅ Project 4: Both categories valid
    ✅ Project 5: Both categories valid
    ✅ Project 6: Both categories valid
  ✅ FIXED Index 6241: Domain 'Computer Science & Information Technology' → 'Mathematical & Computational Sciences'
  ✅ FIXED Index 6241: Method 'Mathematical & Computational Sciences' → 'Quantitative, Statistical & Mathematical Modeling'
  ✅ FIXED Index 6640: Domain 'Archaeological, Heritage & Cultural Heritage' → 'Humanities, Arts & Cultural Heritage'
  ✅ FIXED Index 6640: Method 'Remote Sensing, Geospatial Analysis & Mapping' → 'Archaeological, Heritage & Conservation Methods'
  ✅ FIXED Index 6663: Domain 'Biomedical Engineering & Medical Technology' → 'Cancer & Oncology'
  ✅ FIXED Index 6663: Method 'Robotics & Autonomous Systems' → 'Diagnostic, Therapeutic & Medical Technology Development'
  ✅ FIXED Index 6762: Domain 'Genetic Engineering & Synthetic Biology' → 'Biological & Life Sciences'
  ✅ FIXED Index 6762: Method 'Genetic Engineering & Synthetic Biology' → 'Genetic Engineering & Synthetic Biology'
  ✅ FIXED Index 6798: Domain 'Immunology & Infectious Disease Research' → 'Microbiology, Virology & Infectious Diseases'
  ✅ FIXED Index 6798: Method 'Omics, Molecular & Cellular Biology Techniques' → 'Omics, Molecular & Cellular Biology Techniques'
  ✅ FIXED Index 7022: Domain 'Cybersecurity, Network Engineering & Data Protection' → 'Security & Defense'

In [158]:
# S7 FINAL CONSOLIDATED CATEGORIES 
S7_DOMAIN_CATEGORIES = [
    "Health, Medicine & Life Sciences",
    "Physical, Mathematical & Space Sciences", 
    "Engineering, Manufacturing & Technology",
    "Information, Computation & Digital Systems",
    "Environment, Climate & Earth Systems",
    "Economy, Business & Agriculture",
    "Society, Culture & Human Behavior",
    "Humanities, Arts & Cultural Heritage",
    "Policy, Governance & Law",
    "Education & Learning Systems",
    "Global Development & Sustainability"
]

S7_METHOD_CATEGORIES = [
    "Data Analysis, Modeling & Computational Methods",
    "Qualitative, Social Inquiry & Policy Research",
    "Engineering Design, Prototyping & Systems Development",
    "Experimental, Laboratory & Field Investigation",
    "Material, Chemical & Bioprocess Development",
    "Imaging, Sensing & Measurement Techniques",
    "Clinical, Health & Therapeutic Development Methods",
    "Communication, Collaboration & Knowledge Exchange",
    "Innovation, Strategic Management & Evaluation",
    "Educational, Human-Centered & Training Methods"
]

print(f"🎯 S7 FINAL CONSOLIDATED CATEGORIES LOADED")
print(f"   Domains: {len(S7_DOMAIN_CATEGORIES)} categories")
print(f"   Methods: {len(S7_METHOD_CATEGORIES)} categories")

# S7 Classification Prompt - Enhanced for the highly consolidated taxonomy
S7_BATCH_CLASSIFY_PROMPT = """You are an expert taxonomist specializing in research project classification. Your task is to classify multiple research project summaries using a highly consolidated taxonomy system.

You must assign each project exactly ONE domain area and ONE method area from the provided lists.

DOMAIN AREAS (11 broad categories - WHAT field/application the project focuses on):
{domain_categories}

METHOD AREAS (10 broad categories - HOW the research work is being conducted):
{method_categories}

Classification Guidelines:
1. DOMAIN SELECTION: Choose the primary field or application area that best represents the project's core focus
   - Health, Medicine & Life Sciences: Medical research, biology, biotechnology, health sciences
   - Physical, Mathematical & Space Sciences: Physics, chemistry, mathematics, astronomy, space research
   - Engineering, Manufacturing & Technology: All engineering disciplines, manufacturing, industrial technology
   - Information, Computation & Digital Systems: Computer science, IT, AI, data science, digital technology
   - Environment, Climate & Earth Systems: Environmental science, climate research, earth sciences, sustainability
   - Economy, Business & Agriculture: Economic research, business studies, agricultural sciences, food systems
   - Society, Culture & Human Behavior: Sociology, anthropology, psychology, cultural studies, social sciences
   - Humanities, Arts & Cultural Heritage: Literature, arts, history, philosophy, cultural heritage
   - Policy, Governance & Law: Public policy, governance, legal studies, political science
   - Education & Learning Systems: Educational research, pedagogy, learning sciences, training systems
   - Global Development & Sustainability: Development studies, international cooperation, sustainable development

2. METHOD SELECTION: Choose the primary approach or methodology used in the research
   - Focus on the main way the research work is being accomplished
   - Consider the core techniques, approaches, or methodologies that drive the project

3. Use EXACT spelling and capitalization as shown in the lists above
4. Select the single best match for each category - do not overthink edge cases

Projects to Classify:
{project_summaries}

Output Format:
Project 1:
Domain Area: [Selected Domain Area - must be exactly as shown in the list]
Method Area: [Selected Method Area - must be exactly as shown in the list]

Project 2:
Domain Area: [Selected Domain Area - must be exactly as shown in the list]
Method Area: [Selected Method Area - must be exactly as shown in the list]

... continue for all projects ...

Important: For each project, select only ONE domain area and ONE method area. Both must be exact matches from the provided lists."""

def s7_classify_batch(project_summaries: List[str], max_retries: int = 3) -> List[Dict[str, str]]:
    """Classify a batch of project summaries using S7 final categories"""
    
    # Format the project summaries for the prompt
    formatted_summaries = ""
    for i, summary in enumerate(project_summaries, 1):
        # Use full summaries for best results
        formatted_summaries += f"Project {i}:\n{summary}\n\n"
    
    # Create the prompt
    prompt = S7_BATCH_CLASSIFY_PROMPT.format(
        domain_categories="\n".join(S7_DOMAIN_CATEGORIES),
        method_categories="\n".join(S7_METHOD_CATEGORIES),
        project_summaries=formatted_summaries
    )
    
    # Process with model (with retries)
    output_text = ""
    for attempt in range(max_retries):
        try:
            response = model.generate_content(prompt)
            output_text = response.text
            break
        except Exception as e:
            print(f"Error on attempt {attempt + 1}: {e}")
            if attempt < max_retries - 1:
                sleep_time = 2 ** (attempt + 1)
                print(f"Retrying in {sleep_time} seconds...")
                time.sleep(sleep_time)
            else:
                print("Failed all retry attempts")
                return [{"domain": "API Failed", "method": "API Failed"} for _ in project_summaries]
    
    # Parse results
    results = []
    project_blocks = re.split(r'Project \d+:', output_text)
    
    # Skip the first item if it's empty
    if project_blocks and not project_blocks[0].strip():
        project_blocks = project_blocks[1:]
    
    # If we didn't get enough results, pad with failures
    if len(project_blocks) < len(project_summaries):
        print(f"Warning: Expected {len(project_summaries)} results but got {len(project_blocks)}")
        project_blocks.extend(["" for _ in range(len(project_summaries) - len(project_blocks))])
    
    # Process each project block
    for i, block in enumerate(project_blocks[:len(project_summaries)]):
        domain = "Parse Failed"
        method = "Parse Failed"
        
        for line in block.strip().split('\n'):
            line = line.strip()
            if line.startswith("Domain Area:"):
                domain = line.replace("Domain Area:", "").strip()
                # Clean up formatting
                domain = domain.strip('"\'- ')
            elif line.startswith("Method Area:"):
                method = line.replace("Method Area:", "").strip()
                # Clean up formatting
                method = method.strip('"\'- ')
        
        results.append({"domain": domain, "method": method})
    
    return results

def display_s7_first_batch_results(batch_summaries: List[str], batch_results: List[Dict[str, str]]):
    """Display detailed results for the first S7 batch"""
    print("\n===== S7 FIRST BATCH RESULTS =====")
    print(f"Showing results for the first batch of {len(batch_summaries)} projects")
    
    for i, result in enumerate(batch_results):
        summary = batch_summaries[i]
        domain = result["domain"]
        method = result["method"]
        
        # Truncate summary for display
        truncated_summary = summary[:150] + "..." if len(summary) > 150 else summary
        truncated_summary = truncated_summary.replace('\n', ' ')
        
        print(f"\nProject {i+1}:")
        print(f"Summary: {truncated_summary}")
        print(f"S7 Domain: {domain}")
        print(f"S7 Method: {method}")
    
    print("\n================================")

def s7_classify_dataset():
    """Process the dataset using S7 final consolidated categories"""
    
    print(f"🚀 STARTING S7 FINAL CONSOLIDATED CLASSIFICATION")
    print(f"="*80)
    print(f"Using S7 final categories:")
    print(f"  {len(S7_DOMAIN_CATEGORIES)} Domain areas (highly consolidated)")
    print(f"  {len(S7_METHOD_CATEGORIES)} Method areas (highly consolidated)")
    print(f"  Batch size: {DEFAULT_BATCH_SIZE}")
    print(f"  Trial mode: {RUN_OVERALL_TRIAL_MODE}")
    if RUN_OVERALL_TRIAL_MODE:
        print(f"  Max trial batches: {MAX_BATCHES_FOR_TRIAL}")
    
    # Initialize new S7 result columns
    df_complete['s7_final_domain'] = ""
    df_complete['s7_final_method'] = ""
    
    # Determine scope using global variables
    if RUN_OVERALL_TRIAL_MODE:
        max_rows = DEFAULT_BATCH_SIZE * MAX_BATCHES_FOR_TRIAL
        process_df = df_complete.iloc[:max_rows].copy()
        print(f"TRIAL MODE: Processing {len(process_df)} rows")
    else:
        process_df = df_complete.copy()
        print(f"FULL MODE: Processing {len(process_df)} rows")
    
    # Process in batches
    total_records = len(process_df)
    total_batches = (total_records + DEFAULT_BATCH_SIZE - 1) // DEFAULT_BATCH_SIZE
    
    for batch_num, start_idx in enumerate(range(0, total_records, DEFAULT_BATCH_SIZE)):
        end_idx = min(start_idx + DEFAULT_BATCH_SIZE, total_records)
        batch_size_actual = end_idx - start_idx
        
        print(f"\nProcessing S7 batch {batch_num + 1}/{total_batches} (records {start_idx+1}-{end_idx})")
        
        # Extract summaries for this batch
        batch_summaries = []
        for idx in range(start_idx, end_idx):
            summary = process_df.iloc[idx]['full_text']
            batch_summaries.append(summary)
        
        # Classify the batch using S7 categories
        batch_results = s7_classify_batch(batch_summaries)
        
        # Save results directly to df_complete
        for i in range(batch_size_actual):
            original_idx = process_df.index[start_idx + i]
            if i < len(batch_results):
                df_complete.loc[original_idx, 's7_final_domain'] = batch_results[i]['domain']
                df_complete.loc[original_idx, 's7_final_method'] = batch_results[i]['method']
            else:
                df_complete.loc[original_idx, 's7_final_domain'] = "API Failed"
                df_complete.loc[original_idx, 's7_final_method'] = "API Failed"
        
        # Display detailed results for first batch only
        if batch_num == 0:
            display_s7_first_batch_results(batch_summaries, batch_results)
        
        # Save every 20 batches
        if (batch_num + 1) % 20 == 0:
            df_complete.to_csv(MAIN_DATAFRAME_CHECKPOINT_FILE, index=False)
            print(f"  ✅ S7 SAVED at batch {batch_num + 1}")
        
        # Wait between batches
        if batch_num < total_batches - 1:
            print(f"Waiting {DEFAULT_WAIT_TIME} seconds before next S7 batch...")
            time.sleep(DEFAULT_WAIT_TIME)
    
    return df_complete

def s7_check_category_matches():
    """Check which S7 assigned categories match the provided lists"""
    
    print("="*60)
    print("S7 FINAL CATEGORY MATCH CHECK") 
    print("="*60)
    
    # Get all assigned categories
    assigned_domains = df_complete['s7_final_domain'].dropna().unique()
    assigned_methods = df_complete['s7_final_method'].dropna().unique()
    
    # Find non-matching domains
    non_matching_domains = []
    for domain in assigned_domains:
        if domain not in S7_DOMAIN_CATEGORIES and domain not in ["API Failed", "Parse Failed"]:
            non_matching_domains.append(domain)
    
    # Find non-matching methods  
    non_matching_methods = []
    for method in assigned_methods:
        if method not in S7_METHOD_CATEGORIES and method not in ["API Failed", "Parse Failed"]:
            non_matching_methods.append(method)
    
    # Report results
    print(f"Total unique S7 domains assigned: {len(assigned_domains)}")
    print(f"S7 Domains matching your list: {len(assigned_domains) - len(non_matching_domains)}")
    print(f"S7 Domains NOT in your list: {len(non_matching_domains)}")
    
    if non_matching_domains:
        print(f"\nNON-MATCHING S7 DOMAINS:")
        for domain in non_matching_domains:
            count = (df_complete['s7_final_domain'] == domain).sum()
            print(f"  '{domain}': {count} projects")
    
    print(f"\nTotal unique S7 methods assigned: {len(assigned_methods)}")
    print(f"S7 Methods matching your list: {len(assigned_methods) - len(non_matching_methods)}")
    print(f"S7 Methods NOT in your list: {len(non_matching_methods)}")
    
    if non_matching_methods:
        print(f"\nNON-MATCHING S7 METHODS:")
        for method in non_matching_methods:
            count = (df_complete['s7_final_method'] == method).sum()
            print(f"  '{method}': {count} projects")
    
    # Calculate match rates
    total_projects = len(df_complete)
    domain_exact_matches = sum(1 for d in df_complete['s7_final_domain'] if d in S7_DOMAIN_CATEGORIES)
    method_exact_matches = sum(1 for m in df_complete['s7_final_method'] if m in S7_METHOD_CATEGORIES)
    
    print(f"\n" + "="*60)
    print("S7 FINAL MATCH RATES")
    print("="*60)
    print(f"S7 Domain exact match rate: {domain_exact_matches}/{total_projects} ({domain_exact_matches/total_projects*100:.1f}%)")
    print(f"S7 Method exact match rate: {method_exact_matches}/{total_projects} ({method_exact_matches/total_projects*100:.1f}%)")
    
    return non_matching_domains, non_matching_methods

def s7_reclassify_failed_categories(batch_size: int = 5, max_retries: int = 5):
    """Re-classify S7 projects that got non-matching categories"""
    
    print("="*60)
    print("S7 RE-CLASSIFYING NON-MATCHING CATEGORIES")
    print("="*60)
    
    # Identify failed S7 classifications
    domain_failures = ~df_complete['s7_final_domain'].isin(S7_DOMAIN_CATEGORIES + ["API Failed", "Parse Failed"])
    method_failures = ~df_complete['s7_final_method'].isin(S7_METHOD_CATEGORIES + ["API Failed", "Parse Failed"])
    
    # Get indices that need re-classification
    failed_indices = df_complete[domain_failures | method_failures].index.tolist()
    
    if not failed_indices:
        print("No failed S7 classifications found. Nothing to reclassify.")
        return df_complete
    
    print(f"Found {len(failed_indices)} S7 projects with non-matching categories")
    print(f"Using batch size: {batch_size}")
    
    # Enhanced S7 prompt for reclassification
    S7_RECLASSIFY_PROMPT = """You are an expert taxonomist. You must classify projects using ONLY the exact categories from the provided lists.

This is a highly consolidated taxonomy with only 11 domains and 10 methods. Choose the best fit from these broad categories.

DOMAIN AREAS (11 broad categories):
{domain_categories}

METHOD AREAS (10 broad categories):
{method_categories}

Projects to Classify:
{project_summaries}

Output Format (MUST follow exactly):
Project 1:
Domain Area: [Selected Domain Area - must be EXACTLY as shown in the Domain list above]
Method Area: [Selected Method Area - must be EXACTLY as shown in the Method list above]

Project 2:
Domain Area: [Selected Domain Area - must be EXACTLY as shown in the Domain list above]
Method Area: [Selected Method Area - must be EXACTLY as shown in the Method list above]

Continue for all projects. Select ONLY from the provided lists."""

    def s7_reclassify_batch(project_summaries: List[str], indices: List[int]) -> List[Dict[str, str]]:
        """Reclassify a batch with S7 enhanced prompt"""
        
        # Format summaries
        formatted_summaries = ""
        for i, summary in enumerate(project_summaries, 1):
            formatted_summaries += f"Project {i}:\n{summary}\n\n"
        
        # Create enhanced S7 prompt
        prompt = S7_RECLASSIFY_PROMPT.format(
            domain_categories="\n".join(S7_DOMAIN_CATEGORIES),
            method_categories="\n".join(S7_METHOD_CATEGORIES),
            project_summaries=formatted_summaries
        )
        
        # Process with more retries
        output_text = ""
        for attempt in range(max_retries):
            try:
                response = model.generate_content(prompt)
                output_text = response.text
                break
            except Exception as e:
                print(f"  S7 Retry {attempt + 1}: {e}")
                if attempt < max_retries - 1:
                    sleep_time = 2 ** (attempt + 1)
                    print(f"  Waiting {sleep_time}s...")
                    time.sleep(sleep_time)
                else:
                    print("  All S7 retries failed")
                    return [{"domain": "S7 Reclassify Failed", "method": "S7 Reclassify Failed"} for _ in project_summaries]
        
        # Parse results
        results = []
        project_blocks = re.split(r'Project \d+:', output_text)
        
        if project_blocks and not project_blocks[0].strip():
            project_blocks = project_blocks[1:]
        
        if len(project_blocks) < len(project_summaries):
            project_blocks.extend(["" for _ in range(len(project_summaries) - len(project_blocks))])
        
        for i, block in enumerate(project_blocks[:len(project_summaries)]):
            domain = "S7 Reclassify Failed"
            method = "S7 Reclassify Failed"
            
            for line in block.strip().split('\n'):
                line = line.strip()
                if line.startswith("Domain Area:"):
                    domain = line.replace("Domain Area:", "").strip()
                    domain = domain.strip('"\'- ')
                elif line.startswith("Method Area:"):
                    method = line.replace("Method Area:", "").strip()
                    method = method.strip('"\'- ')
            
            results.append({"domain": domain, "method": method, "index": indices[i] if i < len(indices) else None})
        
        return results
    
    # Process failed items in batches
    total_failed = len(failed_indices)
    total_batches = (total_failed + batch_size - 1) // batch_size
    
    successful_reclassifications = 0
    
    for batch_num, start_idx in enumerate(range(0, total_failed, batch_size)):
        end_idx = min(start_idx + batch_size, total_failed)
        batch_indices = failed_indices[start_idx:end_idx]
        
        print(f"\nS7 Reclassifying batch {batch_num + 1}/{total_batches} ({len(batch_indices)} projects)")
        
        # Get batch of failed items
        batch_summaries = []
        for idx in batch_indices:
            summary = df_complete.loc[idx, 'full_text']
            batch_summaries.append(summary)
            
            # Show what failed
            old_domain = df_complete.loc[idx, 's7_final_domain']
            old_method = df_complete.loc[idx, 's7_final_method']
            print(f"  Project {idx}: '{old_domain}' / '{old_method}'")
        
        # Reclassify this batch
        batch_results = s7_reclassify_batch(batch_summaries, batch_indices)
        
        # Update results and show changes
        for i, idx in enumerate(batch_indices):
            if i < len(batch_results):
                new_domain = batch_results[i]['domain']
                new_method = batch_results[i]['method']
                
                df_complete.loc[idx, 's7_final_domain'] = new_domain
                df_complete.loc[idx, 's7_final_method'] = new_method
                
                # Check if reclassification was successful
                domain_success = new_domain in S7_DOMAIN_CATEGORIES
                method_success = new_method in S7_METHOD_CATEGORIES
                
                if domain_success and method_success:
                    successful_reclassifications += 1
                    print(f"    ✅ Fixed: '{new_domain}' / '{new_method}'")
                else:
                    print(f"    ❌ Still failed: '{new_domain}' / '{new_method}'")
        
        # Wait between batches
        if batch_num < total_batches - 1:
            print(f"  Waiting {DEFAULT_WAIT_TIME}s...")
            time.sleep(DEFAULT_WAIT_TIME)
    
    # Final save
    df_complete.to_csv(MAIN_DATAFRAME_CHECKPOINT_FILE, index=False)
    
    print(f"\n" + "="*60)
    print("S7 RECLASSIFICATION COMPLETE")
    print("="*60)
    print(f"Total S7 projects reclassified: {total_failed}")
    print(f"Successfully fixed: {successful_reclassifications}")
    print(f"Still failed: {total_failed - successful_reclassifications}")
    
    return df_complete

# MAIN S7 EXECUTION FUNCTION
def run_s7_final_classification():
    """Run the complete S7 final classification process"""
    
    print("🎯 STARTING COMPLETE S7 FINAL CLASSIFICATION")
    print("="*80)
    
    # Check prerequisites
    if 'df_complete' not in globals() or df_complete.empty:
        print("❌ ERROR: df_complete not available")
        return None
    elif 'model' not in globals() or not model:
        print("❌ ERROR: model not available")
        return None
    elif 'full_text' not in df_complete.columns:
        print("❌ ERROR: 'full_text' column missing")
        return None
    
    # Step 1: Run main S7 classification
    print("🚀 STEP 1: Main S7 Final Classification")
    df_result = s7_classify_dataset()
    
    # Step 2: Check for mismatches
    print("\n🔍 STEP 2: Checking S7 Category Matches")
    non_matching_domains, non_matching_methods = s7_check_category_matches()
    
    # Step 3: Fix any mismatches
    if non_matching_domains or non_matching_methods:
        print("\n🔧 STEP 3: Fixing S7 Non-Matching Categories")
        df_result = s7_reclassify_failed_categories()
        
        # Final check
        print("\n✅ STEP 4: Final S7 Verification")
        s7_check_category_matches()
    else:
        print("\n✅ No S7 reclassification needed!")
    
    # Final save and summary
    df_complete.to_csv(MAIN_DATAFRAME_CHECKPOINT_FILE, index=False)
    print(f"\n🎉 S7 FINAL CLASSIFICATION COMPLETE!")
    
    # Show sample results
    print(f"\nS7 Sample Results:")
    sample_cols = ['id', 'full_text', 's7_final_domain', 's7_final_method']
    available_cols = [col for col in sample_cols if col in df_complete.columns]
    if available_cols:
        display(df_complete[available_cols].head())
    
    # Generate summary statistics
    domain_counts = df_complete['s7_final_domain'].value_counts()
    method_counts = df_complete['s7_final_method'].value_counts()
    
    print(f"\nTop S7 assigned domain categories:")
    for domain, count in domain_counts.head(len(S7_DOMAIN_CATEGORIES)).items():
        print(f"- {domain}: {count}")
    
    print(f"\nTop S7 assigned method categories:")
    for method, count in method_counts.head(len(S7_METHOD_CATEGORIES)).items():
        print(f"- {method}: {count}")
    
    return df_result

# USAGE:
df_s7_result = run_s7_final_classification()

🎯 S7 FINAL CONSOLIDATED CATEGORIES LOADED
   Domains: 11 categories
   Methods: 10 categories
🎯 STARTING COMPLETE S7 FINAL CLASSIFICATION
================================================================================
🚀 STEP 1: Main S7 Final Classification
🚀 STARTING S7 FINAL CONSOLIDATED CLASSIFICATION
================================================================================
Using S7 final categories:
  11 Domain areas (highly consolidated)
  10 Method areas (highly consolidated)
  Batch size: 15
  Trial mode: False
FULL MODE: Processing 15341 rows

Processing S7 batch 1/1023 (records 1-15)

===== S7 FIRST BATCH RESULTS =====
Showing results for the first batch of 15 projects

Project 1:
Summary: Digitizing Other Economies: A Comparative Approach: How do longstanding, primarily non-industrial, non-capitalist societies adopt and adapt digital te...
S7 Domain: Society, Culture & Human Behavior
S7 Method: Qualitative, Social Inquiry & Policy Research

Project 2:
Summary: MOLECULAR QUANTUM DYNAMICS IN LOW TEMPERATURE CONDENSED PHASE ASTROCHEMISTRY: The James Webb Space Telescope (JWST) has ushered in a new era in observ...
S7 Domain: Physical, Mathematical & Space Sciences
S7 Method: Experimental, Laboratory & Field Investigation

Project 3:
Summary: Multiscale modelling of aberrant phase transitions in biocondensates: The spatiotemporal organization of the cell material represents one of the great...
S7 Domain: Health, Medicine & Life Sciences
S7 Method: Data Analysis, Modeling & Computational Methods

Project 4:
Summary: The first comprehensive Atlas of the Milky Way: The Milky Way is the cosmic environment in which the solar system, the Earth, and life as we know it c...
S7 Domain: Physical, Mathematical & Space Sciences
S7 Method: Data Analysis, Modeling & Computational Methods

Project 5:
Summary: Untapping multiparametric 2D luminescence sensing through MACHine LEarning and Spectral Sorting: Cellular organisms are complex machines whose health ...
S7 Domain: Engineering, Manufacturing & Technology
S7 Method: Imaging, Sensing & Measurement Techniques

Project 6:
Summary: Making Sense of the Unexpected in the Gravitational-Wave Sky: General Relativity (GR) is more than a century old, but is still our best macroscopic de...
S7 Domain: Physical, Mathematical & Space Sciences
S7 Method: Data Analysis, Modeling & Computational Methods

Project 7:
Summary: Hernando Colón’s universal library. European culture and intellectual production at the dawn of the global world: While newly printed books were circu...
S7 Domain: Humanities, Arts & Cultural Heritage
S7 Method: Qualitative, Social Inquiry & Policy Research

Project 8:
Summary: UA EURATOM NCP SUPPORT OF UKRAINIAN RESEARCH ENTITIES INTEGRATION INTO NUCLEAR RESEARCH FUNDED BY THE EURATOM RESEARCH AND TRAINING PROGRAMME 2021-202...
S7 Domain: Policy, Governance & Law
S7 Method: Communication, Collaboration & Knowledge Exchange

Project 9:
Summary: FISA 2025 – EURADWASTE’25  conferences on Euratom fission research and training: The FISA-EURADWASTE event is a high-level, research policy conference...
S7 Domain: Policy, Governance & Law
S7 Method: Communication, Collaboration & Knowledge Exchange

Project 10:
Summary: Market & Technology Analysis: Adsorbi is a deep tech startup company from Gothenburg Sweden and was founded after several years of research within mat...
S7 Domain: Economy, Business & Agriculture
S7 Method: Innovation, Strategic Management & Evaluation

Project 11:
Summary: Female leadership in Medsensio, a digital health technology startup: Medsensio was founded in 2017 as a spinout from a research project in health data...
S7 Domain: Health, Medicine & Life Sciences
S7 Method: Innovation, Strategic Management & Evaluation

Project 12:
Summary: Detecting the right moment to do embryo transfer in In Vitro Fertilisation treatments.: In-vitro Fertilization (IVF) is a well-known fertility treatme...
S7 Domain: Health, Medicine & Life Sciences
S7 Method: Clinical, Health & Therapeutic Development Methods

Project 13:
Summary: Elia - Smart Assistant for English Learning: We are a startup founded exclusively by women holding the top positions CEO and CTO. Our vision is to red...
S7 Domain: Education & Learning Systems
S7 Method: Information, Computation & Digital Systems

Project 14:
Summary: EUCYS Leiden2022: The main objective of this Proposal is the organisation of the Young Talents Programme which contains two separate events. The first...
S7 Domain: Education & Learning Systems
S7 Method: Educational, Human-Centered & Training Methods

Project 15:
Summary: European Union Contest for Young Scientists (EUCYS) 2024: This proposal concerns the organization of the 35th European Union Contest for Young Scienti...
S7 Domain: Education & Learning Systems
S7 Method: Communication, Collaboration & Knowledge Exchange

================================
Waiting 0 seconds before next S7 batch...

Processing S7 batch 2/1023 (records 16-30)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 3/1023 (records 31-45)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 4/1023 (records 46-60)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 5/1023 (records 61-75)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 6/1023 (records 76-90)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 7/1023 (records 91-105)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 8/1023 (records 106-120)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 9/1023 (records 121-135)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 10/1023 (records 136-150)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 11/1023 (records 151-165)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 12/1023 (records 166-180)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 13/1023 (records 181-195)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 14/1023 (records 196-210)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 15/1023 (records 211-225)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 16/1023 (records 226-240)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 17/1023 (records 241-255)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 18/1023 (records 256-270)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 19/1023 (records 271-285)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 20/1023 (records 286-300)
  ✅ S7 SAVED at batch 20
Waiting 0 seconds before next S7 batch...

Processing S7 batch 21/1023 (records 301-315)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 22/1023 (records 316-330)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 23/1023 (records 331-345)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 24/1023 (records 346-360)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 25/1023 (records 361-375)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 26/1023 (records 376-390)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 27/1023 (records 391-405)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 28/1023 (records 406-420)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 29/1023 (records 421-435)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 30/1023 (records 436-450)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 31/1023 (records 451-465)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 32/1023 (records 466-480)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 33/1023 (records 481-495)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 34/1023 (records 496-510)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 35/1023 (records 511-525)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 36/1023 (records 526-540)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 37/1023 (records 541-555)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 38/1023 (records 556-570)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 39/1023 (records 571-585)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 40/1023 (records 586-600)
  ✅ S7 SAVED at batch 40
Waiting 0 seconds before next S7 batch...

Processing S7 batch 41/1023 (records 601-615)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 42/1023 (records 616-630)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 43/1023 (records 631-645)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 44/1023 (records 646-660)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 45/1023 (records 661-675)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 46/1023 (records 676-690)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 47/1023 (records 691-705)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 48/1023 (records 706-720)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 49/1023 (records 721-735)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 50/1023 (records 736-750)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 51/1023 (records 751-765)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 52/1023 (records 766-780)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 53/1023 (records 781-795)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 54/1023 (records 796-810)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 55/1023 (records 811-825)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 56/1023 (records 826-840)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 57/1023 (records 841-855)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 58/1023 (records 856-870)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 59/1023 (records 871-885)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 60/1023 (records 886-900)
  ✅ S7 SAVED at batch 60
Waiting 0 seconds before next S7 batch...

Processing S7 batch 61/1023 (records 901-915)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 62/1023 (records 916-930)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 63/1023 (records 931-945)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 64/1023 (records 946-960)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 65/1023 (records 961-975)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 66/1023 (records 976-990)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 67/1023 (records 991-1005)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 68/1023 (records 1006-1020)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 69/1023 (records 1021-1035)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 70/1023 (records 1036-1050)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 71/1023 (records 1051-1065)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 72/1023 (records 1066-1080)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 73/1023 (records 1081-1095)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 74/1023 (records 1096-1110)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 75/1023 (records 1111-1125)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 76/1023 (records 1126-1140)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 77/1023 (records 1141-1155)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 78/1023 (records 1156-1170)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 79/1023 (records 1171-1185)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 80/1023 (records 1186-1200)
  ✅ S7 SAVED at batch 80
Waiting 0 seconds before next S7 batch...

Processing S7 batch 81/1023 (records 1201-1215)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 82/1023 (records 1216-1230)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 83/1023 (records 1231-1245)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 84/1023 (records 1246-1260)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 85/1023 (records 1261-1275)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 86/1023 (records 1276-1290)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 87/1023 (records 1291-1305)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 88/1023 (records 1306-1320)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 89/1023 (records 1321-1335)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 90/1023 (records 1336-1350)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 91/1023 (records 1351-1365)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 92/1023 (records 1366-1380)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 93/1023 (records 1381-1395)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 94/1023 (records 1396-1410)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 95/1023 (records 1411-1425)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 96/1023 (records 1426-1440)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 97/1023 (records 1441-1455)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 98/1023 (records 1456-1470)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 99/1023 (records 1471-1485)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 100/1023 (records 1486-1500)
  ✅ S7 SAVED at batch 100
Waiting 0 seconds before next S7 batch...

Processing S7 batch 101/1023 (records 1501-1515)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 102/1023 (records 1516-1530)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 103/1023 (records 1531-1545)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 104/1023 (records 1546-1560)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 105/1023 (records 1561-1575)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 106/1023 (records 1576-1590)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 107/1023 (records 1591-1605)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 108/1023 (records 1606-1620)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 109/1023 (records 1621-1635)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 110/1023 (records 1636-1650)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 111/1023 (records 1651-1665)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 112/1023 (records 1666-1680)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 113/1023 (records 1681-1695)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 114/1023 (records 1696-1710)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 115/1023 (records 1711-1725)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 116/1023 (records 1726-1740)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 117/1023 (records 1741-1755)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 118/1023 (records 1756-1770)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 119/1023 (records 1771-1785)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 120/1023 (records 1786-1800)
  ✅ S7 SAVED at batch 120
Waiting 0 seconds before next S7 batch...

Processing S7 batch 121/1023 (records 1801-1815)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 122/1023 (records 1816-1830)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 123/1023 (records 1831-1845)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 124/1023 (records 1846-1860)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 125/1023 (records 1861-1875)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 126/1023 (records 1876-1890)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 127/1023 (records 1891-1905)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 128/1023 (records 1906-1920)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 129/1023 (records 1921-1935)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 130/1023 (records 1936-1950)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 131/1023 (records 1951-1965)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 132/1023 (records 1966-1980)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 133/1023 (records 1981-1995)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 134/1023 (records 1996-2010)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 135/1023 (records 2011-2025)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 136/1023 (records 2026-2040)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 137/1023 (records 2041-2055)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 138/1023 (records 2056-2070)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 139/1023 (records 2071-2085)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 140/1023 (records 2086-2100)
  ✅ S7 SAVED at batch 140
Waiting 0 seconds before next S7 batch...

Processing S7 batch 141/1023 (records 2101-2115)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 142/1023 (records 2116-2130)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 143/1023 (records 2131-2145)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 144/1023 (records 2146-2160)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 145/1023 (records 2161-2175)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 146/1023 (records 2176-2190)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 147/1023 (records 2191-2205)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 148/1023 (records 2206-2220)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 149/1023 (records 2221-2235)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 150/1023 (records 2236-2250)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 151/1023 (records 2251-2265)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 152/1023 (records 2266-2280)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 153/1023 (records 2281-2295)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 154/1023 (records 2296-2310)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 155/1023 (records 2311-2325)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 156/1023 (records 2326-2340)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 157/1023 (records 2341-2355)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 158/1023 (records 2356-2370)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 159/1023 (records 2371-2385)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 160/1023 (records 2386-2400)
  ✅ S7 SAVED at batch 160
Waiting 0 seconds before next S7 batch...

Processing S7 batch 161/1023 (records 2401-2415)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 162/1023 (records 2416-2430)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 163/1023 (records 2431-2445)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 164/1023 (records 2446-2460)
Waiting 0 seconds before next S7 batch...

Processing S7 batch 165/1023 (records 2461-2475)
Waiting 0 seconds before next S7 batch...


,id,full_text,s7_final_domain,s7_final_method
0,101116741,Digitizing Other Economies: A Comparative Appr...,"Society, Culture & Human Behavior","Qualitative, Social Inquiry & Policy Research"
1,101163161,MOLECULAR QUANTUM DYNAMICS IN LOW TEMPERATURE ...,"Physical, Mathematical & Space Sciences","Experimental, Laboratory & Field Investigation"
2,101160499,Multiscale modelling of aberrant phase transit...,"Health, Medicine & Life Sciences","Data Analysis, Modeling & Computational Methods"
3,101166905,The first comprehensive Atlas of the Milky Way...,"Physical, Mathematical & Space Sciences","Data Analysis, Modeling & Computational Methods"
4,101162875,Untapping multiparametric 2D luminescence sens...,"Engineering, Manufacturing & Technology","Imaging, Sensing & Measurement Techniques"

Top S7 assigned domain categories:
- Health, Medicine & Life Sciences: 4105
- Engineering, Manufacturing & Technology: 3193
- Environment, Climate & Earth Systems: 1900
- Physical, Mathematical & Space Sciences: 1401
- Society, Culture & Human Behavior: 1086
- Information, Computation & Digital Systems: 1022
- Economy, Business & Agriculture: 999
- Humanities, Arts & Cultural Heritage: 731
- Policy, Governance & Law: 455
- Education & Learning Systems: 300
- Global Development & Sustainability: 142

Top S7 assigned method categories:
- Data Analysis, Modeling & Computational Methods: 3283
- Experimental, Laboratory & Field Investigation: 2745
- Engineering Design, Prototyping & Systems Development: 2258
- Material, Chemical & Bioprocess Development: 1952
- Qualitative, Social Inquiry & Policy Research: 1799
- Innovation, Strategic Management & Evaluation: 914
- Imaging, Sensing & Measurement Techniques: 823
- Clinical, Health & Therapeutic Development Methods: 730
- Communication, Collaboration & Knowledge Exchange: 554
- Educational, Human-Centered & Training Methods: 255

In [160]:
# COMPLETE S7 FIX STAGE - 
# S7 FINAL CONSOLIDATED CATEGORIES (from your original code)
S7_DOMAIN_CATEGORIES = [
    "Health, Medicine & Life Sciences",
    "Physical, Mathematical & Space Sciences", 
    "Engineering, Manufacturing & Technology",
    "Information, Computation & Digital Systems",
    "Environment, Climate & Earth Systems",
    "Economy, Business & Agriculture",
    "Society, Culture & Human Behavior",
    "Humanities, Arts & Cultural Heritage",
    "Policy, Governance & Law",
    "Education & Learning Systems",
    "Global Development & Sustainability"
]

S7_METHOD_CATEGORIES = [
    "Data Analysis, Modeling & Computational Methods",
    "Qualitative, Social Inquiry & Policy Research",
    "Engineering Design, Prototyping & Systems Development",
    "Experimental, Laboratory & Field Investigation",
    "Material, Chemical & Bioprocess Development",
    "Imaging, Sensing & Measurement Techniques",
    "Clinical, Health & Therapeutic Development Methods",
    "Communication, Collaboration & Knowledge Exchange",
    "Innovation, Strategic Management & Evaluation",
    "Educational, Human-Centered & Training Methods"
]

def find_s7_failed_projects():
    """Find the exact projects that still have non-matching S7 categories - STRICT MODE"""
    
    print("🔍 FINDING S7 FAILED PROJECTS (STRICT - NO PARSE FAILED ALLOWED)")
    print("="*60)
    
    # Load current data
    try:
        df = pd.read_csv("df_processing_checkpoint.csv")
        print(f"✅ Loaded checkpoint CSV: {df.shape}")
    except:
        df = globals()['df_complete'].copy()
        print(f"✅ Using global df_complete: {df.shape}")
    
    # STRICT: Only empty strings and None are acceptable "failures"
    # Everything else (including "Parse Failed", "API Failed", etc.) must be fixed
    acceptable_errors = ["", None]
    
    failed_projects = []
    
    for idx in df.index:
        domain = df.loc[idx, 's7_final_domain']
        method = df.loc[idx, 's7_final_method']
        
        # Check if domain is problematic
        domain_bad = (pd.notna(domain) and 
                     str(domain).strip() != "" and  # Not empty string
                     domain not in S7_DOMAIN_CATEGORIES)  # Not valid category
        
        # Check if method is problematic  
        method_bad = (pd.notna(method) and 
                     str(method).strip() != "" and  # Not empty string
                     method not in S7_METHOD_CATEGORIES)  # Not valid category
        
        if domain_bad or method_bad:
            project_id = df.loc[idx, 'id'] if 'id' in df.columns else idx
            failed_projects.append({
                'index': idx,
                'id': project_id,
                'domain': domain,
                'method': method,
                'domain_bad': domain_bad,
                'method_bad': method_bad,
                'summary': str(df.loc[idx, 'full_text'])[:200] + "..."
            })
    
    print(f"Found {len(failed_projects)} projects with invalid S7 categories")
    
    # Group by bad categories to see patterns
    if failed_projects:
        domain_issues = {}
        method_issues = {}
        
        for proj in failed_projects:
            if proj['domain_bad']:
                domain = str(proj['domain'])
                if domain not in domain_issues:
                    domain_issues[domain] = []
                domain_issues[domain].append(proj['index'])
            
            if proj['method_bad']:
                method = str(proj['method'])
                if method not in method_issues:
                    method_issues[method] = []
                method_issues[method].append(proj['index'])
        
        print(f"\n❌ ALL PROBLEMATIC S7 DOMAINS (including Parse Failed, API Failed, etc.):")
        for domain, indices in domain_issues.items():
            print(f"  '{domain}': {len(indices)} projects")
        
        print(f"\n❌ ALL PROBLEMATIC S7 METHODS (including Parse Failed, API Failed, etc.):")
        for method, indices in method_issues.items():
            print(f"  '{method}': {len(indices)} projects")
    
    return failed_projects, df

def fix_s7_failed_projects_no_parse_failed(failed_projects, df, model):
    """Fix S7 projects - return empty strings instead of failure messages"""
    
    if not failed_projects:
        print("✅ No S7 failed projects to fix!")
        return df
    
    print(f"🔧 S7 FIXING - {len(failed_projects)} PROJECTS (NO PARSE FAILED ALLOWED)")
    print("="*60)
    
    # Enhanced prompt for problem cases - simplified for S7's broad categories
    TARGETED_S7_PROMPT = """You are an expert research taxonomist. You must classify these projects using ONLY the exact categories from the highly consolidated lists below.

This is a very broad taxonomy with only 11 domains and 10 methods. Choose the best general fit.

CRITICAL RULES:
1. Select EXACTLY ONE domain from the Domain list for each project
2. Select EXACTLY ONE method from the Method list for each project  
3. Use the EXACT spelling, punctuation, and capitalization shown
4. DO NOT create new categories or modify existing ones
5. These are very broad categories - pick the best general fit

DOMAIN AREAS (11 broad consolidated areas - choose ONE per project):
{domain_list}

METHOD AREAS (10 broad consolidated approaches - choose ONE per project):
{method_list}

PROJECTS TO CLASSIFY:
{project_summaries}

RESPOND IN THIS EXACT FORMAT:
Project 1:
Domain Area: [EXACT match from Domain list above]
Method Area: [EXACT match from Method list above]

Project 2:
Domain Area: [EXACT match from Domain list above]
Method Area: [EXACT match from Method list above]

... continue for all projects ...

Remember: These are very broad, consolidated categories. Pick the best general fit for each project."""

    changes_made = []
    df_working = df.copy()
    
    # Process 8 projects at a time (can be larger since S7 categories are simpler)
    batch_size = 8
    total_batches = (len(failed_projects) + batch_size - 1) // batch_size
    
    for batch_num in range(total_batches):
        start_idx = batch_num * batch_size
        end_idx = min(start_idx + batch_size, len(failed_projects))
        batch_projects = failed_projects[start_idx:end_idx]
        
        print(f"\n--- S7 Batch {batch_num+1}/{total_batches} ({len(batch_projects)} projects) ---")
        
        # Show what we're fixing
        for i, proj in enumerate(batch_projects):
            print(f"  Project {i+1} (ID {proj['id']}, Index {proj['index']}):")
            print(f"    Current Domain: '{proj['domain']}' {'❌' if proj['domain_bad'] else '✅'}")
            print(f"    Current Method: '{proj['method']}' {'❌' if proj['method_bad'] else '✅'}")
        
        # Prepare batch summaries
        project_summaries = ""
        for i, proj in enumerate(batch_projects, 1):
            project_text = str(df_working.loc[proj['index'], 'full_text'])[:1000]  # Shorter for S7
            project_summaries += f"Project {i}:\nTitle and Description: {project_text}\n\n"
        
        # Create focused prompt
        prompt = TARGETED_S7_PROMPT.format(
            domain_list="\n".join(S7_DOMAIN_CATEGORIES),
            method_list="\n".join(S7_METHOD_CATEGORIES),
            project_summaries=project_summaries
        )
        
        # Try to get results from LLM
        batch_success = False
        try:
            print(f"🤖 Calling LLM for batch {batch_num+1}...")
            
            response = model.generate_content(prompt)
            output = response.text.strip()
            
            print(f"✅ Got LLM response, parsing...")
            
            # Parse results for the batch
            project_blocks = re.split(r'Project \d+:', output)
            if project_blocks and not project_blocks[0].strip():
                project_blocks = project_blocks[1:]
            
            if len(project_blocks) >= len(batch_projects):
                batch_results = []
                
                for i, block in enumerate(project_blocks[:len(batch_projects)]):
                    new_domain = ""  # Default to EMPTY instead of "Parse Failed"
                    new_method = ""  # Default to EMPTY instead of "Parse Failed"
                    
                    lines = block.strip().split('\n')
                    for line in lines:
                        line = line.strip()
                        if line.startswith("Domain Area:"):
                            candidate = line.replace("Domain Area:", "").strip()
                            candidate = candidate.strip('"\'- ')
                            # Only assign if it's actually in our valid list
                            if candidate in S7_DOMAIN_CATEGORIES:
                                new_domain = candidate
                            else:
                                # Try fuzzy matching for S7 since categories are fewer
                                for valid_domain in S7_DOMAIN_CATEGORIES:
                                    if candidate.lower() in valid_domain.lower() or valid_domain.lower() in candidate.lower():
                                        new_domain = valid_domain
                                        print(f"    🔧 Fuzzy domain match: '{candidate}' → '{valid_domain}'")
                                        break
                        elif line.startswith("Method Area:"):
                            candidate = line.replace("Method Area:", "").strip()
                            candidate = candidate.strip('"\'- ')
                            # Only assign if it's actually in our valid list
                            if candidate in S7_METHOD_CATEGORIES:
                                new_method = candidate
                            else:
                                # Try fuzzy matching for S7 since categories are fewer
                                for valid_method in S7_METHOD_CATEGORIES:
                                    if candidate.lower() in valid_method.lower() or valid_method.lower() in candidate.lower():
                                        new_method = valid_method
                                        print(f"    🔧 Fuzzy method match: '{candidate}' → '{valid_method}'")
                                        break
                    
                    batch_results.append({
                        'domain': new_domain,
                        'method': new_method
                    })
                
                # Apply all results in this batch
                for i, result in enumerate(batch_results):
                    proj = batch_projects[i]
                    idx = proj['index']
                    
                    old_domain = df_working.loc[idx, 's7_final_domain']
                    old_method = df_working.loc[idx, 's7_final_method']
                    
                    # Only update categories that were actually problematic
                    if proj['domain_bad']:
                        df_working.loc[idx, 's7_final_domain'] = result['domain']
                        print(f"  🔄 Fixed Domain {idx}: '{old_domain}' → '{result['domain']}'")
                    
                    if proj['method_bad']:
                        df_working.loc[idx, 's7_final_method'] = result['method']
                        print(f"  🔄 Fixed Method {idx}: '{old_method}' → '{result['method']}'")
                    
                    changes_made.append({
                        'index': idx,
                        'id': proj['id'],
                        'old_domain': old_domain,
                        'new_domain': result['domain'] if proj['domain_bad'] else old_domain,
                        'old_method': old_method,
                        'new_method': result['method'] if proj['method_bad'] else old_method
                    })
                
                batch_success = True
                print(f"  ✅ Batch {batch_num+1} processed successfully")
            else:
                print(f"  ⚠️ Got {len(project_blocks)} project blocks, expected {len(batch_projects)}")
                
        except Exception as e:
            print(f"  ❌ LLM error for batch {batch_num+1}: {e}")
        
        if not batch_success:
            print(f"  🔄 Batch {batch_num+1} failed - setting empty strings for problematic categories")
            # Set empty strings for failed attempts (so they get caught in next iteration)
            for proj in batch_projects:
                idx = proj['index']
                if proj['domain_bad']:
                    df_working.loc[idx, 's7_final_domain'] = ""
                    print(f"    Set domain to empty for index {idx}")
                if proj['method_bad']:
                    df_working.loc[idx, 's7_final_method'] = ""
                    print(f"    Set method to empty for index {idx}")
        
        # Small delay between batches
        if batch_num < total_batches - 1:
            time.sleep(3)
    
    print(f"\n💾 SAVING S7 FIXES")
    print("="*60)
    
    # Save back to CSV
    df_working.to_csv("df_processing_checkpoint.csv", index=False)
    print(f"✅ Saved to df_processing_checkpoint.csv")
    
    # Update global if possible
    try:
        globals()['df_complete'] = df_working.copy()
        print(f"✅ Updated global df_complete")
    except:
        pass
    
    print(f"\n📊 S7 FIX SUMMARY:")
    print(f"   Failed projects processed: {len(failed_projects)}")
    print(f"   Batches processed: {total_batches}")
    print(f"   Changes attempted: {len(changes_made)}")
    
    return df_working

def run_s7_complete_fix():
    """Main function to run complete S7 fixes until everything is clean"""
    
    print("🎯 S7 COMPLETE FIX - NO PARSE FAILED ALLOWED")
    print("="*80)
    
    # Get model
    try:
        model = globals()['model']
        print(f"✅ Using global model")
    except:
        print("❌ ERROR: Global 'model' not found")
        return None
    
    # Keep running fix iterations until no more failures
    max_iterations = 5
    
    for iteration in range(max_iterations):
        print(f"\n🔄 S7 FIX ITERATION {iteration + 1}/{max_iterations}")
        print("="*60)
        
        # Step 1: Find failed projects (strict mode)
        failed_projects, df = find_s7_failed_projects()
        
        if not failed_projects:
            print(f"🎉 S7 COMPLETE - No more failed projects after {iteration + 1} iteration(s)!")
            break
        
        print(f"📋 Found {len(failed_projects)} projects that need fixing")
        
        # Step 2: Apply fixes
        df = fix_s7_failed_projects_no_parse_failed(failed_projects, df, model)
        
        # Step 3: Show progress
        print(f"\n📊 Iteration {iteration + 1} complete")
        
        if iteration == max_iterations - 1:
            print(f"⚠️ Reached maximum iterations ({max_iterations})")
            print(f"   Some projects may still need manual review")
    
    # Final verification
    print(f"\n🔍 FINAL S7 VERIFICATION")
    print("="*60)
    
    final_failed, df_final = find_s7_failed_projects()
    
    domain_matches = sum(1 for d in df_final['s7_final_domain'] if d in S7_DOMAIN_CATEGORIES)
    method_matches = sum(1 for m in df_final['s7_final_method'] if m in S7_METHOD_CATEGORIES)
    empty_domains = sum(1 for d in df_final['s7_final_domain'] if pd.isna(d) or str(d).strip() == "")
    empty_methods = sum(1 for m in df_final['s7_final_method'] if pd.isna(m) or str(m).strip() == "")
    total_projects = len(df_final)
    
    print(f"📊 FINAL S7 STATISTICS:")
    print(f"   Total projects: {total_projects}")
    print(f"   Valid domain categories: {domain_matches} ({domain_matches/total_projects*100:.2f}%)")
    print(f"   Valid method categories: {method_matches} ({method_matches/total_projects*100:.2f}%)")
    print(f"   Empty domains (acceptable): {empty_domains} ({empty_domains/total_projects*100:.2f}%)")
    print(f"   Empty methods (acceptable): {empty_methods} ({empty_methods/total_projects*100:.2f}%)")
    print(f"   Remaining problematic projects: {len(final_failed)}")
    
    if len(final_failed) == 0:
        print(f"\n🎉🎉🎉 PERFECT! 100% S7 SUCCESS - NO MORE PARSE FAILED! 🎉🎉🎉")
    else:
        print(f"\n⚠️ Still have {len(final_failed)} projects with invalid categories:")
        # Show first few remaining problems
        for proj in final_failed[:5]:
            print(f"   - Index {proj['index']}: Domain='{proj['domain']}', Method='{proj['method']}'")
        
        if len(final_failed) > 5:
            print(f"   ... and {len(final_failed) - 5} more")
        
        # Show what the remaining bad categories are
        remaining_domains = {}
        remaining_methods = {}
        
        for proj in final_failed:
            if proj['domain_bad']:
                domain = str(proj['domain'])
                remaining_domains[domain] = remaining_domains.get(domain, 0) + 1
            if proj['method_bad']:
                method = str(proj['method'])
                remaining_methods[method] = remaining_methods.get(method, 0) + 1
        
        if remaining_domains:
            print(f"\n   Remaining bad domains:")
            for domain, count in remaining_domains.items():
                print(f"     - '{domain}': {count} projects")
        
        if remaining_methods:
            print(f"\n   Remaining bad methods:")
            for method, count in remaining_methods.items():
                print(f"     - '{method}': {count} projects")
    
    print(f"\n🎯 S7 COMPLETE FIX FINISHED!")
    
    return df_final

# USAGE:
df_s7_clean = run_s7_complete_fix()

🎯 S7 TARGETED FAILED PROJECT FIXER
================================================================================
🔍 FINDING S7 FAILED PROJECTS
============================================================
✅ Loaded checkpoint CSV: (15341, 16)
Found 35 projects with bad S7 categories

❌ PROBLEMATIC S7 DOMAINS:
  'Material, Chemical & Bioprocess Development': 7 projects

❌ PROBLEMATIC S7 METHODS:
  'Information, Computation & Digital Systems': 21 projects
  'Policy, Governance & Law': 7 projects
✅ Using global model
🔧 TARGETED S7 FIXING - 35 PROJECTS (batches of 6)
============================================================

--- S7 Targeted Batch 1/6 (6 projects) ---
  Project 1 (ID 101114248, Index 12):
    Domain: 'Education & Learning Systems' ✅
    Method: 'Information, Computation & Digital Systems' ❌
  Project 2 (ID 101113961, Index 70):
    Domain: 'Health, Medicine & Life Sciences' ✅
    Method: 'Information, Computation & Digital Systems' ❌
  Project 3 (ID 101114484, Index 94):
    Domain: 'Health, Medicine & Life Sciences' ✅
    Method: 'Information, Computation & Digital Systems' ❌
  Project 4 (ID 101113932, Index 102):
    Domain: 'Health, Medicine & Life Sciences' ✅
    Method: 'Information, Computation & Digital Systems' ❌
  Project 5 (ID 101119387, Index 632):
    Domain: 'Environment, Climate & Earth Systems' ✅
    Method: 'Policy, Governance & Law' ❌
  Project 6 (ID 101182167, Index 702):
    Domain: 'Environment, Climate & Earth Systems' ✅
    Method: 'Policy, Governance & Law' ❌
🤖 S7 batch targeted attempt 1...
Raw LLM output preview: Project 1:
Domain Area: Education & Learning Systems
Method Area: Educational, Human-Centered & Training Methods

Project 2:
Domain Area: Health, Medicine & Life Sciences
Method Area: Data Analysis, Modeling & Computational Methods

Project 3:
Domain Area: Health, Medicine & Life Sciences
Method Are...
    ✅ Project 1: Both categories valid
    ✅ Project 2: Both categories valid
    ✅ Project 3: Both categories valid
    ✅ Project 4: Both categories valid
    ✅ Project 5: Both categories valid
    ✅ Project 6: Both categories valid
  ✅ FIXED Index 12: Domain 'Education & Learning Systems' → 'Education & Learning Systems'
  ✅ FIXED Index 12: Method 'Information, Computation & Digital Systems' → 'Educational, Human-Centered & Training Methods'
  ✅ FIXED Index 70: Domain 'Health, Medicine & Life Sciences' → 'Health, Medicine & Life Sciences'
  ✅ FIXED Index 70: Method 'Information, Computation & Digital Systems' → 'Data Analysis, Modeling & Computational Methods'
  ✅ FIXED Index 94: Domain 'Health, Medicine & Life Sciences' → 'Health, Medicine & Life Sciences'
  ✅ FIXED Index 94: Method 'Information, Computation & Digital Systems' → 'Data Analysis, Modeling & Computational Methods'
  ✅ FIXED Index 102: Domain 'Health, Medicine & Life Sciences' → 'Health, Medicine & Life Sciences'
  ✅ FIXED Index 102: Method 'Information, Computation & Digital Systems' → 'Imaging, Sensing & Measurement Techniques'
  ✅ FIXED Index 632: Domain 'Environment, Climate & Earth Systems' → 'Policy, Governance & Law'
  ✅ FIXED Index 632: Method 'Policy, Governance & Law' → 'Qualitative, Social Inquiry & Policy Research'
  ✅ FIXED Index 702: Domain 'Environment, Climate & Earth Systems' → 'Environment, Climate & Earth Systems'
  ✅ FIXED Index 702: Method 'Policy, Governance & Law' → 'Qualitative, Social Inquiry & Policy Research'

--- S7 Targeted Batch 2/6 (6 projects) ---
  Project 1 (ID 101081928, Index 746):
    Domain: 'Environment, Climate & Earth Systems' ✅
    Method: 'Information, Computation & Digital Systems' ❌
  Project 2 (ID 101188248, Index 749):
    Domain: 'Environment, Climate & Earth Systems' ✅
    Method: 'Information, Computation & Digital Systems' ❌
  Project 3 (ID 101057802, Index 917):
    Domain: 'Information, Computation & Digital Systems' ✅
    Method: 'Policy, Governance & Law' ❌
  Project 4 (ID 101136916, Index 928):
    Domain: 'Economy, Business & Agriculture' ✅
    Method: 'Policy, Governance & Law' ❌
  Project 5 (ID 101080377, Index 1213):
    Domain: 'Environment, Climate & Earth Systems' ✅
    Method: 'Policy, Governance & Law' ❌
  Project 6 (ID 101073928, Index 2617):
    Domain: 'Policy, Governance & Law' ✅
    Method: 'Information, Computation & Digital Systems' ❌
🤖 S7 batch targeted attempt 1...
Raw LLM output preview: Project 1:
Domain Area: Environment, Climate & Earth Systems
Method Area: Engineering Design, Prototyping & Systems Development

Project 2:
Domain Area: Environment, Climate & Earth Systems
Method Area: Data Analysis, Modeling & Computational Methods

Project 3:
Domain Area: Policy, Governance & Law...
    ✅ Project 1: Both categories valid
    ✅ Project 2: Both categories valid
    ✅ Project 3: Both categories valid
    ✅ Project 4: Both categories valid
    ✅ Project 5: Both categories valid
    ✅ Project 6: Both categories valid
  ✅ FIXED Index 746: Domain 'Environment, Climate & Earth Systems' → 'Environment, Climate & Earth Systems'
  ✅ FIXED Index 746: Method 'Information, Computation & Digital Systems' → 'Engineering Design, Prototyping & Systems Development'
  ✅ FIXED Index 749: Domain 'Environment, Climate & Earth Systems' → 'Environment, Climate & Earth Systems'
  ✅ FIXED Index 749: Method 'Information, Computation & Digital Systems' → 'Data Analysis, Modeling & Computational Methods'
  ✅ FIXED Index 917: Domain 'Information, Computation & Digital Systems' → 'Policy, Governance & Law'
  ✅ FIXED Index 917: Method 'Policy, Governance & Law' → 'Qualitative, Social Inquiry & Policy Research'
  ✅ FIXED Index 928: Domain 'Economy, Business & Agriculture' → 'Economy, Business & Agriculture'
  ✅ FIXED Index 928: Method 'Policy, Governance & Law' → 'Innovation, Strategic Management & Evaluation'
  ✅ FIXED Index 1213: Domain 'Environment, Climate & Earth Systems' → 'Policy, Governance & Law'
  ✅ FIXED Index 1213: Method 'Policy, Governance & Law' → 'Qualitative, Social Inquiry & Policy Research'
  ✅ FIXED Index 2617: Domain 'Policy, Governance & Law' → 'Policy, Governance & Law'
  ✅ FIXED Index 2617: Method 'Information, Computation & Digital Systems' → 'Engineering Design, Prototyping & Systems Development'

--- S7 Targeted Batch 3/6 (6 projects) ---
  Project 1 (ID 101137209, Index 3014):
    Domain: 'Environment, Climate & Earth Systems' ✅
    Method: 'Policy, Governance & Law' ❌
  Project 2 (ID 101112781, Index 3104):
    Domain: 'Environment, Climate & Earth Systems' ✅
    Method: 'Policy, Governance & Law' ❌
  Project 3 (ID 101154827, Index 5174):
    Domain: 'Material, Chemical & Bioprocess Development' ❌
    Method: 'Material, Chemical & Bioprocess Development' ✅
  Project 4 (ID 101142229, Index 9070):
    Domain: 'Society, Culture & Human Behavior' ✅
    Method: 'Information, Computation & Digital Systems' ❌
  Project 5 (ID 101158067, Index 9134):
    Domain: 'Humanities, Arts & Cultural Heritage' ✅
    Method: 'Information, Computation & Digital Systems' ❌
  Project 6 (ID 101106196, Index 9953):
    Domain: 'Material, Chemical & Bioprocess Development' ❌
    Method: 'Material, Chemical & Bioprocess Development' ✅
🤖 S7 batch targeted attempt 1...
Raw LLM output preview: Project 1:
Domain Area: Policy, Governance & Law
Method Area: Qualitative, Social Inquiry & Policy Research

Project 2:
Domain Area: Environment, Climate & Earth Systems
Method Area: Innovation, Strategic Management & Evaluation

Project 3:
Domain Area: Physical, Mathematical & Space Sciences
Method...
    ✅ Project 1: Both categories valid
    ✅ Project 2: Both categories valid
    ✅ Project 3: Both categories valid
    ✅ Project 4: Both categories valid
    ✅ Project 5: Both categories valid
    ✅ Project 6: Both categories valid
  ✅ FIXED Index 3014: Domain 'Environment, Climate & Earth Systems' → 'Policy, Governance & Law'
  ✅ FIXED Index 3014: Method 'Policy, Governance & Law' → 'Qualitative, Social Inquiry & Policy Research'
  ✅ FIXED Index 3104: Domain 'Environment, Climate & Earth Systems' → 'Environment, Climate & Earth Systems'
  ✅ FIXED Index 3104: Method 'Policy, Governance & Law' → 'Innovation, Strategic Management & Evaluation'
  ✅ FIXED Index 5174: Domain 'Material, Chemical & Bioprocess Development' → 'Physical, Mathematical & Space Sciences'
  ✅ FIXED Index 5174: Method 'Material, Chemical & Bioprocess Development' → 'Material, Chemical & Bioprocess Development'
  ✅ FIXED Index 9070: Domain 'Society, Culture & Human Behavior' → 'Information, Computation & Digital Systems'
  ✅ FIXED Index 9070: Method 'Information, Computation & Digital Systems' → 'Data Analysis, Modeling & Computational Methods'
  ✅ FIXED Index 9134: Domain 'Humanities, Arts & Cultural Heritage' → 'Humanities, Arts & Cultural Heritage'
  ✅ FIXED Index 9134: Method 'Information, Computation & Digital Systems' → 'Engineering Design, Prototyping & Systems Development'
  ✅ FIXED Index 9953: Domain 'Material, Chemical & Bioprocess Development' → 'Physical, Mathematical & Space Sciences'
  ✅ FIXED Index 9953: Method 'Material, Chemical & Bioprocess Development' → 'Material, Chemical & Bioprocess Development'

--- S7 Targeted Batch 4/6 (6 projects) ---
  Project 1 (ID 101108978, Index 9994):
    Domain: 'Material, Chemical & Bioprocess Development' ❌
    Method: 'Engineering Design, Prototyping & Systems Development' ✅
  Project 2 (ID 101110303, Index 10231):
    Domain: 'Material, Chemical & Bioprocess Development' ❌
    Method: 'Material, Chemical & Bioprocess Development' ✅
  Project 3 (ID 101105057, Index 10400):
    Domain: 'Material, Chemical & Bioprocess Development' ❌
    Method: 'Experimental, Laboratory & Field Investigation' ✅
  Project 4 (ID 101136128, Index 11819):
    Domain: 'Engineering, Manufacturing & Technology' ✅
    Method: 'Information, Computation & Digital Systems' ❌
  Project 5 (ID 101121269, Index 12019):
    Domain: 'Policy, Governance & Law' ✅
    Method: 'Information, Computation & Digital Systems' ❌
  Project 6 (ID 101121309, Index 12024):
    Domain: 'Policy, Governance & Law' ✅
    Method: 'Information, Computation & Digital Systems' ❌
🤖 S7 batch targeted attempt 1...
Raw LLM output preview: Project 1:
Domain Area: Health, Medicine & Life Sciences
Method Area: Material, Chemical & Bioprocess Development

Project 2:
Domain Area: Health, Medicine & Life Sciences
Method Area: Material, Chemical & Bioprocess Development

Project 3:
Domain Area: Health, Medicine & Life Sciences
Method Area: ...
    ✅ Project 1: Both categories valid
    ✅ Project 2: Both categories valid
    ✅ Project 3: Both categories valid
    ✅ Project 4: Both categories valid
    ✅ Project 5: Both categories valid
    ✅ Project 6: Both categories valid
  ✅ FIXED Index 9994: Domain 'Material, Chemical & Bioprocess Development' → 'Health, Medicine & Life Sciences'
  ✅ FIXED Index 9994: Method 'Engineering Design, Prototyping & Systems Development' → 'Material, Chemical & Bioprocess Development'
  ✅ FIXED Index 10231: Domain 'Material, Chemical & Bioprocess Development' → 'Health, Medicine & Life Sciences'
  ✅ FIXED Index 10231: Method 'Material, Chemical & Bioprocess Development' → 'Material, Chemical & Bioprocess Development'
  ✅ FIXED Index 10400: Domain 'Material, Chemical & Bioprocess Development' → 'Health, Medicine & Life Sciences'
  ✅ FIXED Index 10400: Method 'Experimental, Laboratory & Field Investigation' → 'Material, Chemical & Bioprocess Development'
  ✅ FIXED Index 11819: Domain 'Engineering, Manufacturing & Technology' → 'Engineering, Manufacturing & Technology'
  ✅ FIXED Index 11819: Method 'Information, Computation & Digital Systems' → 'Engineering Design, Prototyping & Systems Development'
  ✅ FIXED Index 12019: Domain 'Policy, Governance & Law' → 'Policy, Governance & Law'
  ✅ FIXED Index 12019: Method 'Information, Computation & Digital Systems' → 'Engineering Design, Prototyping & Systems Development'
  ✅ FIXED Index 12024: Domain 'Policy, Governance & Law' → 'Information, Computation & Digital Systems'
  ✅ FIXED Index 12024: Method 'Information, Computation & Digital Systems' → 'Engineering Design, Prototyping & Systems Development'

--- S7 Targeted Batch 5/6 (6 projects) ---
  Project 1 (ID 101040025, Index 12299):
    Domain: 'Material, Chemical & Bioprocess Development' ❌
    Method: 'Experimental, Laboratory & Field Investigation' ✅
  Project 2 (ID 101061016, Index 12623):
    Domain: 'Humanities, Arts & Cultural Heritage' ✅
    Method: 'Information, Computation & Digital Systems' ❌
  Project 3 (ID 101073920, Index 12678):
    Domain: 'Policy, Governance & Law' ✅
    Method: 'Information, Computation & Digital Systems' ❌
  Project 4 (ID 101094901, Index 12710):
    Domain: 'Health, Medicine & Life Sciences' ✅
    Method: 'Information, Computation & Digital Systems' ❌
  Project 5 (ID 101061157, Index 13009):
    Domain: 'Humanities, Arts & Cultural Heritage' ✅
    Method: 'Information, Computation & Digital Systems' ❌
  Project 6 (ID 101148965, Index 14094):
    Domain: 'Material, Chemical & Bioprocess Development' ❌
    Method: 'Experimental, Laboratory & Field Investigation' ✅
🤖 S7 batch targeted attempt 1...
Raw LLM output preview: Project 1:
Domain Area: Physical, Mathematical & Space Sciences
Method Area: Material, Chemical & Bioprocess Development

Project 2:
Domain Area: Humanities, Arts & Cultural Heritage
Method Area: Engineering Design, Prototyping & Systems Development

Project 3:
Domain Area: Policy, Governance & Law
...
    ✅ Project 1: Both categories valid
    ✅ Project 2: Both categories valid
    ✅ Project 3: Both categories valid
    ✅ Project 4: Both categories valid
    ✅ Project 5: Both categories valid
    ✅ Project 6: Both categories valid
  ✅ FIXED Index 12299: Domain 'Material, Chemical & Bioprocess Development' → 'Physical, Mathematical & Space Sciences'
  ✅ FIXED Index 12299: Method 'Experimental, Laboratory & Field Investigation' → 'Material, Chemical & Bioprocess Development'
  ✅ FIXED Index 12623: Domain 'Humanities, Arts & Cultural Heritage' → 'Humanities, Arts & Cultural Heritage'
  ✅ FIXED Index 12623: Method 'Information, Computation & Digital Systems' → 'Engineering Design, Prototyping & Systems Development'
  ✅ FIXED Index 12678: Domain 'Policy, Governance & Law' → 'Policy, Governance & Law'
  ✅ FIXED Index 12678: Method 'Information, Computation & Digital Systems' → 'Engineering Design, Prototyping & Systems Development'
  ✅ FIXED Index 12710: Domain 'Health, Medicine & Life Sciences' → 'Information, Computation & Digital Systems'
  ✅ FIXED Index 12710: Method 'Information, Computation & Digital Systems' → 'Data Analysis, Modeling & Computational Methods'
  ✅ FIXED Index 13009: Domain 'Humanities, Arts & Cultural Heritage' → 'Humanities, Arts & Cultural Heritage'
  ✅ FIXED Index 13009: Method 'Information, Computation & Digital Systems' → 'Data Analysis, Modeling & Computational Methods'
  ✅ FIXED Index 14094: Domain 'Material, Chemical & Bioprocess Development' → 'Physical, Mathematical & Space Sciences'
  ✅ FIXED Index 14094: Method 'Experimental, Laboratory & Field Investigation' → 'Material, Chemical & Bioprocess Development'

--- S7 Targeted Batch 6/6 (5 projects) ---
  Project 1 (ID 190121231, Index 15022):
    Domain: 'Engineering, Manufacturing & Technology' ✅
    Method: 'Information, Computation & Digital Systems' ❌
  Project 2 (ID 190161902, Index 15047):
    Domain: 'Humanities, Arts & Cultural Heritage' ✅
    Method: 'Information, Computation & Digital Systems' ❌
  Project 3 (ID 190153016, Index 15128):
    Domain: 'Economy, Business & Agriculture' ✅
    Method: 'Information, Computation & Digital Systems' ❌
  Project 4 (ID 190154650, Index 15162):
    Domain: 'Health, Medicine & Life Sciences' ✅
    Method: 'Information, Computation & Digital Systems' ❌
  Project 5 (ID 190155873, Index 15259):
    Domain: 'Economy, Business & Agriculture' ✅
    Method: 'Information, Computation & Digital Systems' ❌
🤖 S7 batch targeted attempt 1...
Raw LLM output preview: Project 1:
Domain Area: Engineering, Manufacturing & Technology
Method Area: Data Analysis, Modeling & Computational Methods

Project 2:
Domain Area: Humanities, Arts & Cultural Heritage
Method Area: Data Analysis, Modeling & Computational Methods

Project 3:
Domain Area: Economy, Business & Agricul...
    ✅ Project 1: Both categories valid
    ✅ Project 2: Both categories valid
    ✅ Project 3: Both categories valid
    ✅ Project 4: Both categories valid
    ✅ Project 5: Both categories valid
  ✅ FIXED Index 15022: Domain 'Engineering, Manufacturing & Technology' → 'Engineering, Manufacturing & Technology'
  ✅ FIXED Index 15022: Method 'Information, Computation & Digital Systems' → 'Data Analysis, Modeling & Computational Methods'
  ✅ FIXED Index 15047: Domain 'Humanities, Arts & Cultural Heritage' → 'Humanities, Arts & Cultural Heritage'
  ✅ FIXED Index 15047: Method 'Information, Computation & Digital Systems' → 'Data Analysis, Modeling & Computational Methods'
  ✅ FIXED Index 15128: Domain 'Economy, Business & Agriculture' → 'Economy, Business & Agriculture'
  ✅ FIXED Index 15128: Method 'Information, Computation & Digital Systems' → 'Data Analysis, Modeling & Computational Methods'
  ✅ FIXED Index 15162: Domain 'Health, Medicine & Life Sciences' → 'Health, Medicine & Life Sciences'
  ✅ FIXED Index 15162: Method 'Information, Computation & Digital Systems' → 'Engineering Design, Prototyping & Systems Development'
  ✅ FIXED Index 15259: Domain 'Economy, Business & Agriculture' → 'Economy, Business & Agriculture'
  ✅ FIXED Index 15259: Method 'Information, Computation & Digital Systems' → 'Engineering Design, Prototyping & Systems Development'

💾 SAVING TARGETED S7 FIXES
============================================================
✅ Saved to df_processing_checkpoint.csv
✅ Updated global df_complete

📊 TARGETED S7 FIX SUMMARY:
   Failed projects processed: 35
   Batches processed: 6
   Changes applied: 35
   Success rate: 35/35 (100.0%)

🔍 FINAL S7 VERIFICATION
============================================================
🔍 FINDING S7 FAILED PROJECTS
============================================================
✅ Loaded checkpoint CSV: (15341, 16)
Found 0 projects with bad S7 categories
📊 FINAL S7 STATISTICS:
   Total projects: 15341
   Domain matches: 15341 (100.00%)
   Method matches: 15341 (100.00%)
   Remaining failed projects: 0

🎉🎉🎉 PERFECT! 100% S7 SUCCESS ACHIEVED! 🎉🎉🎉

🎯 S7 TARGETED FIX COMPLETE!

In [161]:
### Simplify  col names
df = pd.read_csv("df_processing_checkpoint.csv")

# Create a renaming dictionary
rename_dict = {
    'l3_tech_domain': 'L3 Domain',
    'l3_strategic_method': 'L3 Method',
    'l3_std_domain_area': 'L4 Domain',
    'l3_std_method_area': 'L4 Method',
    's5_curated_domain': 'L5 Domain',
    's5_curated_method': 'L5 Method',
    's6_refined_domain': 'L6 Domain',
    's6_refined_method': 'L6 Method',
    's7_final_domain': 'L7 Domain',
    's7_final_method': 'L7 Method'
}

# Apply renaming
df.rename(columns=rename_dict, inplace=True)

# Save the updated CSV
df.to_csv("df_processing_checkpoint.csv", index=False)