In [21]:
import pandas as pd
import csv

file_path = "/Users/jonaslorler/Documents/cordis-HORIZONprojects-csv/project.csv"

# Read the file and fix multi-line records
fixed_rows = []
current_row = []
expected_fields = 0

with open(file_path, 'r', encoding='utf-8') as f:
    # Read header
    header_line = f.readline().strip()
    header = list(csv.reader([header_line], delimiter=';', quotechar='"'))[0]
    expected_fields = len(header)
    
    # Find indices of columns we want
    id_idx = header.index('id')
    title_idx = header.index('title')
    objective_idx = header.index('objective')
    
    # Process data lines
    in_multiline = False
    
    for line_num, line in enumerate(f, start=2):
        # Count fields in current line
        try:
            # Try to parse with csv reader
            parsed_line = list(csv.reader([line.strip()], delimiter=';', quotechar='"'))
            if parsed_line:
                fields = parsed_line[0]
            else:
                fields = []
                
            # Check if this is a complete row
            if len(fields) == expected_fields and not in_multiline:
                # This is a complete row - extract only the columns we want
                fixed_rows.append([fields[id_idx], fields[title_idx], fields[objective_idx]])
            elif len(fields) < expected_fields or in_multiline:
                # This might be a continuation or start of a multi-line field
                if not in_multiline:
                    # Start of a multi-line record
                    current_row = fields
                    in_multiline = True
                else:
                    # Continuation of previous line - append text to objective field (usually the multiline culprit)
                    if current_row and len(current_row) > objective_idx:
                        current_row[objective_idx] += ' ' + line.strip()
                    elif current_row:
                        current_row[-1] += ' ' + line.strip()
                    
                    # Check if we now have enough fields
                    if line.strip().endswith('"'):
                        # Try parsing the combined row
                        combined = ';'.join(current_row)
                        parsed = list(csv.reader([combined], delimiter=';', quotechar='"'))
                        if parsed and len(parsed[0]) >= expected_fields:
                            complete_row = parsed[0][:expected_fields]
                            fixed_rows.append([complete_row[id_idx], complete_row[title_idx], complete_row[objective_idx]])
                            in_multiline = False
                            current_row = []
            else:
                # Row has too many fields - truncate and extract what we need
                fixed_rows.append([fields[id_idx], fields[title_idx], fields[objective_idx]])
                
        except Exception as e:
            # If parsing fails, try to handle it gracefully
            if in_multiline and current_row:
                if len(current_row) > objective_idx:
                    current_row[objective_idx] += ' ' + line.strip()
                else:
                    current_row[-1] += ' ' + line.strip()

# Create DataFrame with just the columns we want
df_complete = pd.DataFrame(fixed_rows, columns=['id', 'title', 'objective'])
print(f"Total rows recovered: {len(df_complete)}")

# Clean up the data
df_complete.columns = df_complete.columns.str.strip('"')

# Convert ID to numeric
df_complete['id'] = pd.to_numeric(df_complete['id'], errors='coerce')

# Remove rows without valid ID
df_complete = df_complete.dropna(subset=['id'])

print(f"Rows after cleanup: {len(df_complete)}")
print(df_complete.info())


# Reset options if needed
pd.reset_option('display.max_colwidth')

# Show first few rows
print("\nFirst 15 rows:")
df_complete.head(15)

Total rows recovered: 15341
Rows after cleanup: 15341
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15341 entries, 0 to 15340
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         15341 non-null  int64
 1   title      15341 non-null  object
 2   objective  15341 non-null  object
dtypes: int64(1), object(2)
memory usage: 359.7+ KB
None
id                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                101116741
title                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Digitizing Other Economies: A Comparative Approach
objective    How do longstanding, primarily non-industrial, non-capitalist societies adopt and adapt digital technologies in their daily practices and systems of values? Classical anthropological theory once arranged basic economic types on an evolutionary ladder ranging from hunter-gatherers, horticulturalists, pastoralists, and agriculturalists to industrialists. Today, the existence of these economies other than industrialism are correctly approached not as anachronisms but as contemporaneous to (post-)industrial life. Still, research on digitization has largely taken place in (post-) industrial contexts, meaning we know next to nothing about how different types of longstanding economies adopt and adapt digital technologies. At the same time, researchers have stipulated that digitization threatens global economic diversity. By comparing digitization to processes of colonization, they have argued that digital technologies facilitate assimilation into (post-)industrial economic systems and their often capitalist values by virtue of their technological design. This project empirically investigates these claims through in-depth ethnographic research among hunter-gatherers (Brazilian Amazon), pastoralists (Kyrgyz Republic), horticulturalists (Solomon Islands) and indigenous agriculturalists (India) who have long resisted assimilation into industrial-capitalism. Additional ethnological comparison of the four sites will offer unique macro-level insights into the possibilities for economic diversity in the digital age. Finally, the project advances a novel theoretical and methodological approach that advances both ethnographic research and ethnological comparison. This approach recognizes the significance of both technological design and contextual adaptations and provides tools for new research agendas not just on digital industrial-capitalism but on diverse economic systems and values.
Name: 0, dtype: object

First 15 rows:

,id,title,objective
0,101116741,Digitizing Other Economies: A Comparative Appr...,"How do longstanding, primarily non-industrial,..."
1,101163161,MOLECULAR QUANTUM DYNAMICS IN LOW TEMPERATURE ...,The James Webb Space Telescope (JWST) has ushe...
2,101160499,Multiscale modelling of aberrant phase transit...,The spatiotemporal organization of the cell ma...
3,101166905,The first comprehensive Atlas of the Milky Way,The Milky Way is the cosmic environment in whi...
4,101162875,Untapping multiparametric 2D luminescence sens...,Cellular organisms are complex machines whose ...
5,101167314,Making Sense of the Unexpected in the Gravitat...,General Relativity (GR) is more than a century...
6,101165261,Hernando Colón’s universal library. European c...,While newly printed books were circulating wid...
7,101072693,UA EURATOM NCP SUPPORT OF UKRAINIAN RESEARCH E...,UAinEuratom21 is 24 months project is addresse...
8,101172406,FISA 2025 – EURADWASTE’25 conferences on Eura...,"The FISA-EURADWASTE event is a high-level, res..."
9,101114128,Market & Technology Analysis,Adsorbi is a deep tech startup company from Go...
10,101114412,"Female leadership in Medsensio, a digital heal...",Medsensio was founded in 2017 as a spinout fro...
11,101114020,Detecting the right moment to do embryo transf...,In-vitro Fertilization (IVF) is a well-known f...
12,101114248,Elia - Smart Assistant for English Learning,We are a startup founded exclusively by women ...
13,101052410,EUCYS Leiden2022,The main objective of this Proposal is the org...
14,101172981,European Union Contest for Young Scientists (E...,This proposal concerns the organization of the...

In [27]:
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np

# Prepare the text data - combine title and objective
df_complete['combined_text'] = df_complete['title'] + ' ' + df_complete['objective']

# Remove any rows with missing text
df_complete = df_complete.dropna(subset=['combined_text'])
df_complete = df_complete[df_complete['combined_text'].str.len() > 50]  # Remove very short texts

print(f"Processing {len(df_complete)} documents")

Processing 15341 documents

In [39]:
import pandas as pd
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer # Import CountVectorizer
import csv # For saving output with QUOTE_ALL


# --- BERTopic Configuration ---
SAMPLE_SIZE = None  # Set to None to use all data from df_complete
EMBEDDING_MODEL = "all-MiniLM-L6-v2"
# Adjust MIN_TOPIC_SIZE based on your dataset size. If using the small simulation, make it smaller.
# For the full dataset, 15-50 might be reasonable start. For the 10-doc simulation, needs to be smaller e.g. 2-3
MIN_TOPIC_SIZE = 3 # Adjusted for the small 10-doc simulation
NR_TOPICS = "auto"


def run_bertopic_on_dataframe(df: pd.DataFrame):
    """
    Runs BERTopic analysis on a pre-loaded DataFrame with 'id', 'title', 'objective',
    incorporating stopword removal for better topic representations.
    """
    if not isinstance(df, pd.DataFrame) or df.empty:
        print("ERROR: Input is not a valid or non-empty DataFrame. Exiting.")
        return None, None # Return None for both results if error

    required_cols = ['id', 'title', 'objective']
    if not all(col in df.columns for col in required_cols):
        print(f"ERROR: DataFrame must contain columns: {required_cols}")
        print(f"Available columns: {df.columns.tolist()}")
        return None, None

    print(f"Processing DataFrame with {len(df)} rows for BERTopic.")

    # --- 1. Combine 'title' and 'objective' ---
    print("\nCombining 'title' and 'objective' columns...")
    df_working = df.copy()
    df_working['title'] = df_working['title'].fillna('').astype(str)
    df_working['objective'] = df_working['objective'].fillna('').astype(str)
    df_working['combined_text'] = df_working['title'] + " " + df_working['objective']
    df_working['combined_text'] = df_working['combined_text'].str.strip()

    print("Successfully created 'combined_text' column.")
    if not df_working.empty:
        example_text_display = df_working['combined_text'].iloc[0][:200] if len(df_working['combined_text'].iloc[0]) > 0 else "N/A (empty)"
        print(f"Example combined text: '{example_text_display}...'")
    
    df_filtered = df_working[df_working['combined_text'] != ''].copy()
    texts_for_bertopic = df_filtered['combined_text'].tolist()
    ids_for_bertopic = df_filtered['id'].tolist()

    if not texts_for_bertopic:
        print("ERROR: No text data available for BERTopic after combining. Check DataFrame content.")
        return None, None
    
    print(f"Number of non-empty documents for BERTopic: {len(texts_for_bertopic)}")

    if len(texts_for_bertopic) < MIN_TOPIC_SIZE * 2 and len(texts_for_bertopic) > 0: # Heuristic: need enough docs for clustering
        print(f"Warning: Number of documents ({len(texts_for_bertopic)}) is very small for min_topic_size={MIN_TOPIC_SIZE}. Results may be poor or errors might occur.")
        # Adjust min_topic_size if too few documents for it
        new_min_topic_size = max(2, len(texts_for_bertopic) // 3) # ensure it's at least 2
        if new_min_topic_size < MIN_TOPIC_SIZE:
            print(f"Adjusting min_topic_size to {new_min_topic_size} due to small dataset size.")
            current_min_topic_size = new_min_topic_size
        else:
            current_min_topic_size = MIN_TOPIC_SIZE
    elif len(texts_for_bertopic) == 0:
        print("ERROR: No documents to process after filtering.")
        return None, None
    else:
        current_min_topic_size = MIN_TOPIC_SIZE


    # Apply sampling if SAMPLE_SIZE is set
    if SAMPLE_SIZE and len(texts_for_bertopic) > SAMPLE_SIZE:
        print(f"Sampling {SAMPLE_SIZE} documents for BERTopic processing...")
        sampled_df_indices = df_filtered.sample(n=SAMPLE_SIZE, random_state=42).index
        texts_to_process = df_filtered.loc[sampled_df_indices, 'combined_text'].tolist()
        ids_to_process = df_filtered.loc[sampled_df_indices, 'id'].tolist()
    else:
        print("Processing all available non-empty documents from the DataFrame...")
        texts_to_process = texts_for_bertopic
        ids_to_process = ids_for_bertopic


    # --- 2. Initialize BERTopic with Stopword Removal ---
    print(f"\nInitializing BERTopic with model: {EMBEDDING_MODEL}")
    print(f"Min topic size: {current_min_topic_size}, Nr topics: {NR_TOPICS}")
    print("Using CountVectorizer with English stopwords for topic representation.")

    # Define a CountVectorizer with English stopwords
    vectorizer = CountVectorizer(stop_words="english")

    topic_model = BERTopic(
        embedding_model=EMBEDDING_MODEL,
        vectorizer_model=vectorizer,  # Use the vectorizer with stopwords
        min_topic_size=current_min_topic_size, # Use potentially adjusted min_topic_size
        nr_topics=NR_TOPICS,
        verbose=True,
    )

    print("Fitting BERTopic model... This can take a significant amount of time.")
    try:
        topics, probabilities = topic_model.fit_transform(texts_to_process)
        print("BERTopic model fitting complete.")
    except Exception as e:
        print(f"ERROR: BERTopic fitting failed: {e}")
        import traceback
        traceback.print_exc()
        return None, None

    # --- 3. Explore and Save Results ---
    print("\n--- BERTopic Results ---")
    topic_info = topic_model.get_topic_info()
    print("Top topics found:")
    print(topic_info.head(15))

    if -1 in topic_info['Topic'].values:
        outlier_count_series = topic_info[topic_info['Topic'] == -1]['Count']
        if not outlier_count_series.empty:
            outlier_count = outlier_count_series.iloc[0]
            print(f"\nNumber of outlier documents (Topic -1): {outlier_count}")
        else:
            print("\nNo outlier topic (-1) found in topic_info, or it has no count.")


    results_df = pd.DataFrame({
        'id': ids_to_process,
        'topic_id': topics
    })
    
    topic_labels_map = {topic_id: "_".join([word for word, _ in topic_model.get_topic(topic_id)[:4]]) # Show top 4 words
                        for topic_id in set(topics) if topic_model.get_topic(topic_id) is not None}
    if -1 in set(topics) and -1 not in topic_labels_map : # Handle outliers if not already (e.g. if get_topic(-1) was None)
        topic_labels_map[-1] = "Outliers"
    results_df['topic_label'] = results_df['topic_id'].map(topic_labels_map)
    
    final_output_df_subset = df_filtered[df_filtered['id'].isin(ids_to_process)][['id', 'title', 'objective', 'combined_text']].copy()
    final_output_df = pd.merge(final_output_df_subset, results_df, on='id', how='left')

    output_csv_path = "cordis_projects_with_bertopics_stopwords_removed.csv"
    print(f"\nSaving results with topic assignments to: {output_csv_path}")
    final_output_df.to_csv(output_csv_path, index=False, quoting=csv.QUOTE_ALL)

    model_save_path = "bertopic_cordis_model_stopwords_removed"
    print(f"Saving BERTopic model to: {model_save_path}")
    topic_model.save(model_save_path, serialization="safetensors")

    print("\nScript finished successfully!")
    return final_output_df, topic_model


# --- How to use it ---
if __name__ == "__main__":
    if 'df_complete' in locals() or 'df_complete' in globals():
        print("Using existing df_complete for BERTopic analysis.")
        final_results_df, trained_model = run_bertopic_on_dataframe(df_complete) # Call the function
        if final_results_df is not None:
            print("\nDisplaying head of the final results DataFrame:")
            print(final_results_df.head())
    else:
        print("ERROR: df_complete is not defined. Please ensure it's loaded before running BERTopic analysis.")

2025-05-13 17:05:17,055 - BERTopic - Embedding - Transforming documents to embeddings.

Using existing df_complete for BERTopic analysis.
Processing DataFrame with 15341 rows for BERTopic.

Combining 'title' and 'objective' columns...
Successfully created 'combined_text' column.
Example combined text: 'Digitizing Other Economies: A Comparative Approach How do longstanding, primarily non-industrial, non-capitalist societies adopt and adapt digital technologies in their daily practices and systems of ...'
Number of non-empty documents for BERTopic: 15341
Processing all available non-empty documents from the DataFrame...

Initializing BERTopic with model: all-MiniLM-L6-v2
Min topic size: 3, Nr topics: auto
Using CountVectorizer with English stopwords for topic representation.
Fitting BERTopic model... This can take a significant amount of time.

Batches:   0%|          | 0/480 [00:00<?, ?it/s]

2025-05-13 17:06:24,931 - BERTopic - Embedding - Completed ✓
2025-05-13 17:06:24,932 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-05-13 17:06:26,413 - BERTopic - Dimensionality - Completed ✓
2025-05-13 17:06:26,414 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-05-13 17:06:26,739 - BERTopic - Cluster - Completed ✓
2025-05-13 17:06:26,739 - BERTopic - Representation - Extracting topics from clusters using representation models.
2025-05-13 17:06:28,266 - BERTopic - Representation - Completed ✓
2025-05-13 17:06:28,268 - BERTopic - Topic reduction - Reducing number of topics
2025-05-13 17:06:30,347 - BERTopic - Topic reduction - Reduced number of topics from 894 to 615

BERTopic model fitting complete.

--- BERTopic Results ---
Top topics found:
    Topic  Count                                                 Name  \
0      -1   5122                         -1_research_project_new_cell
1       0    448                     0_climate_food_bioeconomy_forest
2       1    317                        1_galaxies_dark_stars_stellar
3       2    278                  2_researchers_night_science_schools
4       3    262                        3_brain_neural_visual_sensory
5       4    176                           4_battery_batteries_li_ion
6       5    154                     5_quantum_qubits_qubit_computers
7       6    142                6_democracy_democratic_political_news
8       7    128                          7_marine_ocean_blue_coastal
9       8    121               8_rehabilitation_patient_spinal_stroke
10      9    119                9_circular_plastic_plastics_packaging
11     10    114          10_archaeological_roman_ancient_archaeology
12     11    111                         11_perovskite_solar_pv_oleds
13     12     95                    12_marine_archaea_ocean_microbial
14     13     95  13_manufacturing_remanufacturing_production_product

                                                                                                 Representation  \
0                                [research, project, new, cell, data, cells, based, development, cancer, human]
1                         [climate, food, bioeconomy, forest, soil, biodiversity, nbs, policy, farmers, cities]
2                    [galaxies, dark, stars, stellar, galaxy, gravitational, universe, physics, star, neutrino]
3               [researchers, night, science, schools, activities, public, innovation, careers, research, 2022]
4                       [brain, neural, visual, sensory, language, cognitive, cortex, motor, cortical, neurons]
5                        [battery, batteries, li, ion, charging, lithium, electrolyte, storage, cathode, anode]
6         [quantum, qubits, qubit, computers, photonic, classical, superconducting, computing, photon, optical]
7         [democracy, democratic, political, news, media, disinformation, citizens, trust, democracies, online]
8                       [marine, ocean, blue, coastal, seas, biodiversity, sea, restoration, waters, fisheries]
9                    [rehabilitation, patient, spinal, stroke, ai, healthcare, clinical, cord, patients, motor]
10                  [circular, plastic, plastics, packaging, economy, waste, recycling, circularity, wood, bio]
11  [archaeological, roman, ancient, archaeology, sites, extinction, past, palaeolithic, prehistoric, cultural]
12                   [perovskite, solar, pv, oleds, organic, emitting, photovoltaics, photovoltaic, tadf, pscs]
13            [marine, archaea, ocean, microbial, coral, archaeal, biogeochemical, eukaryotes, carbon, methane]
14          [manufacturing, remanufacturing, production, product, chains, circular, digital, value, ai, supply]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Representative_Docs
0                                                                                                           [Autonomous Living Cell analYsis ON-chip for Evaluation of space Environment Effects: low-power integrated lab-on-chip for the assessment of radiation damage on living systems in nanosatellite missions The project aims at the design and realization of a new analytical platform implementing a series of innovative technologies able to provide a highly-integrated solution for the analysis in-situ of the effects of the space environment on model biological systems and for the evaluation of shielding technologies combined with radioprotective agents. The main objective of the project will be achieved through the development of a lab-on-chip device with integrated thin-film sensors and actuators that will implement an extremely compact cell-incubator capable to sample the status of the cell culture during a space mission using real-time monitoring techniques based on bioluminescence. Genetically modified microorganisms will be designed in order to monitor specific stress responses based on a luciferase-based reporter system. An electronic system will be integrated in the platform for the characterization of the radiation environment allowing  to evaluate the correlation between observed biological effects and radiation exposure.The main features of the proposed technology include low power consumption, extreme compactness, high data efficiency and full automation making it suitable for cubesat missions. In particular, a complete cubesat payload will be designed to address and solve any integration issue and to provide a test bench for a preliminary set of experiments to be carried out on ground facilities simulating the deep space environment. The proposed system will therefore represent a key element to pave the route toward deep space human mission as it offers the possibility to test the effects of long term exposure to the space environment on model biological systems using simple platforms as cubesats. This opens new scenarios where minor effortwill be required to plan multiple low-cost missions for improving the risk modeling and for testing new countermeasures in a continuous-improvement scheme., Alliance for Modelling Industries towards the Green Deal’s objectives And circuLArity The objective of the European Green Deal policy is to be climate-neutral by 2050. However, the key problem of the industry transition towards climate neutrality is that the combined response of demand, global trade and industrial production to policy measures is highly complex.The aim of the AMIGDALA project is to facilitate decision makers in governments and in the EU’s industries to define and evaluate pathways towards climate neutrality, circularity and sustainability. In this project we combine insights in decision-making with integrated modelling of scenarios to analyze transformation pathways. We analyze decisions-making in government and in industry by the control options that they have such as incentives, regulatory measures and investments in capital projects to contribute to the Green Deal’s objectives. We deliver an integrated model to represent EU industry’s transformation pathways up to 2070 and cover historical developments from 1990. We develop a method to combine established models of separate domains and let them operate as-one. This integrated model shows the combined effect of control options on economy, trade, energy, materials flow, biomass and industrial production on an EU systems-level and within a global context. On a local-level we use models to analyze the decisions by industry clusters to invest in transformative solutions and utility operators to build infrastructure. With the integrated model we run scenarios that we develop on the basis of the control options of decisionmakers to achieve industrial transformation towards climate neutrality. The integrated model allows to analyze the effect of framework conditions on the uptake of transformative solutions and products and on energy demand, emissions, and material use. The AMIGDALA consortium has a deep and shared knowledge of technologies, economy, life cycle analysis and complex systems modelling and decision support analysis., Creating FUTUre societal RESILIENCE through innovative, science-based co-creation labs The FUTURESILIENCE project aims to strengthen European economic and social resilience through an enhanced ability to quickly respond to future crises. This will be accomplished by facilitating the fast and effective use of policy relevant research and innovation (R&I) findings for actors at national, regional and local level. The project has four specific objectives:1) Map existing policy relevant European R&I findings with high potential to inform policy making for economic and social resilience, and to help address societal challenges at local level2) Define a set of methodologies for testing in how far the identified R&I findings can inform policies addressing national, regional and local needs3) Implement the testing methodologies through multi-stakeholder experiments across Europe in co-creation with stakeholders from research, policy, economy, civil society organisations as well as citizens4) Develop a Knowledge Base of the successfully tested research findings with high capacity to inform policy actors and a Toolbox of methods for testing policy relevant research findingsFUTURESILIENCE will set up 'Future Resilience Labs' to test policy relevant R&I findings through 10 pilot exercises: three pre-identified working on climate change, migration and the financial crisis and urban planning; and seven selected through an open call. During the experimentation, multiple stakeholders will discuss and test evidence-based strategies tailored to their specific context and matching their local needs, aiming at reducing vulnerabilities and increasing capacities to be prepared for multiple types of possible crisis. The project will be implemented by a robust consortium with know-how in the fields of resilience, R&I policy and crisis management as well as experience with various co-creation and participative methodologies and specifically hands-on experience with foresight, scenario planning, virtual simulation and agent-based modelling.]

In [53]:
import pandas as pd
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
import csv

# --- BERTopic Configuration ---
# SAMPLE_SIZE = None # Set to None to use all data from df_complete, or a number for sampling
# Forcing 100 topics might require a decent number of documents.
# If df_complete is small, BERTopic might struggle to find 100 distinct topics.
# Consider SAMPLE_SIZE based on the size of your actual df_complete.
# For now, assuming you want to run on the full df_complete.
SAMPLE_SIZE = None

EMBEDDING_MODEL = "all-mpnet-base-v2"
# Adjust MIN_TOPIC_SIZE based on your dataset size and desired granularity for 100 topics
# A common heuristic: total_docs / nr_topics / (some_factor like 2 or 3)
# If you have 15000 docs and 100 topics, average topic size is 150.
# min_topic_size could be around 25-75.
MIN_TOPIC_SIZE = 25 # You might need to adjust this
NR_TOPICS = 100     # Forcing 100 topics

# Define custom stopwords, including "research" and "project"
CUSTOM_STOPWORDS = ["research", "project", "study", "aims", "objective", "proposal", "horizon", "european", "eu", "article", "paper", "chapter", "section", "conclusion", "introduction", "results", "discussion", "methodology", "approach", "work", "based", "provide", "develop", "development", "understand", "understanding", "data", "analysis", "system", "model", "process", "new", "novel", "high", "low", "within", "also", "however", "therefore", "further", "different", "various", "specific", "general", "important", "key", "main", "focus", "context", "issue", "problem", "solution", "impact", "effect", "role", "field", "area", "use", "application", "potential", "value", "framework"]


def run_bertopic_on_dataframe_v2(df: pd.DataFrame):
    """
    Streamlined BERTopic analysis on a pre-loaded DataFrame.
    - Uses custom stopwords including "research" and "project".
    - Aims for a specified number of topics (e.g., 100).
    - Outputs a cleaner CSV with only id, combined_text, topic_id, topic_label.
    """
    if not isinstance(df, pd.DataFrame) or df.empty:
        print("ERROR: Input is not a valid or non-empty DataFrame.")
        return None, None

    required_cols = ['id', 'title', 'objective']
    if not all(col in df.columns for col in required_cols):
        print(f"ERROR: DataFrame must contain columns: {required_cols}. Got: {df.columns.tolist()}")
        return None, None

    print(f"Processing DataFrame with {len(df)} rows for BERTopic.")

    # --- 1. Combine 'title' and 'objective', prepare texts ---
    df_working = df.copy()
    df_working['title'] = df_working['title'].fillna('').astype(str)
    df_working['objective'] = df_working['objective'].fillna('').astype(str)
    df_working['combined_text'] = df_working['title'] + " " + df_working['objective']
    df_working['combined_text'] = df_working['combined_text'].str.strip()
    
    df_filtered = df_working[df_working['combined_text'] != ''].copy()
    texts_for_bertopic = df_filtered['combined_text'].tolist()
    ids_for_bertopic = df_filtered['id'].tolist() # Original IDs

    if not texts_for_bertopic:
        print("ERROR: No text data available for BERTopic after combining.")
        return None, None
    
    print(f"Number of non-empty documents for BERTopic: {len(texts_for_bertopic)}")

    current_min_topic_size = MIN_TOPIC_SIZE
    if len(texts_for_bertopic) < NR_TOPICS * (MIN_TOPIC_SIZE / 2) and len(texts_for_bertopic) > 0 : # Heuristic
         print(f"Warning: Dataset size ({len(texts_for_bertopic)}) might be small for {NR_TOPICS} topics with min_topic_size={MIN_TOPIC_SIZE}.")
         # Optionally adjust min_topic_size if dataset is too small for the target number of topics
         # new_min = max(2, int(len(texts_for_bertopic) / (NR_TOPICS * 1.5) ))
         # if new_min < MIN_TOPIC_SIZE:
         # current_min_topic_size = new_min
         # print(f"Adjusted min_topic_size to {current_min_topic_size}")


    # Apply sampling if SAMPLE_SIZE is set (though it's None by default now)
    if SAMPLE_SIZE and len(texts_for_bertopic) > SAMPLE_SIZE:
        print(f"Sampling {SAMPLE_SIZE} documents for BERTopic processing...")
        sampled_df_indices = df_filtered.sample(n=SAMPLE_SIZE, random_state=42).index
        texts_to_process = df_filtered.loc[sampled_df_indices, 'combined_text'].tolist()
        ids_to_process = df_filtered.loc[sampled_df_indices, 'id'].tolist()
    else:
        texts_to_process = texts_for_bertopic
        ids_to_process = ids_for_bertopic

    if not texts_to_process:
        print("ERROR: No texts to process after sampling (if any).")
        return None, None

    # --- 2. Initialize BERTopic ---
    print(f"\nInitializing BERTopic: Model={EMBEDDING_MODEL}, MinTopicSize={current_min_topic_size}, TargetTopics={NR_TOPICS}")
    
    # Combine sklearn's English stopwords with our custom list
    from sklearn.feature_extraction import _stop_words
    all_stopwords = list(_stop_words.ENGLISH_STOP_WORDS) + CUSTOM_STOPWORDS
    # Remove duplicates that might arise
    all_stopwords = sorted(list(set(all_stopwords)))


    vectorizer = CountVectorizer(stop_words=all_stopwords, ngram_range=(1,1)) # Using (1,1) for now, can try (1,2) later

    topic_model = BERTopic(
        embedding_model=EMBEDDING_MODEL,
        vectorizer_model=vectorizer,
        min_topic_size=current_min_topic_size,
        nr_topics=NR_TOPICS, # Instruct BERTopic to reduce topics to this number
        verbose=True,
        calculate_probabilities=False # Can speed up if probabilities aren't strictly needed for this run
    )

    print("Fitting BERTopic model...")
    try:
        topics, _ = topic_model.fit_transform(texts_to_process) # Probabilities not stored if calculate_probabilities=False
        print("BERTopic model fitting complete.")
    except Exception as e:
        print(f"ERROR: BERTopic fitting failed: {e}")
        import traceback
        traceback.print_exc()
        return None, None

    # --- 3. Prepare and Save Results ---
    print("\n--- BERTopic Results ---")
    topic_info = topic_model.get_topic_info()
    print(f"Number of topics found (after potential reduction): {len(topic_info)}")
    print("Top topics found:")
    print(topic_info.head(15)) # Display more topics

    results_df = pd.DataFrame({
        'id': ids_to_process,
        'topic_id': topics
    })
    
    # Generate topic labels (top N words)
    topic_labels_map = {topic_id: "_".join([word for word, _ in topic_model.get_topic(topic_id)[:4]]) # Top 4 words
                        for topic_id in topic_info['Topic'] # Iterate through actual topics found
                        if topic_model.get_topic(topic_id) is not None}
    if -1 in topic_info['Topic'].values and -1 not in topic_labels_map:
        topic_labels_map[-1] = "Outliers"
    results_df['topic_label'] = results_df['topic_id'].map(topic_labels_map)
    
    # Merge with the 'combined_text' from the processed documents
    # df_filtered contains the 'id' and 'combined_text' for all docs that had text.
    # We need to merge results_df (which has 'id' and topic info for *processed* docs) back to this.
    
    # Create a temporary DataFrame with id and combined_text for merging
    processed_texts_df = pd.DataFrame({'id': ids_to_process, 'combined_text': texts_to_process})
    
    # Merge the BERTopic results (topic_id, topic_label) with this processed_texts_df
    final_output_df = pd.merge(processed_texts_df, results_df[['id', 'topic_id', 'topic_label']], on='id', how='left')
    
    # Ensure 'id' column is first, then 'combined_text', 'topic_id', 'topic_label'
    final_output_df = final_output_df[['id', 'combined_text', 'topic_id', 'topic_label']]


    output_csv_path = "cordis_bertopics_100topics_custom_stopwords.csv"
    print(f"\nSaving results to: {output_csv_path}")
    final_output_df.to_csv(output_csv_path, index=False, quoting=csv.QUOTE_ALL)

    model_save_path = "bertopic_cordis_100topics_custom_stopwords_model"
    print(f"Saving BERTopic model to: {model_save_path}")
    topic_model.save(model_save_path, serialization="safetensors")

    print("\nScript finished successfully!")
    return final_output_df, topic_model

In [55]:
import pandas as pd
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
import csv

# --- BERTopic Configuration ---
SAMPLE_SIZE = None # Set to None to run on the full df_complete

# Use the more powerful all-mpnet-base-v2 model
EMBEDDING_MODEL = "sentence-transformers/all-mpnet-base-v2"

# For initial granular topics with combined text (which is richer):
INITIAL_MIN_TOPIC_SIZE = 20 # Can be a bit larger than for titles only (adjust this!)
INITIAL_NR_TOPICS = "auto"  # Let BERTopic find as many as it can

# Target for final general topics:
FINAL_NR_TOPICS = 100

CUSTOM_STOPWORDS = ["research", "project", "study", "aims", "objective", "proposal", "horizon", "european", "eu", "article", "paper", "chapter", "section", "conclusion", "introduction", "results", "discussion", "methodology", "approach", "work", "based", "provide", "develop", "development", "understand", "understanding", "data", "analysis", "system", "model", "process", "new", "novel", "high", "low", "within", "also", "however", "therefore", "further", "different", "various", "specific", "general", "important", "key", "main", "focus", "context", "issue", "problem", "solution", "impact", "effect", "role", "field", "area", "use", "application", "potential", "value", "framework"]


def run_bertopic_combined_text_hierarchical_mpnet(df: pd.DataFrame):
    """
    BERTopic analysis on combined 'title' + 'objective'.
    - Uses sentence-transformers/all-mpnet-base-v2 for embeddings.
    - Uses custom stopwords.
    - Finds granular topics first, then reduces to FINAL_NR_TOPICS.
    - Outputs a CSV with id, combined_text, topic_id, topic_label.
    """
    if not isinstance(df, pd.DataFrame) or df.empty:
        print("ERROR: Input is not a valid or non-empty DataFrame.")
        return None, None

    required_cols = ['id', 'title', 'objective']
    if not all(col in df.columns for col in required_cols):
        print(f"ERROR: DataFrame must contain columns: {required_cols}. Got: {df.columns.tolist()}")
        return None, None

    print(f"Processing DataFrame with {len(df)} rows for BERTopic (Combined Text, MPNet, Hierarchical).")

    # --- 1. Combine 'title' and 'objective', prepare texts ---
    df_working = df.copy()
    df_working['title'] = df_working['title'].fillna('').astype(str)
    df_working['objective'] = df_working['objective'].fillna('').astype(str)
    df_working['combined_text'] = df_working['title'] + " " + df_working['objective']
    df_working['combined_text'] = df_working['combined_text'].str.strip()
    
    df_filtered = df_working[df_working['combined_text'] != ''].copy()
    texts_to_process = df_filtered['combined_text'].tolist()
    ids_to_process = df_filtered['id'].tolist() # Original IDs

    if not texts_to_process:
        print("ERROR: No text data available for BERTopic after combining.")
        return None, None
    
    print(f"Number of non-empty combined texts for BERTopic: {len(texts_to_process)}")

    # Apply sampling if SAMPLE_SIZE is set
    if SAMPLE_SIZE and len(texts_to_process) > SAMPLE_SIZE:
        print(f"Sampling {SAMPLE_SIZE} documents for BERTopic processing...")
        # Create a temporary DataFrame for sampling to keep ids and texts aligned
        temp_df_for_sampling = pd.DataFrame({'id': ids_to_process, 'text_data': texts_to_process})
        sampled_data = temp_df_for_sampling.sample(n=SAMPLE_SIZE, random_state=42)
        texts_to_process = sampled_data['text_data'].tolist()
        ids_to_process = sampled_data['id'].tolist()
    # else: # texts_to_process and ids_to_process are already set for full data

    if not texts_to_process:
        print("ERROR: No texts to process after potential sampling.")
        return None, None

    # --- 2. Initialize BERTopic for Granular Topics ---
    print(f"\nStep 1: Initializing BERTopic for GRANULAR topics.")
    print(f"Embedding Model={EMBEDDING_MODEL}, MinTopicSize={INITIAL_MIN_TOPIC_SIZE}, TargetTopics={INITIAL_NR_TOPICS}")
    
    from sklearn.feature_extraction import _stop_words
    all_stopwords = sorted(list(set(list(_stop_words.ENGLISH_STOP_WORDS) + CUSTOM_STOPWORDS)))

    vectorizer = CountVectorizer(stop_words=all_stopwords, ngram_range=(1, 2)) # Using (1,2) ngrams

    topic_model = BERTopic(
        embedding_model=EMBEDDING_MODEL, # Using all-mpnet-base-v2
        vectorizer_model=vectorizer,
        min_topic_size=INITIAL_MIN_TOPIC_SIZE,
        nr_topics=INITIAL_NR_TOPICS, # "auto"
        verbose=True,
        calculate_probabilities=True 
    )

    print("Fitting BERTopic model for GRANULAR topics (using MPNet)... This will take longer.")
    try:
        initial_topics, initial_probabilities = topic_model.fit_transform(texts_to_process)
        print("Initial GRANULAR topic model fitting complete.")
    except Exception as e:
        print(f"ERROR: BERTopic initial fitting failed: {e}")
        import traceback
        traceback.print_exc()
        return None, None

    initial_topic_info = topic_model.get_topic_info()
    print(f"\nNumber of initial GRANULAR topics found: {len(initial_topic_info)}")
    print("Top initial granular topics:")
    print(initial_topic_info.head(10))
    
    # --- 3. Reduce to More General Topics ---
    # Only reduce if the number of found topics (excluding outlier) is greater than target
    if (len(initial_topic_info) - (1 if -1 in initial_topic_info["Topic"].values else 0)) > FINAL_NR_TOPICS:
        print(f"\nStep 2: Reducing topics from {len(initial_topic_info)-1} to {FINAL_NR_TOPICS} general topics...")
        try:
            new_topics_assigned = topic_model.reduce_topics(texts_to_process, nr_topics=FINAL_NR_TOPICS)
            print("Topic reduction complete.")
        except Exception as e:
            print(f"ERROR: Topic reduction failed: {e}")
            new_topics_assigned = initial_topics 
            print("Proceeding with initial granular topics due to reduction error.")
    else:
        print(f"\nNumber of initial topics ({len(initial_topic_info)-1}) is already less than or equal to target ({FINAL_NR_TOPICS}). No reduction performed.")
        new_topics_assigned = initial_topics

    # --- 4. Prepare and Save Final Results ---
    final_topic_info = topic_model.get_topic_info()
    print(f"\n--- Final BERTopic Results ({len(final_topic_info)-1 if -1 in final_topic_info['Topic'].values else len(final_topic_info)} General Topics) ---") # Adjusted count
    print("Top general topics found:")
    print(final_topic_info.head(15))

    results_df = pd.DataFrame({
        'id': ids_to_process,
        'topic_id': new_topics_assigned
    })
    
    topic_labels_map = {topic_id: "_".join([word for word, _ in topic_model.get_topic(topic_id)[:4]])
                        for topic_id in final_topic_info['Topic'] 
                        if topic_model.get_topic(topic_id) is not None}
    if -1 in final_topic_info['Topic'].values and -1 not in topic_labels_map:
        topic_labels_map[-1] = "Outliers"
    results_df['topic_label'] = results_df['topic_id'].map(topic_labels_map)
    
    processed_texts_df = pd.DataFrame({'id': ids_to_process, 'combined_text': texts_to_process})
    final_output_df = pd.merge(processed_texts_df, results_df[['id', 'topic_id', 'topic_label']], on='id', how='left')
    final_output_df = final_output_df[['id', 'combined_text', 'topic_id', 'topic_label']]

    output_csv_path = f"cordis_bertopics_mpnet_hierarchical_{FINAL_NR_TOPICS}topics.csv"
    print(f"\nSaving results to: {output_csv_path}")
    final_output_df.to_csv(output_csv_path, index=False, quoting=csv.QUOTE_ALL)

    model_save_path = f"bertopic_cordis_mpnet_hierarchical_{FINAL_NR_TOPICS}topics_model"
    print(f"Saving BERTopic model to: {model_save_path}")
    topic_model.save(model_save_path, serialization="safetensors")

    print("\nScript finished successfully!")
    return final_output_df, topic_model

# --- How to use it ---
if __name__ == "__main__":
    if 'df_complete' not in globals() and 'df_complete' not in locals():
        print("ERROR: df_complete is not defined. Please load or create it first.")
        # For testing, you might want to un-comment a simulation block or load a pickled DataFrame.
        # Example placeholder for testing if df_complete isn't available:
        # data_for_simulation = {'id': [1,2,3]*100, 'title': ['t']*300, 'objective': ['This is a sample objective with several words to ensure text processing works.']*300} # Minimal data
        # df_complete = pd.DataFrame(data_for_simulation)
        # df_complete['id'] = df_complete.index # ensure unique ids for testing
        exit()

    print("Using existing df_complete for HIERARCHICAL BERTopic analysis with MPNet (Combined Text).")
    final_results_df_mpnet, trained_model_mpnet = run_bertopic_combined_text_hierarchical_mpnet(df_complete) # Call the new function
    if final_results_df_mpnet is not None:
        print("\nDisplaying head of the final MPNet hierarchical results DataFrame:")
        print(final_results_df_mpnet.head())
        print(f"\nShape of final results: {final_results_df_mpnet.shape}")
        print(f"\nValue counts for topic_label (top 10):")
        print(final_results_df_mpnet['topic_label'].value_counts().head(10))

2025-05-13 17:48:17,404 - BERTopic - Embedding - Transforming documents to embeddings.

Using existing df_complete for HIERARCHICAL BERTopic analysis with MPNet (Combined Text).
Processing DataFrame with 15341 rows for BERTopic (Combined Text, MPNet, Hierarchical).
Number of non-empty combined texts for BERTopic: 15341

Step 1: Initializing BERTopic for GRANULAR topics.
Embedding Model=sentence-transformers/all-mpnet-base-v2, MinTopicSize=20, TargetTopics=auto
Fitting BERTopic model for GRANULAR topics (using MPNet)... This will take longer.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.4k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/480 [00:00<?, ?it/s]

2025-05-13 17:56:23,477 - BERTopic - Embedding - Completed ✓
2025-05-13 17:56:23,477 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-05-13 17:56:25,321 - BERTopic - Dimensionality - Completed ✓
2025-05-13 17:56:25,321 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-05-13 17:56:29,636 - BERTopic - Cluster - Completed ✓
2025-05-13 17:56:29,637 - BERTopic - Representation - Extracting topics from clusters using representation models.
2025-05-13 17:56:36,301 - BERTopic - Representation - Completed ✓
2025-05-13 17:56:36,311 - BERTopic - Topic reduction - Reducing number of topics
2025-05-13 17:56:42,853 - BERTopic - Topic reduction - Reduced number of topics from 140 to 50

Initial GRANULAR topic model fitting complete.

Number of initial GRANULAR topics found: 50
Top initial granular topics:
   Topic  Count                                    Name  \
0     -1   5900    -1_technology_social_knowledge_using
1      0   4284  0_energy_climate_sustainable_solutions
2      1   1229              1_cell_cells_cancer_immune
3      2    385      2_health_patients_patient_clinical
4      3    372        3_quantum_light_states_materials
5      4    343            4_bone_materials_tissue_soft
6      5    273       5_galaxies_dark_physics_formation
7      6    216    6_archaeological_ancient_roman_human
8      7    145    7_theory_geometry_geometric_problems
9      8    134            8_brain_neural_memory_visual

                                                                                               Representation  \
0                          [technology, social, knowledge, using, systems, cell, human, europe, design, time]
1       [energy, climate, sustainable, solutions, support, design, production, systems, technologies, europe]
2                   [cell, cells, cancer, immune, disease, molecular, tumor, mechanisms, treatment, clinical]
3                     [health, patients, patient, clinical, cancer, care, ai, healthcare, treatment, medical]
4                 [quantum, light, states, materials, electron, systems, topological, matter, state, optical]
5                            [bone, materials, tissue, soft, cell, self, properties, systems, mechanical, 3d]
6         [galaxies, dark, physics, formation, galaxy, gravitational, universe, cosmic, observations, matter]
7                [archaeological, ancient, roman, human, archaeology, cultural, past, history, period, sites]
8  [theory, geometry, geometric, problems, conjecture, groups, algebraic, equations, manifolds, mathematical]
9            [brain, neural, memory, visual, sensory, cognitive, activity, information, decision, processing]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Representative_Docs
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 [INDUSTRIAL WATER CIRCULARITY: REUSE, RESOURCE RECOVERY AND ENERGY EFFICIENCY FOR GREENER DIGITISED EU PROCESSES RESURGENCE addresses industrial circular water systems in a wide perspective which embraces efficient technologies for water circularity, energy and feedstock recovery, with the aim of contribute to EU climate neutrality, circularity, and competitiveness.RESURGENCE will work in 4 case studies that include 3 industrial sectors – Pulp&Paper, Chemical and Steel – as well as a 4th case to explore the synergies between urban water treatment and industries.Innovative solutions will be tested for water treatment – membranes, electrochemical technologies, adsorbents, advanced oxidation processes and hybrid biological systems – exploring also the recovery of energy (heat, electricity, biogas, H2) and feedstocks ( bioactive fenols, biopolymers, cellulose, lignin, latex, acrylic polymers, phosphate & nitrogen, biochar, MOFs and metals, including Critical Raw Materials). Digital tools will be also developed and applied, including models for energy, water and risk management, physical and software sensors for data acquisition, digital twins, and decision-support tools enabling optimal water treatment technology set-up and day-to-day operation with seized flexibility opportunities on smart grids.The project will be guided by a comprehensive sustainability and economic assessment to support by evidence the gains of these technologies, togheter with H&S analysis. Local effects multiplication of case studies is pursued by promoting seeds of future hubs for circularity. A comprehensive consortium of 20 partners from 11 countries covering the whole geographical scope of the EU, and with international cooperation with Turkey and Pakistan will work together to achieve significant outcomes and produce long-term impact., Interventions to promote mental and physical health in changing working environments due to climate change, sustainable work practices, and in green jobs Work environments are rapidly changing in Europe. The COVID-19 pandemic resulted in an acceleration of a range of complex and multidimensional trends at the workplace. There is also increasing awareness of the importance of mental and physical health of workers and fundamental interconnections of work, health and well-being. Climate change is further shaping the future of work on an unprecedented scale. European economies are undergoing transformation and reorientation towards sustainability. The European Green Deal is reforming the workplace through implementation of new sustainable work practices and policies, circular economy solutions, and rapid expansion of work in green jobs, resulting in novel workplace exposures with likely impacts on health. Increases in complex algorithmic management and performance monitoring are also taking place with a view towards sustainability. There have been calls towards inclusive green economies ensuring social protection, and the creation of decent green jobs. The overall objective of the INTERCAMBIO project is to promote mental and physical health of workers in changing work environments due to climate change, implementation of new working practices, and among workers in green jobs. We will examine key research questions regarding mental and physical health of workers and conduct detailed evaluation of interventions in strategic industries in Europe relevant to green and digital transitions, including in outdoor construction, health care, public transit, renewable energy (wind turbine), and waste management/recycling using a variety of multidisciplinary and state-of-the-art research methods. We will leverage large, geographically diverse longitudinal cohort consortia for new climate-related studies, promote a framework for social protection, and engage multi-level stakeholders. Findings are expected to have major scientific and societal relevance and will provide support for new policy action in occupational health., Scientific training Programme for Advanced Research and Knowledge in Light-Matter Engineering SPARKLE will build a mixed experimental and theoretical network to develop the necessary tools and techniques to exploit light-matter coupling to manipulate materials functionalities. SPARKLE will bridge the gap between photonics on the one hand and materials science on the other, by advancing the understanding of light-matter interaction via two distinct yet complementary approaches: (i) the utilization of tailored laser fields and (ii) the confinement of light in optical environments, called cavities. The network will connect leading academic and industrial experts, to push the development of novel detection techniques, innovative light sources, state-of-the-art ab-initio simulation methods and innovative designs of light-matter hybrid solid-state systems for devices at the interface of photonics, electronics and quantum technology. We are convinced that this topic is mature enough to provide Europe with a first generation of 14 early stage career scientists trained on interdisciplinary and intersectoral aspects of light and matter based technology, while at the same time pushing forward a cutting edge research field, the one of polaritonics. SPARKLE, will follow the guiding principle of ""model - simulate - design - measure"", providing the doctoral candidates with a unique multidisciplinary training which will place them at the forefront of the research on light-matter hybrid systems. They will collectively engage in a scientific endeavour, the control and manipulation of the quantum nature of material and light, that bridges the domains of theoretical solid state physics, quantum optics, ab initio material simulations, photonic engineering, laser physics and ultrafast spectroscopies. Last but not least the doctoral candidates will be equipped with the required entrepreneurship, innovation, organizational, “soft” and management skills to become successful future leaders in both academic and industrial environments.""]

In [58]:
import pandas as pd
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
import csv
import torch # Import torch to check for MPS availability

# --- BERTopic Configuration ---
SAMPLE_SIZE = None

# Use BAAI/bge-large-en-v1.5
EMBEDDING_MODEL = "BAAI/bge-large-en-v1.5"

INITIAL_MIN_TOPIC_SIZE = 20 # Adjust based on dataset size and text richness
INITIAL_NR_TOPICS = "auto"

FINAL_NR_TOPICS = 100

CUSTOM_STOPWORDS = ["research", "project", "study", "aims", "objective", "proposal", "horizon", "european", "eu", "article", "paper", "chapter", "section", "conclusion", "introduction", "results", "discussion", "methodology", "approach", "work", "based", "provide", "develop", "development", "understand", "understanding", "data", "analysis", "system", "model", "process", "new", "novel", "high", "low", "within", "also", "however", "therefore", "further", "different", "various", "specific", "general", "important", "key", "main", "focus", "context", "issue", "problem", "solution", "impact", "effect", "role", "field", "area", "use", "application", "potential", "value", "framework"]


def run_bertopic_combined_text_hierarchical_bge(df: pd.DataFrame):
    """
    BERTopic analysis on combined 'title' + 'objective'.
    - Uses BAAI/bge-large-en-v1.5 for embeddings.
    - Attempts to use MPS for acceleration on macOS.
    - Uses custom stopwords.
    - Finds granular topics first, then reduces to FINAL_NR_TOPICS.
    """
    if not isinstance(df, pd.DataFrame) or df.empty:
        print("ERROR: Input is not a valid or non-empty DataFrame.")
        return None, None

    required_cols = ['id', 'title', 'objective']
    if not all(col in df.columns for col in required_cols):
        print(f"ERROR: DataFrame must contain columns: {required_cols}. Got: {df.columns.tolist()}")
        return None, None

    print(f"Processing DataFrame with {len(df)} rows for BERTopic (Combined Text, BGE-Large, Hierarchical).")

    # --- Check for MPS (Apple Silicon GPU) availability ---
    device = None
    if torch.backends.mps.is_available():
        device = torch.device("mps")
        print("MPS (Apple Silicon GPU) is available and will be used if sentence-transformers supports it for this model.")
    elif torch.cuda.is_available():
        device = torch.device("cuda")
        print("CUDA GPU is available and will be used.")
    else:
        device = torch.device("cpu")
        print("MPS or CUDA not available, using CPU. This will be slower.")
    
    # Note: SentenceTransformer objects usually auto-detect the best device.
    # If you explicitly pass a device to SentenceTransformer, ensure your PyTorch version fully supports it.
    # For BERTopic, directly passing the model name is often sufficient,
    # and SentenceTransformer (used internally by BERTopic) will handle device placement.

    # --- 1. Combine 'title' and 'objective', prepare texts ---
    df_working = df.copy()
    df_working['title'] = df_working['title'].fillna('').astype(str)
    df_working['objective'] = df_working['objective'].fillna('').astype(str)
    df_working['combined_text'] = df_working['title'] + " " + df_working['objective']
    df_working['combined_text'] = df_working['combined_text'].str.strip()
    
    df_filtered = df_working[df_working['combined_text'] != ''].copy()
    texts_to_process = df_filtered['combined_text'].tolist()
    ids_to_process = df_filtered['id'].tolist()

    if not texts_to_process:
        print("ERROR: No text data available for BERTopic after combining.")
        return None, None
    
    print(f"Number of non-empty combined texts for BERTopic: {len(texts_to_process)}")

    if SAMPLE_SIZE and len(texts_to_process) > SAMPLE_SIZE:
        print(f"Sampling {SAMPLE_SIZE} documents for BERTopic processing...")
        temp_df_for_sampling = pd.DataFrame({'id': ids_to_process, 'text_data': texts_to_process})
        sampled_data = temp_df_for_sampling.sample(n=SAMPLE_SIZE, random_state=42)
        texts_to_process = sampled_data['text_data'].tolist()
        ids_to_process = sampled_data['id'].tolist()

    if not texts_to_process:
        print("ERROR: No texts to process after potential sampling.")
        return None, None

    # --- 2. Initialize BERTopic for Granular Topics ---
    print(f"\nStep 1: Initializing BERTopic for GRANULAR topics.")
    print(f"Embedding Model={EMBEDDING_MODEL}, MinTopicSize={INITIAL_MIN_TOPIC_SIZE}, TargetTopics={INITIAL_NR_TOPICS}")
    
    from sklearn.feature_extraction import _stop_words
    all_stopwords = sorted(list(set(list(_stop_words.ENGLISH_STOP_WORDS) + CUSTOM_STOPWORDS)))

    vectorizer = CountVectorizer(stop_words=all_stopwords, ngram_range=(1, 2))

    # For BGE models, sentence-transformers might require a specific pooling strategy or
    # instructions. Often, just passing the name works, but if not, one might need to
    # create the SentenceTransformer object explicitly.
    # We'll try direct passing first as BERTopic/SentenceTransformer are usually good at this.
    # from sentence_transformers import SentenceTransformer
    # embedding_sbert_model = SentenceTransformer(EMBEDDING_MODEL, device=device if device else None) # Explicit device
    
    topic_model = BERTopic(
        embedding_model=EMBEDDING_MODEL, # Pass BGE model name.
                                        # SentenceTransformer (used by BERTopic) will load it.
                                        # It should auto-detect MPS if available and PyTorch supports it.
        vectorizer_model=vectorizer,
        min_topic_size=INITIAL_MIN_TOPIC_SIZE,
        nr_topics=INITIAL_NR_TOPICS,
        verbose=True,
        calculate_probabilities=True 
    )

    print(f"Fitting BERTopic model for GRANULAR topics (using {EMBEDDING_MODEL})... This will take longer.")
    try:
        initial_topics, initial_probabilities = topic_model.fit_transform(texts_to_process)
        print("Initial GRANULAR topic model fitting complete.")
    except Exception as e:
        print(f"ERROR: BERTopic initial fitting failed: {e}")
        import traceback
        traceback.print_exc()
        if "mps" in str(e).lower() or "metal" in str(e).lower():
            print("\n--- MPS RELATED ERROR DETECTED ---")
            print("Attempting to run on CPU as a fallback...")
            print("Ensure your PyTorch and sentence-transformers versions are compatible with MPS.")
            try:
                # Fallback to CPU if MPS fails
                from sentence_transformers import SentenceTransformer
                cpu_device = torch.device("cpu")
                embedding_sbert_model_cpu = SentenceTransformer(EMBEDDING_MODEL, device=cpu_device)
                topic_model_cpu = BERTopic(
                    embedding_model=embedding_sbert_model_cpu,
                    vectorizer_model=vectorizer,
                    min_topic_size=INITIAL_MIN_TOPIC_SIZE,
                    nr_topics=INITIAL_NR_TOPICS,
                    verbose=True,
                    calculate_probabilities=True
                )
                initial_topics, initial_probabilities = topic_model_cpu.fit_transform(texts_to_process)
                print("Successfully re-ran on CPU after MPS error.")
                topic_model = topic_model_cpu # Replace original model with CPU version
            except Exception as e_cpu:
                print(f"ERROR: Fallback to CPU also failed: {e_cpu}")
                return None, None
        else:
            return None, None # Other non-MPS error

    initial_topic_info = topic_model.get_topic_info()
    print(f"\nNumber of initial GRANULAR topics found: {len(initial_topic_info)}")
    print("Top initial granular topics:")
    print(initial_topic_info.head(10))
    
    # --- 3. Reduce to More General Topics ---
    if (len(initial_topic_info) - (1 if -1 in initial_topic_info["Topic"].values else 0)) > FINAL_NR_TOPICS:
        print(f"\nStep 2: Reducing topics from {len(initial_topic_info)-1} to {FINAL_NR_TOPICS} general topics...")
        try:
            new_topics_assigned = topic_model.reduce_topics(texts_to_process, nr_topics=FINAL_NR_TOPICS)
            print("Topic reduction complete.")
        except Exception as e:
            print(f"ERROR: Topic reduction failed: {e}")
            new_topics_assigned = initial_topics 
            print("Proceeding with initial granular topics due to reduction error.")
    else:
        print(f"\nNumber of initial topics ({len(initial_topic_info)-1}) is already less than or equal to target ({FINAL_NR_TOPICS}). No reduction performed.")
        new_topics_assigned = initial_topics

    # --- 4. Prepare and Save Final Results ---
    final_topic_info = topic_model.get_topic_info()
    final_topic_count = len(final_topic_info) - (1 if -1 in final_topic_info['Topic'].values else 0)
    print(f"\n--- Final BERTopic Results ({final_topic_count} General Topics) ---")
    print("Top general topics found:")
    print(final_topic_info.head(15))

    results_df = pd.DataFrame({
        'id': ids_to_process,
        'topic_id': new_topics_assigned
    })
    
    topic_labels_map = {topic_id: "_".join([word for word, _ in topic_model.get_topic(topic_id)[:4]])
                        for topic_id in final_topic_info['Topic'] 
                        if topic_model.get_topic(topic_id) is not None}
    if -1 in final_topic_info['Topic'].values and -1 not in topic_labels_map:
        topic_labels_map[-1] = "Outliers"
    results_df['topic_label'] = results_df['topic_id'].map(topic_labels_map)
    
    processed_texts_df = pd.DataFrame({'id': ids_to_process, 'combined_text': texts_to_process})
    final_output_df = pd.merge(processed_texts_df, results_df[['id', 'topic_id', 'topic_label']], on='id', how='left')
    final_output_df = final_output_df[['id', 'combined_text', 'topic_id', 'topic_label']]

    output_csv_path = f"cordis_bertopics_bge_large_hierarchical_{FINAL_NR_TOPICS}topics.csv"
    print(f"\nSaving results to: {output_csv_path}")
    final_output_df.to_csv(output_csv_path, index=False, quoting=csv.QUOTE_ALL)

    model_save_path = f"bertopic_cordis_bge_large_hierarchical_{FINAL_NR_TOPICS}topics_model"
    print(f"Saving BERTopic model to: {model_save_path}")
    topic_model.save(model_save_path, serialization="safetensors")

    print("\nScript finished successfully!")
    return final_output_df, topic_model

# --- How to use it ---
if __name__ == "__main__":
    if 'df_complete' not in globals() and 'df_complete' not in locals():
        print("ERROR: df_complete is not defined. Please load or create it first.")
        # Example placeholder for testing if df_complete isn't available:
        # data_for_simulation = {'id': [1,2,3]*100, 'title': ['t']*300, 'objective': ['This is a sample objective for BGE model with several words to ensure text processing works.']*300} # Minimal data
        # df_complete = pd.DataFrame(data_for_simulation)
        # df_complete['id'] = df_complete.index # ensure unique ids for testing
        exit()

    print("Using existing df_complete for HIERARCHICAL BERTopic analysis with BGE-Large (Combined Text).")
    final_results_df_bge, trained_model_bge = run_bertopic_combined_text_hierarchical_bge(df_complete)
    if final_results_df_bge is not None:
        print("\nDisplaying head of the final BGE-Large hierarchical results DataFrame:")
        print(final_results_df_bge.head())
        print(f"\nShape of final results: {final_results_df_bge.shape}")
        print(f"\nValue counts for topic_label (top 10):")
        print(final_results_df_bge['topic_label'].value_counts().head(10))

2025-05-13 18:01:08,489 - BERTopic - Embedding - Transforming documents to embeddings.

Using existing df_complete for HIERARCHICAL BERTopic analysis with BGE-Large (Combined Text).
Processing DataFrame with 15341 rows for BERTopic (Combined Text, BGE-Large, Hierarchical).
MPS (Apple Silicon GPU) is available and will be used if sentence-transformers supports it for this model.
Number of non-empty combined texts for BERTopic: 15341

Step 1: Initializing BERTopic for GRANULAR topics.
Embedding Model=BAAI/bge-large-en-v1.5, MinTopicSize=20, TargetTopics=auto
Fitting BERTopic model for GRANULAR topics (using BAAI/bge-large-en-v1.5)... This will take longer.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/94.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/779 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

Batches:   0%|          | 0/480 [00:00<?, ?it/s]

2025-05-13 18:38:56,671 - BERTopic - Embedding - Completed ✓
2025-05-13 18:38:56,686 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-05-13 18:38:59,243 - BERTopic - Dimensionality - Completed ✓
2025-05-13 18:38:59,244 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-05-13 18:39:02,074 - BERTopic - Cluster - Completed ✓
2025-05-13 18:39:02,075 - BERTopic - Representation - Extracting topics from clusters using representation models.
2025-05-13 18:39:09,538 - BERTopic - Representation - Completed ✓
2025-05-13 18:39:09,548 - BERTopic - Topic reduction - Reducing number of topics
2025-05-13 18:39:16,029 - BERTopic - Topic reduction - Reduced number of topics from 109 to 50

Initial GRANULAR topic model fitting complete.

Number of initial GRANULAR topics found: 50
Top initial granular topics:
   Topic  Count                                          Name  \
0     -1   6076        -1_energy_knowledge_technology_systems
1      0   3756           0_climate_social_sustainable_energy
2      1   1875                  1_cancer_cell_patients_cells
3      2    313                2_cell_cells_molecular_protein
4      3    284            3_galaxies_formation_dark_universe
5      4    200  4_quantum_computing_quantum computing_qubits
6      5    178                5_6g_wireless_networks_network
7      6    176            6_vaccine_clinical_vaccines_health
8      7    147          7_theory_geometry_geometric_problems
9      8    144                    8_traffic_road_rail_safety

                                                                                                             Representation  \
0                          [energy, knowledge, technology, systems, materials, using, design, europe, technologies, health]
1                        [climate, social, sustainable, energy, change, knowledge, environmental, europe, production, food]
2                                     [cancer, cell, patients, cells, brain, clinical, treatment, disease, immune, patient]
3                                [cell, cells, molecular, protein, transcription, dna, proteins, biology, mechanisms, gene]
4                       [galaxies, formation, dark, universe, observations, cosmic, galaxy, gravitational, evolution, star]
5  [quantum, computing, quantum computing, qubits, classical, systems, quantum information, computers, states, information]
6                             [6g, wireless, networks, network, communication, 5g, communications, sensing, radio, optical]
7                                        [vaccine, clinical, vaccines, health, africa, tb, malaria, covid, pandemic, trial]
8                [theory, geometry, geometric, problems, conjecture, equations, groups, algebraic, mathematical, manifolds]
9                                  [traffic, road, rail, safety, transport, atm, airspace, operations, management, freight]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Representative_Docs
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   [Compliant and fully AUToMATed circular solutions for multiple battery and battery embedded device enhanced by digital solutions The increasing need to find alternative energy sources, combined with the general urgency to decarbonise the way we produce, store and consume in order to meet the EU's climate and sustainability targets, is stimulating a massive and rapid use of critical raw materials, which are fundamental to the production of electrical and electronic equipment and batteries, pillars of the green and digital transition that the EU is called upon to achieve. The challenges are increasingly important given the rapidly changing geopolitical environment. AutoMat is responding to these cross-cutting and urgent challenges through the timely introduction of disruptive, holistic, circular and sustainable target-driven concepts and solutions, driven by the implementation of the following key aspects: i) High value-added recycling technologies, mainly focused on preparing batteries and EEE components (battery packs, modules, cells, parts and materials) for re-use, through the most advanced collaborative-adaptive and flexible disassembly, sorting and material recovery technologies and integrated solutions, in order to drastically reduce the amount of non-reusable parts and materials, and to return to the market with new products (including chemicals) able to meet the needs of the market ii) Transversal digitisation of solutions towards a multi-level and continuous digital data exchange and elaboration able to support new strategies of advanced and compliant separate collection to increase the quality and availability of target streams, support in real time the efficiency of recycling-reuse processes through the homogenisation of external inputs, provide always personalised and predictive information on the most appropriate operations to be applied, aiming at a massive reduction of risks and waste during handling, collection and recycling operations, provide digital passports to second life applications, to strengthen the efficiency of the outputs coming from the AutoMat global value chain., INTEGRATED DIGITAL SOLUTION FOR SUSTAINABLE AND RELIABLE MANAGEMENT OF INTERNATIONAL RENEWABLE ENERGY SYSTEMS. The increase in energy demand in industry, buildings, services, and transportation together with the associated greenhouse gas emissions bring great challenges to the energy sector. To face them, this sector must aggressively look for more efficient ways of operations so as to support this growing consumption, avoid supply problems and, at the same time, reduce operating costs. The answer to these challenges lies in digitalization, which is one of the essential pillars for the transformation of this sector in Europe and worldwide. INTEREST goes beyond the state of the art, with the objective of developing a hierarchical distributed Model PredictiveControl for real-time monitoring and energy management of renewable energy systems with improved features such as sustainability, stability, reliability, and replicability. This objective will be addressed using innovative tools that will bring intelligence to the system, allowing a more preventive than reactive performance, which is fundamental to overcoming the challenges already presented. Such innovations are essential to increase the system's efficiency by improving the control of the energy flows. INTEREST will bring to practice the concepts of predictive maintenance and joint energy and health management by using data intelligence for a better understanding of demand, predicting, and anticipating undesirable faults in a self-healing operation. The ending status of INTEREST concept can be expressed by TRL5 aiming to boost the European outstanding position in global applied science. This way INTEREST solution presents a great potential of being a leading exporting technology focusing on the emergent markets worldwide and ensuring the political priorities of sustainable.Strongly aligned with the EU policy framework for climate and energy, the outcomes are oriented towards the development of comprehensive, innovative, and evidence-based frameworks to move Europe into a technological leadership position in this field., Innovating with nature for sustainable water management in the global south Water, particularly access to safe drinking water and sanitation remains a worldwide challenge. By 2040, it is estimated that 1 in 4 children will be living in regions of extremely high-water stress because of overuse, population growth, and climate change. One of the regions most affected by these issues is the Global South. An inclusive approach for managing water resources circularly is needed to address the clean water crisis. Here, the expertise from the European Union countries can support the research needs and knowledge gaps from the Global South, while simultaneously leading to an assessment of current challenges and best practises in the Global North. For that, 6 academic institutions, 1 SME and 1 water utility join efforts through NEUTRAL4GS.By implementing co-creation and co-design strategies between partners from the Global South and EU, the project aims to develop and test solutions inspired by nature for urban water management. This includes jointly working with i) different types of urban water (stormwater, greywater and wastewater), as well as with ii) a range of different treatment technologies combining nature-based solutions with supporting technological units (e.g., membranes, nanofiber biomass carriers, graphene-based nanocomposites, lightweight porous media or photocatalysis) that can be innovated for more sustainable or close to nature performance to deliver treated water and water for reuse. Holistic sustainability and economic assessments will guide the development and prioritization of technologies. Thus, NEUTRAL4GS will pioneer innovative solutions in water treatment, ensure social acceptance and adoption of technologies, and generate significant impacts in terms of societal, environmental, and public-health benefits. By garnering awareness and involving the local authorities and local community in the process, NEUTRAL4GS strive to ensure sustainability and long-term success of the project’s outcomes beyond its lifetime.]

In [60]:
final_results_df_bge.head(100)

,id,combined_text,topic_id,topic_label
0,101116741,"Digitizing Other Economies: A Comparative Approach How do longstanding, primarily non-industrial, non-capitalist societies adopt and adapt digital technologies in their daily practices and systems of values? Classical anthropological theory once arranged basic economic types on an evolutionary ladder ranging from hunter-gatherers, horticulturalists, pastoralists, and agriculturalists to industrialists. Today, the existence of these economies other than industrialism are correctly approached not as anachronisms but as contemporaneous to (post-)industrial life. Still, research on digitization has largely taken place in (post-) industrial contexts, meaning we know next to nothing about how different types of longstanding economies adopt and adapt digital technologies. At the same time, researchers have stipulated that digitization threatens global economic diversity. By comparing digitization to processes of colonization, they have argued that digital technologies facilitate assimilation into (post-)industrial economic systems and their often capitalist values by virtue of their technological design. This project empirically investigates these claims through in-depth ethnographic research among hunter-gatherers (Brazilian Amazon), pastoralists (Kyrgyz Republic), horticulturalists (Solomon Islands) and indigenous agriculturalists (India) who have long resisted assimilation into industrial-capitalism. Additional ethnological comparison of the four sites will offer unique macro-level insights into the possibilities for economic diversity in the digital age. Finally, the project advances a novel theoretical and methodological approach that advances both ethnographic research and ethnological comparison. This approach recognizes the significance of both technological design and contextual adaptations and provides tools for new research agendas not just on digital industrial-capitalism but on diverse economic systems and values.",-1,energy_knowledge_technology_systems
1,101163161,"MOLECULAR QUANTUM DYNAMICS IN LOW TEMPERATURE CONDENSED PHASE ASTROCHEMISTRY The James Webb Space Telescope (JWST) has ushered in a new era in observational astrochemistry. JWST's ability to obtain infrared spectra of molecular ices condensed on interstellar dust grains in dense, star-forming clouds and in protoplanetary disks is expected to revolutionize the field, since these ices are known to be important sources of complex organic molecules. On a fundamental level, the physico-chemical behavior of these ices obeys the laws of molecular quantum dynamics occurring in low-temperature condensed phases. This is a forefront research area in chemical physics that, unfortunately, remains poorly understood. This project establishes an interdisciplinary, synergistic research consortium to address this knowledge deficit, bringing together the unique expertise of the groups of Alec Wodtke (Chemical Physics at Surfaces), Liv Hornekr (Astrochemistry and Scanning Tunneling Microscopy) and Peter Saalfrank (Theoretical Quantum Dynamics). Under IRASTRO, we will develop and employ advanced infrared technology based on superconducting nanowire single-photon detectors (SNSPDs) for new experimental capability in laboratory experiments directly relevant to astrochemistry. We will combine megapixel SNSPD arrays with chelle spectrometers enabling solid-state mid-infrared emission spectroscopy, including single-molecule mid-IR spectroscopy in a scanning tunneling microscope. With these new experiments and forefront quantum theory, we will tackle three research themes: 1) Infrared Spectra of Molecules on Surfaces under Interstellar Conditions, 2) Energy Dissipation Channels on Low Temperature Surfaces, and 3) Chemical Reactivity under Interstellar Conditions. IRASTROs focus on IR spectroscopy will make the projects findings directly relevant to the interpretation of JWST observational data and, through a fruitful collaboration of experiment and theory, provide a better fundamental understanding of astrochemistry.",3,galaxies_formation_dark_universe
2,101160499,"Multiscale modelling of aberrant phase transitions in biocondensates The spatiotemporal organization of the cell material represents one of the great wonders in physics, chemistry and biology. Compartmentalization plays a key role in such precise molecular coordination and enables cellular function. Over the past decade, transformative experiments have revealed that most intracellular compartments are not enclosed by membranes, but instead they are dynamical assemblies, termed condensates, and thought to occur via liquid-liquid phase separation of biomolecules. Nevertheless, the misregulation of these condensatesmostly formed by proteins and nucleic acidscan give rise to deleterious solid-like aggregates, which are associated with the proliferation of age-related and neurodegenerative disorders.In-phase aims to develop an innovative computational approach to resolve the dynamical behaviour of molecules inside functional condensates that drift their complex physicochemical behaviour into pathological solid aggregates. To this end, we plan to develop a multiscale modelling platformcombining coarse-grained force fields and atomistic simulationswhich will address the following critical questions: What are the encoded molecular features in RNA and protein sequences regulating phase behaviour? What pushes biomolecular condensates to shift their material properties over time? Can we prevent the proliferation of pathological aggregates induced by condensate misregulation? The overarching goals of this project are: (1) to understand the thermodynamic and intermolecular forces driving condensates out-of-function; and (2) devise potential strategies for preventing RNA/protein aberrant phase transitions in biomolecular condensates. This alone is ground-breaking because it will reveal the underlying mechanisms and interactions by which the structure and sequence of RNA and proteins dictate the material properties of intracellular condensates, and their implication in cellular dysfunction.",-1,energy_knowledge_technology_systems
3,101166905,"The first comprehensive Atlas of the Milky Way The Milky Way is the cosmic environment in which the solar system, the Earth, and life as we know it came into being. It is also the veil through which we peer into the extra-galactic universe. Its dust obscures our view of the formation of the cosmos. Its magnetic fields distort the observations of nature's most powerful particle accelerators. Its structure and metabolism determine the great diversity of observed star and planetary systems, including our own. Due to a lack of distance information, currently most information about the structure of the Milky Way is two-dimensional, while three-dimensional information is needed. For a breakthrough in Galactic cartography and the science it enables, we will create the first comprehensive three-dimensional atlas of all the physical components of the Milky Way. Our atlas will be self-consistent between component maps, quantify their remaining uncertainties, and be the most detailed to date. Thanks to the dramatic progress in observations at all wavelengths and in algorithmic methods based on information field theory in recent years, now is the right time to do this. Our team's combined expertise in galactic astrophysics, algorithms, observations, Milky Way surveys, and information field theory with its application to galactic tomography puts us in a unique position to generate the first comprehensive Milky Way Atlas. We will apply this atlas to a number of pressing questions in cosmology, cosmic ray, and interstellar medium research and transfer the used tomography technologies into other areas, like medical imaging, Earth monitoring, and industrial data analysis.",3,galaxies_formation_dark_universe
4,101162875,"Untapping multiparametric 2D luminescence sensing through MACHine LEarning and Spectral Sorting Cellular organisms are complex machines whose health and functioning are dictated by parameters including temperature, oxygen concentration, and pH. Luminescence nanosensing is a technology that promises all the features required to reliably monitor these parameters at the intracellular level: minimal invasiveness, remote working principle, and submicrometric spatial resolution. These features are ensured by the use of sub-micrometric sensors (particles) whose luminescence is sensitive to changes in the parameters to be sensed. Yet, despite the hype about luminescence nanosensing, its reliability in the study of cells is limited by interparticle variability in optical properties and sensing performance, simultaneous response to several parameters (cross-sensitivity), and lack of a measurement technology that enables fast 2D mapping of multiple parameters with sub-second temporal resolution. MAtCHLESS tackles heads on these limitations to develop a reliable luminescence sensing technology for multiparameteric sensing in cell studies. This project entails: design of a novel family of composite submicrometric luminescent sensors, elimination of interparticle fluctuations in optical properties using a spectral sorting strategy, introduction of the paradigm shift of making cross-sensitivity a desirable feature via machine learning, and use of a novel optical technology to build a setup for 2D mapping of multiple parameters with high temporal and spatial resolution. MAtCHLESS will test the reliability of the sensing approach in mammalian cell lines and extremophiles microorganisms that can withstand extreme conditions of, e.g., temperature, oxygen concentration, and pH. These investigations will show the potential of the developed technology to monitor both slight and extreme changes in biological parameters, towards a deeper understanding of, e.g., how cancer can be more effectively treated, as well as how Life evolved on Earth and can be adapted beyond our planet.",1,cancer_cell_patients_cells
...,...,...,...,...
95,101097010,"Boosting female entrepreneurship through joint services and activities The 24-month Womenture project aligns its efforts with the European Commission's objective to create interconnected, inclusive and more efficient innovation ecosystems across Europe that draws on the existing strengths of European, national, regional, and local ecosystems and pulls in new, less well-represented stakeholders and less advanced in innovation territories, to set, undertake, and achieve collective ambitions towards challenges for the benefit of the society, including green, digital, and social transitions. The overall objective of the project is to empower innovation agencies and accelerators to generate and embed new joint services and activities into their initiatives to boost female entrepreneurship and women innovation in the participating ecosystems. The consortium brings together innovation agencies and accelerators from strong, moderate, and emerging innovator regions with the aim to support women innovators, spread the entrepreneurial mindset, present them the already existing initiatives of the partners, projects, and networks dealing with women innovators and connect each other. Through the delivery of its activities (co-creation, co-design, co-assessment, capacity building, business support programme, innovation ecosystem hub creation), the project will result in enhanced connections, strengthened and more effective capacity of innovation ecosystem actors, improved visibility and increased involvement of women innovators in innovation initiatives towards economic development and growth.",0,climate_social_sustainable_energy
96,101112921,"EIT Health Business Plan 2023-2025 EIT Health is one of eight Knowledge and Innovation Communities (KICs) of the European Institute of Innovation and Technology (EIT), an EU body and Institutionalised Partnership under Horizon Europe’s Pillar III – Innovative Europe. EIT Health’s vibrant community of more than 150 partner organisations from the worlds of business, research and academia, empowers a network of world-leading health innovators. We bridge the gap between industry and academia to take on some of Europe’s biggest health challenges – promoting better health of citizens, strengthening healthcare systems and contributing to a sustainable health economy. EIT Health collaborates across disciplines, borders and sectors, reinforcing excellence, creating knowledge and innovation, and encouraging greater investment, to deliver outcomes that matter most to citizens and patients. In the eighth year since its inception, EIT Health is consolidating its activities under a single unified structure: the Flagship. The 2023-2025 Flagships will tackle single-issue, highly focused topics based on EU health priorities and will be the pathways to EIT Health reaching the impact set in it's Strategic Agenda.",-1,energy_knowledge_technology_systems
97,101114052,"Cell line engineering for imporved fertility treatment kyron.bio is a female led biotech company on a mission is to unclog bottlenecks in therapeutic protein production, allowing better drugs to reach patients. We are using synthetic biology to engineer mammalian cell lines for improved bioproduction, harnessing highly efficient enzymes from diverse life forms. Our preliminary data demonstrates a 3X yield gain for the amount of therapeutic produced in our system, with further gains in yield, activity and stability predicted post optimisation",1,cancer_cell_patients_cells
98,101114225,"Upcycling of fruit and vegetable losses and by-products into sustainable and natural clean-label ingredients: AgroGrIN Tech pilot approach Molecule Message Unipessoal is a food waste upcycling company, that produces sustainable and clean label ingredients, through a patent technology that uses green chemistry that enables to isolate of concentrated extracts of natural enzymes and vitamins, still reusing the remaining fraction into the production of naturally gluten-free flours and natural flavouring powders. The main activities are related to innovation and technology transfer to the market of technology and innovation, coming from fundamental research associated with the food industry and sustainability area.",-1,energy_knowledge_technology_systems
99,101096781,"Consolidating deep & inclusive social innovation ecosystems Consolid8 is paving the way for the integration of social innovation actors in innovation networks in 15 European ecosystems using the quadruple helix collaboration. From the challenges we identified in 5 pioneering ecosystems with different innovation performances (strong innovator – Ireland, moderate innovators – Italy, Greece, Slovenia, emerging innovator – Romania) we developed 5 capacity building programs that we will deliver to cater to the needs of 5 target groups from both the social innovation landscape, and the classic innovation ecosystems. We will harvest the lessons learned in delivering the different pioneering programs and we will exploit them in a follow-up European accelerator targeting additional 10 ecosystems which we will support through a validated methodology for accelerating ecosystems (developed and implemented by DEEP Ecosystems). We will link the 5 pioneering programs & showcase their results during a European social innovation festival in Brașov, Romania, that will aim to interlink social innovation actors with innovation ecosystems. We will ensure widespread visibility for this event at European level and we will launch an open call for the ecosystem builders to register for the accelerator for ecosystem builders. The project proposes strong pathways towards achieving impact, including activities aimed at developing 3 crowdfunding campaigns for social innovators, 1 research on an alternative financing program for social innovation for local authorities or researching and testing and showcasing 12 social innovation models with potential of scaling up and replicability. For the achievement of the project’s results, 8 partners across the quadruple helix are collaborating.",0,climate_social_sustainable_energy

In [57]:
# Assuming df_complete is your DataFrame with id, title, objective
final_results_df_mpnet.head(20)

,id,combined_text,topic_id,topic_label
0,101116741,"Digitizing Other Economies: A Comparative Approach How do longstanding, primarily non-industrial, non-capitalist societies adopt and adapt digital technologies in their daily practices and systems of values? Classical anthropological theory once arranged basic economic types on an evolutionary ladder ranging from hunter-gatherers, horticulturalists, pastoralists, and agriculturalists to industrialists. Today, the existence of these economies other than industrialism are correctly approached not as anachronisms but as contemporaneous to (post-)industrial life. Still, research on digitization has largely taken place in (post-) industrial contexts, meaning we know next to nothing about how different types of longstanding economies adopt and adapt digital technologies. At the same time, researchers have stipulated that digitization threatens global economic diversity. By comparing digitization to processes of colonization, they have argued that digital technologies facilitate assimilation into (post-)industrial economic systems and their often capitalist values by virtue of their technological design. This project empirically investigates these claims through in-depth ethnographic research among hunter-gatherers (Brazilian Amazon), pastoralists (Kyrgyz Republic), horticulturalists (Solomon Islands) and indigenous agriculturalists (India) who have long resisted assimilation into industrial-capitalism. Additional ethnological comparison of the four sites will offer unique macro-level insights into the possibilities for economic diversity in the digital age. Finally, the project advances a novel theoretical and methodological approach that advances both ethnographic research and ethnological comparison. This approach recognizes the significance of both technological design and contextual adaptations and provides tools for new research agendas not just on digital industrial-capitalism but on diverse economic systems and values.",-1,technology_social_knowledge_using
1,101163161,"MOLECULAR QUANTUM DYNAMICS IN LOW TEMPERATURE CONDENSED PHASE ASTROCHEMISTRY The James Webb Space Telescope (JWST) has ushered in a new era in observational astrochemistry. JWST's ability to obtain infrared spectra of molecular ices condensed on interstellar dust grains in dense, star-forming clouds and in protoplanetary disks is expected to revolutionize the field, since these ices are known to be important sources of complex organic molecules. On a fundamental level, the physico-chemical behavior of these ices obeys the laws of molecular quantum dynamics occurring in low-temperature condensed phases. This is a forefront research area in chemical physics that, unfortunately, remains poorly understood. This project establishes an interdisciplinary, synergistic research consortium to address this knowledge deficit, bringing together the unique expertise of the groups of Alec Wodtke (Chemical Physics at Surfaces), Liv Hornekr (Astrochemistry and Scanning Tunneling Microscopy) and Peter Saalfrank (Theoretical Quantum Dynamics). Under IRASTRO, we will develop and employ advanced infrared technology based on superconducting nanowire single-photon detectors (SNSPDs) for new experimental capability in laboratory experiments directly relevant to astrochemistry. We will combine megapixel SNSPD arrays with chelle spectrometers enabling solid-state mid-infrared emission spectroscopy, including single-molecule mid-IR spectroscopy in a scanning tunneling microscope. With these new experiments and forefront quantum theory, we will tackle three research themes: 1) Infrared Spectra of Molecules on Surfaces under Interstellar Conditions, 2) Energy Dissipation Channels on Low Temperature Surfaces, and 3) Chemical Reactivity under Interstellar Conditions. IRASTROs focus on IR spectroscopy will make the projects findings directly relevant to the interpretation of JWST observational data and, through a fruitful collaboration of experiment and theory, provide a better fundamental understanding of astrochemistry.",-1,technology_social_knowledge_using
2,101160499,"Multiscale modelling of aberrant phase transitions in biocondensates The spatiotemporal organization of the cell material represents one of the great wonders in physics, chemistry and biology. Compartmentalization plays a key role in such precise molecular coordination and enables cellular function. Over the past decade, transformative experiments have revealed that most intracellular compartments are not enclosed by membranes, but instead they are dynamical assemblies, termed condensates, and thought to occur via liquid-liquid phase separation of biomolecules. Nevertheless, the misregulation of these condensatesmostly formed by proteins and nucleic acidscan give rise to deleterious solid-like aggregates, which are associated with the proliferation of age-related and neurodegenerative disorders.In-phase aims to develop an innovative computational approach to resolve the dynamical behaviour of molecules inside functional condensates that drift their complex physicochemical behaviour into pathological solid aggregates. To this end, we plan to develop a multiscale modelling platformcombining coarse-grained force fields and atomistic simulationswhich will address the following critical questions: What are the encoded molecular features in RNA and protein sequences regulating phase behaviour? What pushes biomolecular condensates to shift their material properties over time? Can we prevent the proliferation of pathological aggregates induced by condensate misregulation? The overarching goals of this project are: (1) to understand the thermodynamic and intermolecular forces driving condensates out-of-function; and (2) devise potential strategies for preventing RNA/protein aberrant phase transitions in biomolecular condensates. This alone is ground-breaking because it will reveal the underlying mechanisms and interactions by which the structure and sequence of RNA and proteins dictate the material properties of intracellular condensates, and their implication in cellular dysfunction.",1,cell_cells_cancer_immune
3,101166905,"The first comprehensive Atlas of the Milky Way The Milky Way is the cosmic environment in which the solar system, the Earth, and life as we know it came into being. It is also the veil through which we peer into the extra-galactic universe. Its dust obscures our view of the formation of the cosmos. Its magnetic fields distort the observations of nature's most powerful particle accelerators. Its structure and metabolism determine the great diversity of observed star and planetary systems, including our own. Due to a lack of distance information, currently most information about the structure of the Milky Way is two-dimensional, while three-dimensional information is needed. For a breakthrough in Galactic cartography and the science it enables, we will create the first comprehensive three-dimensional atlas of all the physical components of the Milky Way. Our atlas will be self-consistent between component maps, quantify their remaining uncertainties, and be the most detailed to date. Thanks to the dramatic progress in observations at all wavelengths and in algorithmic methods based on information field theory in recent years, now is the right time to do this. Our team's combined expertise in galactic astrophysics, algorithms, observations, Milky Way surveys, and information field theory with its application to galactic tomography puts us in a unique position to generate the first comprehensive Milky Way Atlas. We will apply this atlas to a number of pressing questions in cosmology, cosmic ray, and interstellar medium research and transfer the used tomography technologies into other areas, like medical imaging, Earth monitoring, and industrial data analysis.",5,galaxies_dark_physics_formation
4,101162875,"Untapping multiparametric 2D luminescence sensing through MACHine LEarning and Spectral Sorting Cellular organisms are complex machines whose health and functioning are dictated by parameters including temperature, oxygen concentration, and pH. Luminescence nanosensing is a technology that promises all the features required to reliably monitor these parameters at the intracellular level: minimal invasiveness, remote working principle, and submicrometric spatial resolution. These features are ensured by the use of sub-micrometric sensors (particles) whose luminescence is sensitive to changes in the parameters to be sensed. Yet, despite the hype about luminescence nanosensing, its reliability in the study of cells is limited by interparticle variability in optical properties and sensing performance, simultaneous response to several parameters (cross-sensitivity), and lack of a measurement technology that enables fast 2D mapping of multiple parameters with sub-second temporal resolution. MAtCHLESS tackles heads on these limitations to develop a reliable luminescence sensing technology for multiparameteric sensing in cell studies. This project entails: design of a novel family of composite submicrometric luminescent sensors, elimination of interparticle fluctuations in optical properties using a spectral sorting strategy, introduction of the paradigm shift of making cross-sensitivity a desirable feature via machine learning, and use of a novel optical technology to build a setup for 2D mapping of multiple parameters with high temporal and spatial resolution. MAtCHLESS will test the reliability of the sensing approach in mammalian cell lines and extremophiles microorganisms that can withstand extreme conditions of, e.g., temperature, oxygen concentration, and pH. These investigations will show the potential of the developed technology to monitor both slight and extreme changes in biological parameters, towards a deeper understanding of, e.g., how cancer can be more effectively treated, as well as how Life evolved on Earth and can be adapted beyond our planet.",1,cell_cells_cancer_immune
5,101167314,"Making Sense of the Unexpected in the Gravitational-Wave Sky General Relativity (GR) is more than a century old, but is still our best macroscopic description of gravity. Key GR predictions are black holes (BHs) and gravitational waves (GWs), whose spectacular confirmation led to two recent physics Nobel Prizes. The future of GW astronomy, however, is even brighter, since detectors will observe BHs at cosmic dawn and probe their enigmatic event horizon, where GR clashes with quantum mechanics in the information loss paradox. These experiments will measure signals hundreds of times smaller than today, necessarily discovering anomalies and deviations from current predictions, e.g., due to the astrophysical environment. On the fundamental side, precision GW astronomy will open countless possibilities for understanding the standard model of particle physics (and its extensions), gravity and cosmology. By itself, however, precision is not knowledge. To harness the power of these measurements, a groundbreaking framework is urgently needed to solve the very nonlinear equations of GR and develop waveform models to unprecedented accuracy, and to convert these results into concrete interpretation tools. GWSky will leverage the world-leading expertise of its PIs in astrophysics, GW-source modeling, particle physics and GR, and recent paradigm shifts to build an overarching framework answering a fundamental question: When, inevitably, an anomaly in a GW signal is identified, what is it? A gravitational effect not predicted by GR? The influence of nearby matter? Or merely an imprecise calculation of the expected signal? Even tiny deviations from GR would shake physics to its core, but to claim a deviation from it, one needs to filter out first the contributions from the astrophysical environment, instrumental artifacts and systematic modeling uncertainties. GWSky will provide tools to disentangle these contributions, enabling precision GW astronomy with upcoming observational runs, and new facilities on the ground and in space.",5,galaxies_dark_physics_formation
6,101165261,"Hernando Colón’s universal library. European culture and intellectual production at the dawn of the global world While newly printed books were circulating widely around Europe, when more than half a century had passed since Gutenbergs invention, Hernando Coln (1488-1539), second son of Christopher Columbus, undertook the extraordinary challenge of keeping physical track of the proliferation of knowledge. He not only purchased everything, incessantly, and everywhere, marking on the books place and date of purchase, the local price, and the conversion to Spanish currency; for accessing, managing and reusing his colossal library, he and his invisible technicians also developed a sophisticated cross-indexing and symbols system which is foundational in the history of bibliography and knowledge management. The Colombina library of Seville still preserves over one third of the almost 16,000 titles which Coln left at his death, as well a dozen manuscript indexes and catalogues that, recording all sorts of information, make it possible to reconstruct the lost portions of the collection, including the volumes famously shipwrecked on their way from Venice to Seville in 1521. Financing, gathering, cataloguing and managing a library of such scale required widespread connections, the support of an international network, and a vision deeply intertwined with the politics of knowledge acquisition of the new-born Spanish Empire. COLIBRI aims at opening the doors and explore the legacy of the most important library of the early modern period, completing the reconstruction of its content in order to investigate it; understanding how it worked as the first large-scale information processing system of modern times, and as a place for the production, not only for the storage and preservation, of knowledge; exploring the still new relationship between written and print culture and the early European and intercontinental book market; finally, showing how the movement and the stories of Colons books reflect the developments of Western culture of the last five centuries.",0,energy_climate_sustainable_solutions
7,101072693,"UA EURATOM NCP SUPPORT OF UKRAINIAN RESEARCH ENTITIES INTEGRATION INTO NUCLEAR RESEARCH FUNDED BY THE EURATOM RESEARCH AND TRAINING PROGRAMME 2021-2025 UAinEuratom21 is 24 months project is addressed to support activities of the Ukrainian ‘National Contact Point to Euratom’ (UA Euratom NCP) and aimed to contribute to better integration of Ukrainian research entities (researchers) into European nuclear research networks.UAinEuratom21 project has the following specific objectives:•Strengthening the integration of Ukrainian stakeholders in pan-European initiatives and research relevant to all research areas covered by the Euratom Research and Training Programme 2021-2025,•Enhancing of UA Euratom NCP competence,•Euratom programme awareness raising among Ukrainian stakeholders.The UAinEuratom21 project audience is divided into several target groups:•Direct target groups: UA research community, EU research community, UA coordination and support bodies, EU coordination and support bodies,•Indirect target group: the general public.There are four work packages that are planned for project implementation.WP1 - STRENGTHENING OF NETWORKING ACTIVITIES BETWEEN UA AND EU RESEARCHERS;WP2 - UA EURATOM NCP COMPETENCE REINFORCEMENT;WP3 - DISSEMINATION, EXPLOITATION AND COMMUNICATION;WP4 - PROJECT MANAGEMENT.All activities of the UAinEuratom21 project are implemented by the National science center Kharkov Institute of Physics and Technology that has been officially appointed by the Ukrainian authorities as UA Euratom NCP since 2017.",0,energy_climate_sustainable_solutions
8,101172406,"FISA 2025 – EURADWASTE’25 conferences on Euratom fission research and training The FISA-EURADWASTE event is a high-level, research policy conference on the outcomes and perspectives of the Euratom Research and Training Programme. This 11th edition of the conference will be held in Warsaw, Poland, in May 2025, under the auspices of the Polish Presidency of the Council of the EU. The organisers of this conference are: - the National Centre for Nuclear Research (NCBJ) the most important Polish research centre in the nuclear energy field, and the European Commission (DG-RTD). FISA’25 and EURADWASTE ‘25 conference objectives are: - to present progress and key achievements of the latest projects carried out since 2022 as part of the Euratom Programmes; - to stimulate discussions on the state of play of R&D, key challenges addressed at national, European and international levels on Research and Innovation policies, synergies and partnerships benefitting research and innovation programmes and future perspectives. Expected impacts, thanks to an ambitious communication and dissemination action plan, are: - increasing visibility of the Euratom research and training programme; - increasing awareness of nuclear research achievements; - networking EU stakeholders; - bringing new research project ideas and collaboration between different stakeholders; - orienting research, development and innovation orientations at the EU level; - increasing the visibility of national research potential and participation in the Euratom framework programme.",0,energy_climate_sustainable_solutions
9,101114128,"Market & Technology Analysis Adsorbi is a deep tech startup company from Gothenburg Sweden and was founded after several years of research within materials chemistry. Adsorbi's innovation is a biobased adsorbent material, which captures harmful pollutants with high capacity. The aim is to replace activated carbon in applications for pollutant removal to lower the high environmental impact and material use of today. The goal of the project is to identify which of the many potential application areas to target, specifically, what should be the first products and who is the ideal first customer of Adsorbi. The project is divided into four objectives: perform a market analysis, perform a technical feasibility study, perform an IP strategy evaluation, and develop a business case around shortlisted attractive application areas.",-1,technology_social_knowledge_using

In [51]:
import pandas as pd
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
import csv

# --- BERTopic Configuration ---
SAMPLE_SIZE = None
EMBEDDING_MODEL = "all-MiniLM-L6-v2"
MIN_TOPIC_SIZE = 50 # Titles are shorter, might need smaller min_topic_size for 100 topics
NR_TOPICS = 100

CUSTOM_STOPWORDS = ["research", "project", "study", "aims", "objective", "proposal", "horizon", "european", "eu", "article", "paper", "chapter", "section", "conclusion", "introduction", "results", "discussion", "methodology", "approach", "work", "based", "provide", "develop", "development", "understand", "understanding", "data", "analysis", "system", "model", "process", "new", "novel", "high", "low", "within", "also", "however", "therefore", "further", "different", "various", "specific", "general", "important", "key", "main", "focus", "context", "issue", "problem", "solution", "impact", "effect", "role", "field", "area", "use", "application", "potential", "value", "framework"]


def run_bertopic_on_titles(df: pd.DataFrame):
    """
    BERTopic analysis on project titles only.
    - Uses custom stopwords.
    - Aims for a specified number of topics (e.g., 100).
    - Outputs a CSV with id, title, topic_id, topic_label.
    """
    if not isinstance(df, pd.DataFrame) or df.empty:
        print("ERROR: Input is not a valid or non-empty DataFrame.")
        return None, None

    required_cols = ['id', 'title'] # Now only 'id' and 'title' are strictly required from input
    if not all(col in df.columns for col in required_cols):
        print(f"ERROR: DataFrame must contain columns: {required_cols}. Got: {df.columns.tolist()}")
        return None, None

    print(f"Processing DataFrame with {len(df)} rows for BERTopic (using titles only).")

    # --- 1. Prepare texts (titles only) ---
    df_working = df.copy()
    df_working['title'] = df_working['title'].fillna('').astype(str).str.strip()
    
    df_filtered = df_working[df_working['title'] != ''].copy() # Filter out rows with empty titles
    texts_for_bertopic = df_filtered['title'].tolist()
    ids_for_bertopic = df_filtered['id'].tolist() # Original IDs

    if not texts_for_bertopic:
        print("ERROR: No title data available for BERTopic.")
        return None, None
    
    print(f"Number of non-empty titles for BERTopic: {len(texts_for_bertopic)}")

    current_min_topic_size = MIN_TOPIC_SIZE
    if len(texts_for_bertopic) < NR_TOPICS * (MIN_TOPIC_SIZE / 2) and len(texts_for_bertopic) > 0 :
         print(f"Warning: Dataset size ({len(texts_for_bertopic)}) might be small for {NR_TOPICS} topics with min_topic_size={MIN_TOPIC_SIZE}.")


    # Apply sampling if SAMPLE_SIZE is set
    if SAMPLE_SIZE and len(texts_for_bertopic) > SAMPLE_SIZE:
        print(f"Sampling {SAMPLE_SIZE} titles for BERTopic processing...")
        # Create a temporary DataFrame for sampling to keep ids and texts aligned
        temp_df_for_sampling = pd.DataFrame({'id': ids_for_bertopic, 'title_text': texts_for_bertopic})
        sampled_data = temp_df_for_sampling.sample(n=SAMPLE_SIZE, random_state=42)
        texts_to_process = sampled_data['title_text'].tolist()
        ids_to_process = sampled_data['id'].tolist()
    else:
        texts_to_process = texts_for_bertopic
        ids_to_process = ids_for_bertopic

    if not texts_to_process:
        print("ERROR: No titles to process after sampling (if any).")
        return None, None

    # --- 2. Initialize BERTopic ---
    print(f"\nInitializing BERTopic: Model={EMBEDDING_MODEL}, MinTopicSize={current_min_topic_size}, TargetTopics={NR_TOPICS}")
    
    from sklearn.feature_extraction import _stop_words
    all_stopwords = sorted(list(set(list(_stop_words.ENGLISH_STOP_WORDS) + CUSTOM_STOPWORDS)))

    vectorizer = CountVectorizer(stop_words=all_stopwords, ngram_range=(1,1))

    topic_model = BERTopic(
        embedding_model=EMBEDDING_MODEL,
        vectorizer_model=vectorizer,
        min_topic_size=current_min_topic_size,
        nr_topics=NR_TOPICS,
        verbose=True,
        calculate_probabilities=False
    )

    print("Fitting BERTopic model on titles...")
    try:
        topics, _ = topic_model.fit_transform(texts_to_process)
        print("BERTopic model fitting complete.")
    except Exception as e:
        print(f"ERROR: BERTopic fitting failed: {e}")
        import traceback
        traceback.print_exc()
        return None, None

    # --- 3. Prepare and Save Results ---
    print("\n--- BERTopic Results (Titles Only) ---")
    topic_info = topic_model.get_topic_info()
    print(f"Number of topics found (after potential reduction): {len(topic_info)}")
    print("Top topics found:")
    print(topic_info.head(15))

    # DataFrame with original IDs and assigned topic_ids
    results_df = pd.DataFrame({
        'id': ids_to_process, 
        'topic_id': topics
    })
    
    topic_labels_map = {topic_id: "_".join([word for word, _ in topic_model.get_topic(topic_id)[:4]])
                        for topic_id in topic_info['Topic'] 
                        if topic_model.get_topic(topic_id) is not None}
    if -1 in topic_info['Topic'].values and -1 not in topic_labels_map:
        topic_labels_map[-1] = "Outliers"
    results_df['topic_label'] = results_df['topic_id'].map(topic_labels_map)
    
    # Merge with the 'title' from the processed documents for the final output
    # df_filtered contains the 'id' and 'title' for all docs that had non-empty titles.
    
    # Create a temporary DataFrame with id and title for merging
    # This ensures we only include the titles that were actually processed
    processed_titles_df = pd.DataFrame({'id': ids_to_process, 'title': texts_to_process})
    
    # Merge the BERTopic results (topic_id, topic_label) with this processed_titles_df
    final_output_df = pd.merge(processed_titles_df, results_df[['id', 'topic_id', 'topic_label']], on='id', how='left')
    
    # Ensure 'id' column is first, then 'title', 'topic_id', 'topic_label'
    final_output_df = final_output_df[['id', 'title', 'topic_id', 'topic_label']]

    output_csv_path = "cordis_bertopics_titles_100topics.csv"
    print(f"\nSaving results to: {output_csv_path}")
    final_output_df.to_csv(output_csv_path, index=False, quoting=csv.QUOTE_ALL)

    model_save_path = "bertopic_cordis_titles_100topics_model"
    print(f"Saving BERTopic model to: {model_save_path}")
    topic_model.save(model_save_path, serialization="safetensors")

    print("\nScript finished successfully!")
    return final_output_df, topic_model

# --- How to use it ---
if __name__ == "__main__":
    if 'df_complete' not in globals() and 'df_complete' not in locals():
        print("ERROR: df_complete is not defined. Please load or create it first.")
        # Example placeholder for testing if df_complete isn't available:
        # data_for_simulation = {'id': [1,2,3]*100, 'title': ['Example Title Word']*300, 'objective': ['o']*300} # Minimal data
        # df_complete = pd.DataFrame(data_for_simulation)
        # df_complete['id'] = df_complete.index # ensure unique ids for testing
        exit()

    print("Using existing df_complete for BERTopic analysis (titles only).")
    final_results_df_titles, trained_model_titles = run_bertopic_on_titles(df_complete)
    if final_results_df_titles is not None:
        print("\nDisplaying head of the final results DataFrame (titles only):")
        print(final_results_df_titles.head())
        print(f"\nShape of final results: {final_results_df_titles.shape}")
        print(f"\nValue counts for topic_label (top 10):")
        print(final_results_df_titles['topic_label'].value_counts().head(10))

2025-05-13 17:35:43,266 - BERTopic - Embedding - Transforming documents to embeddings.

Using existing df_complete for BERTopic analysis (titles only).
Processing DataFrame with 15341 rows for BERTopic (using titles only).
Number of non-empty titles for BERTopic: 15341

Initializing BERTopic: Model=all-MiniLM-L6-v2, MinTopicSize=50, TargetTopics=100
Fitting BERTopic model on titles...

Batches:   0%|          | 0/480 [00:00<?, ?it/s]

2025-05-13 17:35:52,299 - BERTopic - Embedding - Completed ✓
2025-05-13 17:35:52,300 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-05-13 17:35:53,734 - BERTopic - Dimensionality - Completed ✓
2025-05-13 17:35:53,735 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-05-13 17:35:54,095 - BERTopic - Cluster - Completed ✓
2025-05-13 17:35:54,096 - BERTopic - Representation - Extracting topics from clusters using representation models.
2025-05-13 17:35:54,180 - BERTopic - Representation - Completed ✓
2025-05-13 17:35:54,180 - BERTopic - Topic reduction - Reducing number of topics
2025-05-13 17:35:54,181 - BERTopic - Topic reduction - Reduced number of topics from 40 to 40

BERTopic model fitting complete.

--- BERTopic Results (Titles Only) ---
Number of topics found (after potential reduction): 40
Top topics found:
    Topic  Count                                              Name  \
0      -1   7290               -1_sustainable_digital_using_cancer
1       0     69             0_perovskite_solar_halide_perovskites
2       1    182                   1_batteries_battery_ion_lithium
3       2     64                      2_algae_seaweed_marine_algal
4       3     93              3_additive_manufacturing_printing_3d
5       4    278                       4_storage_energy_heat_power
6       5    554               5_hydrogen_co2_production_catalysts
7       6    435                 6_waste_sustainable_bio_materials
8       7   1006                     7_quantum_photonic_spin_light
9       8    334                 8_gravitational_black_cosmic_dark
10      9    110          9_energy_buildings_transition_renovation
11     10     58  10_pleistocene_reconstructing_ancient_population
12     11     71                    11_wind_offshore_floating_farm
13     12     86               12_health_mental_care_interventions
14     13    120                        13_6g_networks_wireless_5g

                                                                                                        Representation  \
0                            [sustainable, digital, using, cancer, systems, health, innovation, ai, learning, climate]
1                    [perovskite, solar, halide, perovskites, cells, photovoltaics, efficiency, stable, tandem, metal]
2                             [batteries, battery, ion, lithium, solid, state, li, electrolytes, sodium, rechargeable]
3           [algae, seaweed, marine, algal, cyanobacteria, microbial, aquaculture, diatoms, microbiome, phytoplankton]
4                       [additive, manufacturing, printing, 3d, materials, alloys, metal, material, fatigue, advanced]
5                                   [storage, energy, heat, power, thermal, cooling, electric, solar, hybrid, systems]
6                    [hydrogen, co2, production, catalysts, reduction, synthesis, fuel, catalysis, catalytic, ammonia]
7                 [waste, sustainable, bio, materials, circular, recycling, plastic, composite, production, packaging]
8                       [quantum, photonic, spin, light, topological, computing, optical, geometry, theory, photonics]
9                           [gravitational, black, cosmic, dark, evolution, galaxies, stars, matter, holes, cosmology]
10          [energy, buildings, transition, renovation, building, positive, communities, zero, districts, residential]
11  [pleistocene, reconstructing, ancient, population, neanderthal, hominin, fragmented, evolution, dispersal, africa]
12                                [wind, offshore, floating, farm, energy, turbines, farms, power, turbine, renewable]
13                    [health, mental, care, interventions, wellbeing, policy, stressors, healthy, digital, promotion]
14                    [6g, networks, wireless, 5g, intelligent, communication, communications, mimo, sensing, massive]

                                                                                                                                                                                                                                                                                                                                                                                                                                       Representative_Docs
0   [Holistic approach to foster CIRCUlar and resilient transport InfrasTructures and support the deployment of Green and Innovation Public Procurement and innovative engineering practices, Multi-hazard low-carbon resilient technologies and multi-scale digital services for a future-proof, sustainable & user-centred built environment, Artificial Intelligence for early detection of non-communicable disease risk in people with breast cancer]
1                                                                                                                                                                                                                                                         [Printed Perovskite Solar Cells for Large Area User Applications, Graphene-based flexible perovskite solar cells for space applications, FLEXIBLE PEROVSKITE SOLAR CELLS WITH CARBON ELECTRODES]
2                                                                                                                                                           [Towards the next generation of high performance li-ion battery cells, Hybrid Lithium Metal-based Scalable Solid State Battery Manufacturing, Flexible, Safe and efficient REcycling of Li-ion batterieS for a comPetitive, circular, and sustainable European battery manufaCTuring industry]
3                                                                                                                                             [Accelerated Seaweed Production for Innovative and Robust seaweed aquaculture in Europe, EXcellence and competitiveness in marine algae AQUAculture for a sustainable Black Sea, Innovative Approaches for an Integrated Use of Algae in Sustainable Aquaculture Practices and High-Value Food applications]
4                                                                                                                                                                                                                                  [Additive Manufacturing of Living Composite Materials, Resource efficient materials for Additive Manufacturing, Demonstration of a sustainable circular-by-design manufacturing system based on additive manufacturing]
5                                                                                                   [A Power-to-Heat Long Duration Energy Storage for decarbonizing the industrial thermal processes, Scalable, modular, high temperature, cost-efficient thermal energy and power storage and conversion system made of upcycled industrial by-products, Solar-powered Multi-energy Hub for Electric Vehicle and District Heating Thermal Energy Storage]
6                                                                                                                                                                                                                                                                                             [AmmoNia baseD membRane rEActor for green Hydrogen production, CO2 FREE PRODUCTION OF CRITICAL RAW MATERIALS USING HYDROGEN, Hydrogen Production from Waste]
7                                                                                                                                                                                                   [REcycling technologies for Circular REuse and remanufacturing of fiber-reinforced composite mATErials, Recycling plastic waste into high-value materials- Closing the Loop, Circular Systemic Solutions for Plastic, Packaging, Bio-Waste, and Water]
8                                                                                                                                                                                                                                                                             [Advancing Quantum Computers for (and with) Quantum Thermodynamics, moleculAR maTerials for on-chip intEgrated quantuM lIght sourceS, Quantum Materials for Quantum Devices]
9                                                                                                                                                                                                                                                         [Gravitational Physics from the Universe Large Scales Evolution, Deep Learning the Dark Universe with Gravitational Waves, Precision cosmology And Dark sectOr physics with graVitational wAves]
10                                                                                                                            [Building Intelligent Positive Energy Districts, Innovative methodology based in circular economy and artificial intelligence to foster the transition to Sustainable and very high eNergy performance bUildinGs at a cost optimal level, Envelope mAterial System with low Impact for Zero Energy buildings and Renovation]
11                                                                                                                                     [Reconstructing fragmented bones, reconstructing fragmented lives, Spectroscopy and Geochemistry of chert. Reconstructing human mobility in the Pyrenees from the first Modern Humans to the last Pleistocene hunter-gatherers, PalaeoEcology and OPen-LandscapE adaptations of Pleistocene humans in South Africa]
12                                                                                                                                                                                                [Integrated Designs for Future Floating Offshore Wind Farm Technology, Black sea fLoating Offshore Wind, Innovative circular materials and design methods for the development of Floating Wind Turbine components for offshore Wind Farms of the future]
13                                                                                                                                                                                       [Improving mental health, wellbeing, and resilience of healthcare workers in Changing Environments, Environmental Effect on Health Care and Wellbeing and Active Interventions, Improving Digital Mental Health Interventions: ENGAGEment as Mechanism of Impact]
14                                                                                                                                                                                                                                                                                                         [Optical 6G Cell Free Networks, IntelligenT twinning of WIreless Networks for 6G, Integrated SEnsing, Energy and communication for 6G networks]

Saving results to: cordis_bertopics_titles_100topics.csv
Saving BERTopic model to: bertopic_cordis_titles_100topics_model

Script finished successfully!

Displaying head of the final results DataFrame (titles only):
          id  \
0  101116741
1  101163161
2  101160499
3  101166905
4  101162875

                                                                                             title  \
0                                               Digitizing Other Economies: A Comparative Approach
1                     MOLECULAR QUANTUM DYNAMICS IN LOW TEMPERATURE CONDENSED PHASE ASTROCHEMISTRY
2                             Multiscale modelling of aberrant phase transitions in biocondensates
3                                                   The first comprehensive Atlas of the Milky Way
4  Untapping multiparametric 2D luminescence sensing through MACHine LEarning and Spectral Sorting

   topic_id                       topic_label
0        -1  sustainable_digital_using_cancer
1         7       quantum_photonic_spin_light
2        -1  sustainable_digital_using_cancer
3         8   gravitational_black_cosmic_dark
4        -1  sustainable_digital_using_cancer

Shape of final results: (15341, 4)

Value counts for topic_label (top 10):
topic_label
sustainable_digital_using_cancer       7290
quantum_photonic_spin_light            1006
political_europe_medieval_democracy     947
hydrogen_co2_production_catalysts       554
waste_sustainable_bio_materials         435
language_neural_brain_visual            411
cancer_cell_immune_tumor                378
gravitational_black_cosmic_dark         334
storage_energy_heat_power               278
virus_viral_pandemic_infectious         228
Name: count, dtype: int64

In [50]:
final_results_df_titles

,id,title,topic_id,topic_label
0,101116741,Digitizing Other Economies: A Comparative Approach,-1,sustainable_digital_learning_cancer
1,101163161,MOLECULAR QUANTUM DYNAMICS IN LOW TEMPERATURE CONDENSED PHASE ASTROCHEMISTRY,-1,sustainable_digital_learning_cancer
2,101160499,Multiscale modelling of aberrant phase transitions in biocondensates,-1,sustainable_digital_learning_cancer
3,101166905,The first comprehensive Atlas of the Milky Way,11,gravitational_black_galaxies_dark
4,101162875,Untapping multiparametric 2D luminescence sensing through MACHine LEarning and Spectral Sorting,-1,sustainable_digital_learning_cancer
...,...,...,...,...
15336,101114220,Deployment of ModelMe Innovation,8,innovation_circular_bioeconomy_regions
15337,101114193,"Cogo - all ride in one app. Cogo gathers electric shared bikes, scooters, cars and mopeds from 250 mobility operators in more than 700 cities, and is now ready to launch the full-service platform.",48,mobility_freight_logistics_urban
15338,101114191,HORIZER,-1,sustainable_digital_learning_cancer
15339,101114035,AI-powered early warning and surveillance system to identify the risks within the food supply chain,22,food_meat_systems_fermentation
15340,101121353,"Engage2innovate – Enhancing security solution design, adoption and impact through effective engagement and social innovation",-1,sustainable_digital_learning_cancer

In [30]:
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Configure BERTopic with valid parameters
topic_model = BERTopic(
    # Language model
    language="english",
    
    # Number of topics - "auto" lets the model decide, or specify a number
    nr_topics="auto",  # Or try 20-50 for more control
    
    # Minimum cluster size - higher values create fewer, broader topics
    min_topic_size=30,  # Adjust this: 10-20 for more specific, 50+ for more general
    
    # N-gram range for feature extraction
    n_gram_range=(1, 3),  # Captures single words to 3-word phrases
    
    # Vectorizer settings
    vectorizer_model=CountVectorizer(
        stop_words="english",
        max_features=10000,
        ngram_range=(1, 3)
    ),
    
    # For reproducibility
    seed_topic_list=[0, 1, 2, 3, 4],  # Provide seed topics if needed
    
    # Calculate topic probabilities
    calculate_probabilities=True
)

# Fit the model
docs = df_complete['combined_text'].tolist()
topics, probs = topic_model.fit_transform(docs)

# Add topics to dataframe
df_complete['topic'] = topics
df_complete['topic_probability'] = probs

print(f"Number of topics found: {len(set(topics)) - 1}")  # -1 to exclude outliers
print(f"Number of outliers: {sum(topics == -1)}")

TypeError: can only join an iterable

In [32]:
import pandas as pd
from bertopic import BERTopic
import csv # For saving output with QUOTE_ALL

# --- Assume df_complete is already loaded and prepared in your environment ---
# For example, from your previous CSV parsing script or notebook cell:
#
# df_complete = load_and_fix_cordis_csv(CSV_FILE_PATH) # Or however it was created
#
# If running this as a standalone script and df_complete isn't globally available,
# you would need a way to get it, e.g., load it from a cleaned CSV if you saved one.
# For this example, I'll simulate its creation so the script can run standalone.

# --- SIMULATE df_complete if not already in environment (for standalone script testing) ---
# In your actual Jupyter notebook, you would NOT need this simulation part
# if df_complete is already a defined DataFrame.
if 'df_complete' not in locals() and 'df_complete' not in globals():
    print("Simulating df_complete creation for standalone script testing...")
    # This is a placeholder. Replace with your actual df_complete if running standalone
    # or ensure df_complete is available in your notebook's global scope.
    data_for_simulation = {
        'id': [101116741, 101163161, 101160499, 101116742, 101163162],
        'title': [
            "Digitizing Other Economies: A Comparative Approach",
            "MOLECULAR QUANTUM DYNAMICS IN LOW TEMPERATURE CONDENSED PHASE ASTROCHEMISTRY",
            "Multiscale modelling of aberrant phase transitions in biocondensates",
            "Another Example Title for Science",
            "Tech Innovation Project X"
        ],
        'objective': [
            "How do longstanding, primarily non-industrial, non-capitalist societies adopt and adapt digital technologies... (rest of objective 0)",
            "The James Webb Space Telescope (JWST) has ushered in a new era in observational astrochemistry... (rest of objective 1)",
            "The spatiotemporal organization of the cell material represents one of the great wonders... (rest of objective 2)",
            "This project aims to explore novel scientific frontiers using advanced computational methods and big data analytics to solve complex problems.",
            "Developing cutting-edge technology for societal benefit, focusing on sustainable solutions and user-centric design principles."
        ]
    }
    df_complete = pd.DataFrame(data_for_simulation)
    df_complete['id'] = df_complete['id'].astype(int)
    print(f"Simulated df_complete with {len(df_complete)} rows.")
# --- END SIMULATION ---


# --- BERTopic Configuration (same as before) ---
SAMPLE_SIZE = None  # Set to None to use all data from df_complete, or a number for sampling
EMBEDDING_MODEL = "all-MiniLM-L6-v2"
MIN_TOPIC_SIZE = 10 # Adjusted for potentially smaller datasets if you run on a small df_complete
NR_TOPICS = "auto"


def run_bertopic_on_dataframe(df: pd.DataFrame):
    """
    Runs BERTopic analysis on a pre-loaded DataFrame with 'id', 'title', 'objective'.
    """
    if not isinstance(df, pd.DataFrame) or df.empty:
        print("ERROR: Input is not a valid or non-empty DataFrame. Exiting.")
        return

    required_cols = ['id', 'title', 'objective']
    if not all(col in df.columns for col in required_cols):
        print(f"ERROR: DataFrame must contain columns: {required_cols}")
        print(f"Available columns: {df.columns.tolist()}")
        return

    print(f"Processing DataFrame with {len(df)} rows for BERTopic.")

    # --- 1. Combine 'title' and 'objective' ---
    print("\nCombining 'title' and 'objective' columns...")
    # Ensure data types are string and handle NaNs before concatenation
    df_working = df.copy() # Work on a copy
    df_working['title'] = df_working['title'].fillna('').astype(str)
    df_working['objective'] = df_working['objective'].fillna('').astype(str)
    df_working['combined_text'] = df_working['title'] + " " + df_working['objective']
    df_working['combined_text'] = df_working['combined_text'].str.strip()

    print("Successfully created 'combined_text' column.")
    if not df_working.empty:
        print(f"Example combined text: '{df_working['combined_text'].iloc[0][:200]}...'")
    
    # Prepare texts and IDs for BERTopic, filtering out empty combined_text
    df_filtered = df_working[df_working['combined_text'] != ''].copy()
    texts_for_bertopic = df_filtered['combined_text'].tolist()
    ids_for_bertopic = df_filtered['id'].tolist() # Original IDs

    if not texts_for_bertopic:
        print("ERROR: No text data available for BERTopic after combining. Check DataFrame content.")
        return
    
    print(f"Number of non-empty documents for BERTopic: {len(texts_for_bertopic)}")

    # Apply sampling if SAMPLE_SIZE is set
    if SAMPLE_SIZE and len(texts_for_bertopic) > SAMPLE_SIZE:
        print(f"Sampling {SAMPLE_SIZE} documents for BERTopic processing...")
        # Sample directly from df_filtered to keep ids and texts aligned
        sampled_df_indices = df_filtered.sample(n=SAMPLE_SIZE, random_state=42).index
        texts_to_process = df_filtered.loc[sampled_df_indices, 'combined_text'].tolist()
        ids_to_process = df_filtered.loc[sampled_df_indices, 'id'].tolist() # Corresponding original IDs
    else:
        print("Processing all available non-empty documents from the DataFrame...")
        texts_to_process = texts_for_bertopic
        ids_to_process = ids_for_bertopic


    # --- 2. Initialize and run BERTopic ---
    print(f"\nInitializing BERTopic with model: {EMBEDDING_MODEL}")
    print(f"Min topic size: {MIN_TOPIC_SIZE}, Nr topics: {NR_TOPICS}")

    topic_model = BERTopic(
        embedding_model=EMBEDDING_MODEL,
        min_topic_size=MIN_TOPIC_SIZE,
        nr_topics=NR_TOPICS,
        verbose=True,
    )

    print("Fitting BERTopic model... This can take a significant amount of time.")
    try:
        topics, probabilities = topic_model.fit_transform(texts_to_process)
        print("BERTopic model fitting complete.")
    except Exception as e:
        print(f"ERROR: BERTopic fitting failed: {e}")
        import traceback
        traceback.print_exc()
        return

    # --- 3. Explore and Save Results ---
    print("\n--- BERTopic Results ---")
    topic_info = topic_model.get_topic_info()
    print("Top topics found:")
    print(topic_info.head(15))

    if -1 in topic_info['Topic'].values:
        outlier_count = topic_info[topic_info['Topic'] == -1]['Count'].iloc[0]
        print(f"\nNumber of outlier documents (Topic -1): {outlier_count}")

    # Create a DataFrame for the processed texts and their topics using original IDs
    results_df = pd.DataFrame({
        'id': ids_to_process, # These are the original IDs of the texts fed to BERTopic
        'topic_id': topics
    })
    
    topic_labels_map = {topic_id: "_".join([word for word, _ in topic_model.get_topic(topic_id)[:3]])
                        for topic_id in set(topics) if topic_model.get_topic(topic_id) is not None}
    if -1 in set(topics): # Handle outliers
        topic_labels_map[-1] = "Outliers"
    results_df['topic_label'] = results_df['topic_id'].map(topic_labels_map)

    # Merge with original titles/objectives from the *filtered and potentially sampled* subset
    # df_filtered contains the 'id', 'title', 'objective', 'combined_text' for all docs that had text
    # We need to merge results_df (which has 'id' and topic info for *processed* docs) back to this.
    
    # Select the subset of df_filtered that corresponds to ids_to_process
    # (This is essentially creating a df from the lists ids_to_process and texts_to_process, then adding original title/objective)
    final_output_df_subset = df_filtered[df_filtered['id'].isin(ids_to_process)][['id', 'title', 'objective', 'combined_text']].copy()
    final_output_df = pd.merge(final_output_df_subset, results_df, on='id', how='left')


    output_csv_path = "cordis_projects_with_bertopics_from_df.csv"
    print(f"\nSaving results with topic assignments to: {output_csv_path}")
    final_output_df.to_csv(output_csv_path, index=False, quoting=csv.QUOTE_ALL)

    model_save_path = "bertopic_cordis_model_from_df"
    print(f"Saving BERTopic model to: {model_save_path}")
    topic_model.save(model_save_path, serialization="safetensors")

    print("\nScript finished successfully!")
    return final_output_df, topic_model # Optionally return results


# --- How to use it ---
if __name__ == "__main__":
    # This __main__ block now assumes df_complete is created or loaded globally
    # In a Jupyter notebook, you would just call:
    # final_df, model = run_bertopic_on_dataframe(df_complete)
    
    if 'df_complete' in locals() or 'df_complete' in globals():
        print("Using existing df_complete for BERTopic analysis.")
        final_results_df, trained_model = run_bertopic_on_dataframe(df_complete)
        if final_results_df is not None:
            print("\nDisplaying head of the final results DataFrame:")
            print(final_results_df.head())
    else:
        print("ERROR: df_complete is not defined. Please ensure it's loaded before running BERTopic analysis.")

2025-05-13 16:36:59,220 - BERTopic - Embedding - Transforming documents to embeddings.

Using existing df_complete for BERTopic analysis.
Processing DataFrame with 15341 rows for BERTopic.

Combining 'title' and 'objective' columns...
Successfully created 'combined_text' column.
Example combined text: 'Digitizing Other Economies: A Comparative Approach How do longstanding, primarily non-industrial, non-capitalist societies adopt and adapt digital technologies in their daily practices and systems of ...'
Number of non-empty documents for BERTopic: 15341
Processing all available non-empty documents from the DataFrame...

Initializing BERTopic with model: all-MiniLM-L6-v2
Min topic size: 10, Nr topics: auto
Fitting BERTopic model... This can take a significant amount of time.

Batches:   0%|          | 0/480 [00:00<?, ?it/s]

2025-05-13 16:38:05,885 - BERTopic - Embedding - Completed ✓
2025-05-13 16:38:05,885 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-05-13 16:38:14,715 - BERTopic - Dimensionality - Completed ✓
2025-05-13 16:38:14,716 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-05-13 16:38:14,959 - BERTopic - Cluster - Completed ✓
2025-05-13 16:38:14,959 - BERTopic - Representation - Extracting topics from clusters using representation models.
2025-05-13 16:38:16,134 - BERTopic - Representation - Completed ✓
2025-05-13 16:38:16,137 - BERTopic - Topic reduction - Reducing number of topics
2025-05-13 16:38:17,241 - BERTopic - Topic reduction - Reduced number of topics from 243 to 12

BERTopic model fitting complete.

--- BERTopic Results ---
Top topics found:
    Topic  Count                             Name  \
0      -1   5886                 -1_the_and_of_to
1       0   9138                  0_the_and_of_to
2       1     84         1_of_the_theory_geometry
3       2     62               2_of_the_to_theory
4       3     46             3_the_vr_and_virtual
5       4     31              4_the_causal_of_and
6       5     21          5_kidney_ckd_disease_of
7       6     19    6_the_reproductive_and_embryo
8       7     15  7_hearing_auditory_the_cochlear
9       8     15           8_dna_storage_data_and
10      9     13         9_circadian_clock_the_in
11     10     11   10_equations_the_dispersive_of

                                                                  Representation  \
0                                [the, and, of, to, in, will, for, is, with, on]
1                                [the, and, of, to, in, will, for, with, is, on]
2            [of, the, theory, geometry, in, to, and, conjecture, algebraic, is]
3                    [of, the, to, theory, in, is, and, for, cryptography, this]
4                         [the, vr, and, virtual, of, to, reality, in, xr, will]
5                         [the, causal, of, and, to, in, data, models, that, on]
6                        [kidney, ckd, disease, of, and, renal, the, in, is, to]
7                [the, reproductive, and, embryo, to, of, for, ivf, in, embryos]
8          [hearing, auditory, the, cochlear, of, to, music, and, in, listening]
9            [dna, storage, data, and, of, the, to, synthesis, for, information]
10                      [circadian, clock, the, in, scn, of, to, sleep, and, is]
11  [equations, the, dispersive, of, in, waves, inverse, problems, problem, pde]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Representative_Docs
0                                                                                                                                                                                                                                                                                                            [A new EU Framework for an Ethical Re-use of Health Data The EU has recently enhanced the potential of health data in the EU digital market by promoting a number of initiatives and new regulations to facilitate data sharing and re-use among public institutions: the forthcoming provisions of the Digital Strategy Corpus of law. These, in combination with pre-existing rules and practices of health data exploitation, might sharpen the risks for citizens, for example allowing public bodies to exploit big data sets -  to make detrimental decisions regarding the access of certain patients to health care (e.g., in the case of insurance-based systems). In this context, academic analysis is urgently needed, as well as suggesting a revision of the new regulations to EU policy-makers to facilitate responsible data sharing. DataCom aims at building a new framework to facilitate an ethical secondary use of health data held by public bodies, with the aim of improving accountability and enhancing responsible re-use. To build it, I will develop and test in intersectoral practical environments the innovative concept of “Ethical Commodification”: the possibility of exploiting personal data in an ethical way for the public good, in accordance with the data subject’s expectations and needs and taking into account the risks associated with the exploitation of anonymized data sets, focusing on 3 Member States, Italy, Spain, and the Netherlands. In order to reach this objective, DataCom has a strong interdisciplinary and intersectoral approach, bridging law, ethics, and computer science, taking into consideration the needs of the public sector and those of citizens. To ensure the successful implementation of these project goals I will conduct my research at the University of Turin's Law Department, with the guidance of Prof. Ugo Pagallo, a leading scholar. This project will prepare me to become a tenured scholar and obtain advanced funding, strengthening my academic profile and allowing me to establish my own research group., Explaining Individual Lifespan Change The EILisCh project will focus on linguistic variation and change in Icelandic syntax and it will be the most ambitious attempt so far to model, understand, and explain Individual Lifespan Change in linguistic behavior, drawing on recent advances in sociolinguistics, quantitative syntactic theory, clinicial linguistics, as well as resources recently made available by Language Technology. The project will harness these ingredients and the experience of the PI and the infrastructure present in his Language and Technology lab in order to facilitate a new kind of a large scale project that will yield substantial progress towards important empirical, theoretical, and methodological goals, as well as benefits for society. I will track hundreds of Members of Parliament via their speeches over their entire political career and interview dozens of current and former MPs to establish an even deeper profile of how they use language. Carrying this research out in Iceland is important because of the unusually easy access that researchers have to public figures in this small language community. The kind of precise modelling that I describe in this proposal is only possible in a project that builds on substantial pre-existing Language Resources and takes place in a setting where extensive knowledge of the linguistic data and the required technological tools is present. My Language and Technology lab at the University of Iceland is the right place to do this and the experience I have gathered in several previous projects will be essential for my team’s success. However, the scale of this enterprise is beyond the means of national funding agencies in Iceland; thus I turn to the ERC, so that together we can redefine the state of the art in the study of Individual Lifespan Change., Learning from nature: Microbiome training towards improving agricultural sustainability A major challenge for mankind in the age of climate change is to feed the increasing human population in a sustainable manner. Currently, more than one third of crop yields are lost due to abiotic and biotic stresses, such as drought, salinity, pests and diseases. To minimize this yield gap and to simultaneously reduce the environmental impact of current agricultural practices, future crop production needs to be achieved with reduced input of fertilizers and pesticides. These challenges have increased the awareness of plant microbiomes bearing a hidden untapped potential for crop productivity and resilience that we must learn to use. Recently, more and more microbial products are tested in agriculture but often they are based on one or a few bacteria inoculants. However, the performance and efficacy of these products can be affected by many factors such as, soil type, temperature, humidity and the composition of the native microbiomes. The aim of the microTRIAS project is to unfold the potential of microbiomes by steering the native soil microbial communities towards plant-growth promoting and (a)biotic stress alleviating functions. To achieve this goal, I propose an innovative and ambitious multi-disciplinary approach based on the hypothesis that we can stimulate and train functional and taxonomic shifts in microbiomes on demand to remodel and improve existing communities, rather than introducing new elements in a native ecosystem. Additionally, by monitoring the microbiome changes, using beyond the state of art (multi)omics technologies, I will be able to identify microbes and functions fundamental to desirable microbiome traits. This study will suppose the first proof of concept of this novel integrative approach, opening new avenues for microbiome applications in agricultural settings. The findings of this study will be beneficial for improving agriculture sustainability but also will raise societal climate change awareness on the local and global scale.]

In [33]:
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Configure BERTopic without problematic parameters
topic_model = BERTopic(
    language="english",
    min_topic_size=30,  # Adjust this: 10-20 for more specific, 50+ for more general
    nr_topics="auto",  # Or try 20-50 for more control
    n_gram_range=(1, 3),
    vectorizer_model=CountVectorizer(
        stop_words="english",
        max_features=10000,
        ngram_range=(1, 3)
    ),
    calculate_probabilities=True
)

# Fit the model
docs = df_complete['combined_text'].tolist()
topics, probs = topic_model.fit_transform(docs)

# Add topics to dataframe
df_complete['topic'] = topics
df_complete['topic_probability'] = probs

print(f"Number of topics found: {len(set(topics)) - 1}")  # -1 to exclude outliers
print(f"Number of outliers: {sum(topics == -1)}")

ValueError: Expected a 1D array, got an array with shape (15341, 44)

In [34]:
from bertopic import BERTopic
import pandas as pd

# Configure BERTopic without probability calculation
topic_model = BERTopic(
    language="english",
    min_topic_size=30,  
    nr_topics="auto",
    n_gram_range=(1, 3),
    calculate_probabilities=False  # Don't calculate probabilities
)

# Fit the model
docs = df_complete['combined_text'].tolist()
topics, probs = topic_model.fit_transform(docs)

# Add topics to dataframe
df_complete['topic'] = topics

print(f"Number of topics found: {len(set(topics)) - 1}")
print(f"Number of outliers: {sum(topics == -1)}")

Number of topics found: 45

TypeError: 'bool' object is not iterable

In [36]:
# Properly count topics and outliers
unique_topics = set(topics)
num_topics = len(unique_topics) - (1 if -1 in unique_topics else 0)
num_outliers = len([t for t in topics if t == -1])

print(f"Number of topics found: {num_topics}")
print(f"Number of outliers: {num_outliers}")
print(f"Total documents: {len(topics)}")

Number of topics found: 45
Number of outliers: 6648
Total documents: 15341

In [37]:
# Get topic information
topic_info = topic_model.get_topic_info()
print("\nTopic overview:")
print(topic_info.head(10))

# Get top words for each topic
print("\nTop words per topic:")
for topic_num in topic_info['Topic'].values[:10]:
    if topic_num == -1:  # Skip outliers
        continue
    topic_words = topic_model.get_topic(topic_num)
    words = [word[0] for word in topic_words[:5]]
    count = len(df_complete[df_complete['topic'] == topic_num])
    print(f"Topic {topic_num} ({count} docs): {', '.join(words)}")

Topic overview:
   Topic  Count                  Name  \
0     -1   6648      -1_and_the_of_to
1      0   3068       0_and_the_of_to
2      1    488   1_quantum_the_of_to
3      2    305       2_the_of_in_and
4      3    298       3_and_the_of_in
5      4    283       4_the_and_of_to
6      5    267       5_the_of_and_in
7      6    247       6_the_of_and_to
8      7    241  7_cancer_cells_of_to
9      8    237       8_the_of_and_to

                                                  Representation  \
0                [and, the, of, to, in, for, will, is, with, on]
1            [and, the, of, to, in, for, will, with, of the, be]
2   [quantum, the, of, to, and, in, will, for, with, of quantum]
3              [the, of, in, and, to, will, is, that, brain, ad]
4       [and, the, of, in, to, on, social, political, how, will]
5            [the, and, of, to, climate, in, will, for, ice, on]
6        [the, of, and, in, of the, to, history, in the, on, as]
7  [the, of, and, to, in, will, of the, galaxies, dark, physics]
8     [cancer, cells, of, to, the, in, and, tumor, cell, immune]
9           [the, of, and, to, in, imaging, for, will, is, with]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Representative_Docs
0                                                                                  [Interoperable opeN-source Tools to Enable hybRidisation, utiliSation, and moneTisation of stORage flExibility Storage is becoming one of the most critical assets for modern energy systems. At the same time storage is a very diverse universe of solutions and technologies with very different characteristics. InterSTORE plans to address this complexity by developing an innovative middleware that, while virtualising the storage technology, will simplify its use from the point of view of integration platform thanks to a technology agnostic approach.The middleware will facilitate the integration of storage creating an independence from hardware solutions which are critical from customer perspectives to avoid vendor lock-in solutions. It will also facilitate its use from a monetisation perspective making sure that more investments in storage are enabled.  InterSTORE middleware will be released as a full open-source product integrating a set of already available standards and protocols in a coherent and advanced architecture.The new InterSTORE solution will be tested and validated in a laboratory environment with the goal to develop testing software to be adopted in the future for interoperability certification.  The middleware solution will also be integrated both in open source and commercial platforms that will be integrated in 4 real life demos to enhance the flexibility platforms and analyze the user acceptance and economic value of the new solution. Moreover, new and legacy systems will be taken into account. InterSTORE also has a strong focus towards impact. The solution will become part of existing commercial platforms ensuring that a real adoption will be deployed beyond the end of the project. The consortium will ensure that software maintenance will continue beyond the end of the project with the support of Linux Foundation Energy and that the work done will be considered by on-going standardization activities. SSH experts will perform an impact analysis to maximize the economic impact adopting innovative approaches to data monetization in the context of data spaces., EU-CONEXUS ENABLES - Promoting excellence through innovative eco-systems The concept of EU-CONEXUS ENABLES is built upon the strong foundation of our Alliance within the Joint Research Area as an excellent network for cooperation between the partners with several points of gravity such as the 4 Joint Research Institutes (an outcome of H2020-SwafS project) - Coastal Engineering Institute, Environmental Sciences and Biodiversity Institute, Life Sciences and Biotechnology Institute, Social, Culture and Human Sciences Institute, and the Doctoral School framework of EU-CONEXUS European University. The project is devoted to promote scientific and academic cooperation between the members of the alliance in the same time with an effective implementation of ERA policy agenda main objectives. Using as thematical background 4 major challenges, the project is dedicated to achieve specific objectives that are aligned with mostly all of the ERA goals. The scope of the EU-CONEXUS ENABLES project is to create the framework of an innovative ecosystem promoting sustainable synergies between the alliance and its partners such as the fellow municipalities, other stakeholders, in order to develop long term solutions for Smart Urban Coastal Sustainability challenges, based on the Digital Twin approach.The project is focused on  one hand to raise excellence in value creation through deeper and geographically inclusive cooperation, and on the other hand to the societal based topics and needs coming from our supporting ecosystems of stakeholders. The project will also offer training and capacity-building programs for researchers, promoting a culture of collaboration, innovation, and continuous improvement.Through hackathons, capacity building, and knowledge exchange activities, the project will engage experts, researchers, and stakeholders in the development and implementation of innovative Digital Twin solutions. Citizen engagement in participatory science activities will also be facilitated, encouraging evidence-based policies and interventions., Towards development of new antibacterial strategy for dentistry ARGO project will be dedicated to explore innovative activities with focus on strong international, interdisciplinary and inter-sectoral cooperation in fields of chemistry, biomaterials, nanotechnology, microbiology, cell biology and dentistry. ARGO network will involve academic and industrial partners from EU MS and associated countries with the aim to open potential for innovative solutions in nanomaterials and clinical dentistry. The primary research goal of the project is to facilitate R&I activities with complementary competences of participant organizations for development of new antibacterial materials for dentistry, particular for the development a new antibacterial root-filling material.The project will be realized through the tight cooperation between partner organizations to create synergies for development and testing of innovative biomaterials for dentistry. The innovative technologies will be used to produce a root-filling material with nanoparticles with tailored biological and antibacterial properties. Evaluation of a new biomaterials with silver nanoparticles in vitro will be carried out on a specially designed tooth model. Biocompatibility and in-vivo assessment will be used to prove antibacterial effect of the new biomaterial on a relevant animal model. Interdisciplinary and inter-sectoral secondment will be the main tool for project realization with aim of strengthening research, training, communication and networking capacities of participant organizations and knowledge transfer from academia to industry and vice versa. Proposed research and training goals will lead to increased research, transferable skills and competences of early stage researcher with the aim to improve employability and career perspectives in both academic and industrial sectors. Public dissemination of new research results will increase the awareness in the general society of the role of research and researchers in development of EU as a leading destination for R&I.]

In [38]:
from sklearn.feature_extraction.text import CountVectorizer

# Inside your run_bertopic_on_dataframe function, before initializing BERTopic:

# Define a CountVectorizer with English stopwords
vectorizer = CountVectorizer(stop_words="english")

# Then, when initializing BERTopic:
topic_model = BERTopic(
    embedding_model=EMBEDDING_MODEL,
    vectorizer_model=vectorizer,  # ADD THIS LINE
    min_topic_size=MIN_TOPIC_SIZE,
    nr_topics=NR_TOPICS,
    verbose=True,
)